### ISSUE TITLE
Create a router middleware for compression of data sent to requestor

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#10]
Create a Kitura-Router middleware that supports the common forms of over the wire compression. 

For the gzip compression we should probably use zLib.

This requires some work in the base router to APIs to add "plugins" that operate in the read/write path.

- [ ] Read Accept-Encoding from RouterRequest "gzip, deflate"
- [ ] Add Content-Encoding to RouterResponse: gzip
- [ ] Set correct content-length

**Comment by rfdickerson** [comment]
I agree we should probably use the "de facto" standard of zlib for this task. However, it would add another system-level library to our dependencies. (I realize that most systems use zlib, but we will need to install zlib1g-dev" for the development headers. The other option is for me to implement a pure Swift version of LZ77 and deflate.

**Comment by billabt** [comment]
I was planning on building a small framework for compression based on zlib. Basically pass in an NSData and get a compressed NSData and vice versa.

**Comment by billabt** [comment]
Actually just found this. Nice favorable license, just needs a little code cleanup for Swift 3.0. https://github.com/1024jp/NSData-GZIP/blob/master/README.md

**Comment by rfdickerson** [comment]
I was able to bring in zLib and compile the following code, however it seems to always throw a buffer error on the compression step.

```swift
typealias Byte = UInt8

let size: Int = 100000

var simpleData = [Byte](repeating: 3, count: size)

let dataCompressed = NSMutableData(capacity: 2000)

var pd = UnsafeMutablePointer<Bytef>(dataCompressed!.bytes)

//var dataCompressed = [Byte](repeating: 6, count: size)

simpleData[3] = 2
simpleData[4] = 1

var sizeDataCompressed: uLongf = 0

withUnsafeMutablePointer(&simpleData) {
let result = compress2( pd, &sizeDataCompressed,
                        UnsafeMutablePointer($0), uLong(size), Z_BEST_SPEED )

switch result {
    case Z_OK:
        print("Everything's OK")
    case Z_BUF_ERROR:
        print("Buffer error")
    default:
        print("Some other error")
}
```

**Comment by rfdickerson** [comment]
We could use that existing library, but I'm somewhat reluctant to bring in yet another dependency for something that's pretty easy to do on our own.

**Comment by shmuelk** [comment]
Reviewed looks great.
