### ISSUE TITLE
Add monitoring hooks into KituraNet HTTP

### ISSUE THREAD

**Issue by mattcolegate** [IBM-Swift/Kitura#1004]
#840 allows server-side monitoring hooks to see requests and responses flowing through a Kitura server. As an extension of that work, SwiftMetrics would like to be able to gather metrics about outbound HTTP requests/responses that are fired from a Swift Application using KituraNet's HTTP/ClientRequest object. I think the easiest thing to do to achieve this is to store some kind of delegate that wraps the callback set in the ClientRequest initialiser e.g.:

if (monitoringDelagate.exists())
self.callback = monitoringDelegate.generateCallback(callback)
else
self.callback = callback.

This would enable the monitoring delegate to intercept the ClientResponse.

FYI, the kind of metrics we're hoping to get (taken from https://github.com/RuntimeTools/appmetrics)

Event: 'http-outbound'

Emitted when the application makes an outbound HTTP request.

    data (Object) the data from the HTTP request:
        time (Number) the milliseconds when the request was made. This can be converted to a Date using new Date(data.time).
        method (String) the HTTP method used for the request.
        url (String) the URL on which the request was made.
        contentType (String) the HTTP response content-type.
        statusCode (String) the HTTP response status code.
        duration (Number) the time taken for the HTTP request to be responded to in ms.

Tagging people who might be interested: @tobespc @seabaylea @shmuelk

**Comment by shmuelk** [comment]
This sounds quite do able.

However. There is a big push to get rid of KituraNet.ClientRequest and KituraNet.ClientResponse and to move to URLSession and friends. This is will very true in the Swift 3.1 as it seems that they are finally getting the bugs out of URLSession and DispatchSource.

**Comment by mattcolegate** [comment]
Hmmm. Perhaps it would be better hung from KituraNet.HTTP then?

**Comment by shmuelk** [comment]
If you mean KituraNet.HTTP.request(), then that's the same as ClientRequest and ClientResponse.

**Comment by ianpartridge** [comment]
Closing as no longer in our plans.
