### ISSUE TITLE
Response is not closed and hangs if router handlers do not call end() or next()

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Kitura#1009]
Kitura Router.handle() calls `response.end()` in case none of the handlers call it, but this is dependent on the route handlers calling next(). Check and ensure RouterResponse end() has been invoked in it's deinitialization so we always end the response when we are done with it.

http://stackoverflow.com/questions/42176639/simplify-kitura-routerhandler-by-removing-next-closure/

**Comment by youming-lin** [comment]
I would argue that it **should** be dependent on route handlers calling `next()`, especially for handlers that perform asynchronous work.

**Comment by na-gupta** [comment]
That's a good point about handlers that do asynchronous work. I think we can introduce a flag for handlers to signal the need to defer ending the response, while making it more intuitive for the bulk of users. Are you aware of any uses of kitura where handlers are doing asynchronous work that requires deferring response.end() ?

**Comment by youming-lin** [comment]
Anytime a handler needs to use asynchronous libraries, for example HTTP/database calls. I wrote an example as answer to an SO question: http://stackoverflow.com/a/40227985

**Comment by na-gupta** [comment]
@youming-lin Makes sense. I think we can achieve the objective by checking and calling end() in RouterResponse's deinit unless I missed something else. Thanks!

**Comment by youming-lin** [comment]
We need to discuss this change. IIRC in my tests the current Kitura behavior matches Node ExpressJS's; that is, if neither `next()` nor `response.end()` is called in the handler, then the request "hangs".

In the case that `next()` isn't called, do we 1) continue onto the next handler, or 2) end request processing here? If we insert `end()` in `RouterResponse`'s `denit` without making any other changes, 2) becomes the behavior, but I'm betting developers still expect 1) as the correct behavior.

**Comment by na-gupta** [comment]
RouterResponse's denit will not be invoked until after `Router.handle(request:response:)` finishes and all handler/middleware objects with a reference to it exit that scope. Not sure why we would end request processing after the first handler does not call next()?

As long as any router/handlers/middleware have a strong reference to the `RouterResponse`, deinit should not be invoked.

**Comment by youming-lin** [comment]
It's the same reason why not calling `next()` currently hangs the request. The middleware/element walking basically stops if `next()` isn't called. `Router` has the default response logic that *should* handle ending the response if it wasn't manually ended, but this code isn't executed if `next()` isn't called. This is because that code isn't reached due to the walker loop ending prematurely if `next()` isn't called.

**Comment by na-gupta** [comment]
Still not understanding the issue. After the RouterResponse instance's deinit is invoked (in which we would now clean up - flush and close the socket), no other handlers should have a strong reference this RouterResponse instance. If they have a weak/unowned reference it will either now be nil or cause a crash if used.

Even if we were not to make this change, once the RouterResponse's deinit has been invoked, no handlers/middleware would be able to perform any operations on this RouterResponse instance anyway. The only difference would be that the underlying socket would not be closed and the client request would hang.

Maybe we should table this discussion till Monday :)
