### ISSUE TITLE
Merge the memory leak fixes into master

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#1012]
Merge fixes that have been made as part of the work on issue #928

**Comment by carlbrown** [comment]
Memory run results:
![issue_1012](https://cloud.githubusercontent.com/assets/67206/23077052/8fdd5138-f508-11e6-8d28-3a78b627daa7.png)

**Comment by carlbrown** [comment]
Valgrind Logs, as requested:

[screenlog.3001.1487717329.log.txt](https://github.com/IBM-Swift/Kitura/files/791748/screenlog.3001.1487717329.log.txt)
[screenlog.3000.1487717286.log.txt](https://github.com/IBM-Swift/Kitura/files/791751/screenlog.3000.1487717286.log.txt)
[massif.out.20992.log.txt](https://github.com/IBM-Swift/Kitura/files/791750/massif.out.20992.log.txt)
[massif.out.22129.log.txt](https://github.com/IBM-Swift/Kitura/files/791749/massif.out.22129.log.txt)
