### ISSUE TITLE
Async Route handling

### ISSUE THREAD

**Issue by cliapis** [IBM-Swift/Kitura#1027]
Hello, I have an issue handling async responses.
What I need to do is to perform an API request and then send a response.
The problem is that I never get a response back from Alamofire. 
I have tested the code outside the get handler and works as expected, but somehow when I  add it inside the router callback it doesn't.
It's like the execution is suspended once the block terminates.

Any ideas on how to overcome this issue?
Here is a sample code
```Swift
router.get("/test") { request, response, next in
 
    Alamofire.request("url...").responseJSON(completionHandler: { (_) in
        
        do {
            
            try response.status(.OK).send("OK").end()
            next()
        }
        catch {}
    })
}

Kitura.addHTTPServer(onPort: 5525, with: router)
Kitura.run()
```

Thanks

**Comment by naithar** [comment]
That's probably not a Kitura related issue.

First thing i did - i removed Alamofire usage from your example and used `URLSession` (as it is what Alamofire uses under the hood):
```swift
router.get("/test") { request, response, next in
    let task = URLSession.shared.dataTask(with: URL(string: "https://httpbin.org/get")!) { _ in
        do {
            try response.status(.OK).send("OK").end()
            next()
        }
        catch {}
    }
    
    task.resume()
}
```
And everything worked fine.

Then I tested only Alamofire with:
```swift
Alamofire.request("https://httpbin.org/get").response { response in
    print("OK")
}
sleep(5)
```
and i never received that "OK" text. Using `URLSession` worked fine as it did in the first example.

Could you please try using `URLSession` yourself and check if it works?

**Comment by cliapis** [comment]
Hello, Indeed the use of URLSession solves the problem. 
I will switch URLSession. Thank you.
