### ISSUE TITLE
Multipart - no data in Part.body

### ISSUE THREAD

**Issue by Daredevll** [IBM-Swift/Kitura#1032]
I'm trying to upload a file with simple html form using "multipart/form-data".
`request.body?.asMultiPart` passes as expected but then there's no data in the body. Here's a part of the print: `Kitura.Part.HeaderType.type: "Content-Type: text/plain"], body: Kitura.ParsedBody.raw(0 bytes)`

**Comment by ianpartridge** [comment]
As far as I'm aware this should work. Please reopen if you are still seeing this problem.
