### ISSUE TITLE
Does Kitura have something similar to PerfectRepeater ?

### ISSUE THREAD

**Issue by sohaeb** [IBM-Swift/Kitura#1033]
Perfect Repeater library enables recurring events to be executed, i.e: 

Repeater.exec(timer: 3.0, callback: c)

**Comment by shmuelk** [comment]
@sohaeb Unlike Perfect, which tells you to **not** use Apple's Foundation library. Kitura was built with the use of Foundation in mind. See DispatchSourceTimer to get a block invoked on timer based events.
