### ISSUE TITLE
xcode 8.2.1 can not open the generated project

### ISSUE THREAD

**Issue by Jaykong** [IBM-Swift/Kitura#1037]
1. swift package  init --type executable
2. swift package generate-xcodeproj
if i did not include dependency of kitura, it work well.
However, it can not open by xcode if dependency of kitura is included

**Comment by na-gupta** [comment]
@Jaykong Could you please provide some more details starting with the error message.

**Comment by na-gupta** [comment]
@Jaykong Please create a new issue if this is still a problem.
