### ISSUE TITLE
SSL performance analysis

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1041]
I started on a simple SSL-enabled benchmarking exercise a couple of months ago, but was blocked by #983 and #991.

Now that these are resolved, I'd like to look at how we perform with SSL - the cost of the initial handshake vs. cost of encryption (eg. for keepalive connections), how we perform on Mac vs Linux,  and how Kitura compares to other frameworks (eg. Express/js).

**Comment by ianpartridge** [comment]
Closing as our performance work is currently focussed towards NIO.
