### ISSUE TITLE
clone_build_kitura.sh is missing

### ISSUE THREAD

**Issue by NikolasEisberg** [IBM-Swift/Kitura#1045]
There was another issue for this problem which was fixed a year ago #270 
I´ve tried to create the docker container with the current image (see logs below), but the file is missing again.
I´ve done all steps that are mentioned in this [guide](http://www.kitura.io/en/starter/deploying.html).

I´m using the latest version of Docker and macOS.
If you need any further information feel free to say so.

Terminal Output:

OPO:myFirstProject nikolaswerner$ docker pull ibmcom/kitura-ubuntu:latest

latest: Pulling from ibmcom/kitura-ubuntu

30d541b48fc0: Pull complete 

8ecd7f80d390: Pull complete 

46ec9927bb81: Pull complete 

2e67a4d67b44: Pull complete 

7d9dd9155488: Pull complete 

92946cebb21d: Pull complete 

ddd76bab96e1: Pull complete 

9ee211dfe651: Pull complete 

58e71740cd09: Pull complete 

1a5f48301d58: Pull complete 

9c4b83cae1a2: Pull complete 

0ff1401e684f: Pull complete 

66b597bd884b: Pull complete 

def932b893cc: Pull complete 

2b66fb10a8d5: Pull complete 

400ac4700791: Pull complete 

Digest: sha256:a3c10ccfef8106ed095872d5ebfbcb5f6de0fdbbcb0450f0e3157a6faf3399dd

Status: Downloaded newer image for ibmcom/kitura-ubuntu:latest

OPO:myFirstProject nikolaswerner$ docker run -i -p 8090:8090 -t ibmcom/kitura-ubuntu:latest /bin/bash

root@356ee7d59140:~# /root/clone_build_kitura.sh

bash: /root/clone_build_kitura.sh: No such file or directory

root@356ee7d59140:~# find -iname "clone_build_kitura.sh"

root@356ee7d59140:~#

**Comment by rolivieri** [comment]
@NikolasEisberg Hello, those instructions are a little outdated. I will file an issue against the guide (kitura.io) soon. In the meantime, I'd suggest you instead go to the README for Kitura-Starter: https://github.com/IBM-Bluemix/Kitura-Starter. There you will find the most up to date information. Also, at the bottom of the README, you will find links to blog posts that have been recently updated about running Kitura-Starter in a container. If after this, you still run into issues, please let us know by opening an issue under the Kitura-Starter repo: https://github.com/IBM-Bluemix/Kitura-Starter.

**Comment by NikolasEisberg** [comment]
Thanks for the help. With the instructions provided I was able to set it up on Bluemix.
