### ISSUE TITLE
Update Kitura repos to Swift 3.1

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Kitura#1047]

**Comment by youming-lin** [comment]
Steps for each repo:
1. Update `.swift-version` file to `3.1`
2. `swift package pin --disable-autopin`
3. Update `.travis.yml` with additional trusty build against 3.0.2 toolchain
4. Open PR, merge code, tag new release

**Comment by na-gupta** [comment]
In addition to disabling autopin, we also have to make sure no packages are already pinned by a prior swift command. The file contents should look like this:
```
{
  "autoPin": false,
  "pins": [],
  "version": 1
}
```
