### ISSUE TITLE
Clean up multiple directories inside Sources

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#1050]
Just had a problem with Kitura-CouchDB (which will become a radar soon, and I'll put the id here), where `xcodebuild` would segfault when trying to compile code coverage.  Although this is technically Xcode's fault, we can avoid the crash by removing the Sources/CouchDBSample directory.

This is a similar root cause as #974 - putting multiple subdirectories in the same Sources directory puts us in a situation that's rare and barely (if ever) tested.

We need to clean up all our repos and don't do that anymore.

**Comment by christiancompton** [comment]
Closing - reopen if needed.
