### ISSUE TITLE
getOriginalRepositoryPath() in staticFileServer/ResourcePathHandler broken in xcode

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Kitura#1051]
This line: `let currentFilePath = #file` in getOriginalRepositoryPath() assumes that the value will be:
```
        // <original repository directory>/Sources/Kitura/staticFileServer/ResourcePathHandler.swift
        // the original repository directory is four path components up
```
However, with Swift 3.1, when Kitura is a dependency, the value is actually something like:
```
<original repository directory>/.build/checkouts/Kitura.git-6522211175291160341/Sources/Kitura/staticFileServer/ResourcePathHandler.swift
```

When running tests in Kitura itself, the value is still what it used to be, and so Kitura tests run fine.

However, this breaks several Kitura-Sample tests (where Kitura is a dependency) when running inside xcode 8.3 or using `xcodebuild test`
The same tests pass when using `swift test` with swift 3.1 because they use the current working directory to get the path to the file.

This can also break applications using Kitura StaticFileServer when running the application from xcode.

**Comment by carlbrown** [comment]
Put this in Slack, but should put it here, too.  Note that Apple considers the location where dependencies are checked out an "implementation detail" and reserves the right to change it on a whim.

**Comment by shmuelk** [comment]
Fortunately while we are tied somewhat to the location of the Kitura repository, we are not in any way tied to the name of the directory.

This "dependency" is actually in two places. The commit above fixes both f them for now.....
