### ISSUE TITLE
Responses render unicode string output incorrectly.

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#106]
![screen shot 2016-02-09 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/1310293/12930072/e800b3da-cf3b-11e5-8165-492f9e0b06ce.png)

**Comment by dfirsht** [comment]
@rfdickerson Can you elaborate on this?

**Comment by rfdickerson** [comment]
Not really sure what more to say, the screenshot above shows couldn (a with a cap) (euro) (trade mark) t when it should just say "couldn't"

**Comment by dfirsht** [comment]
Just tested this, seems to be working for me:
<img width="698" alt="screen shot 2016-03-08 at 3 12 44 pm" src="https://cloud.githubusercontent.com/assets/5191832/13616615/4bbfeed0-e540-11e5-8d89-658001f41b8a.png">
