### ISSUE TITLE
Kitura-WebSocket is broken on Linux on Swift 3.1

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#1063]
Kitura-WebSocket is broken on Linux on Swift 3.1 until https://bugs.swift.org/browse/SR-4435 is fixed or we have a work around.

**Comment by quanvo87** [comment]
There was a Data fix on swift-3.1 that looks to have solved this. https://bugs.swift.org/browse/SR-4435

**Comment by ianpartridge** [comment]
It's likely that Swift 3.1.1 will be released soon, containing this fix.

**Comment by shmuelk** [comment]
Kitura-WebSocket works on Swift 3.1.1 on Linux. All of the unit tests pass, which wasn't the case on Swift 3.1.
