### ISSUE TITLE
Kitura Xcode Errors

### ISSUE THREAD

**Issue by codesworth** [IBM-Swift/Kitura#1067]
I have a simple Kitura project running in xcode but it fails to build with Apple Mach-O Linker (ld) error clang: error: linker command failed with exit code 1 (use -v to see invocation). The Kitura framework is highlighted in the editor as No Such Module "Kitura". However running .build/debug in terminal runs the project on the localhost successfully. What could be wrong

**Comment by quanvo87** [comment]
Try deleting your .build folder and running `swift build` again in the terminal. Then try compiling in Xcode.

**Comment by na-gupta** [comment]
Which version of xcode and Kitura are you using?

You can try deleting your Kitura,xcodeproj/ directory and regenerating it: `swift package generate-xcodeproj`

Then open the newly generated xcodeproj and go to the Product menu. Hold the option key and the "Clean" menu option turns to "Clean Build Folder ...". Do that and try building/running again.

**Comment by codesworth** [comment]
Im running xcode 8.3 with Kitura 1.7.1. I did as suggested in both instances, the error of No such module "Kitura" goes away but it still fails to build or run with 2 errors ;
Apple Mach-O Linker (ld) error clang: error: linker command failed with exit code 1 (use -v to see invocation). in both Kitura and KituraNet modules

**Comment by youming-lin** [comment]
@codesworth Can you try the solution suggested here? https://swift-at-ibm.slack.com/archives/C29BEUQH3/p1491912523697331

**Comment by codesworth** [comment]
I resolved the issue. It appears i had installed swift package manager last year that set my swift version to 3.0GM. Resetting it back to system default as defined by xcode 8.3 resolved the issue.
