### ISSUE TITLE
Replace port 8090 by 8080 in code examples

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#1069]
The query to see 8090 in the code https://github.com/search?q=org%3AIBM-Swift+8090&type=Code.
Currently, 69 references.

**Comment by vadimeisenbergibm** [comment]
A command to find 8090 in Sources, Tests, *.md and *.swiftdoc files:
`find Sources  -type f -exec grep -l '8090' {} \; && find Tests  -type f -exec grep -l '8090' {} \; && find . -name "*.md" -type f -exec grep -l '8090' {} \; && find . -name "*.swiftdoc" -type f -exec grep -l '8090' {} \;`

**Comment by ibhupi** [comment]
Nice!!

**Comment by christiancompton** [comment]
Closing as complete.
