### ISSUE TITLE
Registering a template engine with a subrouter

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura#1070]
Snippet from main router code:

```
router.all("/site", middleware: [session, credentials, SiteRouter.make()])
```

`SiteRouter.make()`:

```
static func make() -> Router {
    let router = Router()
    router.add(templateEngine: StencilTemplateEngine())
    router.get("/home", handler: homeHandler) // renders a stencil
    return router
}
```

This does not work. When I call `/site/home` I get a `Cannot GET /site/home` response.
After some experimentation, I got the code working by calling `router.add(templateEngine: StencilTemplateEngine())` on the main router.
This issue is now reproducible for me, by moving the call to `add` from the main router to the subrouter and back.

**Comment by vadimeisenbergibm** [comment]
After checking the current implementation: today you can set add templateEngine to the "main" router only. We plan to implement "cascading" of template engines, so the users will be able to add template engines to any router in the sub routers chain, including the main router and the current sub-router. So the sub-router will be able to use any template engine that was added by itself, or by any other router in the chain, up to the main router.

**Comment by christiancompton** [comment]
Closing this as complete - please let us know if this is still a problem @svanimpe.
