### ISSUE TITLE
Cannot send large json data on linux

### ISSUE THREAD

**Issue by sujaykakkad** [IBM-Swift/Kitura#1073]
I have a piece of json
```swift
     let json = JSON.parse("huge string")
     try response.status(.OK).send(json: json).end() //This throws oversizeData error on linux
```
The content length of the json response is 183575
I get the response in mac but on linux it throws error
I know the json size is very big but then it should throw error on mac as well

**Comment by sujaykakkad** [comment]
It is not allowing me to send raw string
I also tried by sending raw string and then setting response headers as application/json but still it is throwing error in linux. In mac it is working.

**Comment by shmuelk** [comment]
Are you using Kitura with FastCGI or with a standard HTTP server?

**Comment by sujaykakkad** [comment]
I am using it with FastCGI. I tested the same with HTTP server on Linux but then it didn't throw any error. So the problem is with FastCGI server on linux.

**Comment by shmuelk** [comment]
@sujaykakkad That's actually good news. That makes this issue a duplicate of IBM-Swift/Kitura-net#180. There is a PR for that issue.

**Comment by shmuelk** [comment]
I just merged and tagged the PR that fixes the problem with large responses when using FastCGI.

Please make sure that you do a `swift package update' before trying to rebuild.

**Comment by sujaykakkad** [comment]
Oh thats great. Let me know when the pull request is updated so that I can test it and close this issue.

**Comment by shmuelk** [comment]
It is already merged and tagged. Please rebuild and test

**Comment by sujaykakkad** [comment]
Yes It is working as expected.
Thanks.
