### ISSUE TITLE
Request wont recognise parameters 

### ISSUE THREAD

**Issue by HelgeBecker** [IBM-Swift/Kitura#1079]
Given this url:
    http://localhost:8080/foo;ba?fuu=bo

According to RFC 1808 it should recognise 'ba' as parameter, but it doesn't.
On the other side does NSURL recognise parameters. 
[https://developer.apple.com/reference/foundation/nsurl/1412797-parameterstring](url)

Serverside testimplementation

```
router.all() {
    request, response, next in
    var returnString = "\(request.parameters.count) parameters: "
    for param in request.parameters {
        returnString += param.value
        returnString += " "
    }
    
    returnString += "\(request.queryParameters.count) queryParameters: "
    for queryParameter in request.queryParameters {
        returnString += queryParameter.value
        returnString += " "
    }

    response.send(returnString)
    next()
}
```

**Comment by youming-lin** [comment]
AFAICT, [RFC 1808 has been obsoleted by RFC 3986](https://www.rfc-editor.org/info/rfc3986), and [RFC 3986 doesn't support `;`-style parameters](https://www.ietf.org/rfc/rfc3986.txt). In fact, the `parameterString` instance var does not exist in the `URL` class.

**Comment by TDO-Becker** [comment]
I'm strongly suggest reread of RFC 3986.
Quote form Page 22

RFC 3986                   URI Generic Syntax               January 2005

```
.. Aside from dot-segments in hierarchical paths, a path segment is
   considered opaque by the generic syntax.  URI producing applications
   often use the reserved characters allowed in a segment to delimit
   scheme-specific or dereference-handler-specific subcomponents.  For
   example, the semicolon (";") and equals ("=") reserved characters are
   often used to delimit parameters and parameter values applicable to
   that segment.  The comma (",") reserved character is often used for
   similar purposes.  ....
```

**Comment by youming-lin** [comment]
The semantics of the semicolon is now dependent on the "URI producing application" as opposed to being defined in the spec itself as it was in [RFC 1808](https://tools.ietf.org/html/rfc1808#section-2.4.5). The section quoted suggests that it is up to the application to define the semantics for semicolon as opposed to the spec itself.

**Comment by TDO-Becker** [comment]
Still doesnt help integrating a Kitura backend among other backends, which isnt the reason why we stooed evaluating Kitura but it adds to it. good luck with it.

Mit freundlichen Grüßen

Helge Becker
iOS Developer
Technidoo Solutions UG
Ahornweg 50<x-apple-data-detectors://1/0>
63741 Aschaffenburg<x-apple-data-detectors://1/0>
Telefon +49 (0) 211 90 32 94 – 801<tel:+49%20211%2090%2032%2094%20%E2%80%93%20801> / Fax – 444
www.<http://www.technidoo.com/>technidoo.com<http://www.technidoo.com/>
HRB 13343, Amtsgericht Aschaffenburg

Am 01.06.2017 um 08:14 schrieb Youming Lin <notifications@github.com<mailto:notifications@github.com>>:


The semantics of the semicolon is now dependent on the "URI producing application" as opposed to being defined in the spec itself as it was in RFC 1808<https://tools.ietf.org/html/rfc1808#section-2.4.5>. The section quoted suggests that it is up to the application to define the semantics for semicolon as opposed to the spec itself.

**Comment by youming-lin** [comment]
@TDO-Becker
I wasn't trying to be confrontational about this; you (I assume OP is your other account) mentioned RFC 1808 as the reason why we should support it, and I responded by saying that as of RFC 3986 the semicolon parameter semantics is no longer explicitly mandated by the spec.

You are of course free to choose the backend framework you want to use, but it doesn't help us at all when you curtly say "good luck with it" without expanding on the other reasons you hinted at (Sorry if I missed your true reasons for stopping evaluation of Kitura if you had previously posted them elsewhere). We all want to improve Kitura, and by no means is my opinion always the one chosen by my team.
