### ISSUE TITLE
Use nghtpp2 for HTTP/2 cleartext (non-secured) connection

### ISSUE THREAD

**Issue by ymesika** [IBM-Swift/Kitura#1086]
The http2 spec allows client to move to HTTP/2 protocol over an established non-secured HTTP/1.1 connection by sending HTTP upgrade request.
Although this is not common as all of the modern browser are opening HTTP/2 connection over SSL we begin with this for initial creation and integration of the Kitura-HTTP2 with nghttp2.

**Comment by ianpartridge** [comment]
Our current plan is for HTTP/2 support to come via https://github.com/apple/swift-nio (when it's available) so I'm closing this for now.
