### ISSUE TITLE
Building a context in middleware

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura#1092]
I am using Stencil's template inheritance feature to build my web front-end. This means my contexts have at least two parts:
- whatever my parent template requires.
- whatever the child template requires.
That first part is quite a chore as I have to build this context in every handler. I wrote a utility function to generate a base context (for the parent template) based on state stored in the current session, but I still have to use this utility in every handler.

I am hoping for a solution where I can use middleware to build this base context. Perhaps something like `response.context` that can be filled in by middleware and added to by the `context` parameter of the `render` method? In any case, I think this is quite a common scenario, so a better solution than what I'm currently doing would be much appreciated.

**Comment by shmuelk** [comment]
There is RouterRequest.userInfo, which is a simple Dictionary that is in memory for the life of the request. This field can be filled by Middleware and RouterHandlers as you want.

**Comment by svanimpe** [comment]
This works, thanks for the tip. Seems like I was looking in the wrong place (`RouterResponse`). I wonder if this use case is common enough to warrant a separate field that can be read by `render`? All my render calls now contain `context: request.userInfo.appending([.....])`.
