### ISSUE TITLE
Support HTTP/2 over TLS (https)

### ISSUE THREAD

**Issue by ymesika** [IBM-Swift/Kitura#1096]
Supporting client/browser that makes a request to an "https" URI uses TLS with the application-layer protocol negotiation (ALPN) extension. 
Secured HTTP/2 connection is more common than non-secured ( #1086 ) as all of the modern browsers are capable of opening HTTP/2 connection over TLS but not unsecured.

**Comment by ianpartridge** [comment]
Our current plan is for HTTP/2 support to come via https://github.com/apple/swift-nio (when it's available) so I'm closing this for now.
