### ISSUE TITLE
Create a Kitura-router middleware for session management

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#11]
<a href="https://github.ibm.com/KALLNER"><img src="https://avatars.github.ibm.com/u/3096?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KALLNER](https://github.ibm.com/KALLNER)**
_Thursday Jan 07, 2016 at 10:15 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/11_

----

Create a Kitura-router middleware for session management.

The method used for session storage should be pluggable.

The initial one, which is probably the only built-in one, is for in-memory storage.

A nice session storage to have would be around Redis and some No-SQL DB

**Comment by rolivieri** [comment]
@shmuelk Is this work item for allowing multiple instances of Kitura running in parallel access the session data of a user from a storage system (e.g. Redis)? Or were you just thinking of storing session data in a separate storage system so that it survives a Kitura crash?

**Comment by shmuelk** [comment]
Actually it's to supports Session's like you have in most HTTP Servers.

That is multiple requests that are part of a larger session. If done correctly, one's handlers can still be sort of stateless, with state stored in a shared "state storage" shared by multiple servers. Giving better performance and resilience.

**Comment by irar2** [comment]
Reviewed the code. Tested with Credentials.
