### ISSUE TITLE
Documentation request: Password for SSLConfig

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/Kitura#1102]
On https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/SSLConfig.swift#L72, a password can be used. Where does this come from? Using the instructions here to generate the keys and certificates https://developer.ibm.com/swift/2016/09/22/securing-kitura-part-1-enabling-ssltls-on-your-swift-server/, this asks for two passwords: A challenge password, and an export password. Is it one of these?

**Comment by crspybits** [comment]
I figured it out-- it's the "export password:". Could be good to add that to the docs. Thanks.

**Comment by kweinmeister** [comment]
Fixed in PR #1108
