### ISSUE TITLE
Please provide example about how to use IBM's 'Carbon Design System' with Kitura

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/Kitura#1103]
Carbon Design System is a nice open source project from IBM.
It would be great to have some examples about how to use it in a 'best-practice' way with Kitura.

**Comment by bschwanke** [comment]
Hi @gmosx , We can work on this together. Let me know what your ideas are, and how I can help.

**Comment by jkingoliver** [comment]
Hi @gmosx, check out this sample that I built that has a Kitura Swift backend and a simple frontend with a Carbon Design component. 

The readme has detailed instructions for how to: 
1. Create a Kitura Swift application using a Yeoman generator
2. Install IBM Carbon Design System artifacts using `npm install`
3. Build out a web page and integrate the Carbon Design components of interest

Let me know if you have any questions!
https://github.com/jkingoliver/Kitura-Carbon-Sample

**Comment by gmosx** [comment]
Thank you Jennifer, the example looks useful. I will check it later today.

**Comment by christiancompton** [comment]
Closed because

**Comment by ianpartridge** [comment]
Hi @gmosx hopefully the example helped you. Please reopen if we can help any more.
