### ISSUE TITLE
Replace SwiftyJSON with ObjectMapper

### ISSUE THREAD

**Issue by adozenlines** [IBM-Swift/Kitura#1104]
https://github.com/Hearst-DD/ObjectMapper

**Generate Models for JSON de/serialization Xcode Plugin**
https://github.com/liyanhuadev/ObjectMapper-Plugin

**Comment by youming-lin** [comment]
@adozenlines 
If I understand correctly, that package's features looks very much like what `Codable` will provide in Swift 4: https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md

**Comment by adozenlines** [comment]
Let me take a peek ...

**Comment by adozenlines** [comment]
It sure does look somewhat similar with the extra safety and types.

**Comment by youming-lin** [comment]
We want to rely less on third-party libraries and more on Foundation, so the new `Codable` framework is what we want to leverage. Removing `SwiftyJSON` will be a breaking change (since it's exposed in Kitura's public APIs), so this migration won't happen before the next major Kitura version.

**Comment by adozenlines** [comment]
Well that's going to be like any other API deprecation process in favour of the Foundation framework. I will delete this thread.

**Comment by tettoffensive** [comment]
@youming-lin I'm starting a new project in swift 4 and I'd prefer just to use Codable if it's going to be added soon. I looked into subclassing BodyParser but ran into a bunch of issues there

is there an eta on when the switch to Codable will be made?

**Comment by youming-lin** [comment]
@tettoffensive I don't have an ETA, but this PR will likely be the first step towards `Codable` support: https://github.com/IBM-Swift/Kitura/pull/1163

**Comment by seabaylea** [comment]
@tettoffensive It you take a look at the issue.swift4 branch, there's a lot of work there to add direct support for Codable into the routing framework - that's going to be merged in real soon now (tm).
