### ISSUE TITLE
Always get error: unsatisfiable while build and fetch if I use kitura 1.7

### ISSUE THREAD

**Issue by sangy05** [IBM-Swift/Kitura#1105]
I was using 1.6 Kitura version & recently I changed the dependency package file having Kitura 1.7. But the buil never happens .. somehow ,the fetch fails & always returns " error: unsatisfiable "

**Comment by shmuelk** [comment]
Make sure that you removed .build and Package.pins, before rebuilding.

**Comment by sangy05** [comment]
Yes :) It worked . Thanks .. But why did it happen ? Could you tell me ?

**Comment by shmuelk** [comment]
There were old versions of the dependencies of Kitura in your .build/checkouts directory. Also the Package.pins file, by default, pins your dependencies to a set of specific versions. That list when you built with Kitura 1.6 wasn't compatible with Kitura 1.7.

**Comment by sangy05** [comment]
Great .. Thanks

**Comment by youming-lin** [comment]
Closing issue as the issue has been solved.
