### ISSUE TITLE
Supported Swift versions for Kitura 1.2, 1.3, 1.5, 1.6

### ISSUE THREAD

**Issue by KristofMercier** [IBM-Swift/Kitura#1110]
Hello, I work for the IBM Linux on Z ecosystem team, and I am trying to find out if there is a problem on our end running Kitura versions. It does not specify which Swift versions are supported on the above releases, and I need to know in order to ensure our system is behaving properly. Could someone either label the supported swift versions on these releases, or else respond here and let me know?

Thanks

**Comment by kweinmeister** [comment]
@KristofMercier You can click on the tag icon for each release, to see the code that was tagged at that point in time: https://github.com/IBM-Swift/Kitura/releases. From there, you can look for the `.swift-version` file to determine the support Swift version. Please let us know if that helps.

**Comment by youming-lin** [comment]
@KristofMercier 
You can find the supported Swift version in the `.swift-version` file at project's root for at each version snapshot.

Off top of my head 1.2-1.6 all support Swift 3 (either 3, 3.0.1, or 3.0.2). We made the jump to 3.1.1 in Kitura 1.7.

**Comment by KristofMercier** [comment]
That works! Thank you.

**Comment by youming-lin** [comment]
YW!!! I will close this issue now.
