### ISSUE TITLE
Email sending Kitura

### ISSUE THREAD

**Issue by GiacomoLeopizzi** [IBM-Swift/Kitura#1111]
Is it possible to send email using Kitura? If so, how?

Many thanks! 
Giacomo

**Comment by youming-lin** [comment]
Hi @GiacomoLeopizzi 
We are working on an SMTP client, which we hope to release soon :)

**Comment by GiacomoLeopizzi** [comment]
How soon is soon :) ?

**Comment by youming-lin** [comment]
@GiacomoLeopizzi
No guarantees, but we are hoping for next week due a last issue bug that needs fixing. How soon do you need it?

**Comment by GiacomoLeopizzi** [comment]
@youming-lin Actually as soon as possible. We used another library but on stress test it crashes because of some force-unwrapping... It's so annoying ;)

**Comment by youming-lin** [comment]
@GiacomoLeopizzi 
I'll ask my team and see if we can release it sooner. Unfortunately, we haven't stress-tested our package either, but we are definitely willing to fix any bugs found.

**Comment by quanvo87** [comment]
@GiacomoLeopizzi [Swift-SMTP](https://github.com/IBM-Swift/Swift-SMTP) has been released. Please let us know of any issues you come across!

**Comment by GiacomoLeopizzi** [comment]
@quanvo87 @youming-lin  Thank you so much!
