### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura#1114]
I have the following code in my first middleware (used on all routes):
```
if request.originalURL.hasPrefix("http://") {
   Log.info("--- Adding SSL")
   try response.redirect(request.originalURL.replacingOccurrences(of: "http://", with: "https://"))
}
next()
```
The goal here is ofcourse to make sure all requests are using https. This redirection works in the sense that the client is indeed redirected to `https://...`. However, the value of `originalURL` always starts with `http://` so my app gets stuck in an infinite loop and I end up with a "Too many redirects" error.

This may be the cause of other issues as well, as I've noticed from time to time that my app suddenly jumps from https to http.

**Comment by svanimpe** [comment]
I have also inspected `request.urlURL.scheme` and that always returns `http` as well.

**Comment by shmuelk** [comment]
Are you redirecting to a server on Bluemix? If so, I don't you'll ever see it as HTTPS:, On Bluemix SSL/TLS is terminated on proxy servers and forwarded to you as regular HTTP.

**Comment by svanimpe** [comment]
Yes. my app requires SSL so I added that check/forward to make SSL the default. If this will work, then how do I accomplish what I need?

**Comment by shmuelk** [comment]
I would check the headers to see if it was forded through Bluemix's TLS/SSL termination.

**Comment by svanimpe** [comment]
I see a couple of headers that seems related to this:
```
$WSIS: "true"
$WSSP: "443"
$WSSC: "https"
X-Forwarded-Proto: "https"
```
Which one do you recommend I use?

**Comment by shmuelk** [comment]
X-Forwarded-Proto with a value of https, would imply that the request was originally https. Was it?
I’d add logging to see what that value is, on every request.
Just to make sure of what is going on. Including on the original request with HTTP.

**Comment by svanimpe** [comment]
It was, and the value of `X-Forwarded-Proto` seems to be consistent based on my tests and logs, so I'll try that!

**Comment by svanimpe** [comment]
So far everything works for me using `X-Forwarded-Proto`.
