### ISSUE TITLE
Update Kitura repos for Swift 4

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Kitura#1121]
- Update kitura related repos to work with swift 4, while maintaining backwards compatibility with swift 3.1.
- Add travis builds with the latest swift 4 snapshots to the existing swift 3.1 builds.
- .swift-version should be updated to 4.0 only after swift 4 is released and stay at latest 3.x till then.

**Comment by quanvo87** [comment]
Blocked awaiting data on traffic/clones of the repos. This will help us decide which repos we can delete/deprecate and reduce unneeded work.

**Comment by quanvo87** [comment]
Also working with Ricardo and Package Builder for ways to better automate this process.

**Comment by rolivieri** [comment]
this is done.
