### ISSUE TITLE
App server crash after running for sometime 

### ISSUE THREAD

**Issue by portergoh** [IBM-Swift/Kitura#1127]
Hi Support,

The app server always crash after i ran it for few days and the error was

[ERROR] [IncomingHTTPSocketProcessor.swift:198 parse] Failed to parse a request. Parsed fewer bytes than were passed to the HTTP parser

**Comment by kweinmeister** [comment]
@portergoh Which version of Kitura are you using? Can you try upgrading to the latest to see if the issue still exists?

**Comment by tunniclm** [comment]
We fixed an issue recently (in Kitura-net `1.7.20`) that caused a crash on this message when a malformed request is encountered on a keep alive connection.

**Comment by christiancompton** [comment]
@portergoh I am closing this issue, please reopen if one of the recent versions still causes these problems.
