### ISSUE TITLE
Request throwing error on multiple parallel requests

### ISSUE THREAD

**Issue by sujaykakkad** [IBM-Swift/Kitura#1138]
```sh
Error in RouterResponse end(): Error code: -9980(0x-26FC), Broken pipe
```

**Comment by sujaykakkad** [comment]
Actually this is the complete error
```sh
[WARNING] [RouterResponse.swift:144 deinit] Error in RouterResponse end(): Error code: -9980(0x-26FC), Broken pipe
```

**Comment by na-gupta** [comment]
@sujaykakkad Could you please confirm that you're using the latest version of Kitura (1.7.6) with a clean build and with updated dependencies.

If you are still seeing this, could you describe how to replicate the error, preferably with a small concrete example. Thanks.

**Comment by sujaykakkad** [comment]
Actually it has only come once or twice. I am not able to reproduce it for now. But the version is the same (1.7.6)
