### ISSUE TITLE
how can use Kitura with swift 4.0 ?

### ISSUE THREAD

**Issue by AzAli71** [IBM-Swift/Kitura#1156]
hi , I upgraded my Swift version to swift 4.0 , now I don't know how can import kitura to swift.package 
swift.package syntax has changed and I don't know how can add kitura to package.swift in swift v 4.0 the your tutorial in your website hast expired and their does not work in swift.package with swift 4.0 now I want to add Kitura and HeluimLogger to my package.swift but I can't :( because compiler show compile error in swift 4 , please update your document for usage of Kitura with Swift 4

**Comment by AzAli71** [comment]
import PackageDescription

let package = Package(
    name: "MyApp",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
	.package(url: "https://github.com/IBM-Swift/Kitura.git" , from: "1.7.9"),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git" , from: "1.7.1")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "MyApp",
            dependencies: []),
    ]
)



this is my Package.swift but when I import Kitura in main.swift it shows an error and it can not detect Kitura as framework 
[Swift 4.0]

**Comment by youming-lin** [comment]
@AzAli71 You have to add `Kitura` to your target's dependencies as well:
```swift
targets: [
    // Targets are the basic building blocks of a package. A target can define a module or a test suite.
    // Targets can depend on other targets in this package, and on products in packages which this package depends on.
    .target(
        name: "MyApp",
        dependencies: ["Kitura"]
    ),
]
```

**Comment by AzAli71** [comment]
tnx a lot  , if is possible please update Kitura documentation in kitura.io -> get start section -> package.swift
