### ISSUE TITLE
Migrate Kitura-Sample to Swift 4

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#1159]
https://github.com/IBM-Swift/Kitura-Sample currently specifies `3.1.1` in `.swift-version`.

The repo needs migrating to Swift 4.

**Comment by imjog** [comment]
@ianpartridge i want to work on this. Should i take this issue?

**Comment by ianpartridge** [comment]
Fixed in https://github.com/IBM-Swift/Kitura-Sample/pull/75
