### ISSUE TITLE
Swift 4.0.2 String.characters deprecation warnings

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1170]
`String.characters` has been deprecated in Swift 4 (https://github.com/apple/swift/pull/11881), although it appears this didn't make it into the initial 4.0 release.

Building with 4.0.2 results in warnings such as:
```
Sources/KituraNet/ClientRequest.swift:169:32: warning: 'characters' is deprecated: Please use String or Substring directly
                    if thePath.characters.first != "/" {

Sources/Kitura/contentType/ContentType.swift:77:88: warning: 'characters' is deprecated: Please use String or Substring directly
            lastPathElemRange = fileName.index(after: lastSlash.lowerBound)..<fileName.characters.endIndex
```

**Comment by morganzellers** [comment]
Are you working on refactoring out `.characters`??

**Comment by djones6** [comment]
@morganzellers It looks like most repos have already been addressed, eg:
- https://github.com/IBM-Swift/Kitura/pull/1177
- https://github.com/IBM-Swift/Kitura-net/pull/233

I'm going to close this issue, however I'll see if it would make sense for us to open some 'starter' type issues for pick up.

**Comment by morganzellers** [comment]
Sounds good, thanks @djones6!
