### ISSUE TITLE
Kitura 2.0 415 Unsupported Media Type for all Codable json requests

### ISSUE THREAD

**Issue by tettoffensive** [IBM-Swift/Kitura#1171]
I've been getting `415 Unsupported Media Type` after upgrading to 2.0 for all my requests. Turns out that this method is the culprit

```swift
private func isContentTypeJson(_ request: RouterRequest) -> Bool {
  guard let contentType = request.headers["Content-Type"] else {
    return false
  }
  return (contentType == "application/json")
}
```

I'm using the client Paw to test my application which sends this request:

```
curl -X "POST" "http://localhost:8080/endpoint" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'[...]'
```

If I change the line to read:
```swift
return (contentType == "application/json; charset=utf-8")
```

Then I no longer get the `415`

So I'm not sure if the string compare should check if it starts with `application/json`? Or maybe there's a better solution?

**Comment by seabaylea** [comment]
Thanks Stuart - yes, it should be checking starts with rather than equals.
