### ISSUE TITLE
Getting all registered routes.

### ISSUE THREAD

**Issue by KingAndroid** [IBM-Swift/Kitura#1182]
Hi, Kitura.
How are you and so glad to use this powerful library.

Could you please tell me how to get all registered routes from Route Class?
I think all routes are saved to elements variable of Router Class.
`
public class Router {

    /// Contains the list of routing elements
    var elements: [RouterElement] = []
`
I want to get all those elements with accessible function.
Is there any solution for this?
Please let me know method for this problem.
Great regards.

**Comment by seabaylea** [comment]
Hi @KingAndroid. I don't think there's a public API today that lets your traverse over the set of registered routes/handlers.

Would it be possible to describe your use case for having access to that information, ie. what you would like to achieve?

**Comment by KingAndroid** [comment]
Hello.
Thanks for your reply and I am wanting to get all available routes just like in Laravel.
Please check the screen below.
![snip_20171120142246](https://user-images.githubusercontent.com/4363735/33005035-edeb47a6-cdfe-11e7-8ace-d9f42d91000f.png)

Great regards.

**Comment by seabaylea** [comment]
Hi @KingAndroid. Is this in order to build a solution for #1183, or would you need access to the routes programmatically for other reasons?

**Comment by KingAndroid** [comment]
Hi @seabaylea .
Thanks for your reply and no, I am wanting to get those routes not just from API Documentation.
I am also want to check many things from server side.
For instance, avoiding duplicated table creation and so on.
It was so useful for check things with Laravel.

So I am just want to get all routes from a variable of Kitura that I mentioned at the beginning of this chat field, you know.
BTW, your message from #1183 was so great and I would wait for your finishing time of API Documentation.
Thanks again and bye for now.
Great regards.

**Comment by seabaylea** [comment]
Ok - I'll close this one and convert #1183 to an enhancement request.
