### ISSUE TITLE
Add SwiftDocs Kitura-Redis

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#119]

**Comment by dfirsht** [comment]
@rfdickerson Robert, can you point us to the documentation that describes how to annotate the comments so that the Swift docs tool (http://swiftdoc.org/) can parse it? Also do we already have this for the other repos?

**Comment by rfdickerson** [comment]
Yes, that was my priority- the documentation has been added for Kitura-sys, Kitura-net, and Kitura-router. It takes hours of work, so didn't get around to doing it for these packages. I based it on @billabt 's style. I am not sure where the documentation is for properly documenting code.

**Comment by dfirsht** [comment]
blocked until #135 is complete

**Comment by billabt** [comment]
An' I found it via some code inspection of the Apple code. The doc then appears in Xcode if you hover over a function or variable.

**Comment by dfirsht** [comment]
Great job Robert, looks awesome! We can discuss whether to document private funcs at a later date.
