### ISSUE TITLE
Error listening on port 8090

### ISSUE THREAD

**Issue by Hamza-Almass** [IBM-Swift/Kitura#1191]
Hello All , 

i hope all is well 
please i have an issue when i build my app i get the message  (Error listening on port 8090 Address already in use. Use server.failed(callback:) to handle
Program ended with exit code: 0) and the home screen for kitura it's not load

please how can i fix it 

thanks a lot

**Comment by seabaylea** [comment]
The implication is that something on your machine is already using port 8090. 

On a Mac, you can find out which process is using that port using:
```
lsof -n -i:8090
```
which should give you the COMMAND (name) and the PID (process ID) of the process.

**Comment by Hamza-Almass** [comment]
thank you very much i will check it
