### ISSUE TITLE
kitura init creates project with older kitura modules

### ISSUE THREAD

**Issue by hactar** [IBM-Swift/Kitura#1194]
**Problem**
Running `kitura init` version 0.0.9 (which appears to be the newest version) creates a project that uses older kitura modules, such as kitura-net 1.7.20 instead of 2.0.0. There may be others too, but this one stood out to me as it still generates the warnings for characters being deprecated, which I assume have been resolved in 2.0.0.

**Expectations**
I'd expect `kitura init` to generate a project which compiles without warnings on swift 4.0.

```
/Users/patrick/Documents/localgit/WienPlaces/.build/checkouts/Kitura-net.git--7410958935072501107/Sources/KituraNet/FastCGI/FastCGIServerRequest.swift:235:33: warning: 'characters' is deprecated: Please use String or Substring directly
        for i in versionPortion.characters {
```

**kitura State**

Kitura comand line tool appears to be up to date.

```
# brew update
Already up-to-date.

# brew upgrade kitura
Error: ibm-swift/kitura/kitura 0.0.9 already installed
```

Attached is the Package.resolved that it generated for me.

[Package.resolved.zip](https://github.com/IBM-Swift/Kitura/files/1553702/Package.resolved.zip)

**Comment by tunniclm** [comment]
We are working through some issues in dependencies that are preventing us moving up to Kitura-net `2.0.0` as it will cause problems with some common version ranges. Particularly we want to ensure that projects using SwiftMetrics will resolve dependencies properly when we make the move.

We are currently finalising testing of a compatible SwiftMetrics which will unblock this upgrade. Thanks for your patience!

**Comment by hactar** [comment]
Ah yes, I see, kitura 2.0 still depends on kitura-net 1.7. Ok, not an init issue then, closing.
