### ISSUE TITLE
In router, root routes "/" without wildcards will always be hit

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#120]

**Comment by dfirsht** [comment]
An example of the incorrect behavior is that a route defined for "/" will still be hit if the request url is "/foo". We want to change this so that "/" will only be hit when the request url is "/" and "/*" can still be used to cause the current behavior.

**Comment by dfirsht** [comment]
Ready for validation. This fix added a special case to the buildRegexFromPattern method to ensure that root routes are only hit with an exact match. The fix is also written general enough to prevent similar issues if the route is specified as empty "" or (for some reason) multiple slashes "///...".

**Comment by dfirsht** [comment]
Assigned to @shmuelk for validation.

**Comment by shmuelk** [comment]
Validated via a small test program.
