### ISSUE TITLE
Issues with BluemixAppID and Kitura 2.1.3

### ISSUE THREAD

**Issue by StasIsLovE** [IBM-Swift/Kitura#1204]
Adding:

`.package(url: "https://github.com/ibm-cloud-security/appid-serversdk-swift.git", .upToNextMinor(from: "2.0.0"))`

as a dependency results in following error during the update:

> Updating https://github.com/IBM-Swift/Kitura-Session.git
> error: manifest parse error(s):
> The manifest file at https://github.com/IBM-Swift/CommonCrypto.git (0.1.3) is empty

I thought first that it was something with sub-dependencies of AppID, but as far as I could see it should use CommonCrypto 0.1.5, as does Kitura 2.1.3 when AppID is not added, but together somehow CommonCrypto 0.1.3 appears.

**Solution: Use Kitura 2.0.2**

When downgrading Kitura to versin 2.0.2, it works. Is it a bug or am I missing something about package manager that I am suppose to know?

**Comment by tunniclm** [comment]
@StasIsLovE Yes, unfortunately we have not yet updated the Swift appid SDK for Kitura 2.1.0. I am in the process of dealing with this right now (this and the Object Storage SDK and Push Notifications SDK are the last one's that I am aware of that need updating.)

**Comment by StasIsLovE** [comment]
I did't understand what was happening because all the dependencies seemed right. Thanks for the answer.

**Comment by tunniclm** [comment]
PR open against AppID SDK here: https://github.com/ibm-cloud-security/appid-serversdk-swift/pull/33

**Comment by vitalymibm** [comment]
@tunniclm @StasIsLovE Merged to development and master, published release 2.0.1, thank you.

**Comment by tunniclm** [comment]
@vitalymibm Thanks!

**Comment by vitalymibm** [comment]
@tunniclm @stasislove The release is re-tagged as 3.0.0, because of breaking changes (per request from @sandmman).
