### ISSUE TITLE
KituraNet needed to be included to send custom response status even Kitura depends on Kitura-Net

### ISSUE THREAD

**Issue by CosmicYogi** [IBM-Swift/Kitura#1207]
I was working on my project today and everything was working fine till a Saw a weird behavior.
I wanted to send custom `response codes` for few situations so I refactored the code and started to work on it.

There are 2 issues I faced -
1. You cannot send custom code without importing kituraNet and when you `Option + click` on it to get the info about it, It says declared in Kitura and nothing else I mean either the documentation can be updated or the situation can be better managed it becomes very confusing if someone doesn't know about it.

2. There is an ambiguity faced when you import `KituraNet` in your project and try to catch an error as `Error`.

**Comment by tunniclm** [comment]
I'm not sure what you mean by custom status code, can you past an example?

It is true that `HTTPStatusCode` is defined in the `KituraNet` module and you must import the defining module to refer to a type directly. Often you can avoid this by not naming type and relying on type inference. (Example: `response.status(.OK)` does not require `KituraNet` to be imported but `response.status(HTTPStatusCode.OK)` does)

**Comment by tunniclm** [comment]
It is unfortunate that `KituraNet` defines an `Error` type, and this conflicts with the one in `Swift`.
We should consider renaming it in a future major update, since it forces users of `KituraNet` to disambiguate the types with their module name (`KituraNet.Error` / `Swift.Error`) to use them.

**Comment by CosmicYogi** [comment]
Yeah, doing this the way `response.status(.OK)` worked without importing `KituraNet`. Thanks for the clarification.
It's good that it's working but I think it should be more clear I mean either it should be mentioned in the documentation so that programmers don't get confused while using it.
I also have a doubt I will PM you on Slack regarding it.
