### ISSUE TITLE
Failure to call callbacks leading to memory leaks.

### ISSUE THREAD

**Issue by drewmccormack** [IBM-Swift/Kitura#1216]
We have a Kitura server deployed, and have to restart it every 6 hours to stop it using excessive memory. It steadily climbs over time. Clearly a leak.

We thought it could be our code, so we have investigated with Instruments on the command line, using the Leaks instrument.

We were able to track down and fix some leaks, but they were not in our code, but in Kitura itself. In particular, there are a number of places where callbacks are not called, leading walkers to be incomplete and left hanging in memory due the resulting retain cycle.

Here is one example:
https://github.com/IBM-Swift/Kitura/blob/3d42897fa83537b97592512a7a85af61e9ce53ea/Sources/Kitura/Router.swift#L365-L383

The `process` function of `Router`. There are two paths through this function that do not trigger the callback: 

1. The guard at the top
2. The first branch of the `if`

Why is that so important? Because the `process` function is called by the `handle` function in the same class, and an assumption is made there that the callback will always trigger, leading to a call to `popRouter`. If that call is not made, there is a leak.

This may be the most serious problem we found, but was not the only one. In many other places, there are paths through functions that fail to call the `next` callback. Not doing this can again leave walkers and other asynchronous chains hanging, and leading to a leak.

Here are some of the places we found missing `next` calls:

- `Router` class, `handle` func. Both `guard` fail to call `next`
- `RouterElement`, `process` func. `guard` at top
- `RouterElement`, `performSimpleMatch` func. `guard` at top
- `BodyParser`, `handle` func. Both `guard`s
- In KituraCredentials, there were several paths in `Credentials` class, `handle` and `authenticate` func that do not trigger `next`.

Making these changes, we were able to reduce the leaks considerably, although we weren't able to track leaks that arose during 401 authorization errors. So there are likely more places in Kitura not abiding by the callback rules. An audit of functions using callbacks may be useful, and setting up some sort of leak testing.

**Comment by seabaylea** [comment]
Hi @drewmccormack. Thanks for the thorough write up! @djones6 can you investigate?

**Comment by nethraravindran** [comment]
@drewmccormack Thanks for the write up. With your suggestions, I have created a local branch.

https://github.com/nethraravindran/Kitura/tree/router-memoryleak

With this, I could observe the same minimal amount of leak. I request you to test once and check if the leak still persists. Also it would be great if you could give us the scenario to produce a considerable amount of leak. Thanks!

**Comment by drewmccormack** [comment]
Thanks for looking into this. These fixes seem to work.

I was only seeing a small memory leak per request. I traced this to a NSMutableData object that I was generating myself if custom credentials handler, and attaching to each request. It was being leaked because the request was not being released properly. Over thousands of requests, this added up to hundred's of MB.

I think this fix should help a lot. I will add it to our server and see if there are still issues.

**Comment by ianpartridge** [comment]
I think you missed out the extra calls to `callback()` in `Router.process()` @nethraravindran

**Comment by nethraravindran** [comment]
@ianpartridge Thanks! Have worked on the change.

**Comment by ianpartridge** [comment]
This was fixed in https://github.com/IBM-Swift/Kitura/pull/1232 :)

**Comment by drewmccormack** [comment]
To completely close this out, today I deployed the latest Kitura release on our production server, and there appears to be no memory leaked anymore, which is great. Thanks for fixing it!

**Comment by ianpartridge** [comment]
Great, thanks for letting us know.
