### ISSUE TITLE
Router.route does not honour paths with parameters

### ISSUE THREAD

**Issue by mattcolegate** [IBM-Swift/Kitura#1219]
## Context and Description
Using `Router.route` to specify a path with parameters in (e.g. "/user/:name") does not result in the parameter being made available to the underlying `.get()` function, unlike in Express.

### Environment Details
OS: Ubuntu 14.04
Swift version: 4.0.3 RELEASE
Kitura version: 2.2.0

### Steps to Reproduce
1) Run the following program
```swift
import Kitura
import Foundation

let router = Router()

router.get("/works/:name") { request, response, next in
    print("Works request parameters = \(request.parameters)")
    let name = request.parameters["name"] ?? ""
    response.send("Hello, \(name)!")
    next()
}

router.route("/doesnotwork/:name")
  .get() { request, response, next in
    print("DNW request parameters = \(request.parameters)")
    let name = request.parameters["name"] ?? ""
    response.send("Hello, \(name)!")
    next()
}

Kitura.addHTTPServer(onPort: 8080, with: router)
Kitura.run()
```

2) A call to http://localhost:8080/works/Dave returns the result 'Hello, Dave!' and the console output shows `Works request parameters = ["name": "Dave"]`

3) A call to http://localhost:8080/doesnotwork/Dave returns the result 'Hello, !' and the console output shows `DNW request parameters = [:]`

### Expected vs. Actual Behaviour
- [ ] Expected the call made in step 3) to return the same result and console output as in step 2).

**Comment by ianpartridge** [comment]
Thanks for raising this.  We don't [document](https://ibm-swift.github.io/Kitura/Classes/Router.html) whether or not we support parameters in subrouters but as Express does support this it would be nice to in Kitura.

**Comment by mattcolegate** [comment]
Thanks for the doclink @ianpartridge - after carefully reading the `route` entry, it turns out that you don't support them **by default** https://ibm-swift.github.io/Kitura/Classes/Router.html#/s:6Kitura6RouterC5routeACSS_Sb15mergeParametersSb17allowPartialMatchtF

"_mergeParameters_: Specify if this router should have access to path parameters matched in its parent router. Defaults to `false`."

Adding `mergeParameters: true` to the route method solves this issue. I think this can be closed as RTFM.

**Comment by ianpartridge** [comment]
Is that the same behaviour as Express?

**Comment by youming-lin** [comment]
Yup, this option was specifically added to reach parity with ExpressJS in this one aspect: #818
