### ISSUE TITLE
Leverage async I/O in libdispatch.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#122]
Instead of holding on to a thread for IO tasks, it might be better to have the OS use event notification (like epoll and kqueue) when waiting for resources. Perhaps libdispatch already has so hooks here for simplifying this problem.

**Comment by cloutiertyler** [comment]
@rolivieri libdispatch does already have hooks for this. I just mentioned this over in https://github.com/IBM-Swift/Kitura/issues/121#issuecomment-345557872 as well.

**Comment by christiancompton** [comment]
Closing, per comment above.  Reopen as needed.
