### ISSUE TITLE
Delegate properties should be weak to prevent memory leaks

### ISSUE THREAD

**Issue by drewmccormack** [IBM-Swift/Kitura#1239]
## Context and Description

I have encountered three places in the Kitura + frameworks code that have delegates that are not weak. In general, delegates should be weak, or there is a good chance that a retain cycle will arise, because the owning object is often also the delegate.

I have seen the memory in my app increase gradually through the day, requiring periodic restarts. A retain cycle due to a strong delegate is one possible cause of this.

### Environment Details

Production app is using Linux. Testing on macOS with Swift 4.0.

### Steps to Reproduce

It is suffice to search the code. I performed a search for "public var delegate" and found 3 non-weak delegate properties. There could be many more, and a thorough search is advised.

The ones I found are:

In HTTPServer.swift

    public var delegate: ServerDelegate? 

In Socket.swift

    public var delegate: SSLServiceDelegate? = nil

In FastCGIServer.swift

    public var delegate: ServerDelegate?

### Expected vs. Actual Behaviour

Delegate properties would be weak.

**Comment by ianpartridge** [comment]
Hi Drew, while it is common for delegates to be weak, it's not a requirement - it depends on how the code is designed in each case.  For the ones you have identified I have reviewed and do not believe these are the cause of any leaks.

If you have examples of retain cycles in Kitura (e.g. found through Instruments) _please_ let us know and we will investigate urgently.
