### ISSUE TITLE
How to receive a JSON array (like [Any]) in Kitura 2?

### ISSUE THREAD

**Issue by Coeur** [IBM-Swift/Kitura#1241]
## Context and Description
Moving from Kitura 1.7 to Kitura 2, `ParseBody.json(JSON)` was [replaced](https://github.com/IBM-Swift/Kitura/commit/edbd229ba8b99db936bc552c8e4f8e190a6dc633) with `ParseBody.json([String: Any])`, which can't match to an array `[Any]`.

So how do I parse a JSON response body which is, for instance, of the form `[String]`?

See the specs on "application/json": https://www.ietf.org/rfc/rfc4627.txt

### Environment Details
macOS High Sierra, Swift 4.1, Xcode 9.3.

**Comment by Coeur** [comment]
Nevermind, I found a workaround by parsing the raw data to JSON myself. So instead of:

    case let .json(jsonBody) = parsedBody,
             let batch = jsonBody.array

I now use:

    case let .raw(rawBody) = parsedBody,
             let batch = JSON(data: rawBody).array

**Comment by ianpartridge** [comment]
Glad you found a workaround, thanks.
