### ISSUE TITLE
SSLHandshake Internal Error

### ISSUE THREAD

**Issue by jamesrp13** [IBM-Swift/Kitura#1244]
## Context and Description
I am trying to run an HTTP server with SSL, but when I configure the SSL with my self-signed certificate and run the executable, the SSLHandshake in SSLService.swift, line 1210, fails with status code -9810, which is Internal Error. No further information.

Running the executable on other machines appears to work most of the time, but never on mine.

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.
macOS 10.13.4, Swift 4.1, Xcode 9.3

### Steps to Reproduce
1) Run executable
2) Main calls `ServerController.shared.run()`. `ServerController` is below:

```swift
public class ServerController {
    public static let shared = ServerController()
    
    private let router = Router()
    
    private var chainFilePath: String {
        return FileManager.default.currentDirectoryPath + "/cert.pfx"
    }

    public func run() {
        Routes.setup(router: router)
        let sslConfig = SSLConfig(withChainFilePath: chainFilePath, withPassword: "password", usingSelfSignedCerts: true)
        Kitura.addHTTPServer(onPort: 8080, with: router, withSSL: sslConfig)
        Kitura.run()
    }
    
    public func stop() {
        Kitura.stop()
    }
}
```

3) Go to https://localhost:8080/ in a browser and it won't connect. If you set a breakpoint in SSLService.swift, line 1210, you'll see that `SSLHandshake` fails with no helpful error messages.

### Expected vs. Actual Behaviour
- It is expected that a secure connection can be created between the client and server
- Actual behavior is that there is no secure connection made

**Comment by ianpartridge** [comment]
Hi @ShihabMehboob can you take a look at this please?

**Comment by ShihabMehboob** [comment]
@jamesrp13 Hey! I noticed that you're using a `.pfx` formatted certificate, according to the docs for [BlueSSLService](https://github.com/IBM-Swift/BlueSSLService), this should be in the `.pem` format.

**Comment by ianpartridge** [comment]
Good catch @ShihabMehboob. @jamesrp13 please reopen if you still need help.
