### ISSUE TITLE
CodableRouter: unprocessableEntity should return the error to client

### ISSUE THREAD

**Issue by hactar** [IBM-Swift/Kitura#1249]
## Context and Description
CodableRouter decodes JSON into a Codable object. If a client posts/gets/whatever a JSON object missing a required parameter, the CodableRouter correctly returns a 422 unprocessable entity and the current unreleased version even logs that to the server.

The person coding the client may not have access to the server logs however, and so it would be great if kitura would actually output the decoding error to the client as this allows debugging any malformed/incorrect json without the aid of the server developer.

This is especially important if you are developing a public api and want to help 3rd party developers with why their requests aren't working - these will never have access to the server logs.

### Environment Details
Swift 4.0.3, Kitura 2.2.x

### Steps to Reproduce

1) Create a simple kitura server app that accepts a codable via post route, such as:

```
public struct SuggestAction: Codable {
    public let title: String
    public let value: String
}
```

2) Submit a post to the server that isn't correct, for example its missing the "title":

```
{
  value: "woof"
}
```

### Expected vs. Actual Behaviour
- Expected to happen...
I should get a 422 http status, and an error message sent back to the client with the decoding error, such as:
`keyNotFound(CodingKeys(stringValue: "title", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"title\", intValue: nil) (\"title\").", underlyingError: nil))`
- Actually happened...
I only get a 422 http status back, and if I have no access to the server logs, I can only guess as to why the server did not accept my post.

### Additional
- I do not have a proposal of how to actually format the returned error. Should kitura just return the raw error string from the decode catch? should it return it in some JSON format? Personally I wouldn't care, as long as the error is returned in some form.
- Maybe make this toggable incase someone prefers the "quiet" option that kitura currently has.

### How to fix
Once the Kitura Team agrees upon a format of returning the error, all it needs is a response.send here:
https://github.com/IBM-Swift/Kitura/blob/661fc8a169b1718f4649aa990d9e745a01663c93/Sources/Kitura/CodableRouter.swift#L730
and maybe here:
https://github.com/IBM-Swift/Kitura/blob/661fc8a169b1718f4649aa990d9e745a01663c93/Sources/Kitura/CodableRouter.swift#L754

I added a `response.send("Decode Error: \(error)")` to my version. I'm sure this could be done prettier, but this at least gives client devs an idea of what went wrong.

**Comment by ianpartridge** [comment]
What do you think @seabaylea?

**Comment by seabaylea** [comment]
Yes - we should be providing better error messages for .unprocessableEntity. We also need to make sure that we don't leak internal information (i.e. expose information on internals that could potentially enable a security attack).

This means we should probably process the DecodingError (documented here):
    https://developer.apple.com/documentation/swift/decodingerror
rather than just dumping it.

**Comment by ianpartridge** [comment]
Sounds good.  @hactar would you be interested in opening a PR to improve this?

**Comment by hactar** [comment]
I can take a stab at it - I'd write some code to produce a human readable error string based on the DecodingError.  Typical produced error messages would be:

- JSON did not contain the required key "title".
- JSON did not contain a value for the key "title".
- The key "title" was not of the expected type "String".
- The data you sent could not be decoded as JSON.

I'd then return it like so: `request.send("DecodingError: \(humanReadableErrorMessage)")`

**Comment by ianpartridge** [comment]
Sounds perfect - thanks!

**Comment by hactar** [comment]
PR is in, passes (updated) tests.

**Comment by djones6** [comment]
FYI, #1256 has been merged and will be tagged in the next minor of Kitura.
