### ISSUE TITLE
BodyParser Does Not Produce JSON

### ISSUE THREAD

**Issue by linxyfe** [IBM-Swift/Kitura#1251]
## Context and Description
As I try to access the request's body info with ParsedBody, json feature seem to be missing.

### Environment Details
Swift 4.0.3 on Ubuntu 16.04
```
.package(url: "https://github.com/IBM-Swift/Kitura.git", from: "2.2.1"),
```
### Steps to Reproduce
Codes for setup:
```
router.all("/*", middleware: BodyParser())
router.post("/quests", handler: handlers.createQuest)
```

Codes for route handler:
```
public func createQuest(request: RouterRequest, response: RouterResponse, next: @escaping () -> Void) throws {

    guard let parsedBody = request.body else {
        next()
        return
    }

    switch parsedBody {
    case .json(let jsonBody):
            let name = jsonBody["name"] ?? ""
            try response.send("Hello \(name)").end()
    default:
        break
    }
    next()
}
```

Command on bash:
swift build

### Expected vs. Actual Behaviour
- Expected to happen...
build success
- Actually happened...
```
Compiling Error:
/src/Sources/QuestsService/Handlers/Handlers+Quest.swift:17:32: error: value of type 'Any?' has no member 'string'
            let name = jsonBody["name"].string ?? ""
                       ~~~~~~~~^~~~~~~~ ~~~~~~
error: terminated(1): /usr/bin/swift-build-tool -f /src/.build/debug.yaml main
```

**Comment by NocturnalSolutions** [comment]
The code you provided for your route handler above does not match what seemed to be used to generate that error. The latter has that `.string` bit which, yes, does not exist for an Any object.

What you're probably looking for is along the lines of:

```swift
let name = jsonBody["name"] as? String ?? ""
```

**Comment by ianpartridge** [comment]
Thanks for helping out @NocturnalSolutions :-)  I'll close this for now as your answer is correct.

@linxyfe _please_ reopen this if you still have problems.

**Comment by linxyfe** [comment]
@NocturnalSolutions thanks for your reply, but the above code inside the router handler is copied from  official tutorial here: http://www.kitura.io/en/resources/tutorials/parsingrequests.html
Doesn't it mean ".string" is a build in feature of ParsedBody ?
I even tried to embrace SwiftyJSON, still doesn't work for me😂, I don't know what's going on any more.

**Comment by ianpartridge** [comment]
I'm sorry, there was a mistake in the tutorial.  I've just updated it.

The correct line is:

```swift
let name = jsonBody["name"] as? String ?? ""
```

**Comment by ianpartridge** [comment]
By the way, if you just want to process some POSTed JSON, you might find Codable Routing to be a good solution.  Define a `Codable` struct and avoid all the type-casting in the above code.

http://www.kitura.io/en/resources/tutorials/codablerouting.html

**Comment by linxyfe** [comment]
OK,thx, I will check it out. Hope it would help, type-casting is really unsafe.
