### ISSUE TITLE
Add HTTP methods PATCH and OPTIONS

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#129]
- [x] Get
- [x] Post
- [x] Put
- [x] Head
- [x] Delete
- [x] Options
- [ ] Trace
- [ ] Copy
- [ ] Lock
- [ ] Mkcol
- [ ] Move
- [ ] Purge
- [ ] Propfind
- [ ] Proppatch
- [ ] Unlock
- [ ] Report
- [ ] Mkactivity
- [ ] Checkout
- [ ] Merge
- [ ] M-search
- [ ] Notify
- [ ] Subscribe
- [ ] Unsubscribe
- [x] Patch
- [ ] Search
- [ ] Connect

Unfortunately, as I have started working on the TodoList, there are a few HTTP methods that we don't handle, namely patch and options. The TodoList API will use PATCH to set a todo item as completed (I don't know why they simply just use PUT). For some reason, because OPTIONS is not specified, the front-end does not know it can use DELETE to delete an option (another thing I'm not sure about the API). 

Anyhow, the change to add these methods should just be adding to KituraRouter the HttpMethod enum and adding a method for adding a route of that type. And to KituraNet ClientRequest the curlHelperSetOptBool and these new method types. I will of course not make these change before Interconnect since we already tagged 0.2- however it is top on my priority list to get this implemented since without it- the todo list does not have the ability to delete or edit items.

[HTTP methods](http://restful-api-design.readthedocs.org/en/latest/methods.html)

**Comment by shmuelk** [comment]
Actually you need to add two methods to Router for every HTTP method you add. One with a path and one without a path.

**Comment by shmuelk** [comment]
While we're at it, why not all of them?

**Comment by rfdickerson** [comment]
Taken from [Wikipedia](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol):

> GET
The GET method requests a representation of the specified resource. Requests using GET should only retrieve data and should have no other effect. (This is also true of some other HTTP methods.)[1] The W3C has published guidance principles on this distinction, saying, "Web application design should be informed by the above principles, but also by the relevant limitations."[13] See safe methods below.
HEAD
The HEAD method asks for a response identical to that of a GET request, but without the response body. This is useful for retrieving meta-information written in response headers, without having to transport the entire content.
POST
The POST method requests that the server accept the entity enclosed in the request as a new subordinate of the web resource identified by the URI. The data POSTed might be, for example, an annotation for existing resources; a message for a bulletin board, newsgroup, mailing list, or comment thread; a block of data that is the result of submitting a web form to a data-handling process; or an item to add to a database.[14]
PUT
The PUT method requests that the enclosed entity be stored under the supplied URI. If the URI refers to an already existing resource, it is modified; if the URI does not point to an existing resource, then the server can create the resource with that URI.[15]
DELETE
The DELETE method deletes the specified resource.
TRACE
The TRACE method echoes the received request so that a client can see what (if any) changes or additions have been made by intermediate servers.
OPTIONS
The OPTIONS method returns the HTTP methods that the server supports for the specified URL. This can be used to check the functionality of a web server by requesting '*' instead of a specific resource.
CONNECT
[16] The CONNECT method converts the request connection to a transparent TCP/IP tunnel, usually to facilitate SSL-encrypted communication (HTTPS) through an unencrypted HTTP proxy.[17][18] See HTTP CONNECT tunneling.
PATCH
The PATCH method applies partial modifications to a resource.[19]

**Comment by rfdickerson** [comment]
It looks like the TRACE and the CONNECT methods, if we need to handle them, should be done a the Kitura layer- not exposed to end users. For instance, TRACE simply echoes the request back. I'm closing this ticket since DELETE, PATCH, and OPTIONS are now working in the TodoApp (on develop).

**Comment by shmuelk** [comment]
There are a lot more HTTP methods. Express.js supports this list:

        'get',    'post',    'put',    'head',    'delete',    'options',    'trace',    'copy',
        'lock',    'mkcol',    'move',    'purge',    'propfind',    'proppatch',
        'unlock',    'report',    'mkactivity',    'checkout',    'merge',    'm-search',
        'notify',    'subscribe',    'unsubscribe',    'patch',    'search',    'connect'

I found list this (via Google):
           http://www.iana.org/assignments/http-methods/http-methods.xhtml
