### ISSUE TITLE
Create a static file serving middleware for Kitura-router

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#13]
<a href="https://github.ibm.com/KALLNER"><img src="https://avatars.github.ibm.com/u/3096?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KALLNER](https://github.ibm.com/KALLNER)**
_Thursday Jan 07, 2016 at 10:18 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/13_

----

**Comment by shmuelk** [comment]
No. All I did was add some stuff that displays a simple page with the Kitura logo on it, if a request was made that returns a 404 to a request of slash (/).

**Comment by irar2** [comment]
https://github.com/IBM-Swift/Kitura-router/commit/b045fa91bb038b2b47908937fbbf3dbfcb1f4247
https://github.com/IBM-Swift/Kitura/commit/3de51d768cfe0cee4d015bfd8baccd83e0d219a3
https://github.com/IBM-Swift/Kitura-net/commit/06d469b02fc2b16c92e89b468ae6d0b35e57b5bd

**Comment by shmuelk** [comment]
I fixed build issues with these commits:

https://github.com/IBM-Swift/Kitura-net/commit/2d7e040bc7758a4e87922d6c447305422ba9a23e

https://github.com/IBM-Swift/Kitura-router/commit/add34853f02b59fc81ef7da602f6064abcbdd820

**Comment by dfirsht** [comment]
Relavent commit: 3de51d768cfe0cee4d015bfd8baccd83e0d219a3

**Comment by dfirsht** [comment]
Verified as working correctly. We should consider creating a test case for this functionality in the future.
