### ISSUE TITLE
HTTPServer - Name refactoring task

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#132]
As reference from other languages/stacks:

https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html\

https://msdn.microsoft.com/en-us/library/system.web.http.httpserver(v=vs.118).aspx

**Comment by shmuelk** [comment]
I don't understand this issue. You want it to be HTTPServer? Or do you want it to be HttpServer?

It is currently the latter.

**Comment by rolivieri** [comment]
My understanding was that we had HTTPServer and it should be changed to HttpServer. If it is already the latter, then we can close this issue.

@kweinmeister - Anything else you wanted the team to address regarding this issue? I don't have any other context than what you shared on the slack channel.

**Comment by rolivieri** [comment]
@shmuelk From kweinmeister - "vadime had a good explanation of #138. He found that Apple uses all caps for classes like NSHTTPURLResponse. That is I believe what the tweet aimed at us was getting at. So, I think the issue is we’re using HttpServer and we should use HTTPServer instead."

**Comment by dfirsht** [comment]
In addition includes: HTTP, HTTPServerSPI, HTTPParser, SPIUtils, URLParser

**Comment by vadimeisenbergibm** [comment]
The Apple convention is [here](https://swift.org/documentation/api-design-guidelines/#general-conventions)

> Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:
```swift
var utf8Bytes: [UTF8.CodeUnit];
var isRepresentableAsASCII = true;
var userSMTPServer: SecureSMTPServer;
```

**Comment by aquarchitect** [comment]
Hello, have you guys had a chance to look at this proposal (accepted but yet implemented for Swift 3):
https://github.com/apple/swift-evolution/blob/master/proposals/0036-enum-dot.md

The proposal's short description: cases in `enum` should follow camel case convention.
Since you are refactoring, I thought I should bring this up so you guys can consider, especially the situation with `HTTPStatusCode`.

Just my two-cent opinion.
