### ISSUE TITLE
KituraTests.TestCustomCoders testCustomQueryEncoder failure

### ISSUE THREAD

**Issue by weissi** [IBM-Swift/Kitura#1337]
## Context and Description

Tests `KituraTests.TestCustomCoders testCustomQueryEncoder` failed

```
Test Case '-[KituraTests.TestCustomCoders testCustomQueryEncoder]' started.
[VERBOSE] [Router.swift:95 init(mergeParameters:)] Router initialized
/private/tmp/.nio-release-tools_dOgew6/Kitura/Tests/KituraTests/TestCustomCoders.swift:156: error: -[KituraTests.TestCustomCoders testCustomQueryEncoder] : XCTAssertEqual failed: ("Optional("&date=2018-02-21T9:47:36%2B0000")") is not equal to ("Optional("&date=2018-02-21T09:47:36%2B0000")") - 
/private/tmp/.nio-release-tools_dOgew6/Kitura/Tests/KituraTests/TestCustomCoders.swift:156: error: -[KituraTests.TestCustomCoders testCustomQueryEncoder] : XCTAssertEqual failed: ("Optional("&date=2018-02-21T9:47:36%2B0000")") is not equal to ("Optional("&date=2018-02-21T09:47:36%2B0000")") - 
/private/tmp/.nio-release-tools_dOgew6/Kitura/Tests/KituraTests/TestCustomCoders.swift:180: error: -[KituraTests.TestCustomCoders testCustomQueryEncoder] : XCTAssertEqual failed: ("Optional("&date=2018-02-21T9:47:36%2B0000")") is not equal to ("Optional("&date=2018-02-21T09:47:36%2B0000")") - 
/private/tmp/.nio-release-tools_dOgew6/Kitura/Tests/KituraTests/TestCustomCoders.swift:180: error: -[KituraTests.TestCustomCoders testCustomQueryEncoder] : XCTAssertEqual failed: ("Optional("&date=2018-02-21T9:47:36%2B0000")") is not equal to ("Optional("&date=2018-02-21T09:47:36%2B0000")") - 
Test Case '-[KituraTests.TestCustomCoders testCustomQueryEncoder]' failed (0.050 seconds).
```

it seems to be a leading 0 that might or might not be there: `T9:` vs `T09:`

### Environment Details

- macOS 10.14
- Xcode 10
- with and without `export KITURA_NIO=1`

### Steps to Reproduce
1) check out current master (`bb19ec7ef8321082a234624cc76c11a17cd88971`)
2) `swift test`

### Expected vs. Actual Behaviour
- [x] Expected to happen...

tests pass

- [x] Actually happened...

1 test failure

**Comment by djones6** [comment]
@Andrew-Lees11 Looks like this test is fragile (possibly related to locale?), would be possible for the test to generate the expected string represenation rather than hard-code it?

**Comment by weissi** [comment]
@pushkarnk / @Andrew-Lees11 I'm still seeing this continuously

**Comment by Andrew-Lees11** [comment]
@weissi Hey
We have a pull request [here](https://github.com/IBM-Swift/Kitura/pull/1349) which should fix this issue.
@djones6  would you be able to review this change?

**Comment by djones6** [comment]
@weissi #1349 has been merged.

**Comment by weissi** [comment]
thanks @djones6 & @Andrew-Lees11 , I can confirm that works (hit another TSan issue though, filing in a sec).
