### ISSUE TITLE
Kitura build failed on Ubuntu18.04

### ISSUE THREAD

**Issue by samding01** [IBM-Swift/Kitura#1341]
Build/test` Kitura (v2.4) ` with swift v4.2 on Ubuntu 18.04 gets following error:
```

  Compile Swift Module 'SSLService' (1 sources)
/home/work/sw/Kitura/.build/checkouts/BlueSSLService.git-8195854929476318645/Sources/SSLService/SSLService.swift:318:54: error: use of undeclared type 'SSL'
                public private(set) var cSSL: UnsafeMutablePointer<SSL>? = nil
                                                                   ^~~
/home/work/sw/Kitura/.build/checkouts/BlueSSLService.git-8195854929476318645/Sources/SSLService/SSLService.swift:322:49: error: use of undeclared type 'SSL_METHOD'
                public private(set) var method: UnsafePointer<SSL_METHOD>? = nil
...
``` 
The `openssl` version is 
```
openssl version
OpenSSL 1.1.0g  2 Nov 2017
```
According the `Kitura Slack`, it seems that the OpenSSL v1.1 is not supported now. Please confirm.

By the way, `Kitura (v2.4) ` is successfully built and tested on` Ubuntu 16.04 `, on which OpenSSL version is v1.0.2g 

### Environment Details
on both x86_64 and LinuxOne
Ubuntu 18.06;
Swift v4.2;

### Steps to Reproduce
1) Under `Kitura` foder, issue command `swift test`

**Comment by ianpartridge** [comment]
Yes that's correct, currently `BlueSSLService` does not support OpenSSL 1.1

**Comment by mamabusi** [comment]
@djones6 worked around this to build Kitura successfully on 18_04. Here are the documented steps: https://gist.github.com/djones6/338aa7df92c3bdda831edefe5b24c040
