### ISSUE TITLE
Failing build under Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by thevojacek** [IBM-Swift/Kitura#1342]
## Context and Description
It is not possible to build an Kitura application under Linux using IBM`s Linux docker (Ubuntu 14.04 and Swift 4.2) when BlueSSLService is included alongside Kitura.

Interestingly enough, theres no problem on macOS, probably related to a fact that some of the Kitura packages uses OpenSSL only for Linux builds.

I found out that it might be related to a fact tha BlueSSLService uses system library OpenSSL, but BlueCryptor and others uses https://github.com/IBM-Swift/OpenSSL.git ...

### Environment Details
Ubuntu 14.04
Swift 4.2

### Packages
.package(url: "https://github.com/IBM-Swift/Kitura.git", from: "2.5.3"),
.package(url: "https://github.com/IBM-Swift/HeliumLogger", from: "1.7.1"),
.package(url: "https://github.com/IBM-Swift/Kitura-Session.git", from: "3.2.0"),
.package(url: "https://github.com/thevojacek/Kitura-MiniHandlebars", from: "1.2.2"),
.package(url: "https://github.com/OpenKitten/MongoKitten", from: "4.1.3"),
.package(url: "https://github.com/thevojacek/Kitura-MongoDbSessionStore", from: "0.2.2"),
.package(url: "https://github.com/IBM-Swift/Swift-JWT", from: "2.0.0"),
.package(url: "https://github.com/krzyzanowskim/CryptoSwift", from: "0.12.0")

### Steps to Reproduce
Try to build on official Kitura's docker building image of Ubuntu.

**Comment by djones6** [comment]
Apologies, it turns out that the Swift 4.2 system library targets declared in different packages cannot have the same name (even though they are not exported).

I've reworked the dependencies in BlueSSLService, BlueCryptor and BlueRSA so that they revert to using the separate OpenSSL dependency, which has been updated to use a structure that Swift 4.2 supports.  This should resolve your issue.

**Comment by thevojacek** [comment]
Thanks for help. It is related to https://github.com/IBM-Swift/BlueSSLService/issues/58
It works after updating.
