### ISSUE TITLE
Poor performance of RouterResponse.send

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura#1356]
## Context and Description
In a recent performance study of Kitura (with Kitura-NIO), using a simple HelloWorld benchmark and flamegraphs, it was found that a considerable amount of time is being spent in [RouterResponse.send()](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/RouterResponse.swift#L438), where most of the time in turn is spent in the call to `lengthOfBytes(using: .utf8)` [here](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/RouterResponse.swift#L443). Simply replacing this by `str.utf8.count` improves the performance 14%.

### Environment Details
Ubuntu 16.04, 16CPU machine

**Comment by pushkarnk** [comment]
Discussed this with @ianpartridge and he pointed out that `lengthOfBytes` is defined on `NSString`. Invoking it on a `String` involved bridging which could be the reason for the slowdown.

**Comment by ianpartridge** [comment]
Fixed in #1369
