### ISSUE TITLE
Deterministic ordering of routes in generated Swagger

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1364]
## Context and Description
The `SwaggerGenerator` uses `JSONEncoder` to generate our OpenAPI specification based on an in-memory model built during route registration.

Unfortunately, this has the effect of producing a document that contains lists of elements (such as routes) whose ordering is unpredictable, and changes from one execution to the next.

It would make the consumption and comparison of OpenAPI documents easier if the ordering was deterministic (such as registration order or alphabetical order).

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.

### Steps to Reproduce
1) ...
2) ...
etc

### Expected vs. Actual Behaviour
- [ ] Expected to happen...
- [ ] Actually happened...

**Comment by coenmooij** [comment]
Would love to see this feature sooner than later!

**Comment by djones6** [comment]
I've prototyped a basic solution for this applying a lexicographical sort to the document elements in #1393.  Feedback appreciated.

**Comment by coenmooij** [comment]
Took a look and added some feedback.
https://github.com/IBM-Swift/Kitura/pull/1393#issuecomment-456399378

**Comment by djones6** [comment]
#1393 has been merged and tagged in Kitura `2.6.1`.
