### ISSUE TITLE
Option to allow Swagger to be written to disk

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1365]
## Context and Description
We would like to be able to request that the Swagger document is written to a file on disk.

It would probably make sense for this to occur when the server is started, as route registration would normally have been completed by then.  However, that's not a limitation we currently impose, so this would need some consideration.

**Comment by saiHemak** [comment]
pushed the code to ```https://github.com/saiHemak/Kitura-OpenAPI/tree/store-swagger```

**Comment by saiHemak** [comment]
https://github.com/IBM-Swift/Kitura-OpenAPI/pull/25 has been raised

**Comment by saiHemak** [comment]
As per @ianpartridge  inputs new API has been created which writes the output of ```router.swaggerJSON``` to disk.

**Comment by djones6** [comment]
IBM-Swift/Kitura-OpenAPI#25 merged and tagged.
