### ISSUE TITLE
Dependence on Dictionary ordering in Kitura tests

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1375]
## Context and Description
The Kitura tests contain a handful of tests that return an array, and then test that the returned array is equal to some expected value.  The creation of this array has a dependency on the ordering of iteration of elements from a Dictionary, as it is created using `dictionary.map { $0.value }`:

The dictionary in question is created with the same three elements each time:
https://github.com/IBM-Swift/Kitura/blob/2.5.6/Tests/KituraTests/TestCodableRouter.swift#L62

In Swift 4.2 and earlier, this worked because the hash value of strings is fixed for each execution, and so although the ordering varies across executions, within any one test run it was consistent.

In Swift 5, it appears that each Dictionary instance has its own randomness added to the hashing, so creating the same dictionary over and over yields different ordering.

This is a problem when `KituraTestBuilder` re-executes the same test again, with the same expectations, but with SSL enabled.  Between the tests, to reset any side-effects (such as modification to this dictionary), it calls `setUp()` to create it afresh:
https://github.com/IBM-Swift/Kitura/blob/2.5.6/Tests/KituraTests/KituraTest.swift#L85

This has the effect in Swift 5 of randomising the order, whilst the array copy of the previous dictionary (stored within the expectation) still has the old order.  The second (SSL) execution of the test is likely to fail.

I've modified the test above to use a fixed array order in the `issue.swift5` branch here:
https://github.com/IBM-Swift/Kitura/commit/8f9e8e146477f7ed1f1ad22a0234823126323608

The same sort of fix needs to be applied to other tests that are failing for the same reason - I believe these are:
- TestTypeSafeMiddleware testSingleMiddlewareGetIdentifierCodableArray
- TestTypeSafeMiddleware testMultipleMiddlewareGetIdentifierCodableArray

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.

### Steps to Reproduce
1) ...
2) ...
etc

### Expected vs. Actual Behaviour
- [ ] Expected to happen...
- [ ] Actually happened...

**Comment by Andrew-Lees11** [comment]
Fix raised in PR [here](https://github.com/IBM-Swift/Kitura/pull/1376)
