### ISSUE TITLE
Create documentation on how to create XCTests for Kitura Apps

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#138]
We have been getting some questions regarding writing XCTests for Kitura apps. We should document this.

**Comment by dfirsht** [comment]
I took a first stab at creating this documentation: https://github.com/IBM-Swift/Kitura/wiki/Testing-your-Kitura-Apps

**Comment by kweinmeister** [comment]
Looks like a great start. I would add info about this in the CONTRIBUTING.md and also link to this documentation in the pull request template. Both are now in .github.

**Comment by dfirsht** [comment]
Well this guide is more on how to create a new testing suite rather than adding to an existing one. I'm not sure adding a link would be helpful in those places.

**Comment by dfirsht** [comment]
With no other comments on this documentation, I am closing this issue. We can always make changes later.
