### ISSUE TITLE
Create private repo to hold credentials / private information

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#139]

**Comment by rfdickerson** [comment]
Let's discuss this and whether this is needed. Perhaps using Travis's environment variables is what we want to use here if for our CI.

**Comment by rolivieri** [comment]
@rfdickerson We can discuss with you tomorrow. Daniel and I discussed this and we'd rather not have a dependency on Travis for credentials. We want to be able to execute the test cases in and outside of Travis.

**Comment by dfirsht** [comment]
Created the private repo and added the couchdb credentials. For obvious reasons I cannot link it here.

**Comment by rolivieri** [comment]
@dfirsht Just looked at the private repo. It looks good! Just one minor step before we can close this issue. We need a "dummy" version of the Kitura-CouchDB/Sources/CouchDBSample/credentials.json file checked in under the Kitura-CouchDB repo; something along these lines:

{
   "username": “<username>”,
   "password": “<password>”,
   "host": “<hostname>”
}

**Comment by dfirsht** [comment]
It seems I was working off an old version of the couchDB repo and put the credentials in the wrong place. I updated the credentials repo to place the credentials in the same place they are in inside the CouchDB repo.

**Comment by dfirsht** [comment]
@rolivieri Is this ok to close now?

**Comment by rolivieri** [comment]
Looks good, thx!
