### ISSUE TITLE
Kitura 2.6.1 tagged on master

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#1398]
It seems that `2.6.1` was tagged on the `master` branch, not `kitura-2.6`. Probably we should have backported the fixes we made on `master` that we wanted in `2.6.1`.

See also https://github.com/IBM-Swift/Kitura-NIO/issues/164

**Comment by ianpartridge** [comment]
@djones6 do you have time to sort this out on Monday?

**Comment by djones6** [comment]
The tag itself is fine: all of the commits in 2.6.1 are commits we intended for 2.6.1.  The only issue here is that the kitura-2.6 branch is stale, but we can just fast-forward it to the 2.6.1 tag.  I'll do that today.

**Comment by djones6** [comment]
`kitura-2.6` has been fast-forwarded to be even with the 2.6.1 tag on master. Future 2.6.x releases should be cherry-picked and tagged from this branch, to enable us to accumulate changes in master for the next major.
