### ISSUE TITLE
Update CI build to leverage private repo for credentials

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#141]
This tasks includes integrating the gradle script for copying property files over to the main project repo at build time.

blocked until #139 is complete.

**Comment by dfirsht** [comment]
@rolivieri Would it be possible to paste the relevant commits into this issue so it can be validated?

**Comment by rolivieri** [comment]
@dfirsht Good observation... but I included this change along with the CI changes. Let's review the code tomorrow together.

**Comment by dfirsht** [comment]
Relavent commit: https://github.com/IBM-Swift/Kitura-CI/commit/b8de46e47ba7f006f210d5a2e562e8792e38cf8f

**Comment by dfirsht** [comment]
Verified on Travis CI
