### ISSUE TITLE
macOS Kitura app – "Couldn't create project" message

### ISSUE THREAD

**Issue by chriscrossen** [IBM-Swift/Kitura#1415]
## Context and Description
A description of the issue.
I start the Kitura app on my mac running macOS Mojave and select any of the project templates, click the Create button, enter a project name in the dialog, and push the Create button. I get a dialog box titled, "Couldn't create project" with the text "Error resolving dependencies".

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.
macOS Mojave 10.14.3
Apple Swift version 4.2.1
Xcode Version 10.1
Command Line Tools for Xcode are installed

### Steps to Reproduce
1) Start Kitura app on macOS
2) Select any of the templates
3) Enter HelloKitura for Project Name
4) Click "Create" button

### Expected vs. Actual Behaviour
- [ ] Expected to happen...Project Created
- [ ] Actually happened...   Error Dialog
![kituraerror](https://user-images.githubusercontent.com/30850047/53615890-5a283700-3b9d-11e9-8b34-fbcb09cb3fdf.png)

**Comment by ddunn2** [comment]
Hi @chriscrossen, Thanks for raising this issue! 

Could I also ask you provide the version of the Kitura macOS app you are using? 

You can find this by selecting `Kitura` in the menu bar and selecting `About Kitura`

Thanks!

**Comment by chriscrossen** [comment]
Kitura Version 1.1 (1)

I just downloaded and installed it yesterday.

**Comment by ddunn2** [comment]
@chriscrossen Thanks!

I can't seem to recreate the issue, that is, it works successfully for me. 

At the point the app attempts to resolve dependencies it has already created the project files in your chosen destination. 

I was wondering if you would be able to open your project in a Terminal and run the following command: 

`swift package resolve`

And provide me with the output you get from this? I'm expecting it to fail as this is the command the macOS is attempting to run when it fails for you.

**Comment by chriscrossen** [comment]
Chriss-MacBook-Pro:HelloKitura chriscrossen$ pwd
/Users/chriscrossen/HelloKitura
Chriss-MacBook-Pro:HelloKitura chriscrossen$ ls -al
total 152
drwxr-xr-x  24 chriscrossen  staff    768 Feb 28 19:18 .
drwxr-xr-x+ 24 chriscrossen  staff    768 Feb 28 21:07 ..
drwxr-xr-x   6 chriscrossen  staff    192 Feb 28 19:18 .bluemix
-rw-r--r--   1 chriscrossen  staff     36 Feb 28 19:18 .cfignore
-rw-r--r--   1 chriscrossen  staff     28 Feb 28 19:18 .dockerignore
-rw-r--r--   1 chriscrossen  staff     97 Feb 28 19:18 .gitignore
-rw-r--r--   1 chriscrossen  staff      6 Feb 28 19:18 .swift-version
-rw-r--r--   1 chriscrossen  staff      0 Feb 28 19:18 .swiftservergenerator-project
-rw-r--r--   1 chriscrossen  staff     61 Feb 28 19:18 .yo-rc.json
-rw-r--r--   1 chriscrossen  staff   1003 Feb 28 19:18 Dockerfile
-rw-r--r--   1 chriscrossen  staff   1173 Feb 28 19:18 Dockerfile-tools
-rw-r--r--   1 chriscrossen  staff    100 Feb 28 19:18 Jenkinsfile
-rw-r--r--   1 chriscrossen  staff   1077 Feb 28 19:18 LICENSE
-rw-r--r--   1 chriscrossen  staff    934 Feb 28 19:18 Package.swift
-rw-r--r--   1 chriscrossen  staff   8095 Feb 28 19:18 README.md
-rw-r--r--   1 chriscrossen  staff  13863 Feb 28 19:18 README.rtf
drwxr-xr-x   4 chriscrossen  staff    128 Feb 28 19:18 Sources
drwxr-xr-x   4 chriscrossen  staff    128 Feb 28 19:18 Tests
drwxr-xr-x   3 chriscrossen  staff     96 Feb 28 19:18 chart
-rw-r--r--   1 chriscrossen  staff   2021 Feb 28 19:18 cli-config.yml
drwxr-xr-x   7 chriscrossen  staff    224 Feb 28 19:18 debian
-rwxr-xr-x   1 chriscrossen  staff   2636 Feb 28 19:18 iterative-dev.sh
-rw-r--r--   1 chriscrossen  staff    160 Feb 28 19:18 manifest.yml
drwxr-xr-x   6 chriscrossen  staff    192 Feb 28 19:18 terraform
Chriss-MacBook-Pro:HelloKitura chriscrossen$ swift package resolve
error: terminated(72): xcrun --sdk macosx --find xctest output:

**Comment by chriscrossen** [comment]
I'm afraid I've just confused the issue. The above output is from a project I created with the command line. I erased the folder and just tried again with the app and no folder was created. I also tried with the program to create a starter project on the Desktop and no folder was created.

**Comment by chriscrossen** [comment]
This may be a macOS Mojave issue. 

I just installed the Kitura app on my iMac and it worked perfectly.
The iMac is running:
macOS High Sierra (Version 10.13.6)
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Xcode Version 10.1 (10B61)

**Comment by ddunn2** [comment]
This line:
`error: terminated(72): xcrun --sdk macosx --find xctest output:`

Makes me think that your `xcode-select` path could be wrong. 

If you run `xcode-select -version` in Terminal what is the output? 

Alternatively...
It may be useful to also check the Command Line Tools you're using. 
You can check which Command Line Tools you are using within Xcode: 
1. Click Xcode in the menu bar
2. Select Preferences
3. Click on the Locations tab
4. Ensure the Command Line Tools are set to: `Xcode 10.1`


I am also on Mojave and it seems to work for me, so I'm going to check on a different machine to ensure I haven't got any additional config setup which is causing mine to succeed.

**Comment by chriscrossen** [comment]
Nice work! Thank you.  It was the Command Line Tools.

**Mojave**
xcode-select -version
xcode-select version 2354.

**High Sierra**
xcode-select -version
xcode-select version 2349.

**High Sierra:**
![highsierracommandlinetools](https://user-images.githubusercontent.com/30850047/53670378-c48db580-3c37-11e9-870d-2bdfb04463c9.png)

**Mojave:**
<img width="822" alt="mojavecommandlinetools" src="https://user-images.githubusercontent.com/30850047/53670399-d66f5880-3c37-11e9-88d3-b8bb2a654be0.png">

I changed Mojave Command Line Tools: to be Xcode 10.1 and now it works.

Thank you very much.

**Comment by ddunn2** [comment]
Awesome! 

I'm glad you were able to get it working. 
If you have any other issues please raise them here and we'll be happy to help! 

You can also join our [slack channel](http://swift-at-ibm-slack.mybluemix.net/) to talk to members of the Kitura team and Kitura Community to get help using Kitura or just to chat about Server-Side Swift in general :) 

Thanks again!
