### ISSUE TITLE
Add support for Nest

### ISSUE THREAD

**Issue by takebayashi** [IBM-Swift/Kitura#142]
[Nest](https://github.com/nestproject/Nest) is a common interface for server-side applications in Swift. If Kitura supports Nest, we can deploy our apps not only with KituraNet but with any other Nest-compatible servers.

**Comment by Ahti** [comment]
I agree that support for this would be great to have. Rack (which is similar to Nest in concept) has no doubt helped in making the Ruby web ecosystem what it is today.

I'd think the Swift ecosystem could only benefit from having a similar de-facto standard.

**Comment by ianpartridge** [comment]
We don't plan to support this at this time.
