### ISSUE TITLE
Update CI to test Swift 4.2.3 and official Docker images

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1425]
Swift 4.2.3 was recently released.  We should update the IBM-Swift projects' CI to run against this version.

In addition, we should update to run Dockerized builds using the official Swift Docker images, rather than the base Ubuntu images.  The former provide a nice build time improvement as Swift and dependencies are already installed in the image.  This work has already been completed for the Kitura repo (https://github.com/IBM-Swift/Kitura/pull/1403), and should be rolled out to others.

**Comment by djones6** [comment]
Done: BlueCryptor BlueECC BlueRSA BlueSignals BlueSocket BlueSSLService

PRs raised: Kitura Kitura-net Kitura-NIO Kitura-CouchDB SwiftKueryMySQL Swift-Kuery-SQLite

Branches pushed: CircuitBreaker CloudEnvironment Configuration FileKit Health HeliumLogger Kitura-Cache Kitura-Compression KituraContracts Kitura-CORS Kitura-Credentials Kitura-CredentialsFacebook Kitura-CredentialsGitHub Kitura-CredentialsGoogle Kitura-CredentialsHTTP Kitura-Markdown Kitura-OpenAPI Kitura-Session Kitura-StencilTemplateEngine Kitura-TemplateEngine Kitura-WebSocket LoggerAPI Swift-cfenv swift-html-entities Swift-JWT Swift-Kuery Swift-Kuery-ORM SwiftyRequest TypeDecoder

To do:
- Kitura-redis, Kitura-Session-Redis: awaiting merge of existing 18.04 CI fix
- Swift-Kuery-PostgreSQL: needs adjusting so that it will work under Docker
- Kitura-Sample
- Package-Builder

**Comment by ianpartridge** [comment]
Finished!
