### ISSUE TITLE
Swift 5 bringup

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#1433]
- .swift-version to 5.0
- adopt swift:5.0 docker images
- tools-version:5.0
- resolve any compile errors, warnings, test failures...

Done:
- CloudEnvironment (https://github.com/IBM-Swift/CloudEnvironment/pull/59), tagged `9.0.1`
- Configuration (https://github.com/IBM-Swift/Configuration/pull/59), tagged `3.0.3`
- FileKit (https://github.com/IBM-Swift/FileKit/pull/8), tagged `0.0.2`
- Health (https://github.com/IBM-Swift/Health/pull/16), tagged `1.0.5`
- HeliumLogger (https://github.com/IBM-Swift/HeliumLogger/pull/72), tagged `1.8.1`
- Kitura (https://github.com/IBM-Swift/Kitura/pull/1436)
- KituraContracts (https://github.com/IBM-Swift/KituraContracts/pull/39), tagged `1.1.2`
- Kitura-net (https://github.com/IBM-Swift/Kitura-net/pull/297), tagged `2.2.1`
- Kitura-NIO (https://github.com/IBM-Swift/Kitura-NIO/pull/176), tagged `2.0.0`
- Kitura-TemplateEngine (https://github.com/IBM-Swift/Kitura-TemplateEngine/pull/34), tagged `2.0.1`
- LoggerAPI (https://github.com/IBM-Swift/LoggerAPI/pull/44), tagged `1.8.1`
- TypeDecoder (https://github.com/IBM-Swift/TypeDecoder/pull/25), tagged `1.3.3`
- BlueECC (https://github.com/IBM-Swift/BlueECC/pull/13), tagged `1.2.1`
- Kitura-OpenAPI (https://github.com/IBM-Swift/Kitura-OpenAPI/pull/23), tagged `1.2.1`
- Package-Builder (https://github.com/IBM-Swift/Package-Builder/pull/164) (doesn't need tagging)
- SwiftyRequest (https://github.com/IBM-Swift/SwiftyRequest/pull/56), tagged `2.0.5`
- KituraKit (https://github.com/IBM-Swift/KituraKit/pull/46), tagged `0.0.23`
- Kitura-Credentials(https://github.com/IBM-Swift/Kitura-Credentials/pull/80), tagged `2.4.1`
- Kitura-CredentialsFacebook(https://github.com/IBM-Swift/Kitura-CredentialsFacebook/pull/53), tagged `2.3.1`
- Kitura-CredentialsGitHub(https://github.com/IBM-Swift/Kitura-CredentialsGitHub/pull/39), tagged  `2.1.1`
- Kitura-CredentialsGoogle(https://github.com/IBM-Swift/Kitura-CredentialsGoogle/pull/39), tagged `2.3.1`
- Kitura-CredentialsHTTP(https://github.com/IBM-Swift/Kitura-CredentialsHTTP/pull/58), tagged `2.1.3`
- Kitura-redis(https://github.com/IBM-Swift/Kitura-redis/pull/73), tagged `2.1.1`
- Kitura-Session(https://github.com/IBM-Swift/Kitura-Session/pull/66), tagged `3.3.3`
- Swift-JWT(https://github.com/IBM-Swift/Swift-JWT/pull/49), tagged `3.4.1`
- Kitura-Session-Redis(https://github.com/IBM-Swift/Kitura-Session-Redis/pull/44), tagged `2.1.1`
- Kitura-Cache (https://github.com/IBM-Swift/Kitura-Cache/pull/36), tagged `2.0.2`
- Kitura-Compression (https://github.com/IBM-Swift/Kitura-Compression/pull/45), tagged `2.2.2`
- Kitura-CORS (https://github.com/IBM-Swift/Kitura-CORS/pull/40), tagged `2.1.1`
- swift-html-entities (https://github.com/IBM-Swift/swift-html-entities/pull/54/files), tagged `3.0.12`
- Kitura-WebSocket (https://github.com/IBM-Swift/Kitura-WebSocket/pull/92), tagged `2.1.2`
- Swift-SMTP (https://github.com/IBM-Swift/Swift-SMTP/pull/99), tagged `5.1.1`
- Kitura-WebSocket-NIO (inherited from Kitura-WebSocket, manual changes during the initial push) tagged `2.0.0`
- Swift-Kuery (tagged direct from branch rel_301) tagged `3.0.1`
- SwiftKueryMySQL (https://github.com/IBM-Swift/SwiftKueryMySQL/pull/53) tagged `2.0.1`
- Swift-Kuery-ORM (https://github.com/IBM-Swift/Swift-Kuery-ORM/pull/108) tagged `0.5.2`
- Swift-Kuery-PostgreSQL (tagged direct from branch rel_211) tagged `2.1.1`
- Swift-Kuery-SQLite (tagged direct from branch rel_201) tagged `2.0.1`
- Swift-cfenv (https://github.com/IBM-Swift/Swift-cfenv/pull/73) tagged `6.0.3`
- Kitura-StencilTemplateEngine (https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/pull/44) tagged `1.11.1`
- Kitura-CouchDB (https://github.com/IBM-Swift/Kitura-CouchDB/pull/101) tagged `3.1.1`
- Kitura-Markdown (https://github.com/IBM-Swift/Kitura-Markdown/pull/24) tagged `1.1.1`
- CircuitBreaker (https://github.com/IBM-Swift/CircuitBreaker/pull/51) tagged `5.0.2`
- BlueCryptor (https://github.com/IBM-Swift/BlueCryptor/pull/54) tagged `1.0.27`
- BlueSocket (https://github.com/IBM-Swift/BlueSocket/pull/170) tagged `1.0.46`
- BlueSignals (https://github.com/IBM-Swift/BlueSignals/pull/19) tagged `1.0.99`
- BlueSSLService (https://github.com/IBM-Swift/BlueSSLService/pull/73) tagged `1.0.46`
- BlueRSA (https://github.com/IBM-Swift/BlueRSA/pull/45) tagged `1.0.28`
- SwiftMetrics (https://github.com/RuntimeTools/SwiftMetrics/pull/214) tagged `2.6.1`
- Kitura-Sample(https://github.com/IBM-Swift/Kitura-Sample/pull/128) - No tagging needed

**Comment by potap75** [comment]
Hi, 
Is that why it doesn't build anymore? The problem began after I ran _**swift package tools-version --set-current**_:

**"FAILED Failed to build the app.

Executing /swift-utils/tools-utils.sh build release command started at Sun Mar 31 17:51:59 2019 ⠒ Dumping output from the command:
Current folder: /swift-project
Command: build
Build configuration: release
Build folder: /swift-project/.build-ubuntu
Compiling the project…
Build configuration: release
/swift-project: error: package at ‘/swift-project’ requires a minimum Swift tools version of 5.0.0 (currently 4.2.0)"**

**Comment by djones6** [comment]
@potap75 I expect that is because your generated project is still using the Swift 4.2 toolchain to perform the build, and so when it encounters your Package.swift with tools-version:5.0 it can't build it.

You probably need to edit the Dockerfiles to say `FROM swift:5.0` to get the latest toolchain.

**Comment by potap75** [comment]
Thank  you! That  helped!

**Comment by pushkarnk** [comment]
@ianpartridge I realised that when I picked up the `Swift 5 bringup changes` from `Kitura-WebSocket` while pushing code to `Kitura-WebSocket-NIO`, tag `2.0.0` has these changes.

**Comment by ianpartridge** [comment]
Done!
