### ISSUE TITLE
Is it possible to save data to local web storage?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Kitura#1438]
as title and take a look following, please
![storage](https://user-images.githubusercontent.com/39903550/55531346-7bb89900-56dc-11e9-84b3-6360dec19ce6.png)

**Comment by saiHemak** [comment]
@diuming , I am not sure about the context of your question in Kitura space . Please let us know what you are exactly looking from Kitura end in this context  ?

As per the question, Local Storage  is a feature introduced in HTML 5 and it is a client side feature. If the browser supports the Local Storage  feature then  you should be able to save the data using ```localStorage ``` and it saves the data in the form of key-value pair on a user’s computer similar to cookies. Saving data on the client-side can help to speed up the performance of your web applications as it can reduce the number of database queries that are needed on the server.
