### ISSUE TITLE
Reconfigure Travis CI build on Travis.org

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#144]

**Comment by rfdickerson** [comment]
Just a small thing- can you change the badges to be the markdown:

[![Build Status](https://travis-ci.org/IBM-Swift/Kitura.svg?branch=master)](https://travis-ci.org/IBM-Swift/Kitura)

and for develop:

 [![Build Status](https://travis-ci.org/IBM-Swift/Kitura.svg?branch=develop)](https://travis-ci.org/IBM-Swift/Kitura)

The advantage here is that the Swift Package Index has issues rendering images that are not markdown. Plus, it would be nice to have the link directly to the build log.
