### ISSUE TITLE
Kitura 2.7 performance measurement

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#1444]
Now that Kitura 2.7 and Swift 5.0.1 is released we can re-run some numbers including TechEmpower.

**Comment by pushkarnk** [comment]
The "per-PR" performance test automation that we agreed to take up can be tracked using https://github.com/IBM-Swift/Kitura-NIO/issues/109 I'm closing this issue for now because there seems to action here.
