### ISSUE TITLE
What warnings when I switch to Kitura-NIO 2?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Kitura#1447]
Hi,
I switch to `Kitura-NIO 2` that i got some issues.
How do i get rid of these issues?
thanks

macOS 10.14.4
xcode 10.2.1
swift 5.0

issues
--------------------------------------------------------
[si_destination_compare] send failed: Invalid argument
[si_destination_compare] send failed: Undefined error: 0

**Comment by pushkarnk** [comment]
Hi @diuming can you please share a test case that reproduces this issue? The warnings don't seem to be coming from Kitura, so it is difficult to guess what's going wrong.

**Comment by diuming** [comment]
@pushkarnk thanks for help

take a look my simple code, please.

code
---
import Kitura

let router = Router()
Kitura.addHTTPServer(onPort: 8080, with: router)
Kitura.run()

thanks

**Comment by awadodeh** [comment]
What was the fix for this issue?

**Comment by pushkarnk** [comment]
Hi @awadodeh , our best guess is that these messages are logged by Network.framework or some other macOS library. Do you only see these messages or does any functionality appear broken?

**Comment by awadodeh** [comment]
@pushkarnk, I have seen this error but I give up on it for couple days. I will investigate it more and post an update about the issue.

**Comment by pushkarnk** [comment]
@weissi Any idea who logs these warning/error messages? They're seen only while launching Kitura with Kitura-NIO, in Xcode
```
[si_destination_compare] send failed: Invalid argument
[si_destination_compare] send failed: Undefined error: 0
```

**Comment by weissi** [comment]
@pushkarnk I can't reproduce I think unfortunately. I created a `KituraTest` executable and it doesn't print anything:

```
$ cat KituraTest/main.swift 
import Kitura

let router = Router()
Kitura.addHTTPServer(onPort: 8080, with: router)
Kitura.run()
johannes:~/extsrc/Kitura/Sources (master)
$ KITURA_NIO=1 swift run KituraTest

```

I also checked Console.app but didn't see this error.

**Comment by weissi** [comment]
Oops, excuse me. I can actually reproduce. Here's a `dtrace` trace that shows where this is coming from:

```
$ sudo dtrace -n 'pid$target::_os_log_error_impl:entry { ustack(); }' -c .build/debug/KituraTest
dtrace: description 'pid$target::_os_log_error_impl:entry ' matched 1 probe
CPU     ID                    FUNCTION:NAME
  4  38184         _os_log_error_impl:entry 
              libsystem_trace.dylib`_os_log_error_impl
              libsystem_info.dylib`si_destination_fill_netsrc+0x201
              libsystem_info.dylib`si_destination_fill_netsrc+0x17e
              libsystem_info.dylib`si_destination_cache_create+0x1d6
              libsystem_info.dylib`si_destination_lookup+0x64
              libsystem_info.dylib`si_destination_compare_internal+0xe0
              libsystem_info.dylib`si_destination_compare+0x22f
              libsystem_info.dylib`_gai_addr_sort+0x6f
              libsystem_c.dylib`_isort+0xca
              libsystem_c.dylib`_qsort+0x84c
              libsystem_info.dylib`_gai_sort_list+0x305
              libsystem_info.dylib`si_addrinfo+0x6f3
              libsystem_info.dylib`_getaddrinfo_internal+0xe7
              libsystem_info.dylib`getaddrinfo+0x3d
              KituraTest`static SocketAddress.makeAddressResolvingHost(_:port:)+0x183
              KituraTest`closure #1 in ServerBootstrap.bind(host:port:)+0x31
              KituraTest`partial apply for closure #1 in ServerBootstrap.bind(host:port:)+0x1f
              KituraTest`ServerBootstrap.bind0(_:)+0x44
              KituraTest`ServerBootstrap.bind(host:port:)+0x7f
              KituraTest`HTTPServer.listen(_:)+0x1234

  4  38184         _os_log_error_impl:entry 
              libsystem_trace.dylib`_os_log_error_impl
              libsystem_info.dylib`si_destination_fill_netsrc+0x201
              libsystem_info.dylib`si_destination_cache_create+0x1d6
              libsystem_info.dylib`si_destination_lookup+0x64
              libsystem_info.dylib`si_destination_compare_internal+0xe0
              libsystem_info.dylib`si_destination_compare+0x22f
              libsystem_info.dylib`_gai_addr_sort+0x6f
              libsystem_c.dylib`_isort+0xca
              libsystem_c.dylib`_qsort+0x84c
              libsystem_info.dylib`_gai_sort_list+0x305
              libsystem_info.dylib`si_addrinfo+0x6f3
              libsystem_info.dylib`_getaddrinfo_internal+0xe7
              libsystem_info.dylib`getaddrinfo+0x3d
              KituraTest`static SocketAddress.makeAddressResolvingHost(_:port:)+0x183
              KituraTest`closure #1 in ServerBootstrap.bind(host:port:)+0x31
              KituraTest`partial apply for closure #1 in ServerBootstrap.bind(host:port:)+0x1f
              KituraTest`ServerBootstrap.bind0(_:)+0x44
              KituraTest`ServerBootstrap.bind(host:port:)+0x7f
              KituraTest`HTTPServer.listen(_:)+0x1234
              KituraTest`HTTPServer.listen(on:address:)+0x16d
```

**Comment by weissi** [comment]
this is macOS's resolver trying to resolve the host. This message can be safely ignored.

There's nothing SwiftNIO can do better here. It's the correct thing to do to resolve whatever host was passed to SwiftNIO even if it's already an IP address for proper IPv6 support (I think [RFC 7050](https://www.ietf.org/rfc/rfc7050.txt) is the relevant here).

If KituraNIO definitely doesn't want NIO to invoke the resolver when binding, it could switch to [`ServerBootstrap.bind(to:)`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/ServerBootstrap.html#/s:3NIO15ServerBootstrapC4bind2toAA15EventLoopFutureCyAA7Channel_pGAA13SocketAddressO_tF) and supplying a `SocketAddress` retrieved from [`SocketAddress.init(ipAddress:port:)`](https://apple.github.io/swift-nio/docs/current/NIO/Enums/SocketAddress.html#/s:3NIO13SocketAddressO02ipC04portACSS_SitKcfc).

For example

```
ServerBootstrap(group: group).
   ...
   .bind(to: try SocketAddress(ipAddress: "127.0.0.1", port: port)
```

in which case SwiftNIO will not try and resolve `"127.0.0.1"`. But I would not recommend this, the current behaviour is good.

If you don't want to just ignore the message from the resolver, please file a bug against macOS using [Feedback Assistant](https://feedbackassistant.apple.com/welcome)

**Comment by pushkarnk** [comment]
Thanks @weissi for the investigation and explanation!
