### ISSUE TITLE
swift build error

### ISSUE THREAD

**Issue by itsaboutcode** [IBM-Swift/Kitura#145]
When I ran the `swift build` command, i got the following error :(

`<unknown>:0: error: no such file or directory: 'build'`

**Comment by irar2** [comment]
Please add 
<path to your swift>/swift-latest.xctoolchain/usr/bin 
to your PATH

**Comment by tkinjo1985** [comment]
You can make the tools available for use from the terminal with the following command:
On OSX
$ export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"

On Linux
$ export PATH=/path/to/Swift/usr/bin:"${PATH}"

**Comment by itsaboutcode** [comment]
I believe the issue has to do with `release vs development snapshots`. 

Reference: https://github.com/apple/swift-package-manager#installing

**Comment by brunophilipe** [comment]
I found out the problem is that the path `/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin` should come before the rest of the default path, so the dev version installed in the path above takes precedence over the Swift version bundled with Xcode.

Although the instructions display the export line correctly, this is not an explicit instruction.

**Comment by matteocrippa** [comment]
@itsaboutcode are you using Xcode swift? you need swift 2.2-dev or + to be able to use ```swift build``` command

**Comment by itsaboutcode** [comment]
@matteocrippa - Yap. Using XCode version of swift. I believe I will need [swiftenv](https://github.com/kylef/swiftenv) to mange them :(

**Comment by matteocrippa** [comment]
prob is even faster to use instead docker, I managed to use swiftenv without any success so far.

**Comment by scrumit** [comment]
I've been trying to build for a while on OS X.  Even tried using _build-osx.sh_.

Now getting this error:
> Linking Executable:  .build/debug/KituraSample
> ld: library not found for -lcurlHelpers for architecture x86_64

And there's still an error in the file names:

> *** No rule to make target `Packages/Kitura-net*/Makefile'.  Stop.

Shouldn't it be KituraNet-* ?

**Comment by dfirsht** [comment]
Hey we have been updating and fixing things a lot over this weekend. Please try updating with a git pull and deleting your Packages folder. The development branch should work with the 2/25 binary.

**Comment by rfdickerson** [comment]
Fixed from IBM-Swift/Kitura#175

**Comment by scrumit** [comment]
KituraSample builds now but still fails:

> mel$ ./KituraSample
> dyld: Library not loaded: ./.build/debug/libcurlHelpers.dylib
>   Referenced from: /Users/mel/Kitura/.build/debug/./KituraSample
>   Reason: image not found
> Trace/BPT trap: 5

**Comment by scrumit** [comment]
It works. Many thanks for your patience. Perhaps mention in README that you call KituraSample as:
> ./build/debug/KituraSample

because library load appears to be hard coded: ./.build/debug/libcurlHelpers.dylib

**Comment by Sum1n** [comment]
after path specified you need to run ./swift/utils/build-script
