### ISSUE TITLE
Kitura listens on every available address/interface

### ISSUE THREAD

**Issue by TaborKelly** [IBM-Swift/Kitura#1450]
## Context and Description
Kitura listens on every available address/interface. This is okay when you are running in a Docker container but becomes a real problem when you aren't. For example, I only want Kitura to listen on localhost so that I can force everyone to go through an nginx reverse-proxy.

### Environment Details
Ubuntu 18.04 with Swift 5.0.1.

### Steps to Reproduce
1) Use Kitura to `Kitura.addHTTPServer(onPort: port, ...); Kitura.start()`
2) Notice that Kitura is now listening on `port` for every address/interface.

### Expected vs. Actual Behaviour
I would very much like an option to only listen on one address.

**Comment by djones6** [comment]
This is now available in Kitura-net `2.3.0` and Kitura-NIO tagged `2.1.0`.

The remaining piece is to update the `Kitura.addXXXXServer` API to expose the new option.

**Comment by TaborKelly** [comment]
Can you re-open this issue, since the Kitura changes aren't done yet?

**Comment by TaborKelly** [comment]
Would it be possible to get a tagged release with this change?

**Comment by djones6** [comment]
@TaborKelly this requires a minor version increment as it adds new API.  I expect that we'll do a Kitura 2.8 release next week.

**Comment by djones6** [comment]
This is now tagged in Kitura `2.8.0`.
