### ISSUE TITLE
Maintaining backwards compatibility with Swift 4.2?

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/Kitura#1454]
## Context and Description
Is it a goal of Kitura to maintain backwards compatibility with Swift 4.2 at least in terms of earlier versions of packages?

### Environment Details
I haven't updated my server system yet to Swift 5. I'm using Xcode 10.1 for local development for my server.

### Steps to Reproduce
In my Package.swift, I'm referencing:
.package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.6.0")),
which should reference:
https://github.com/IBM-Swift/Kitura/blob/2.6.3/Package.swift

### Expected vs. Actual Behaviour
I hoped that I'd be able to still build my project with Swift 4.2.  However, Swift 5 package versions are being resolved. It seems this is because of the way the Kitura 2.6.3 Package.swift is specified.

**Comment by ianpartridge** [comment]
Hi, thanks for opening the issue.

Yes, Kitura 2.6 should work fine with Swift 4.2.  Can you paste a `Package.swift` that isn't working for you?  We'll try and recreate.

**Comment by crspybits** [comment]
OK-- whoops. This was my bad. Somehow I had been SWIFT_VERSION's of 5 in my Xcode project, but when I cleaned, and tried again, this isn't happening. I'm closing. Thanks!
