### ISSUE TITLE
Creating OpenAPI project comes "Error resolving dependencies" in macOS Kitura app

### ISSUE THREAD

**Issue by uskithub** [IBM-Swift/Kitura#1455]
## Context and Description
A description of the issue.

This issue is as same as #1415.

Using Kitura app to create a project that is "Starter" or "OpenAPI", it comes to fail with "Error resolving dependencies". "Skeleton" is success.

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.

tools                 | version
---------------|--------
macOS             | Mojave 10.14.3
Xcode Version | 10.1 (10B61)
Kitura app        | 1.1 (1)

```shell
$ swift --version
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0
```

```shell
$ xcode-select -version
xcode-select version 2354.
```

<img width="912" alt="スクリーンショット 2019-05-29 22 51 31" src="https://user-images.githubusercontent.com/763162/58562495-540d2980-8264-11e9-9603-b036fc12c6f3.png">

### Steps to Reproduce

1. Launch the Kitura app.
2. Select to create a "Starter" or "Skeleton" project.
3. Enter the name for new project.
4. Click "Create" button.

### Expected vs. Actual Behaviour
- [ ] Expected to happen...  new project should be created.
- [ ] Actually happened...  an error dialog occurs as below and no project folder is created.

<img width="892" alt="スクリーンショット 2019-05-29 22 16 25" src="https://user-images.githubusercontent.com/763162/58563253-c6cad480-8265-11e9-9d15-c5bb6399120f.png">

Thanks.

**Comment by uskithub** [comment]
@KBryan Do you mean to try "xcode-select --install" again?

**Comment by KBryan** [comment]
No try the Kitura Command Line Interface installation. It should be option 2 in the installing Kitura guide.

**Comment by uskithub** [comment]
Isn't it right that Kitura app should work without the Kitura CLI?

**Comment by KBryan** [comment]
You would think so. Or install Kitura CLI in the background.

**Comment by kilnerm** [comment]
@uskithub If everything works after installing the cli let us know and we can look at resolving that. If not then can you please copy the contents of ypur Package.swift and Package.resolved files from the project if they exist?

Thanks

**Comment by ddunn2** [comment]
@uskithub @KBryan  

The macOS app does not use the CLI in the background nor does it require it. The only link between the macOS app and the CLI is that they both target the same [repository](https://github.com/IBM-Swift/generator-swiftserver-projects) for cloning down the projects. 

One thing I can suggest is ensuring that your command-line tools are actually set, installing them isn't always enough sadly. 

To check if your Command line tools are set:
1. Open Xcode
2. Click on Xcode in the task bar and select `preferences` from the drop down (or press `⌘ + ,`)
3. Once the UI has popped up, go to the locations tab
4. Ensure the `Command Line Tools:` field has a value, if it does not try setting it. 
5. Rerun the macOS app project creation

Let me know if this helps!

**Comment by uskithub** [comment]
@kilnerm I tried to install Kitura CLI by Homebrew, but it came error below.

Is this as same reason as the error of Kitura app, isn't it?

```shell
$ brew install kitura
Updating Homebrew...
==> Installing kitura from ibm-swift/kitura
Error: Your Xcode (10.1) is too outdated.
Please update to Xcode 10.2.1 (or delete it).
Xcode can be updated from the App Store.
```

I will install latest Xcode and try again.

**Comment by kilnerm** [comment]
@uskithub Let me know how it goes!

If you upgrade to Xcode 10.2.1 you will be at the same level as I am and I can create the projects without issues.

Also, you should not need to install the cli tools for the Kitura app to work.

**Comment by ddunn2** [comment]
@uskithub 
The reason you need to update Xcode is the macOS app and the CLI generate projects built for Swift 5 as defined in the generated [Package.swift](https://github.com/IBM-Swift/generator-swiftserver-projects/blob/init/Package.swift#L1) file and Swift 5 support was released in Xcode 10.2

Updating your Xcode to the latest version should resolve this issue at least :)

**Comment by kilnerm** [comment]
@uskithub Did the Xcode upgrade resolve your issue?

**Comment by kilnerm** [comment]
I will mark this as closed, if further assistance is required please re-open as necessary.
