### ISSUE TITLE
Cookie creation enhancement 

### ISSUE THREAD

**Issue by TaborKelly** [IBM-Swift/Kitura#1456]
## Context and Description
Kitura uses Foundations `HTTPCookie`, which is great. However, it would be nice if it were easier to create `HTTPCookie`s. 

### Environment Details
Swift 5.0.1, XCode 10.2.1, macOS 10.14.5.

### Steps to Reproduce
Try to create a cookie to send in a `RouterResponse`. You end up writing something like this:
```swift
func createCookie(key: String, value: String, hostname: String) -> HTTPCookie? {
    var cookieProps: [HTTPCookiePropertyKey: Any]
    cookieProps = [
        HTTPCookiePropertyKey.domain: hostname,
        HTTPCookiePropertyKey.path: "/",
        HTTPCookiePropertyKey.name: key,
        HTTPCookiePropertyKey.value: value
    ]

    let cookie = HTTPCookie(properties: cookieProps)
    return cookie
}
```

### Expected vs. Actual Behaviour
It would be great to have a helper function for this in Kitura.

**Comment by pushkarnk** [comment]
IMO, there shouldn't be a problem in providing some convenience methods to work with cookies.

**Comment by ianpartridge** [comment]
Yes, very happy to accept improvements like this.

**Comment by RudraniW** [comment]
I have initial implementation of the given enhancement. Now I am working on writing test cases and documentation for the same. I will provide a link to a branch with this code soon.

**Comment by RudraniW** [comment]
You can check the implementation code here : https://github.com/RudraniW/Kitura/tree/CreateHTTPCook

**Comment by RudraniW** [comment]
@TaborKelly I have created #1468 with possible solution for this issue. Here is a sample code to use this feature.
```
let attributes: [RouterResponse.CookieAttribute] = [
    .name("foo"),
    .value("bar"),
    .domain("localhost"),
    .path("/"),
]


let router = Router()
router.get("/") {request, response, next in
   let testcookie = response.addCookie(with: attributes)
    response.send("Hello, world!!")
    next()
}
```
Can you review and provide feedback please?

**Comment by TaborKelly** [comment]
Thanks @RudraniW, I commented on #1468.

**Comment by RudraniW** [comment]
@TaborKelly based on your feedback I have new version of `addCookie`. In this new version of `addCookie` these mandatory attributes are made function parameters. User can give other optional cookie attributes through the `otherAttributes` array. The name, value, domain and path attributes are ignored if they are repeated in `otherAttributes` array.
You can check the implementation code here : https://github.com/RudraniW/Kitura/commit/1dd52f3ea06375c8e8ecb3f56629098a31ea09c0
Let us know what you think about this implementation.

**Comment by TaborKelly** [comment]
I apologize for not getting back to you sooner. I'm not a web expert, do we want `domain` to be required? The Apple documentation says that either  `originURL` or `domain` will work. I'm curious if @ianpartridge, @pushkarnk, @djones6, or @kilnerm have more thoughts?

**Comment by pushkarnk** [comment]
Yes, we did consider this "either `originURL` or `domain`" condition. To enforce it, the only way is to introduce a new public enum (which is undesirable here). The `domain` attribute seems to be more common than `originURL`. In fact, there's no mention of `origin URL` in the HTTP Cookies RFC (see [this section](https://tools.ietf.org/html/rfc6265#section-5.2)). Hence the decision to make `domain` mandatory. That's my opinion.

**Comment by TaborKelly** [comment]
That works for me. Thanks pushkarnk and RudraniW!
