### ISSUE TITLE
Is it a correct way to create kitura web using xcode11's swift package?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Kitura#1476]
## Context and Description
I create a kitura web using xcode11's swift package.
- adding main.swift in Sources/ProjectName.
- adding dependencies `Kitura-StencilTemplateEngine` and `Configuration` packages.

let projectPath = `ConfigurationManager.BasePath.project.path`
- run in xcode11
the projectPath doesn't point to project folder, StencilTemplateEngine also can't points to default folder `Views`.
- run in command line
`Kitura-StencilTemplateEngine` and `Configuration` are working very well.

Question: is it possible to create `kitura web`+`kitura-nio` using xcode11's swift package.
thanks

### Environment Details
MacOS 10.15 beta
Xcode 11.0 beta 4

**Comment by gurugeek** [comment]
I think the best way to create web app is this
step 1  -- run this command inside the folder where you want your app to be 

`swift package init --type executable`

step 2 open package.Swift

and add this
```

// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "YOURappName",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura", from: "2.8.0")

        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: "1.9.0"),

        .package(url: "https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git", from: "1.11.1"),
    ],
    targets: [
        .target(
            name: "YOURappName"",
            dependencies: ["Kitura"]),
        .testTarget(
            name: "YOURappName"Tests",
            dependencies: ["YOURappName""]),
    ]
)
```

step 2 
`swift package generate-xcodeproj` to open the project
your app code goes inside -->YOURAppName-->Sources-->main.swift

note that templates go into the Views folder and you can also set a /public folder to serve images, css etc. like this     

`router.all("/public", middleware: StaticFileServer()) // public folder`

**Comment by diuming** [comment]
Just enable `Working Directory`
![wd](https://user-images.githubusercontent.com/39903550/71498771-9c430780-2898-11ea-8896-43d1b6ccc18a.png)
