### ISSUE TITLE
Investigate CouchDB compile issues

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#148]

**Comment by vadimeisenbergibm** [comment]
Currently the following error occurs: 
Kitura-CouchDB/Package.swift:30:15: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
let package = Package(
              ^~~~~~~~
Solution: remove passing dependencies as a parameter. Add dependencies one by one, e.g.:
package.dependencies.append(.Package(url: "https://github.com/IBM-Swift/LoggerAPI.git", versions: Version(0,2,0)..<Version(0,3,0)))

**Comment by rolivieri** [comment]
I just confirmed that kitura-couchdb compiles on both platforms, os x and linux, so I am closing the issue.
