### ISSUE TITLE
Kitura Codable Routes crashing on iOS with EXC_BAD_ACCESS (code=2, ...)

### ISSUE THREAD

**Issue by DanielMandea** [IBM-Swift/Kitura#1492]
## Context and Description
While using Kitura Codable Routes on iOS, the application crashes with `EXC_BAD_ACCESS (code=2, address=...)` in `TypeDecoder.swift` line 748.
If necessary I can provide a screenshot and a demo app that can be used in order to reproduce this issue. 

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.
iOS 13.2, Xcode 11.2

### Steps to Reproduce
1) Run Kitura on iOS 
2) Bind to your router a Codable route
3) App will crash with `EXC_BAD_ACCESS (code=2,` in  in `TypeDecoder.swift` line 748.

### Expected vs. Actual Behaviour
- [ ] Application should not crash and the route should be processed 
- [ ] Application is crashing with `EXC_BAD_ACCESS (code=2,` in  in `TypeDecoder.swift` line 748

Extra:
- if I am not using Codable routs and use some default routs like the one below, app is working fine. 
```
router.post("/events") { request, response, completion in
         // do smth 
  }
```
The actual problem is happening when decoding the route and it seams that we try to write some readonly memory / or smth. 
Tried on MacOS and it works fine ...

**Comment by harish1992** [comment]
Hi @DanielMandea, as we discussed over the call can this issue be closed now? Thanks.

**Comment by DanielMandea** [comment]
After investigating this along with @harish1992 we found that there is a simulator problem and after  erasing all content on that simulator Kitura Codable Routs do not crash anymore. Will close this issue.
