### ISSUE TITLE
Add to the Kitura-router the ability to add error handlers

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#15]
Add to the Kitura router the ability to add error handlers which can be invoked when a handler or middleware indicates that it encountered an error. This error handler could be the part of a server application that creates and returns the error page.

**Comment by dfirsht** [comment]
The error handler is going to be inspired by express: http://expressjs.com/en/guide/error-handling.html.  However we would like it to be a separate function with a use like router.error(). The library will pass any errors to these entities in the order they were written.

**Comment by dfirsht** [comment]
Once validated the router error-handling branch needs to be merged into develop and tagged. Then Package.swift needs to be updated in the Kitura error-handling branch and afterwards, merged into develop.

**Comment by rolivieri** [comment]
Assigning to me for now for validation.

**Comment by rolivieri** [comment]
@dfirsht  Looks good! Can you double check that line 331 in Sources/KituraRouter/Router.swift is using the logger instead of the print statement?

 >> print(self.routeElems[elemIndex].method)

Other than that, I think you can merge.

**Comment by dfirsht** [comment]
Confirmed, merged both branches into develop.
