### ISSUE TITLE
Invoke swift build from make, remove swift build step from README 

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#150]
We can invoke swift build from make, this way reducing the installation steps by one.
The swift build will fail as expected and its failure will be ignored by make.

Caveat: if swift build fails in an unexpected way, make will continue despite that. make will probably fail in the next step during linkage. Anyway, since today swift build is expected to fail, in the current situation the user will ignore swift build failure even today, so we just combine two steps 1) swift build and 2) make into one step for the user.

**Comment by kweinmeister** [comment]
Please also include the step of removing swift build from the vagrantfile also in this issue. By doing so, it would also help validate the file and steps.

**Comment by shmuelk** [comment]
So now, every time you invoke make in Kitura, we run swift build twice?

Also I didn't see that the Makefile-client was updated in the Kitura-net project. The Makefile in Kitura and other places are simply copies of the Makefile-client. We need to be very careful about changes to MAkefile-client as it gets copied all over the place.

**Comment by vadimeisenbergibm** [comment]
Why twice? make executes swift build once, the user should not run swift build.

I did not touch Makefiles in other projects yet.

**Comment by shmuelk** [comment]
Because the inner make also invokes swift build

**Comment by shmuelk** [comment]
The overall goal is to eliminate the make files altogether. As soon as swift build supports C code in the project we will not need make at all. I wouldn't waste time optimizing this now.

**Comment by shmuelk** [comment]
The initial swift build is really there just to fetch the dependencies, in order to run make, in particular the inner make, which is part of Kitura-net. The idea was that the outer make file, would never need to change, as changing it is a maintenance disaster.

**Comment by vadimeisenbergibm** [comment]
Yes, I see, swift build is run twice by make. So the idea was to run swift build once for the first time and then run make for the first time, and then to run make each time the code changes? It is not explained explicitly in the README. So now the user will run a redundant swift build each time they make any change and perform build. I do not see a large problem with that, on the other side we reduce a step in installation with explanation that this step is expected to fail.

**Comment by vadimeisenbergibm** [comment]
Agreed not to change other Makefiles - I propose to change only the one of Kitura since it is the project the users will work with most.

**Comment by dfirsht** [comment]
Once the new swift binary is released, we can replace the first swift build with `swift build --fetch`. This will only fetch the dependencies and not try to build.
