### ISSUE TITLE
Tests created by 'kitura init' fail on Swift 5.1.5

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/Kitura#1503]
## Context and Description
After running `kitura init` to create a Swift app, I then ran `swift test` and the tests ran with 3 warnings but passed. (This is on swift version 5.1.3).

I then converted this into an Appsody project and the tests failed with the following output (shortened below). Looking at the Appsody swift stack it looks like it's pulling in Swift 5.1.5, so these tests (which are created during `kitura init`) appear to fail on later versions of Swift:

```
[Container] Running command:  swift test
/project/user-app/Tests/ApplicationTests/RouteTests.swift:88:19: error: use of undeclared type 'URLRequest'
[Container] private extension URLRequest {
[Container]                   ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/RouteTests.swift:46:9: error: use of unresolved identifier 'URLRequest'
[Container]         URLRequest(forTestWithMethod: "GET")?
[Container]         ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/RouteTests.swift:65:9: error: use of unresolved identifier 'URLRequest'
[Container]         URLRequest(forTestWithMethod: "GET", route: "health")?
[Container]         ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/RouteTests.swift:91:54: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
[Container]         if let url = URL(string: "http://127.0.0.1:\(RouteTests.port)/" + route){
[Container] 
```      

### Environment Details
macOS 10.15.3 Catalina running Swift 5.1.3 and then Swift 5.1.5

### Steps to Reproduce
Listed above

### Expected vs. Actual Behaviour
- [ ] Tests expected to pass
- [ ] Tests failed on later versions of Swift

**Comment by djones6** [comment]
@helenmasters this should be fixed by https://github.com/IBM-Swift/generator-swiftserver-projects/pull/29 - can you confirm?

**Comment by helenmasters** [comment]
@djones6 it's very strange, this did work for me when I ran `appsody test` immediately after you made this fix.

However, today I've been testing the fix for the Appsody swift stack which you made yesterday https://github.com/appsody/stacks/pull/733 and now I am seeing the above failure again? I don't *think* I've changed anything else in my configuration so I'm a bit confused by that.

**Comment by djones6** [comment]
@helenmasters we discovered that a cron job on that repo was still active and the next day it regenerated the (old) project code.  The fix was reapplied in https://github.com/IBM-Swift/generator-swiftserver-projects/pull/30 and the cron has been turned off (as the generator itself is no longer being developed).
