### ISSUE TITLE
could not build C module 'CCurl

### ISSUE THREAD

**Issue by hockeyrun** [IBM-Swift/Kitura#1507]
## Context and Description
A description of the issue.

### Environment Details
Swift version 5.2.4 (swift-5.2.4-RELEASE)
Target: x86_64-unknown-linux-gnu
OS: Ubuntu 20.0 LTS

### Steps to Reproduce
1) make new folder
2) install kitura-cli
3) kitura init
4) kitura build

### Expected vs. Actual Behaviour
- [ ] Can build and run project
- [ ] <module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/root/Documents/SwiftBackend/.build/checkouts/Kitura-net/Sources/CCurl/shim.h:20:9: error: 'curl/curl.h' file not found
#import <curl/curl.h>
        ^
/root/Documents/SwiftBackend/.build/checkouts/Kitura-net/Sources/KituraNet/ClientRequest.swift:18:8: error: could not build C module 'CCurl'
import CCurl

**Comment by dannys42** [comment]
Can you confirm if you have the libcurl-dev package installed?

**Comment by hockeyrun** [comment]
> Can you confirm if you have the libcurl-dev package installed?

Thanks dannys, I can't found libcurl-dev on Ubuntu 20.0 LTS so changed by installing libcurl4-openssl-dev and issue was fixed.
