### ISSUE TITLE
Moustache alternative

### ISSUE THREAD

**Issue by matteocrippa** [IBM-Swift/Kitura#155]
I noticed tha Moustache seems to be compatible atm only with OSX, [Stencil](https://github.com/kylef/Stencil) is pretty similar and it is already used under linux too in other projects

**Comment by vadimeisenbergibm** [comment]
@matteocrippa - good point. @shmuelk what do you think?

**Comment by vadimeisenbergibm** [comment]
@matteocrippa @shmuelk Stencil does not fully work on Linux (Collections do not work) see kylef/Stencil#51

**Comment by matteocrippa** [comment]
I'm looking at it, seems an issue connected to [this](http://stackoverflow.com/questions/32156910/swift-pattern-match-on-arrayany), I'm trying to fix it in the meanwhile

**Comment by kylef** [comment]
I've resolved the problems running Stencil on Linux in the 0.5.3 release. The tests are now passing on Linux.

**Comment by matteocrippa** [comment]
Cool thx @kylef

**Comment by vadimeisenbergibm** [comment]
@matteocrippa first, please take a look at https://github.com/IBM-Swift/Kitura/issues/203#issuecomment-190783107 how any template engine can be integrated with Kitura. Your comments are welcome.

**Comment by matteocrippa** [comment]
@vadimeisenbergibm thx, I'm into creating an ORM for CouchDB, but then I'll look for sure into this

**Comment by vadimeisenbergibm** [comment]
Added a sample app that uses Stencil https://github.com/IBM-Swift/Kitura-SampleStencil

**Comment by dfirsht** [comment]
Confirmed that SampleStencil works.
