### ISSUE TITLE
Docker build failing 

### ISSUE THREAD

**Issue by ajaybeniwal** [IBM-Swift/Kitura#156]
I am not able to install the docker version on mac osx with below error 
Linking Library:  .build/debug/LoggerAPI.a
Compiling Swift Module 'KituraSys' (4 sources)
/root/Kitura/Packages/Kitura-sys-0.2.0/Sources/KituraSys/Queue.swift:48:42: error: use of unresolved identifier 'get_dispatch_queue_concurrent'
        let concurrent: COpaquePointer = get_dispatch_queue_concurrent()
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/root/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu15.10/usr/bin/swift-build-tool", "-f", "/root/Kitura/.build/debug/Kitura-Sys.o/llbuild.yaml"]
Packages/Kitura-net-0.2.0/Makefile:44: recipe for target 'kitura' failed
make[1]: *** [kitura] Error 1
make[1]: Leaving directory '/root/Kitura'
Makefile:21: recipe for target 'make' failed
make: *** [make] Error 2

**Comment by rolivieri** [comment]
We updated the master branch so that it now can compile with the docker image.

**Comment by priyaBagrecha** [comment]
I am getting the same error as Ajaybeniwal is getting when trying to run the make command on MAC terminal. Please help.

**Comment by rolivieri** [comment]
@priyaBagrecha Are you following the docker instructions on the [develop branch](https://github.com/IBM-Swift/Kitura/tree/develop)? If you follow those steps, it should work just fine. Please note you just need to run the /root/clone_build_test_kitura.sh script (in the docker container) to clone, build, and test Kitura.

**Comment by rolivieri** [comment]
@priyaBagrecha Also, make sure you are using the latest version of the docker image by pulling it from Docker Hub.

**Comment by kishanravindra** [comment]
Facing the same Issue .Update docker to latest one and try to clone. But still facing same Issue

**Comment by rolivieri** [comment]
@kishanravindra We just updated the docker image; this should address the issue you ran into. Can you do a docker pull to get the latest image?

`docker pull ibmcom/kitura-ubuntu`
