### ISSUE TITLE
Set SDK Root?

### ISSUE THREAD

**Issue by casamm** [IBM-Swift/Kitura#158]
The swift build/make command is invoking some errors and referring to setting sdk root???

````
Linking Library:  .build/debug/LoggerAPI.a
Compiling Swift Module 'KituraSys' (4 sources)
/Users/ssss/Documents/Kitura/Packages/Kitura-sys-0.2.1/Sources/KituraSys/Queue.swift:17:8: error: cannot load underlying module for 'Dispatch'
import Dispatch
       ^
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun -sdk macosx swiftc" to select the default OS X SDK installed with Xcode
/Users/ssss/Documents/Kitura/Packages/Kitura-sys-0.2.1/Sources/KituraSys/Queue.swift:17:8: error: cannot load underlying module for 'Dispatch'
import Dispatch
````

**Comment by dfirsht** [comment]
Are you building for osx or linux?

**Comment by casamm** [comment]
I'm on OSX, Following the instructions page, installed Docker (new to this) and have completed all 5 steps mentioned. I'm stuck while following Installation (OS X) at #5.

**Comment by dfirsht** [comment]
Well if you are using docker then you should be following the docker instructions, not the OS X ones.

**Comment by casamm** [comment]
sorry got confused, I'm going to rollback, uninstall docker and go with the OS X ones, do I need to do something for this error?

**Comment by dfirsht** [comment]
If you follow all the OS X instructions you shouldn't see that error.

**Comment by casamm** [comment]
the only thing I can think of are the instructions at https://swift.org/download/#apple-platforms for Xcode 7.3 and my path has `/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:/Librar....`

**Comment by dfirsht** [comment]
The build process doesn't use Xcode so it doesn't matter how Xcode is configured. Make sure you are using the development snapshot of swift. Typing `swift -v` should print something that includes: `/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a.xctoolchain/usr/bin/lldb`

**Comment by casamm** [comment]
Here's the output for `swift -v`

````
swift -v
Apple Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)
Target: x86_64-apple-macosx10.9
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a.xctoolchain/usr/bin/lldb "--repl=-target x86_64-apple-macosx10.9 -enable-objc-interop -sdk / -color-diagnostics"
error: failed to launch REPL process: process launch failed: unable to locate debug server
````

**Comment by dfirsht** [comment]
Well that error indicates to me that the swift toolchain wasn't installed correctly. Looking at my output, I see a difference for the -sdk: ```/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a.xctoolchain/usr/bin/lldb "--repl=-target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -color-diagnostics"```
Make sure you installed the sdk correctly.

**Comment by casamm** [comment]
I see the difference, and the reason is I'm using XCode 7.3 Beta, therefore the path is 
`/Applications/Xcode-beta.app/...` instead of `/Applications/Xcode.app/` in your case

**Comment by KevinGong2013** [comment]
<img width="884" alt="screen shot 2016-03-24 at 7 30 02 pm" src="https://cloud.githubusercontent.com/assets/5820203/14015855/d958329e-f1f6-11e5-80e2-8def4a01e4bb.png">

I got this error. can't load lldb ?
