### ISSUE TITLE
Pass along error information for DB create / delete in CouchDB

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#159]
When an error is encountered in CouchDB, we currently create a standard NSError and pass on the error code. However, this drops the body of the error response which contains useful info. The new error class will capture this information and pass it on to the user.

**Comment by dfirsht** [comment]
Instead of creating a new error class, I used the existing create NSError methods to pass along the body of the error response as needed.

**Comment by rolivieri** [comment]
Just finished reviewing!
