### ISSUE TITLE
Tutorial for linking c lib

### ISSUE THREAD

**Issue by Schr3da** [IBM-Swift/Kitura#161]
First of all thanks for the support and priovided framework. 
I would have now an question related to OSX and Kitura. How can I setup it in case that Brew is installing the downloaded libs in a other place. they are not under /usr/local/.. Is it possible to get an Example with the c libs within the Kitura application. I tried it to make it work seemse 4 hours but no success. I would like to play around with it but Im unable to make it work on OSX 10.11 Everthing is installed from Swift point of View I during the make I just get noticed that http-parser cant be found. I used brew to install it but my brew version was custom installed so I need to set the paths for the c "modules". Can someone maybe support an example for this. Like a quick project... Thanks a lot

**Comment by rfdickerson** [comment]
Can you try editing the following file that gets downloaded to your Packages/Kitura-Net directory:

[KituraNet/Makefile](https://github.com/IBM-Swift/Kitura-net/blob/master/Makefile)

In EXTRA_LINK add/replace:
```
EXTRA_LINK=-Xlinker -ldispatch -Xlinker -L /path/to/your/brew/libs
```

**Comment by Schr3da** [comment]
Hello,
Thank you for your response! I tried to modify it but it still couldnt be detected :(. Enclosed you can find the make file. added it as recommended

`ROOT_DIR=.
BUILD_DIR=${ROOT_DIR}/.build/debug

HTTP_PARSER_MODULE=$(wildcard ${ROOT_DIR}/Packages/Kitura-HttpParserHelper-*)
CURL_MODULE=$(wildcard ${ROOT_DIR}/Packages/Kitura-CurlHelpers-*)

# Include where users install header files (i.e. this is where dispatch/dispatch.h and pcre2 should be located).
INCLUDE_DIR=/usr/local/include
#detect OS
UNAME := $(shell uname)

ifeq ($(UNAME),Darwin)
CLANG_EXTRA=-mmacosx-version-min=10.10
**EXTRA_LINK=-Xlinker -ldispatch -Xlinker -L/Developer/libs/homebrew/lib**
else
CLANG_EXTRA=
EXTRA_LINK=-Xlinker -ldispatch -Xlinker -L/Developer/libs/homebrew/lib
endif
`

This shows only the modified part of the make file... but still getting the compile errors:

`
/Kitura-master/Packages/Kitura-net-0.2.0/Sources/KituraNet/HttpParser/HttpParser.swift:18:8: error: could not build Objective-C module 'http_parser_helper'
import http_parser_helper
`

Thats my swift version:
`
Apple Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)
Target: x86_64-apple-macosx10.9
`

Thanks a lot!
regards
