### ISSUE TITLE
Combine Kitura-router and Kitura into one single Swift Package.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#168]
Here's the summary of the discussion we had:

Keep the Kitura-net and Kitura-sys packages (i.e. as separate repos).
Move Kitura-router code into the Kitura repo.
Move the Kitura sample into a new, separate repo. 
Explore using test dependencies for the Kitura sample (i.e. Kitura could have a test dependency on the Kitura sample repo). Be aware of cyclical dependencies.

**Comment by dfirsht** [comment]
After combining them, I can confirm that this is valid using the 0.5.0 tag of Kitura.
