### ISSUE TITLE
Compile GRMustache templating engine on Linux Swift 3.0

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#169]
Compiling GRMustache.swift on Linux, while verifying that nothing is broken on OS X.
Depends on #84

**Comment by vadimeisenbergibm** [comment]
Completed in Swift3.0_with_tests_Linux2 branch.
The branch compiles on Linux. The branch compiles and tests pass on OS X.

**Comment by shmuelk** [comment]
Compiled and tested on Linux and OSX after an update was made by Vadim to the Makefile for running the tests.
