### ISSUE TITLE
Make tests of GRMustache.swift pass on Linux Swift 3.0

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#170]
Making GRMustache.swift tests pass on Linux, while verifying that nothing is broken on OS X and documenting any blockers and dependencies on Apple issues to be resolved.

**Comment by vadimeisenbergibm** [comment]
Depends on #171

**Comment by vadimeisenbergibm** [comment]
Arrived to 273 out of 313 (87%) tests passing on Linux on Swift3.0_with_tests_Linux2, snapshot swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10. The same version passes 100% tests on OS X.

Currently, nothing more to handle on, achieving 100% depends on resolving the issues in IBM-Swift/Kitura/issues/171 .

**Comment by shmuelk** [comment]
GRMustache now works on Linux.
