### ISSUE TITLE
Investigate usage of header only shims for libCurl and http_parser

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#177]
I believe we can move the implementation logic that's in the *.c files for our helpers into their respective header file, producing a header-only bridge to methods that Swift has trouble creating interfaces for (such as variadic functions).

**Comment by rfdickerson** [comment]
We aren't the only ones with this problem:

[Variadic functions for use in Swift](https://akrabat.com/wrapping-variadic-functions-for-use-in-swift/)

**Comment by rfdickerson** [comment]
I have created a patch that offers the same functionality as our curlHelper, but integrated it directly into the libCurl library: 

[PR](https://github.com/curl/curl/pull/683)

**Comment by billabt** [comment]
There are ways around the variadic issues using inline functions in the .h files. I'll take a look on Monday. They worked well for my additions to the stdlib and should work here as well. Usually results in a .swift file plus the header.

**Comment by rfdickerson** [comment]
Oh my gosh, Bill, you're brilliant!! The following code in the header file that I used in our libcurl module map, with a call to set_bool it successfully compiles and links. It didn't occur to me to use an ***inline function***.

The following in the header file worked for wrapping the variadic function:

```swift
inline CURLcode set_bool(CURL *curl, CURLoption option, int yesNo) {
    return curl_easy_setopt(curl, option, yesNo == CURL_TRUE ? 1L : 0L);
}
```

This might have the potential for removing our need for both curlHelper and httpParserHelper. :+1:

**Comment by rfdickerson** [comment]
Ok, confirmed. Moving all the C implementation out to the header files and making them ‘extern inline’ made all of the helpers no longer require a static library or C-compilation step. We can build entirely with Swift Package Manager now:

```
swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib
```

**Comment by Joannis** [comment]
Kitura's Makefile is failing because in Kitura-net's Makefile there is a reference to the C file that has been removed in Kitura-CurlHelpers.
