### ISSUE TITLE
build_osx.sh fails if wget is not installed

### ISSUE THREAD

**Issue by phubbard** [IBM-Swift/Kitura#178]
==> Summary
🍺  /usr/local/Cellar/curl/7.47.1: 359 files, 2.5M
./build_osx.sh: line 33: wget: command not found

**Comment by rolivieri** [comment]
@phubbard - This script was written for our Travis CI builds. The OS X image provided by Travis already has wget. However, I updated the script (develop branch) so that wget is installed if not on the OS X image. Please note that Homebrew is a prerequisite (the script will not installed Homebrew).
