### ISSUE TITLE
Kitura build script "ci.sh" failing in Google Cloud Shell

### ISSUE THREAD

**Issue by parthiban-srinivasan** [IBM-Swift/Kitura#181]
Used Google Cloud Shell.

Created docker container using "docker run -i -t ibmcom/kitura-ubuntu:latest /bin/bash". 
Tried executing "ci.sh" script to build kirtura. 

This is failing. 

loning https://github.com/IBM-Swift/Kitura-TestFramework.git
Resolved version: 0.2.0
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'BlueSocket' (3 sources)
Compiling Swift Module 'SwiftyJSON' (2 sources)
/root/Kitura/Packages/LoggerAPI-0.2.0/Sources/LoggerAPI/Logger.swift:37:68: warning: __FUNCTION__ is deprecated and will be removed in Swift 3, please use #function
    public static func verbose(msg: String, functionName: String = __FUNCTION__,
                                                                   ^~~~~~~~~~~~
                                                                   #function
/root/Kitura/Packages/LoggerAPI-0.2.0/Sources/LoggerAPI/Logger.swift:38:24: warning: __LINE__ is deprecated and will be removed in Swift 3, please use #line
        lineNum: Int = __LINE__, fileName: String = __FILE__ ) {
                       ^~~~~~~~
                       #line

**Comment by dfirsht** [comment]
The `ci.sh` was only meant to be run in the Travis environment. Closing this issue since that script is no longer used at all.
