### ISSUE TITLE
Kitura build script "ci.sh" failing in GKE node - Google Container Engine 

### ISSUE THREAD

**Issue by parthiban-srinivasan** [IBM-Swift/Kitura#182]
Snippets of Kitura "ci.sh" script error.

Compiling Swift Module 'KituraSys' (4 sources)
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
Compiling Swift Module 'HeliumLogger' (1 sources)
<unknown>:0: error: build had 1 command failures
error: exit(1): /root/swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a-ubuntu15.10/usr/bin/swift-build-tool -f /root/Kitura/.build/debug.yaml default
swift build
Compiling Swift Module 'KituraSys' (4 sources)
Compiling Swift Module 'LoggerSample' (1 sources)
Compiling Swift Module 'XCTest' (5 sources)
Linking LoggerSample
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'

**Comment by dfirsht** [comment]
This should be fixed by now, we don't even have a `ci.sh` file anymore.
