### ISSUE TITLE
Attach SwiftLint to our CI

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#184]
It would be good to ensure our code is at the highest level of quality and standardized. For instance, we need consistency in indent levels, syntax, and documentation.

The following tool can provide these checks:

[SwiftLint](https://github.com/realm/SwiftLint)

**Comment by rfdickerson** [comment]
I added SwiftLinting to Kitura and the downloaded Package dependencies. We might want to consider creating a configuration file for specifying our standards exactly. We currently have 5308 violations.

**Comment by rfdickerson** [comment]
Ok, we have proved the efficacy of this approach, now we just need to fix these issues.

**Comment by rfdickerson** [comment]
I did some analysis of some easily fixable Linting warnings for our code:

1. **Opening Brace Spacing Violation**: Opening braces should be preceded by a single space and on the same line as the declaration.

2. **Line Length Violation**: Line should be 100 characters or less.

3. **Missing Docs Violation**: Public declarations should be documented.

4. **Variable Name Violation**: Variable name should only contain alphanumeric characters.

5. **Coma Spacing Violation**: There should be no space before and one after any coma.

There are a few others, but these should get us started.

**Comment by dfirsht** [comment]
Closing for now. We'll open a task in the future to fix these issues.
