### ISSUE TITLE
Rename C module map libraries with prefix C-(libraryname)

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#185]
I suggest we rename our modulemap repositories to match the [Swift recommended convention](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md) to use "C-(libraryname)".

1. [x] Kitura-HttpParserHelper becomes CHttpParser
2. [x] Kitura-Pcre2 will be removed
3. [x] Kitura-hiredis becomes CHiredis
4. [x] Kitura-CurlHelpers becomes CCurl
5. [x] Change `import HttpParserHelper' to `import CHttpParser' in Kitura-Net
6. [x] Change `import CurlHelpers' to `import CCurl' in Kitura-Net
7. [x] Change the URL in Package.swift in Kitura-Net to new repos
8. [x] Change the URL in Package.swift in Kitura-Router to new repos
9. [x] Change the URL in Package.swift in Kitura-CouchDB to new repos

Much of this is now relevant now that our helpers no longer are built C static libraries, rather modulemaps with a header file that helps Swift interface with the problematic C functions (such as variadic). Plus, these might be useful out of the context of Kitura, altogether- as a dependency for external projects needing similar functionality.

**Comment by rfdickerson** [comment]
I think this will break master, so we have to change both branches in parallel.

1. Rename the repositories in Github appropriately
2. Change the URL paths in Package.swift in both develop and master
3. Change the modulename to C-(libraryname)
4. Tag the latest

**Comment by dfirsht** [comment]
Validated during peer programing process.
