### ISSUE TITLE
Variable number of route handlers against a route

### ISSUE THREAD

**Issue by casamm** [IBM-Swift/Kitura#188]
I've a requirement to support multiple route handlers against routes, It can't be a generic one like app.use so it's custom series of route handlers against each route.

Since Kitura is inspired from express.js which supports this convention and I'm not sure if the feature exists?

For instance in express.js we could do

````
app.get(‘/example/b’, function (req, res, next) {
    console.log(‘the response will be sent by the next function …’);
    next();
}, function (req, res) {
    res.send(‘Hello from B!’);
});
````
source: http://expressjs.com/en/guide/routing.html

I'm expecting the route handler's signature to be of this sort.

`func foo(args:AnyObject...) {`

**Comment by dfirsht** [comment]
Hey @casamm, this is a good idea! I'm going to move this issue to the backlog so we can work on it next sprint.

**Comment by casamm** [comment]
Glad to hear, this route chaining has proved to be so powerful in applications.

**Comment by dfirsht** [comment]
@shmuelk Can you please validate?

**Comment by shmuelk** [comment]
Validated by inspection.

Looks good. Especially the added route in the example.

**Comment by casamm** [comment]
thanks for implementing, I'll sure utilize it in my next project, just a confirmation the **second** handler in the sequence will only be called if the **first** handler's `next` is called?

**Comment by shmuelk** [comment]
Correct.

BTW that is also true if you instead had repeated the same path on separate route.method calls.

FWI We now also support arrays of handlers and Middleware in addition to variadic.

**Comment by casamm** [comment]
Great work. I noticed the array implementation too and variadic is my favorite. 

This pattern helped me a lot in separating concerns for any given route by providing a series of different reusable methods for a large scale app. Loved the fact that I'd be able to apply that pattern in Kitura too.

I'd publish some work demonstrating this pattern with integration of Kitura and [PureMVC](https://github.com/PureMVC/puremvc-swift-multicore-framework).

-Saad
