### ISSUE TITLE
Docker image fails to build Kitura...

### ISSUE THREAD

**Issue by dewib** [IBM-Swift/Kitura#189]
Appears to be a name change for Kitura-net. /root/Kitura/Makefile contains the line

make -f Packages/Kitura-net*/Makefile

which fails

however:

make -f Packages/KituraNet*/Makefile

is the fix you need...

**Comment by dfirsht** [comment]
Currently the docker image only works with the develop branch of Kitura. Very soon we are going to have two docker images, one that will work with master and the other for develop.
