### ISSUE TITLE
Housecleaning the repositories of deprecated files

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#192]
I have been going through the repos, and there are a few things that should be cleaned up. Let's discuss the following files before deletion:

- [x] Makefile (in Kitura and KituraNet)
- [x] Makefile.client (in KituraNet)
- [x] .travis.yml.backup
- [x] karl-develop remote branch
- [x] buildTests.sh
- [x] runTests.sh

Please add any additional files you know about, as well.

**Comment by rfdickerson** [comment]
@kweinmeister is it fine to remove this remote branch?

**Comment by eimantas** [comment]
5th step of Usage in README.md gives following command:

```
cp Packages/Kitura-net-0.2.0/Makefile-client Makefile
```

**Comment by dfirsht** [comment]
@eimantas look at the README in the develop branch

**Comment by eimantas** [comment]
@dfirsht the develop branch is for later swift snapshot. I'm trying to use master with 02/08 snapshot. 

Please refer to #213 for info on which snapshot to use on which branch.

**Comment by dfirsht** [comment]
@eimantas Yes that is true for the master branch. The version of Kitura-net downloaded by master (0.2) still has the Makefile-client file and should be used as the master README specifies. This issue is for removing it in future versions.

**Comment by dfirsht** [comment]
All files mentioned were removed from develop branches.
