### ISSUE TITLE
Document steps to follow when moving to a new version of the Swift binaries

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#193]
Let's use the Wiki for this.

**Comment by rolivieri** [comment]
Steps can now be found here: https://github.com/IBM-Swift/Kitura/wiki/Moving-To-A-New-Version-Of-The-Swift-Binaries

**Comment by rolivieri** [comment]
@dfirsht Let me know if you'd like to add any steps.

**Comment by dfirsht** [comment]
Looks good to me.
