### ISSUE TITLE
Investigate how to build the xctest framework on Linux

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#194]

**Comment by rfdickerson** [comment]
I discovered that if all you need is the XCTest file, one can simply just compile with 

`swift build` in the swift-core-libs-xctest directory. However, we want a Swift Package Manager with 'swift test' support so I used the build script with the "--xctest --swiftpm --llbuild' flags and now have the executable, 'swift-test' and also the library files for XCTest. Now I need to figure out how to distribute that to the docker CI. @rolivieri , opinions on this matter?

**Comment by rolivieri** [comment]
@rfdickerson Just saw your update above. I was hoping we could download and build xctest quickly at build time (just like we do with libdispatch). But... if I understood well your comment above, it seems that building xctest takes about an hour?

**Comment by rfdickerson** [comment]
Update, I have produced directions on how to create a SNAPSHOT that has the necessary XCTest swift modules and also the swift-test executable (among other files).

https://gist.github.com/rfdickerson/1cf5be0dbde2bf4711e5
