### ISSUE TITLE
Modify Swift Package Manager to pull the latest from a particular branch

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#196]
In many cases we wish to pull the latest from the develop branch without needing to tag all of the dependencies.

Instead of:

```swift
 dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura-router.git", versions: Version(0,3,0)..<Version(0,4,0)),
    ]
```

Specify a branch

```swift
 dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura-router.git", branch: "develop")
    ]
```

We can create a PR on the mainline once this is complete.

**Comment by dfirsht** [comment]
This has already been proposed and rejected: https://github.com/apple/swift-package-manager/pull/236. Instead they are favoring using a lockfile which can accomplish the same goal on a wider level. See https://github.com/mxcl/swift-evolution/blob/lockfiles/proposals/NNNN-swiftpm-dependency-lockfiles.md

**Comment by rfdickerson** [comment]
Thanks for the share! This is really interesting.
