### ISSUE TITLE
Update Kitura-CouchDB to work with develop Kitura

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#197]

**Comment by rfdickerson** [comment]
It now builds CouchDBSample. Currently working on updating the tests.

**Comment by rfdickerson** [comment]
Tests now 'run' but the asynchronous tests don't.

**Comment by shmuelk** [comment]
See issue #214

**Comment by dfirsht** [comment]
Working with the latest version of develop.
