### ISSUE TITLE
Update Kitura-BluePic to use Kitura (develop)

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#200]

**Comment by rfdickerson** [comment]
There is an [open Bug](https://bugs.swift.org/browse/SR-829) regarding the fact that a build will traverse the dependencies' tests and will fail to find the module.

**Comment by rfdickerson** [comment]
Update: ran 'swift build' over and over and getting past these dependent module tests. However, finally stuck here:

```
Compiling Swift Module 'SwiftRedisAuthtest' (1 sources)
Compiling Swift Module 'KituraNet' (12 sources)
Compiling Swift Module 'SwiftRedistest' (12 sources)
Compiling Swift Module 'KituraRouter' (9 sources)
Compiling Swift Module 'CouchDB' (4 sources)
Compiling Swift Module 'CouchDBtest' (3 sources)
Compiling Swift Module 'CouchDBSample' (1 sources)
Compiling Swift Module 'KituraBluePicserver' (4 sources)
Linking CouchDBSample
Linking KituraBluePic-server
ld: framework not found XCTest for architecture x86_64
```

**Comment by dfirsht** [comment]
@shmuelk I'm not going to go through all the instructions to get BluePic running, can you just confirm that it is working and close this?

**Comment by shmuelk** [comment]
It's working. See issue #327
