### ISSUE TITLE
Eliminate dependency on Kitura-router that exists on Kitura-CouchDB

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#201]
We should tackle this after addressing issue #168.

**Comment by shmuelk** [comment]
I tagged a commit incorrectly. Here is a link:
      https://github.com/IBM-Swift/Kitura-net/commit/a907073a6c46b5c3ba7f32444c4985c33c81eb0f

**Comment by dfirsht** [comment]
Verified as working as expected.
