### ISSUE TITLE
vagrant up errors from develop branch

### ISSUE THREAD

**Issue by jtomchak** [IBM-Swift/Kitura#204]
I was having trouble getting the docker or vagrant on master working, after reading through the issues I switched over to the develop branch. Still getting the following error? 

==> default: <unknown>:0: error: build had 1 command failures
==> default: swift-build: error: exit(1): ["/home/vagrant/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu15.10/usr/bin/swift-build-tool", "-f", "/home/vagrant/Kitura/.build/debug/Kitura-Sys.o/llbuild.yaml"]

**Comment by chrislonge** [comment]
I was having the same issues on master. Switching to develop (and using docker) fixed my build issue..

**Comment by kweinmeister** [comment]
Fixed with commit 767ca008b905b68d31ce4abff1c02b1d8b67889e

**Comment by jtomchak** [comment]
@kweinmeister thanks for the quick fix! Very much appricated.
