### ISSUE TITLE
Update Redis test case to obtain credentials from a properties file

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#206]
The properties file containing the credentials should exist in the new private repository we recently created to hold all test credentials.

As of now, the AuthTests is using environment variables to hold the credentials. 

Without this fix, the CI for Kitura-redis will keep failing.

**Comment by dfirsht** [comment]
Forgot to add IBM-Swift/Kitura: https://github.com/IBM-Swift/Kitura-redis/commit/9a079a7710650bc9c4cb7ffc86be5ad81cb56ce7

**Comment by dfirsht** [comment]
All test cases passing using the property file: https://travis-ci.org/IBM-Swift/Kitura-redis/builds/114604730.
