### ISSUE TITLE
Can't invoke swift build

### ISSUE THREAD

**Issue by eimantas** [IBM-Swift/Kitura#213]
I have latest release of swift 2.2 (march 1st as of this writing). When running `make` on ubuntu 14.04 in the root of kitura, i get an error:

```
swift build
error: unable to invoke subcommand: /home/eimantas/src/swift-2.2/usr/bin/swift-build (No such file or directory)
make: [make] Error 2 (ignored)
```

Any help is appreciated.

**Comment by shmuelk** [comment]
@eimantas  Please install an appropriate Swift 3.0 driver. 02/08 for the master branch of Kitura or 02/25 for the develop branch.

**Comment by eimantas** [comment]
I'm using 02/25 image of Swift on Linux Ubntu 14.04 and attempting to build using the given command in `README.md`, but this is the new error that I get:

```
error: The dependency graph could not be satisfied because an update to `https://github.com/IBM-Swift/Kitura-router.git' is required
```

**Comment by eimantas** [comment]
Okay, so I managed to push a bit further. I removed everything from `Packages/` subdirectory and reran the build command:

```
swift build -Xcc -fblocks
```

After recloning all dependencies and starting building the project it got stuck on building `KituraSys` dependency:

```
swift build
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'SwiftyJSON' (2 sources)
Compiling Swift Module 'BlueSocket' (3 sources)
Compiling Swift Module 'KituraSys' (4 sources)
/home/eimantas/src/swilnius/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/src/swilnius/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/src/swilnius/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/src/swilnius/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
<unknown>:0: error: build had 1 command failures
```

I have applied the swift dispatch library patch before going further, but it seems that there's still something lacking here.

**Comment by vadimeisenbergibm** [comment]
The error probably means that you do not have dispatch directory in /usr/local/include/ . Please make sure that you run sudo make install in swift-corelibs-libdispatch and that dispatch directory is created in /usr/local/include/.

**Comment by eimantas** [comment]
I see. Is there a way to pass the linker a flag where it can find the Dispatch library? Since the library was configured with certain prefix which defines non-standard swift location.

**Comment by vadimeisenbergibm** [comment]
Yes - you can add flags to swift build command to pass compiler/linker options, e.g -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib.

**Comment by eimantas** [comment]
so this is weird. I have verified that libdispatch is present in `/usr/local/lib` and ran the commands. Got the following output:

```
$ cd /usr/local/lib                                                                                                                                             ⏎
$ ls -l libdispatch*
-rwxr-xr-x 1 root root   1026 Mar  3 14:01 libdispatch.la
-rwxr-xr-x 1 root root 871255 Mar  3 14:01 libdispatch.so
$ cd ~/kitura
$ swift build -Xcc -fblocks -Xlinker -I/usr/local/lib -Xswiftc -I/usr/local/include
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'BlueSocket' (3 sources)
Compiling Swift Module 'SwiftyJSON' (2 sources)
Compiling Swift Module 'KituraSys' (4 sources)
/home/eimantas/kitura/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/kitura/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/kitura/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
/home/eimantas/kitura/Packages/Kitura-Sys-0.3.1/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
import Dispatch
       ^
```

**Comment by vadimeisenbergibm** [comment]
The issue is probably with /usr/local/include/ - please verify that you have dispatch directory there.

**Comment by eimantas** [comment]
Verified:

```
$ cd /usr/local/include
$ ls -l dispatch
total 192
drwxr-xr-x 2 root root  4096 Mar  3 14:01 .
drwxr-xr-x 4 root root  4096 Mar  3 13:58 ..
-rw-r--r-- 1 root root  4536 Mar  3 14:01 base.h
-rw-r--r-- 1 root root 17716 Mar  3 14:01 block.h
-rw-r--r-- 1 root root 11014 Mar  3 14:01 data.h
-rw-r--r-- 1 root root  1631 Mar  3 14:01 dispatch.h
-rw-r--r-- 1 root root  8508 Mar  3 14:01 group.h
-rw-r--r-- 1 root root  4905 Mar  3 14:01 introspection.h
-rw-r--r-- 1 root root 25826 Mar  3 14:01 io.h
-rw-r--r-- 1 root root 14487 Mar  3 14:01 object.h
-rw-r--r-- 1 root root  2629 Mar  3 14:01 once.h
-rw-r--r-- 1 root root 34672 Mar  3 14:01 queue.h
-rw-r--r-- 1 root root  3300 Mar  3 14:01 semaphore.h
-rw-r--r-- 1 root root 26610 Mar  3 14:01 source.h
-rw-r--r-- 1 root root  2976 Mar  3 14:01 time.h
```

**Comment by eimantas** [comment]
The path to swift is following:

```
/home/eimantas/src/swift-3.0/usr/bin
```

**Comment by kfbishop** [comment]
Could the build do a quick check `swift --version` and show appropriate error message if < 3.0.  I think overt hand-holding can greatly improve first time explorers.

**Comment by eimantas** [comment]
FWIW:

```
$ swift --version
Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift fc261045a5)
Target: x86_64-unknown-linux-gnu
```

**Comment by mars-rover** [comment]
Your /use/local/include has no dispatch library, just some header files

**Comment by eimantas** [comment]
I thought include is supposed to have header files. And `/usr/local/lib` has all the binaries. No?

**Comment by vadimeisenbergibm** [comment]
@eimantas My mistake regarding /usr/local/include - please verify that dispatch directory exists in <path-to-swift>/usr/lib/swift. Step 4 of README should install it there.

**Comment by eimantas** [comment]
@vadimeisenbergibm it's not there. Should I attempt recompiling and reinstalling the libdispatch?

**Comment by vadimeisenbergibm** [comment]
@eimantas yes, make sure that you provide the correct path to config command.

**Comment by chrisozenne** [comment]
I am having the same problem on OS X with the latest Swift 2.2 from March 1st.
`swift build
error: unable to invoke subcommand: /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-03-01-a.xctoolchain/usr/bin/swift-build (No such file or directory)`

**Comment by vadimeisenbergibm** [comment]
@chrisozenne  Please install Swift 3.0 snapshot, 8th of February for the master branch of Kitura or 25th of February for the develop branch.

**Comment by chrisozenne** [comment]
Where can I find the Swift 3.0 snapshot?

**Comment by chrisozenne** [comment]
Took me a while to figure this out - I could not find the Swift 3.0 snapshot because it's not called Swift 3.0, it's just called "Swift Development Snapshot" on Swift.org.

**Comment by vadimeisenbergibm** [comment]
@chrisozenne  Correct, sorry, I should have mentioned that.

**Comment by eimantas** [comment]
Okay, I got it working! I got a "Hello world!"!!!11!!! I followed the instructions on the develop branch and it works great!

Thanks everyone for support!
