### ISSUE TITLE
Failed on ./configure --with-swift-toolchain=/swift/usr --prefix=/swift/usr

### ISSUE THREAD

**Issue by mars-rover** [IBM-Swift/Kitura#215]
This is my failed log. any one have encounter this?
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking for KQUEUE... configure: error: Package requirements (libkqueue) were not met:

No package 'libkqueue' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables KQUEUE_CFLAGS
and KQUEUE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by kweinmeister** [comment]
Look at the [vagrantfile](https://github.com/IBM-Swift/Kitura/blob/master/vagrantfile) for tips on what is needed to setup your environment. I think this line should help (see libkqueue-dev):
`sudo apt-get --assume-yes install libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev libbsd-dev`

If there are any steps missing in our documentation, please let us know or create a pull request. Thanks.

**Comment by mars-rover** [comment]
@kweinmeister thanks a lot, It works!

**Comment by zwoop** [comment]
I know this is closed, but for those Linux distros (e.g. Fedora) which do not provide a libkqueue, what are the options? Is there a way to disable building libdispatch?

**Comment by ianpartridge** [comment]
libkqueue is now embedded in libdispatch as a git submodule, so you shouldn't need to install the system package, I think.

**Comment by zwoop** [comment]
Hmmm, I tried latest versions right now (today), and it still failed in configure with that message above.

**Comment by ianpartridge** [comment]
@dgrove-oss ?

**Comment by zwoop** [comment]
Let me try one more time with a fresh git clone, maybe I'm doing something wrong... It's definitely not easy to build this thing :).

**Comment by dgrove-oss** [comment]
there's some breakage on the master branch of libdispatch since Jan 24th.  Should be fine on the swift-3.1-branch.  The fix (for now) is to pick up this PR into libdispatch https://github.com/apple/swift-corelibs-libdispatch/pull/207.   I'll ping Apple to see if we can that merged so that master branch is sane again.

**Comment by dgrove-oss** [comment]
ok.  master branch of libdispatch is fixed.  it should work now.   it might be safest to remove your swift-corelibs-libdispatch clone and do the update-checkout again to make sure you get into a clean state.

**Comment by zwoop** [comment]
Great, yeah that seems to fix the libdispatch build issues. Now I'm stuck at

```
In file included from ./CoreFoundation/Base.subproj/CoreFoundation_Prefix.h:30:
../build/buildbot_linux/foundation-linux-x86_64/Foundation/usr//lib/swift/CoreFoundation/CFBase.h:72:10: fatal error: 'Block.h' file not found
#include <Block.h>
```

It seems it does not add the necessary -I for the lldb include dir :/. I'll file a separate issue on that if I can't figure it out.

Thanks again!

**Comment by dgrove-oss** [comment]
The Swift project requires libblocksruntime-dev  to be installed to build Swift from source on Linux (see list of dependencies at https://github.com/apple/swift/blob/master/README.md). Installing that should get you by the Block.h problem.

**Comment by zwoop** [comment]
Ah, so it's not Block.h from lldb that it needs but from "lib blocks? Oddly enough, it worked once I got it to look in include/lldb/Symbol/ for Block.h, but I'm guessing that's just a coincidence?

Sadly, there is no libblock* for Fedora :-/.

**Comment by dgrove-oss** [comment]
There are multiple copies of the block runtime sitting around in the swift tree (including in swift-corelibs-foundation/closure/Block.h and swift-corelibs-libdispatch/src/BlockRuntime/Block.h).   Up until a couple of months ago (I've forgotten the exact timing), the builds would find these embedded header files instead of looking for them on the system.  I think it is probably an unintended change for the compilation of swift-corelibs-foundation to not be finding the Block.h in closure, but I haven't raised it on the swift-dev list to be sure.

**Comment by zwoop** [comment]
Hate to ask this, but is there a tag / branch I can use that is stable / building? I'm having a hell of a time to get any of this to work :-/.

**Comment by zwoop** [comment]
Fwiw, installing https://github.com/mackyle/blocksruntime seems to have fixed this particular problem! Thanks for the help.

But now, one of the regression tests is failing, but at least progress  :).
