### ISSUE TITLE
Usage Step 5 - Makefile

### ISSUE THREAD

**Issue by chrisozenne** [IBM-Swift/Kitura#220]
> 5) Copy the Makefile.client from KituraNet to your project as Makefile:
> 
> `cp Packages/Kitura-net-0.2.0/Makefile-client Makefile`

On Step 5 of the usage instructions from the README, the command fails with "No such file or directory".

It looks like the package manager installs "Kitura-net-0.3.5", not 0.2.0.

I tried copying from the 0.3.5 version, however there's no file called "Makefile-client".

Can anyone help me sort this out?

**Comment by vadimeisenbergibm** [comment]
@chrisozenne you are working on develop branch, please use README.md from develop branch. The instruction regarding makefile relates to master branch

**Comment by chrisozenne** [comment]
Ah! Thank you!
