### ISSUE TITLE
Run the vagrant provisioning script as unprivileged user

### ISSUE THREAD

**Issue by cjwirth** [IBM-Swift/Kitura#232]
In it's current state on the develop branch, the vagrant script is run as root. That means everything that is downloaded in the script will be owned by root. 

It seems okay now, but when I was trying it out a while back, I was having trouble with something (linking or something?) because it had to be run by root to have access, whereas I was logged in as the vagrant user.

It seems like it would be nicer if everything was installed as an unprivileged user.

**Comment by dfirsht** [comment]
Fixed in PR #173
