### ISSUE TITLE
Address miscellaneous items (README file) raised by Karl

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#240]
- Remove Swift badge
- ~~Move build badges to a separate row~~
- ~~Add label for master and develop build bages~~
- ~~Keep remaining badges in a separate row~~

Deferring strikethrough items for later. Having problems a aligning images and text vertically. It seems the CSS from GitHub is overriding any styles applied to the image or text.

**Comment by dfirsht** [comment]
Verified.
