### ISSUE TITLE
Router API updates

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#243]
This is a set of updates to the API of the KituraRouter. Included is:

  1. Added to RouterRequest a method field. It returns a RouterMethod enum value of the method of the request. This includes making RouterMethod a public enum.
  2. Added the ability to handle head requests (i.e. Router.head....)
  3. RouterResponse will now suppress the sending of the body on HEAD requests. Thus HEAD requests can be processed by the developer as if they were GET requests and KituraRouter does the needed magic of not sending out the body.

**Comment by dfirsht** [comment]
Verified.
