### ISSUE TITLE
Add authentication to all redis test cases.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#244]

**Comment by dfirsht** [comment]
Tagged wrong issue: https://github.com/IBM-Swift/Kitura-redis/commit/76df24a52879c9ceb0c26aac25c49e6ffed33870

**Comment by dfirsht** [comment]
All test cases passing using authentication: https://travis-ci.org/IBM-Swift/Kitura-redis/builds/114604730.
