### ISSUE TITLE
Improve the Kitura "Home page"

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#245]
The Kitura "Home page" is displayed by a browser when the request is for a path of "/" (or nothing) and no handler has dealt with that request.

**Comment by shmuelk** [comment]
The following commits implemented this issue:

https://github.com/IBM-Swift/Kitura-router/commit/04d1b95a78df9a44bf04afca65733d887983d702

https://github.com/IBM-Swift/Kitura-router/commit/d8183472825d9283c6383fa191647ae8c74fe55d

**Comment by dfirsht** [comment]
Wow looks awesome! Verified.
