### ISSUE TITLE
Vagrant up errors

### ISSUE THREAD

**Issue by da-na** [IBM-Swift/Kitura#247]
Hi! On my Linux machine with a VM, I've downloaded the repo with `git clone https://github.com/IBM-Swift/Kitura.git` and after executing `vagrant up` I get this list of errors: 

`==> default: Compiling Swift Module 'LoggerAPI' (1 sources)
==> default: Compiling Swift Module 'BlueSocket' (3 sources)
==> default: Compiling Swift Module 'SwiftyJSON' (2 sources)
==> default: Compiling Swift Module 'KituraTemplateEngine' (1 sources)
==> default: Compiling Swift Module 'KituraSys' (4 sources)
==> default: Compiling Swift Module 'HeliumLogger' (1 sources)
==> default: Compiling Swift Module 'KituraMustache' (1 sources)
==> default: Compiling Swift Module 'LoggerSample' (1 sources)
==> default: Linking LoggerSample
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:168:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:175:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:203:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:231:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:261:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:268:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:312:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:356:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:169:18: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 set.__fds_bits = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
==> default:                 ~~~            ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:180:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 0: set.__fds_bits.0 = set.__fds_bits.0 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:181:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 1: set.__fds_bits.1 = set.__fds_bits.1 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:182:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 2: set.__fds_bits.2 = set.__fds_bits.2 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:183:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 3: set.__fds_bits.3 = set.__fds_bits.3 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:184:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 4: set.__fds_bits.4 = set.__fds_bits.4 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:185:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 5: set.__fds_bits.5 = set.__fds_bits.5 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:186:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 6: set.__fds_bits.6 = set.__fds_bits.6 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:187:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 7: set.__fds_bits.7 = set.__fds_bits.7 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:188:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 8: set.__fds_bits.8 = set.__fds_bits.8 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:189:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 9: set.__fds_bits.9 = set.__fds_bits.9 | mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:190:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 10: set.__fds_bits.10 = set.__fds_bits.10 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:191:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 11: set.__fds_bits.11 = set.__fds_bits.11 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:192:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 12: set.__fds_bits.12 = set.__fds_bits.12 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:193:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 13: set.__fds_bits.13 = set.__fds_bits.13 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:194:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 14: set.__fds_bits.14 = set.__fds_bits.14 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:195:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 15: set.__fds_bits.15 = set.__fds_bits.15 | mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:208:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 0: set.__fds_bits.0 = set.__fds_bits.0 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:209:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 1: set.__fds_bits.1 = set.__fds_bits.1 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:210:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 2: set.__fds_bits.2 = set.__fds_bits.2 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:211:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 3: set.__fds_bits.3 = set.__fds_bits.3 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:212:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 4: set.__fds_bits.4 = set.__fds_bits.4 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:213:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 5: set.__fds_bits.5 = set.__fds_bits.5 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:214:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 6: set.__fds_bits.6 = set.__fds_bits.6 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:215:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 7: set.__fds_bits.7 = set.__fds_bits.7 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:216:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 8: set.__fds_bits.8 = set.__fds_bits.8 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:217:28: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 9: set.__fds_bits.9 = set.__fds_bits.9 & mask
==> default:                         ~~~              ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:218:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 10: set.__fds_bits.10 = set.__fds_bits.10 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:219:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 11: set.__fds_bits.11 = set.__fds_bits.11 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:220:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 12: set.__fds_bits.12 = set.__fds_bits.12 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:221:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 13: set.__fds_bits.13 = set.__fds_bits.13 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:222:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 14: set.__fds_bits.14 = set.__fds_bits.14 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:223:30: error: cannot assign to property: 'set' is a 'let' constant
==> default:                 case 15: set.__fds_bits.15 = set.__fds_bits.15 & mask
==> default:                          ~~~               ^
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:168:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:175:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:203:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:231:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:261:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:268:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:312:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:356:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:168:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:175:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:203:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:231:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:261:19: error: 'inout' must appear before the parameter name
==> default:         func fdZero(set: inout fd_set) {
==> default:                          ^~~~~~
==> default:                     inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:268:29: error: 'inout' must appear before the parameter name
==> default:         func fdSet(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:312:29: error: 'inout' must appear before the parameter name
==> default:         func fdClr(fd: Int32, set: inout fd_set) {
==> default:                                    ^~~~~~
==> default:                               inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocketUtils.swift:356:31: error: 'inout' must appear before the parameter name
==> default:         func fdIsSet(fd: Int32, set: inout fd_set) -> Bool {
==> default:                                      ^~~~~~
==> default:                                 inout  
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocket.swift:1097:10: error: '&' used with non-inout argument of type 'fd_set'
==> default:                 fdZero(&readfds)
==> default:                        ^~~~~~~~
==> default:                        
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocket.swift:1098:29: error: '&' used with non-inout argument of type 'fd_set'
==> default:                 fdSet(self.socketfd, set: &readfds)
==> default:                                           ^~~~~~~~
==> default:                                           
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocket.swift:1101:10: error: '&' used with non-inout argument of type 'fd_set'
==> default:                 fdZero(&writefds)
==> default:                        ^~~~~~~~~
==> default:                        
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocket.swift:1102:29: error: '&' used with non-inout argument of type 'fd_set'
==> default:                 fdSet(self.socketfd, set: &writefds)
==> default:                                           ^~~~~~~~~
==> default:                                           
==> default: /home/vagrant/Kitura/Packages/BlueSocket-0.1.3/Sources/BlueSocket.swift:1117:39: error: '&' used with non-inout argument of type 'fd_set'
==> default:                 return (fdIsSet(self.socketfd, set: &readfds), fdIsSet(self.socketfd, set: &writefds))
==> default:                                                     ^~~~~~~~
==> default:                                                     
==> default: <unknown>
==> default: :
==> default: 0
==> default: : 
==> default: error: 
==> default: build had 1 command failures
==> default: swift-build: error: exit(1): /home/vagrant/swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/vagrant/Kitura/.build/debug.yaml default `

Apparently BlueSocket doesn't compile..

**Comment by dfirsht** [comment]
It looks like you aren't using the latest Swift development snapshot. You can get the 03/01 drop here: https://swift.org/download/

**Comment by da-na** [comment]
Thanks dfirsht! 
Though shouldn't the Vagrantfile be updated to use that? 
Cause I haven't really set up anything, I just followed instructions provided here: https://github.com/IBM-Swift/Kitura#installation-vagrant-development-environment

**Comment by dfirsht** [comment]
Yeah, you're right. I updated the Vagrantfile and am testing it now. I'll let you know when I commit it.

**Comment by da-na** [comment]
Awesome! Thanks again

**Comment by dfirsht** [comment]
Hey @da-na sorry for the delay. It should be good to go now!

**Comment by da-na** [comment]
Awesome!
I just did` vagrant up`, and it worked as a charm. 
Thank you

**Comment by dfirsht** [comment]
Glad to hear it! I'm going to go ahead and close this issue then. If you have any other feedback or issues, feel free to open another issue or contact us on [gitter](https://gitter.im/IBM-Swift/Kitura).
