### ISSUE TITLE
error: invalid usage: unknown argument: -X

### ISSUE THREAD

**Issue by chrisozenne** [IBM-Swift/Kitura#250]
I'm getting the following error when running `make run` after cloning Kitura.

```
swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib
error: invalid usage: unknown argument: -X
```

Using: `swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a.xctoolchain`

**Comment by vadimeisenbergibm** [comment]
Kitura works with snapshot of swift-DEVELOPMENT-SNAPSHOT-2016-03-01 or later.

**Comment by chrisozenne** [comment]
Thanks Vidam. Last week I was told to use a different snapshot because the master branch was not updated yet. How can I keep track of which snapshot is compatible with Kitura's master branch when I pull it?

**Comment by vadimeisenbergibm** [comment]
You might want to check [Swift Version]( https://github.com/IBM-Swift/Kitura/tree/master#swift-version) in README.

**Comment by chrisozenne** [comment]
Thank you!
