### ISSUE TITLE
Convert types.json into a swift file

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#256]

**Comment by shmuelk** [comment]
Why do we still get a warning message about "Loading embedded MIME types"?

**Comment by dfirsht** [comment]
@shmuelk Ok, now you'll only see it on Linux. This is because we can't use NSJSONSerialization on Linux yet.

**Comment by dfirsht** [comment]
So I investigated getting this to work in Linux, it fails because the downcast to NSDictionary fails. I messed around with it for a while but couldn't figure out the right downcast. For reference it is an Any object which looks like this printed: 
```
["application/vnd.ezpix-album": ["ez2"], "application/vnd.noblenet-web": ["nnw"], "application/vnd.crick.clicker.wordbank": ["clkw"], "application/vnd.hp-pclxl": ["pclxl"],  ...
```
I think we should leave this alone for now and wait till Foundation is more stable on Linux.
