### ISSUE TITLE
Complete Static file serving

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#260]
Implement any missing functionality in the Kitura static file serving. This includes:

  1. ETag

**Comment by shmuelk** [comment]
The security part of the last commit was tested using a small Node.js program.

We haven't been able t test using curl which uses libCurl under the covers, which the Kitura Http Client API.

**Comment by dfirsht** [comment]
Confirmed working with Kitura-Sample, we should consider writing a test case for this though.
