### ISSUE TITLE
Create a Yeoman project generator for Kitura

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#261]
After a discussion with @rolivieri, we thought it might be useful to create a [Yeoman](https://www.npmjs.com/package/yo) project generator for Kitura applications. It would easily set someone up with an effectively blank project to rapidly start building a new application. This is quite common in the NodeJS community.

So if you run: ``yo kitura``, it would ask you your project name, author info, company info.

It would create the following directory tree and git repo with a Package.swift file and your project name, for instance:

```
- Package.swift
- Sources
  - <Project name>
     - Controllers
         Routes.swift
     - Models
- Tests
  - LinuxMain.swift
  - <Project name>
     - SimpleTest.swift
```

[Kitura-Generator](https://github.com/IBM-Swift/Kitura-Generator)

**Comment by generatronServer** [comment]
We got something in the works, not yeoman based. Still testing

**Comment by ejohnsonw** [comment]
@rfdickerson @rolivieri What would be the default content for: Routes.swift, LinuxMain.swift and SimpletTest.swift

**Comment by ejohnsonw** [comment]
Here is in a nutshell: you only login once

npm install -g generatron
gtron signup
gtron login

gtron init <ProjectName> Kitura-Init [optional Github RepoURL]

if you want full REST endpoints for a specific data model

gtron generate TodoList using Kitura-REST

More details here
https://medium.com/@evoljoh/here-is-how-we-replicated-kitura-s-todolist-sample-application-with-generatron-ff1572c1ac2a#.sj7z7lyxa

**Comment by shmuelk** [comment]
This is being worked on by a team outside of Kitura.
