### ISSUE TITLE
Move target run from Kitura-CI/build/Makefile to the referencing Makefiles

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#262]
There should be no _run_ target in Kitura-CI/build/Makefile. Each referencing Makefile should define a different _run_ target.

**Comment by dfirsht** [comment]
@vadimeisenbergibm Is this issue complete?

**Comment by vadimeisenbergibm** [comment]
@dfirsht the issue is complete on develop branches of Kitura-Sample and Kitura-CI

**Comment by dfirsht** [comment]
@vadimeisenbergibm Ok I see that. Is it ok to close this then?

**Comment by dfirsht** [comment]
Validated.
