### ISSUE TITLE
How to connect with MySQL Database?

### ISSUE THREAD

**Issue by chintan1891** [IBM-Swift/Kitura#267]
Is there any sample available to connect with MySql database using Kitura?

**Comment by kweinmeister** [comment]
I am not aware that there is a [MySQL Connector ](https://www.mysql.com/products/connector/) yet for Swift. That could be a valuable contribution to the community. In the meantime, I believe the next best option would be use the MySQL C connector from a Kitura app. We don't have a sample for that at the moment.

**Comment by michaelsanford** [comment]
@kweinmeister I wonder if one could be ramped quickly using something like [SwiftSocket](https://github.com/swiftsocket/SwiftSocket).

For example, there is no official nodejs connector either, so a project like like [node-mysql](https://github.com/felixge/node-mysql) simply [opens a socket](https://github.com/felixge/node-mysql/blob/master/lib/Connection.js#L79) connection to mysql.

I'm currently not in a position to ponder performance implications of this over another possibly more idiomatic method.

**Comment by billabt** [comment]
*Kitura* uses [BlueSocket](https://github.com/IBM-Swift/BlueSocket) for its socket connections.  That could probably be used to connect to MySQL using the socket interface.  It'd have to be investigated further but I see no reason why it couldn't be done.

**Comment by vadimeisenbergibm** [comment]
Note that [MySQL Connector/C](https://dev.mysql.com/downloads/connector/c/) is GPL.

**Comment by michaelsanford** [comment]
@billabt Thanks for the clarification (I'm brand new to _Kitura_). I'd be interested in taking a look if this is currently unaddressed.

**Comment by kweinmeister** [comment]
@michaelsanford: Sure! Any help with this would be appreciated.

**Comment by billabt** [comment]
@michaelsanford: As @kweinmeister said, any and all help would be greatly appreciated. If you need any help with *BlueSocket* setting it up, just go ahead post your questions/comments as an issue on the *BlueSocket* site and I'll respond as quick as I can. Thanks!!!  This probably a really good way to get your feet wet. 😃

**Comment by generatronServer** [comment]
There is are several swift based connectors as part of https://github.com/PerfectlySoft/Perfect/tree/master/Connectors, they are part of their own server side solution but was just released under  Apache 2.0 license, maybe can fork, and prepare something that could be pulled with the package manager.

**Comment by chintan1891** [comment]
@generatronServer : Yes i have used Perfect My SQL connector.. It worked for me..

Just 1 question regarding Swift Compilation. If i use libmysqliclient.a library, is it necessary to put that library in to /usr/local/lib? Without that i am getting linker error.

**Comment by generatronServer** [comment]
I think yes, you need that library available in the path

**Comment by vadimeisenbergibm** [comment]
@chintan1891 You can add flags to `swift build` and specify the location of  libmysqliclient.a:
`-Xswiftc -I<the location of libmysqliclient.a> -Xlinker -L<the location of libmysqliclient.a>`

**Comment by rfdickerson** [comment]
Any updates on a MySQL driver we can use for Kitura-TodoList?

**Comment by ejohnsonw** [comment]
I know @nicholasjackson had something in the works, nevertheless I would love to see a swift native driver converted to Swft 3 if anybody wants to take the challenge. https://github.com/mcorega/MySqlSwiftNative

**Comment by nicholasjackson** [comment]
Ah github the bane of my life, I never get the notifications.

We have been using this in production, it still needs parameter escaping which I hopefully will be able to do this week and probably bringing in line with the latest releases.  I will do that tomorrow.

https://github.com/notonthehighstreet/swift-mysql

**Comment by sahandnayebaziz** [comment]
@ejohnsonw Swift 3 PR opened :) https://github.com/mcorega/MySqlSwiftNative/pull/17
