### ISSUE TITLE
/root/start_kitura_sample.sh No such file or directory

### ISSUE THREAD

**Issue by alvinvarghese** [IBM-Swift/Kitura#270]
And why this ?

<pre>

Alvins-MacBook-Pro:local Alvin$ docker pull ibmcom/kitura-ubuntu:latest
latest: Pulling from ibmcom/kitura-ubuntu

d9aca89b8809: Pull complete 
094907597129: Pull complete 
02c431b6e99f: Pull complete 
a3ed95caeb02: Pull complete 
859da149403a: Pull complete 
26a9fc923d28: Pull complete 
e4293ddd621e: Pull complete 
848445e0dbad: Pull complete 
aa4d6f6fb5a7: Pull complete 
9bbd84dcd95b: Pull complete 
99121f99d496: Pull complete 
cbb0cdf4c4f2: Pull complete 
6e6d2c3cb06f: Pull complete 
5afd86d3eee8: Pull complete 
b1389e602593: Pull complete 
82704cdd67fb: Pull complete 
a67124e07bda: Pull complete 
5a61104be556: Pull complete 
7dff0da59cc6: Pull complete 
762a3690edee: Pull complete 
f8747833e687: Pull complete 
b4c1ba24017f: Pull complete 
f7a4c18b1021: Pull complete 
7c1efb4d6138: Pull complete 
82327ef6a32e: Pull complete 
f618d0286429: Pull complete 
c3b75a71abc3: Pull complete 
141dcb738bc1: Pull complete 
d5c099270360: Pull complete 
ff749b02abc4: Pull complete 
ca9bbc03c5de: Pull complete 
9d7b101d49be: Pull complete 
9b1ccb2cd97e: Pull complete 
5c32f96680c7: Pull complete 
bddb24ac6780: Pull complete 
3e483e9a20d8: Pull complete 
8c2476302217: Pull complete 
Digest: sha256:613df7e0fa4be6ef8d794ed6f29a2c5aed8b4df731d3c6f9dbf0c2d20989a6a7
Status: Downloaded newer image for ibmcom/kitura-ubuntu:latest
Alvins-MacBook-Pro:local Alvin$ docker run -i -t ibmcom/kitura-ubuntu:latest /bin/bash
root@56639f7867fe:~# /root/clone_build_test_kitura.sh
>> About to clone branch 'develop' for Kitura
Cloning into 'Kitura'...
remote: Counting objects: 1361, done.
remote: Compressing objects: 100% (383/383), done.
remote: Total 1361 (delta 218), reused 0 (delta 0), pack-reused 891
Receiving objects: 100% (1361/1361), 472.00 KiB | 340.00 KiB/s, done.
Resolving deltas: 100% (715/715), done.
Checking connectivity... done.
>> About to build Kitura...
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolved version: 0.5.0
Cloning https://github.com/IBM-Swift/Kitura-sys.git
Resolved version: 0.4.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolved version: 0.4.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolved version: 0.1.4
Cloning https://github.com/IBM-Swift/Kitura-CurlHelpers.git
Resolved version: 0.4.0
Cloning https://github.com/IBM-Swift/Kitura-HttpParserHelper.git
Resolved version: 0.4.0
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolved version: 3.1.0
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolved version: 0.0.1
>> CC_FLAGS: -Xcc -fblocks -Xcc -fmodule-map-file=/root/Kitura/Packages/Kitura-CurlHelpers-0.4.0/module.modulemap -Xcc -fmodule-map-file=/root/Kitura/Packages/Kitura-HttpParserHelper-0.4.0/module.modulemap
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'BlueSocket' (3 sources)
Compiling Swift Module 'SwiftyJSON' (2 sources)
Compiling Swift Module 'KituraTemplateEngine' (1 sources)
Compiling Swift Module 'KituraSys' (4 sources)
Compiling Swift Module 'KituraNet' (12 sources)
Compiling Swift Module 'Kitura' (8 sources)
>> Build for Kitura completed (see above for results).
>> About to test Kitura...
Compiling Swift Module 'Kituratest' (5 sources)
Compiling Swift Module 'nettest' (2 sources)
Linking test-Package.xctest
Test Case 'TestContentType.test_initialize' started.
Type for png is: Optional("image/png")
Test Case 'TestContentType.test_initialize' passed (0.0 seconds).
Executed 1 test, with 0 failures (0 unexpected) in 0.0 (0.001) seconds
Test Case 'TestErrors.testInvalidMethod' started.
ParsedLessThanRead
Test Case 'TestErrors.testInvalidMethod' passed (0.009 seconds).
Test Case 'TestErrors.testInvalidEndpoint' started.
Test Case 'TestErrors.testInvalidEndpoint' passed (0.005 seconds).
Test Case 'TestErrors.testInvalidHeader' started.
Test Case 'TestErrors.testInvalidHeader' passed (0.006 seconds).
Executed 3 tests, with 0 failures (0 unexpected) in 0.02 (30.021) seconds
Test Case 'TestResponse.testSimpleResponse' started.
Test Case 'TestResponse.testSimpleResponse' passed (0.006 seconds).
Test Case 'TestResponse.testPostRequest' started.
Test Case 'TestResponse.testPostRequest' passed (0.007 seconds).
Test Case 'TestResponse.testParameter' started.
Test Case 'TestResponse.testParameter' passed (0.005 seconds).
Test Case 'TestResponse.testRedirect' started.
Test Case 'TestResponse.testRedirect' passed (0.156 seconds).
Executed 4 tests, with 0 failures (0 unexpected) in 0.174 (40.179) seconds
Test Case 'TestMultiplicity.testPlus' started.
Test Case 'TestMultiplicity.testPlus' passed (0.016 seconds).
Test Case 'TestMultiplicity.testStar' started.
Test Case 'TestMultiplicity.testStar' passed (0.016 seconds).
Test Case 'TestMultiplicity.testQuestion' started.
Test Case 'TestMultiplicity.testQuestion' passed (0.017 seconds).
Test Case 'TestMultiplicity.testCombined' started.
Test Case 'TestMultiplicity.testCombined' passed (0.018 seconds).
Executed 4 tests, with 0 failures (0 unexpected) in 0.067 (40.072) seconds
Test Case 'ClientTests.testSimpleHttpClient' started.
Test Case 'ClientTests.testSimpleHttpClient' passed (0.138 seconds).
Executed 1 test, with 0 failures (0 unexpected) in 0.138 (0.138) seconds
Test Case 'ParserTests.testParseSimpleUrl' started.
Test Case 'ParserTests.testParseSimpleUrl' passed (0.0 seconds).
Test Case 'ParserTests.testParseComplexUrl' started.
Test Case 'ParserTests.testParseComplexUrl' passed (0.0 seconds).
Executed 2 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds
Total executed 15 tests, with 0 failures (0 unexpected) in 0.4 (110.412) seconds
>> Finished execution of tests for Kitura (see above for results).
root@56639f7867fe:~# ls
Kitura                      run_tests_kitura.sh                                  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10.tar.gz
clone_build_kitura.sh       start_kitura_sample.sh                               swift-corelibs-libdispatch
clone_build_test_kitura.sh  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10
root@56639f7867fe:~# cd Kitura/
root@56639f7867fe:~/Kitura# la
.build  .gitignore   .swiftlint.yml  CONTRIBUTING.md  Kitura-CI    Makefile       Packages   Sources  vagrantfile
.git    .gitmodules  .travis.yml     Documentation    LICENSE.txt  Package.swift  README.md  Tests
root@56639f7867fe:~/Kitura# ls
CONTRIBUTING.md  Documentation  Kitura-CI  LICENSE.txt  Makefile  Package.swift  Packages  README.md  Sources  Tests  vagrantfile
root@56639f7867fe:~/Kitura# cd ..
root@56639f7867fe:~# ls
Kitura                      run_tests_kitura.sh                                  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10.tar.gz
clone_build_kitura.sh       start_kitura_sample.sh                               swift-corelibs-libdispatch
clone_build_test_kitura.sh  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10
root@56639f7867fe:~# /root/
bash: /root/: Is a directory
root@56639f7867fe:~# cd /root/
root@56639f7867fe:~# ls
Kitura                      run_tests_kitura.sh                                  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10.tar.gz
clone_build_kitura.sh       start_kitura_sample.sh                               swift-corelibs-libdispatch
clone_build_test_kitura.sh  swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10
root@56639f7867fe:~# /root/start_kitura_sample.sh 
/root/start_kitura_sample.sh: line 23: ./.build/debug/KituraSample: No such file or directory
root@56639f7867fe:~# /root/start_kitura_sample.sh
/root/start_kitura_sample.sh: line 23: ./.build/debug/KituraSample: No such file or directory
root@56639f7867fe:~# 

</pre>

I have no idea why this is showing, I have just followed the documentation.

**Comment by alvinvarghese** [comment]
Why no one is responding ? What should i do ?

**Comment by shmuelk** [comment]
Try and edit the /root/clone_build_test_kitura.sh shell script.  Either:

   1. Remove the "-b develop" parameters of the git clone command in there.

   2. Change the repository being cloned from Kitura to Kitura-Sample

In our develop branch we have re-organized our repositories some what.

Sorry about this.

**Comment by rolivieri** [comment]
@alvinvarghese - We missed updating the docker image after some refactoring took place late last week. If you pull down the latest version of the docker image, you should be good now. We just updated it and tested it:

docker pull ibmcom/kitura-ubuntu:latest
