### ISSUE TITLE
Get Kitura apps (like TodoList) to be built in XCode with generate-xcodeproj

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#272]
Admittedly, right now this is a manual process, requiring a complicated XCode project configuration building different targets. One would need to set up the module map paths, build order, etc. But it's doable if they truly want to have an integrated environment with the debugging, profiling, and indexing in XCode.

As an alternative, we can simply show them how to launch 'swift build' as a build step in XCode- but you won't be the above features.

**Comment by chrisozenne** [comment]
What is the current manual process? I'd love to help write the tutorial.

**Comment by rfdickerson** [comment]
@billabt Do you have any suggestions here?

I remember that during Swift.org's debut they showed how to launch XCode using the opensource toolchain. The instructions seem to be gone now, however.

**Comment by loopbum** [comment]
Something would be helpful; get more people involved.

**Comment by dfirsht** [comment]
See this relevant quote from the SPM mailing list:

> I have merged Xcode project generation into master.
> 
> To generate a project from a package:
> 
>     swift build --generate-xcodeproj
> 
> Or, the short-form:
> 
>     swift build -X
> 
> The above will work with the next available snapshot.
> 
> The project contains a dylib target per module and targets for any executables based on how it would build with SwiftPM normally.
> 
> There is an open list of TODO items in the Xcodeproj module directory: https://github.com/apple/swift-package-manager/tree/master/Sources/Xcodeproj
> 
> Max

**Comment by generatronServer** [comment]
this is good news

**Comment by dsperling** [comment]
I just confirmed that the --generate-xcodeproj feature is included in the "swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg" located on Swift.org.  Great work!

**Comment by rfdickerson** [comment]
Have we investigated creating an XCode project using the 3-24 drop, but set the XCode toolchain to 3-01 and see if it builds?

**Comment by dsperling** [comment]
Yes, this works.  Here is the procedure on OSX 10.11.4 & Xcode 7.3:
- export PATH=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a.xctoolchain/usr/bin:$PATH
- cd [pathto]/Kitura
- swift build -X
- open Kitura.xcodeproj
  - [ensure that Xcode 7.3 Toolchain is 2016-03-01]
- Doing a build will result in this error:
  - [pathto]//Kitura/Packages/Kitura-net-0.5.8/Sources/KituraNet/ClientRequest.swift:18:8: error: no such module 'CCurl'
- Open Xcode ‘Build Settings’ for Kitura.xocdeproj
- Select Kitura PROJECT (Blue icon)
  - Add /usr/local/include to 'Header Search Paths'
  - Add /usr/local/lib to 'Library Search Paths'
- Select Kitura TARGET (Gray house icon)
  - Add these two lines to Swift Compiler ‘Import Paths'
  - Packages/CCurl-0.0.1
  - Packages/CHttpParser-0.0.1
- Build

**Comment by rfdickerson** [comment]
Thanks for checking that out! Apparently there seems to still be problems with C module maps and their integration in XCode projects.

**Comment by chrisozenne** [comment]
@dsperling You exported a path to the snapshot dated 2016-03-24, however you stated that we need to ensure that the Xcode 7.3 toolchain is 2016-03-01. Those two toolchains are different dates, is that correct?

**Comment by dsperling** [comment]
Correct.  The 2016-03-24 toolchain supports the 'swift build --generate-xcodeproj' (swift build -X) feature.  However the 2016-03-01 toolchain is currently required to build Kitura.

**Comment by rfdickerson** [comment]
<img width="1105" alt="screen shot 2016-03-25 at 8 50 04 am" src="https://cloud.githubusercontent.com/assets/1310293/14045297/f7b3bfea-f266-11e5-9ff2-7d6f28c1cecb.png">

Alright, I figured out how to get it to build and run inside of XCode.

1. XCode->Preferences->Components select 03-01 Toolchain
2. Change the "Runpath Search Paths" on your executable from 03-15 toolchain to directory where 03-01 toolchain exists
3. Add to both Kitura, KituraNet, and your executable (mine is TodoList) the following "Header Search Paths" 
  - ${SRCROOT}/Packages/CCurl-0.0.1
  - ${SRCROOT}/Packages/CHttpParser-0.0.1
  - /usr/local/include
4. Add to both Kitura and KituraNet the following Library Search Path: `/usr/local/lib`
5. Change the build scheme to your executable (mine is TodoList)
6. Run :)

**Comment by rfdickerson** [comment]
Confirmed that XCode integrated debugging works for the executable (TodoList) and inside of functions in the dependent modules (like Kitura-Net).

**Comment by rfdickerson** [comment]
Wrote up a [basic tutorial](https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-on-XCode) on the Wiki.

**Comment by rfdickerson** [comment]
I tried running the test cases in XCode. I have my doubts that this functionality will work. I get the following message:

```
warning: Swift error in module TodoListDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libKitura.dylibDebug info from this module will be unavailable in the debugger.
```

**Comment by dsperling** [comment]
I have a Kitura.xcodeproj created from my previously posted steps that successfully runs all test cases.  However, when I drag Kitura.xcodeproj into another Xcode project so I can consume the library, it get the following warnings on run.  I am able to run and debug however.

> objc[58118]:  Class _TtCV17SwiftOnoneSupport14_Prespecialize1C is implemented in both /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain/usr/lib/swift/macosx/libswiftSwiftOnoneSupport.dylib and ~/Library/Developer/Xcode/DerivedData/myapp-ghukughkyhsfqqfjowmxkfnelnbl/Build/Products/Debug/myapp. One of the two will be used. Which one is undefined.

Attaching the .xcodeproj if others want a faster starting point.
[Kitura.xcodeproj.zip](https://github.com/IBM-Swift/Kitura/files/189601/Kitura.xcodeproj.zip)

**Comment by billabt** [comment]
That is normal (at least what passes for normal) right now.  There's no problem with it.  I've been seeing that for quite awhile now...

**Comment by rfdickerson** [comment]
I filed a PR regarding the bug where C Modulemaps can't be located in the XCode build process, and my fix. https://bugs.swift.org/browse/SR-1085

**Comment by rfdickerson** [comment]
Apparently this C Module maps not being in the include path has been addressed with this PR: https://github.com/apple/swift-package-manager/pull/226

**Comment by rfdickerson** [comment]
We can close this issue for now and reopen it once the new snapshot comes out and we can then simplify the process.

**Comment by gaylejj** [comment]
With new stuff added, you now need to add ${SRCROOT}/Packages/CHttpParser-0.0.2 to the header paths rather than ${SRCROOT}/Packages/CHttpParser-0.0.1.

**Comment by JoeFerrucci** [comment]
I'm trying to create an Xcode project from my Kitura web app. I am on `DEVELOPMENT-SNAPSHOT-2016-05-03-a` and my web app build nicely in the terminal with `swift build` and runs fine .build/debug/firstKituraProject` -- which runs on `localhost:8090`

But when I try to create an Xcode project so that I may develop and Run in Xcode (using the terminal command `swift build -X` or `swift build --generate-xcodeproject`), I suddenly get a ton of build errors. I switched my Xcode toolchain to match my console toolchain.
