### ISSUE TITLE
Kitura (-> KituraNet) is failing to build on 1st March dev swift release snapshot (i.e. swift 3.0).

### ISSUE THREAD

**Issue by swapsjadhav** [IBM-Swift/Kitura#277]
1. MacBook-Pro:myFirstProject $ **swift --version**
Apple Swift version **3.0-dev** (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)

2. Compiling Swift Module '**KituraNet**' (12 sources)
/Users/Apps/myFirstProject/Packages/**Kitura-net-0.5.1**/Sources/KituraNet/IncomingMessage.swift:173:9: _error: 'guard' body may not fall through, consider using 'return' or 'break' to exit the scope_ }

Please let me know, if I am doing anything wrong here.

Thanks!

**Comment by shmuelk** [comment]
I see that problem. Working on it.

Thanks for reporting it. It seems

**Comment by shmuelk** [comment]
@swapsjadhav The problem is fixed. Please remove the Packages directory and do a  make to build the executable.

**Comment by dfirsht** [comment]
Validated.
