### ISSUE TITLE
Get Kitura-Credentials and Kitura-Bluepic to work with develop branch of Kitura

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#279]

**Comment by shmuelk** [comment]
Commits:

https://github.com/IBM-Swift/Kitura-Credentials/commit/b1d842ae2a33613c7acc8aee6fa4b97bd889f0df

https://github.com/IBM-Swift/Kitura-CredentialsFacebookToken/commit/8ab87d42b81fa0e73acb35c04bc975c3eedc7a8c

https://github.com/IBM-Swift/Kitura-CredentialsFacebookToken/commit/b1fabc628b68e280a8c67ce492a3940bc0b258d1

**Comment by irar2** [comment]
Validated by running Kitura-BluePic
