### ISSUE TITLE
Add annotations

### ISSUE THREAD

**Issue by lucFX11** [IBM-Swift/Kitura#287]
It would be great to have annotations in Kitura a la Spring framework. Would make the code cleaner.

**Comment by vadimeisenbergibm** [comment]
The problem is that Swift does not have custom annotations like Java.

**Comment by Yoseob** [comment]
does't preference Swift annotations Style like Java?

**Comment by kweinmeister** [comment]
Closing the issue due to inactivity. If you want to provide a small sample of what you'd like to see, and the implementation in Kitura, please reopen the issue.
