### ISSUE TITLE
Add custombuild target to Makefile to be used by including Makefile

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#290]
The including Makefile can override custombuild target to perform some operations before build.

**Comment by dfirsht** [comment]
@vadimeisenbergibm What is the status on this? This should have been in one of the milestones.

**Comment by dfirsht** [comment]
@vadimeisenbergibm Is there a reason why this is reopened?

**Comment by vadimeisenbergibm** [comment]
@dfirsht I forgot to validate it and closed it - reopened it for validation. Could you please validate and close?

**Comment by dfirsht** [comment]
Ok, this looks good.
