### ISSUE TITLE
Allow an array of handlers and middleware to be specified for routes

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#292]
Example from Express: app.get('/example/c', [cb0, cb1, cb2]);

**Comment by shmuelk** [comment]
Under this issue we are adding the ability to add a middleware for a particular HTTP method.

As such, the Router.use API is being deprecated. Instead one should use Router.all with a middleware.

**Comment by irar2** [comment]
Validated: reviewed the code, and ran Kitura-BluePic-server
