### ISSUE TITLE
Enhance template engine support to allow multiple engines for different file extensions

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#296]

**Comment by shmuelk** [comment]
I think the latest Error enum declaration needs some work, especially around error messages.

**Comment by vadimeisenbergibm** [comment]
@shmuelk so what should be improved? I have committed a missing whitespace in commit https://github.com/IBM-Swift/Kitura/commit/545f957b462fdf51c6d1a3043c8010f61ec03be9 .

**Comment by shmuelk** [comment]
I was mistaken. The code is fine.
