### ISSUE TITLE
Add hostname property to RouterRequest

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#301]

**Comment by shmuelk** [comment]
Needed for correct cookie and session support

**Comment by shmuelk** [comment]
Until we add settings, in particular whether or not the proxy is trusted, this all that there is to do.

When we add proxy trust, then we need to look at the X-Forwarded-Host instead.

**Comment by shmuelk** [comment]
@dfirsht Please validate

**Comment by dfirsht** [comment]
This is good right now. We can add the X-Forwarded-Host when we add proxy settings.
