### ISSUE TITLE
Add subdomain property to RouterRequest

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#303]
This should be an array of subdomain strings.

**Comment by naithar** [comment]
I have implemented this feature in a separate branch. Should I add it to my current pull request or create a new one?
Here's the code and travis build for reference:
https://github.com/naithar/Kitura/blob/subdomain/Sources/Kitura/RouterRequest.swift#L46-80
https://github.com/naithar/Kitura/blob/subdomain/Tests/Kitura/TestResponse.swift#L353-398
https://travis-ci.org/naithar/Kitura/builds/131382000

**Comment by dfirsht** [comment]
Hey @naithar, thanks for the contribution! You should create a new PR so we can evaluate them separately.

**Comment by naithar** [comment]
@dfirsht done :)

**Comment by dfirsht** [comment]
This issue was completed in the PR.
