### ISSUE TITLE
Add attachment method for RouterResponse

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#307]
Example in Express:
res.attachment();
// Content-Disposition: attachment

res.attachment('path/to/logo.png');
// Content-Disposition: attachment; filename="logo.png"
// Content-Type: image/png

**Comment by dfirsht** [comment]
@shmuelk Sorry, one more to validate.

**Comment by shmuelk** [comment]
Reviewed the code. Looks ok.
