### ISSUE TITLE
Add JSONP support for RouterResponse

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#310]

**Comment by tunniclm** [comment]
I accidentally made the changes based on master, but this is what they look like at the moment:
https://github.com/IBM-Swift/Kitura/compare/master...tunniclm:add_jsonp

**Comment by tunniclm** [comment]
Rebased my changes on top of develop:
https://github.com/IBM-Swift/Kitura/compare/develop...tunniclm:add_jsonp_on_develop

**Comment by ianpartridge** [comment]
Merged in 0430d9d356e9ed8c339c4a6d6b1e4d47da481e56
