### ISSUE TITLE
Error running swift test

### ISSUE THREAD

**Issue by nicholasjackson** [IBM-Swift/Kitura#314]
Hi,

When I try to run "swift test" on my application I get the following error message:

```
Compiling Swift Module 'Kituratest' (6 sources)
/src/Packages/Kitura-0.5.5/Tests/Kitura/TestCookies.swift:135:65: error: cannot convert value of type '[String : String]' to expected argument type '[String : Any]'
                        resultCookie = NSHTTPCookie(properties: properties)
                                                                ^~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): swift-build-tool -f /src/.build/debug.yaml test
```

I have not had a chance to look any further into this and I'm happy to look at a fix tomorrow if this is not already in-process?

## Example code:
[https://github.com/nicholasjackson/helloworld-swift](https://github.com/nicholasjackson/helloworld-swift)

Kind regards,

Nic

**Comment by vadimeisenbergibm** [comment]
Fixed in commit 2abb58670e4ffefc1a73053ddfff74a4be99a958

**Comment by nicholasjackson** [comment]
Looks good thank you, I will test this morning and close the issue.

**Comment by nicholasjackson** [comment]
This is all good now awesome thanks,
Total executed 17 tests, with 0 failures (0 unexpected) in 0.476 (130.492) seconds
