### ISSUE TITLE
Migrate Kitura-Bluepic's iOS app to XCode 7.3

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#315]
Migrate Kitura-Bluepic's iOS app to XCode 7.3, this includes:

   1. Migration from Carthage to CocaPods for all external binaries
   2. Removal of all binaries from GIT
   3. Fixes to deprecated Swift APIs

**Comment by shmuelk** [comment]
Ira. Please validate this issue.

**Comment by irar2** [comment]
Validated
