### ISSUE TITLE
Add support for path pattern matching (multiplicity)

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#32]
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Monday Jan 11, 2016 at 16:43 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/32_

----

Samuel will add a link to this work item with further details.

**Comment by dfirsht** [comment]
@shmuelk Hey Shmuel can you provide more information on this? Would this allow for multiple matching routes to be hit? How would this affect having something like a root endpoint?

**Comment by shmuelk** [comment]
Actually the router already supports multiple routes hitting a request.

The original test/sample program did just this with a middleware that dumped headers from requests and then a handler that did something for real.

This is about handling things like a pattern of /testing/:name* matching the paths /testing/123, /testing/test/test, etc.

Also we need support for + and ? to indicate at leat one and one optionally

**Comment by dfirsht** [comment]
Relavent commit: https://github.com/IBM-Swift/Kitura-router/commit/072275b7d3218af92960f8304b4935779fc6d629

**Comment by dfirsht** [comment]
Looks great! We should consider creating some documentation in the future to highlight this feature. I also created issue #216 to create test cases for this feature.
