### ISSUE TITLE
Create initial docs

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#320]
Looking at automation vs manual writing.

**Comment by dfirsht** [comment]
Look into autogen docs.

**Comment by ianpartridge** [comment]
Here's Apple's specification for marking up Swift code

https://developer.apple.com/library/mac/documentation/Xcode/Reference/xcode_markup_formatting_ref/

**Comment by ianpartridge** [comment]
https://github.com/realm/jazzy is interesting.

**Comment by ianpartridge** [comment]
Investigate:

https://readthedocs.org/
https://www.gitbook.com/
https://readme.io/

**Comment by ianpartridge** [comment]
Also:

https://github.com/SwiftDocOrg/swiftdoc-parser

**Comment by aquarchitect** [comment]
@ianpartridge I thought you might be interested in this - [ReSwift](https://github.com/ReSwift/ReSwift) generating their documentation by combining __jazzy__, __travis ci__, and __gh_pages__. Quoting from [their website](https://reswift.github.io/ReSwift/master/contributing.html):

## Generating documentation

The documentation at `reswift.github.io/ReSwift` is generated from by combining the markdown documentation files with generated documentation using [jazzy](https://github.com/realm/jazzy).

The markdown files used to generated documentation are:

- README.md
- CONTRIBUTING.md
- CHANGELOG.md
- LICENSE.md
- Docs/
    - Getting Started Guide.md
    - templates/
        - heading.md
        - toc.md

Along with the Documentation sections, API sections also support extra documentation found in:

- Docs/
    - Actions.md
    - Reducers.md
    - State.md
    - Stores.md
    - Utilities.md

Each of the markdown files are processed by the `generate_docs.sh` script and saved into `Docs/tmp/` ready for jazzy to generate the final documentation.

The processing of each file can include:

- Extracting a single section (ie, for splitting up README.md)
- Adding a title
- Replacing \{\{version\}\} with the current version
- Ad-hoc string replacements (found in .jazzy.json under "string-replacements")

A forked version of Jazzy is currently used to support individual markdown sections and injecting markdown into API section headers. It can be installed from [https://github.com/agentk/jazzy/](https://github.com/agentk/jazzy/tree/integrated-markdown).

The documentation is hosted by GitHub pages under the [ReSwift gh-pages](https://github.com/ReSwift/ReSwift/tree/gh-pages) branch. The `build.sh` script in the `gh-pages` branch, installs / updates jazzy, checks out the latest master branch of ReSwift, and calls the `generated_docs.sh` script to generate docs into the master folder. Docs changes can then be committed and pushed to the `gh-pages` branch.

The custom jazzy theme is located in: `Docs/jazzy-theme`.

Changes to `generate_docs.sh` will generally only be needed when sections / files are added or removed.

**Comment by ianpartridge** [comment]
Thanks @aquarchitect I'll look into this!

**Comment by aquarchitect** [comment]
@ianpartridge any luck so far? I managed to make the docs generation fully automatic with the combination of __jazzy__, __travis__, and __gh-pages__. Here's what it looks like: [the docs page](https://github.com/aquarchitect/Kitura/tree/gh-pages) and [travis log](https://travis-ci.org/aquarchitect/Kitura/jobs/140101880).

**Comment by aquarchitect** [comment]
@ianpartridge any thought on my doc generation solution?

**Comment by aquarchitect** [comment]
@dfirsht @ianpartridge any thought on my doc generation solution above?
