### ISSUE TITLE
Update the develop branch of various to use the latest develop tag

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#327]
There is now a 0.7.x tag in Kitura and Kitura-net. They should be used by various other repositories, including:

  1. Kitura-Sample
  2. Kitura-CouchDB
  3. Kitura-Credentials
  4. Kitura-CredentialsFacebookToken
  5. Kitura-CredentialsGoogleToken
  6. Kitura-BluePic

**Comment by irar2** [comment]
Validated by running Kitura-Bluepic and Kitura-Sample
