### ISSUE TITLE
Migrate to 3/24 swift binaries

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#328]
Depends on #340

**Comment by rfdickerson** [comment]
Update, we have our fork of SwiftyJSON, Kitura-Net, and BlueSocket migrated over to 3-24. We just need to finish GRMustache and we will be done.

**Comment by tfrank64** [comment]
Excluding GRMustache, Kitura runs fine on my local machine. I had to change SwiftyJson on Mac to get things working so we might need a forked version of SwiftyJson for Mac, otherwise, we are dependent on the SwiftyJson team.

**Comment by kweinmeister** [comment]
If we have to fork SwiftyJSON on OS X too, we should consider having only one combined fork with #if conditions for each OS. Ultimately, I assume that SwiftyJSON will not want to have separate Linux and OS X versions. So, if we maintain one fork, it would be closer to the eventual PR to add Linux support.

**Comment by tfrank64** [comment]
Main Kitura repos are upgraded, including CouchDB and Redis. What is not updated: GRMustache, Kitura-credentials, and BluePic

**Comment by dfirsht** [comment]
All repos are updated to 3/24 binaries.
