### ISSUE TITLE
Make CI use a parameter for which Swift toolchain to use for build and tests

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#329]
Because of the rapid turn-around of new Swift versions and toolchains, and because of the community willing to help with bringing us up to compatibility. Perhaps we should support our CI builds and test suites to run on any version of the Swift toolchain the PR submitter provides as a parameter.

The proposal would be:

Inside of the Kitura project there would be a file called .swift-version that would contain a string such as DEVELOPMENT-SNAPSHOT-2016-03-01-a, DEVELOPMENT-SNAPSHOT-2016-03-24-a, etc. The CI docker instance would download the specified toolchain with that string to use for building the project.

The advantage in this case is that the maintenance complications of handling different toolchain versions could be relegated to the person providing the PR request.

PR's like this could be validated quickly in this case:
https://github.com/IBM-Swift/Kitura-net/pull/16

**Comment by dfirsht** [comment]
We are going forward on this. Implementation is being tracked here: https://github.com/IBM-Swift/Kitura-Build/issues/2
