### ISSUE TITLE
Open Source Approval to use krzyzanowskim/CryptoSwift

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#332]
The package krzyzanowskim/CryptoSwift on github provides encrytion/decryption support (SHA256, AES,.....). It is written purely in Swift, has no pre-requisites, and is compatible with the Swift Package Manager.

An entry has been added to Box comment https://ibm.app.box.com/notes/50224044186

**Comment by shmuelk** [comment]
@pbohrer I know that there is a desire to use OpenSSL wrapped with some Swift code, if needed as part of the Server Foundation  . Until such a time, can we use krzyzanowskim/CryptoSwift as a work around?

We need some encryption to make all sorts of things secure.

@seabaylea  and @billabt  Are there any other things in the near term pipeline? Please note that simply wrapping OpenSSL with a modulemap file has those awful ABI issues.

**Comment by billabt** [comment]
If all you're looking for is crypto, this'll do the job however before using it, it'd have to be verified for vulnerabilities and accuracy or we risk being vulnerable and/or incompatible. If crypto is all you need, you can wrap CommonCrypto in a modulemap and use that. It's available on both Linux and OS X (as part of OS). I've used that library before and it's very easy and straightforward to use. Note, however, that neither one of these provides certificate or SSL functionality. These do crypto only.

**Comment by seabaylea** [comment]
@preecet is starting work this week to evaluate the currently available security libraries for Obj-C, see which ones make most sense on the server, and whether we can implement them as a Swift layer on top of OpenSSL.

In the mean time, if CryptoSwift works, it can provide a stop gap. Note that CryptoSwift won't have any certification, so we'd have to be careful about how "secure" we claim to be.

**Comment by preecet** [comment]
Is there a well defined requirement for certain set of security APIs ?

I see there is also https://github.com/iosdevzone/IDZSwiftCommonCrypto ( under MIT license ) that provided a nicer swift interface. It is around commoncrypto at the moment but could be modified to wrap OpenSSL.

**Comment by billabt** [comment]
CommonCrypto is available on Linux as well.  Apple open sourced it.  It works quite well and could be used right with just a modulemap.  Doesn't have the overhead of OpenSSL as far as setup and tear down.  I've been using in another project for sometime...

**Comment by seabaylea** [comment]
@billabt Where can we find the CommonCrypto open source project? I can find a source dump here:
http://opensource.apple.com/source/CommonCrypto/

but I haven't yet found a live project which the community can contribute to - and where we can tell we could get an update quickly if a vulnerability was found.

**Comment by rfdickerson** [comment]
What's the status of this? Another option could be to use [OpenSSL Swift](https://github.com/Zewo/OpenSSL)

**Comment by billabt** [comment]
I think the Zewo implementation has been ruled out. What do you need CryptoSwift for? All it will buy you is crypto, no SSL.

**Comment by preecet** [comment]
Zewo OpenSSL Swift also has a dependency on VeniceX which may not be desirable,

For the "Short term" a module map for OpenSSL would seem to be the best route

**Comment by rfdickerson** [comment]
That's what I was wondering, as well. I think that it would take quite a bit of effort to use take basic crypto and implement the SSL protocol. Would CryptoSwift be comparable to [libgcrypt](https://www.gnu.org/software/libgcrypt/)?

**Comment by billabt** [comment]
You should be able to use CommonCrypto, no?  That plus a modulemap for OpenSSL should give you what you need.

**Comment by preecet** [comment]
OpenSSL could provide all the crypto routines as well as the SSL protocol.

**Comment by rfdickerson** [comment]
I created a modulemap file a couple of months ago. Might be worthwhile. It links in both libssl and libcrypto.

https://github.com/IBM-Swift/CCryptoSSL/blob/master/module.modulemap

**Comment by billabt** [comment]
@preecet: True it does, but the issue is Swift programmers are used to using CommonCrypto, not OpenSSL which is why I suggested using that instead.

**Comment by preecet** [comment]
Is this requirement for Kitura to use internally or something to be exposed to Kitura application developers? 

I was reading this particular issue as something that was required internally.

**Comment by shmuelk** [comment]
The original request as a starter is for use internally.

Having said that, we also need to expose a set of crypto APIs as well and HTTPS at the server level as well. The latter can be deferred for a while, as we can tell people to place Kitura behind a reverse proxy that is terminating the SSL. But there is often a need for end to end SSL.

**Comment by seabaylea** [comment]
@billabt but if we can provide the CommonCrypto APIs using OpenSSL as the implementation then we solve both with one implementation ;-)

**Comment by shmuelk** [comment]
We will be using another repo for encryption
