### ISSUE TITLE
Add type method to RouterResponse

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#336]
Sets the Content-Type HTTP header to the MIME type

**Comment by dfirsht** [comment]
@shmuelk Please validate.

**Comment by KevinGong2013** [comment]
Also need to set "charset" ?

**Comment by dfirsht** [comment]
@shmuelk Please validate changes.

**Comment by shmuelk** [comment]
I would have coded it as follows:

public func type(type: String, charset: String? = nil) {
    if  let contentType =  ContentType.contentTypeForExtension(type) {
           var contentCharset = ""
           if let charset = charset {
                contentCharset += "; charset=\(charset)"
           }
           setHeader("Content-Type", value: contentType + contentCharset)
    }
}

**Comment by dfirsht** [comment]
@shmuelk Made those changes, can we close now?

**Comment by shmuelk** [comment]
@dfirsht  Yes.
