### ISSUE TITLE
Vagrant Instructions Problem

### ISSUE THREAD

**Issue by justinlevi** [IBM-Swift/Kitura#338]
I'm just trying out this project using Vagrant/Virtual Box and it seems like something is missing...

From the instructions:
```
5. From the Vagrant shell, run the sample program:

Kitura/.build/debug/KituraSample. You should see a message that says "Listening on port 8090".
```

However, there is no "KituraSample" in the `Kitura/.build/debug/` folder. 

If I were to clone the KituraSample project, where should I clone that repo?

**Comment by dfirsht** [comment]
Sorry for the late reply, I just updated the Vagrant instructions. If you were to clone KituraSample you should do it anywhere inside your Vagrant machine.
