### ISSUE TITLE
Refactor and clean up Kitura codebase

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#348]
This is a general issue for the task of cleaning up our codebase. We will begin by creating a list of the changes we want to make. This should be filled out throughout the next sprint ending April 20th. The list of proposed changes can be found here: https://docs.google.com/spreadsheets/d/1Ua10U5tpxznjNsJ496_F7gHq28RfgLkj3Tp8nfbdbQQ/.

Anyone who does not have edit permission can propose a change via a comment below.

**Comment by nicholasjackson** [comment]
I would be interested to implement protocols for RouterRequest and RouterResponse in order to make handlers more unit testable and to enable only testing the logic inside the handler rather than having to run an integration type test.  I am happy to carry out this work tomorrow if this is something you think could be useful?

## Proposed implementation (Pseudo code):

``` Swift
// not sure on the naming convention I have looked at various suggestions for good names and come up blank
protocol RouterRequestProtocol {

}

protocol RouterResponseProtocol {

}
```

### Would a unit test to be written for a handlers like so...

```Swift
import Foundation
import XCTest

@testable import MyService

public class RouterRequestMock: RouterRequestProtocol {
     ….
}

public class RouterResponseMock: RouterResponseProtocol {
     var statusValue: Int

     public status(value) -> RouterResponseProtocol {
       statusValue = value
     }
     ….
}

public class HealthHandlerTests: XCTestCase {
  public func testSendsResponseStatusOK() {
     let request = RouterRequestMock()
     let response = RouterResponseMock()
     let handler = HealthHandler(request: request, response: response)

     handler.handle(request, response)

     XCTAssertEqual(HttpStatusCode.OK, response.statusValue, “Expected response to return OK”)
  }
}

extension HealthHandlerTests {
  static var allTests: [(String, HealthHandlerTests -> () throws -> Void)] {
    return [
      ("testSendsResponseStatusOK", testSendsResponseStatusOK)
    ]
  }
}
```

**Comment by dfirsht** [comment]
All issues completed.
