### ISSUE TITLE
Monitor file system for changes in binaries and load them

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#35]
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Tuesday Jan 12, 2016 at 00:18 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/35_

----

Similar to WAS Liberty and NodeJS, if there are changes in the binary files, these should be detected and loaded.

**Comment by shmuelk** [comment]
Or we could do what Gulp does. If it sees changes in the JavaScript source, it kills the  Node.js process and starts a new one.

**Comment by ianpartridge** [comment]
Not in the current plans.
