### ISSUE TITLE
RouterResponse should return 2xx on a request to a valid route unless status explicitly set

### ISSUE THREAD

**Issue by bobringer** [IBM-Swift/Kitura#351]
By default, responses return a 404 status, regardless of whether or not a route exists for the requested resource.

If a response exists, shouldn't we return a 200 by default and leave it up to the developer to explicitly return something else if necessary?

Currently, we need to explicitly set `response.staus(.OK)` on every successful response.

**Comment by shmuelk** [comment]
What if a route exists, but the developer doesn't do anything?

What if a route exists for a middleware that doesn't really "process" the request but just parses the body or handles sessions, etc. vs a middleware that actually returns something like the static file handling middleware?

**Comment by bobringer** [comment]
404 indicates a request for a resource that doesn't exist.  Your scenarios are still responding with a valid response even if it's empty.  The server should still tell the client everything was ok with the request.

**Comment by kweinmeister** [comment]
Valid points. We will think through this. The final answer to some of the scenarios might include additional codes such as 204 No Content. Also, any pointers to code or documentation from other servers as a reference would be helpful.

**Comment by bobringer** [comment]
I think that makes sense.  If no response is explicitly set, the server should be able to derive 2xx codes from the response payload.

I'm temporarily switching to node.js for the small test project I'm working on (I'm only holding off on switching back to swift when the system dependencies are no longer necessary).  I'll take note of how they default and report back...

**Comment by kweinmeister** [comment]
@bobringer Any updates on your findings from node.js?

**Comment by dfirsht** [comment]
I have changed Kitura's behavior to add the 200 status code if end or send was invoked in a route. @shmuelk please verify.

**Comment by shmuelk** [comment]
@dfirsht I reviewed the changes. They look good.
