### ISSUE TITLE
Kitura on Heroku

### ISSUE THREAD

**Issue by joaoamaral** [IBM-Swift/Kitura#353]
Hi! I'm building a Kitura app and I want to deploy it to Heroku
I'm using DEVELOPMENT-SNAPSHOT-2016-03-24-a and https://github.com/kylef/heroku-buildpack-swift.git buildpack

but I found this error about Dispatch module while compiling KituraSys
can someone give me some help? Thank you :)

```
remote: Compiling KituraSys
remote: /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/Packages/Kitura-Sys-0.7.0/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
remote: import Dispatch
remote:        ^
remote: 
<unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): /app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-03-24-a/usr/bin/swift-build-tool -f /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/.build/release.yaml default
```

**Comment by vadimeisenbergibm** [comment]
Hi, please see [Installation instructions of Kitura on Linux](https://github.com/IBM-Swift/Kitura#installation-linux-apt-based), steps 1. and 3.

**Comment by joaoamaral** [comment]
Thank you so much for the reply @vadimeisenbergibm 
So I guess Kylef's buildpack is the culprit. :)
I guess I must build my own buildpack in order to work with Swift and Kitura on Heroku.
Thank you for pointing me in the right direction.

**Comment by vadimeisenbergibm** [comment]
You are very welcome @joaoamaral 
I do not know if Cloud Foundry build pack could help you - https://github.com/IBM-Swift/swift-buildpack

**Comment by rfdickerson** [comment]
@joaoamaral you can also try this buildpack for swift compiler 03-24. 

https://github.com/rfdickerson/swift-buildpack

Please let me know if it works for you on Heroku

**Comment by ElderFain** [comment]
I'm using a modified version of https://github.com/IBM-Swift/swift-buildpack but running into issues with libdispatch/libpthreads , documented here https://github.com/IBM-Swift/Kitura/issues/346

It looks like there aren't an issue on Ubuntu 15, just 14. Would be good to confirm if you are able to get it working.

**Comment by rfdickerson** [comment]
Can you try the rfdickerson buildpack? It has a toolchain that's all set to go with dispatch library installed on the 03-24 snapshot.

**Comment by joaoamaral** [comment]
@rfdickerson Thank you so much for your help. I tried to use your buildpack I got this return:

```
$ heroku buildpacks:clear
Buildpacks cleared. Next release on kituraheroku will detect buildpack normally.
$ heroku buildpacks:set https://github.com/rfdickerson/swift-buildpack.git
Buildpack set. Next release on kituraheroku will use https://github.com/rfdickerson/swift-buildpack.git.
Run git push heroku master to create a new release using this buildpack.
$ git push heroku master
Counting objects: 17, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (17/17), 28.36 KiB | 0 bytes/s, done.
Total 17 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/rfdickerson/swift-buildpack.git... done
remote: -----> Swift app detected
remote: -----> Updating apt caches
remote:        Get:1 http://ppa.launchpad.net trusty InRelease [15.4 kB]
remote:        Get:2 http://apt.postgresql.org trusty-pgdg InRelease [30.1 kB]
remote:        Ign http://archive.ubuntu.com trusty InRelease
remote:        Get:3 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
remote:        Get:4 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
remote:        Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]
remote:        Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]
remote:        Get:7 http://ppa.launchpad.net trusty/main amd64 Packages [3,338 B]
remote:        Get:8 http://archive.ubuntu.com trusty-security/main amd64 Packages [455 kB]
remote:        Get:9 http://ppa.launchpad.net trusty/main Translation-en [2,645 B]
remote:        Get:10 http://archive.ubuntu.com trusty-security/main Translation-en [250 kB]
remote:        Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [752 kB]
remote:        Get:12 http://archive.ubuntu.com trusty-updates/main Translation-en [376 kB]
remote:        Get:13 http://archive.ubuntu.com trusty/main amd64 Packages [1,350 kB]
remote:        Get:14 http://archive.ubuntu.com trusty/universe amd64 Packages [5,859 kB]
remote:        Get:15 http://apt.postgresql.org trusty-pgdg/main amd64 Packages [58.3 kB]
remote:        Get:16 http://archive.ubuntu.com trusty/main Translation-en [762 kB]
remote:        Get:17 http://archive.ubuntu.com trusty/universe Translation-en [4,089 kB]
remote:        Ign http://archive.ubuntu.com trusty/main Translation-en_US
remote:        Ign http://archive.ubuntu.com trusty/universe Translation-en_US
remote:        Ign http://apt.postgresql.org trusty-pgdg/main Translation-en_US
remote:        Ign http://apt.postgresql.org trusty-pgdg/main Translation-en
remote:        Fetched 14.2 MB in 8s (1,713 kB/s)
remote:        Reading package lists...
remote: cat: /tmp/build_ca83753a2c356ce77716ce4c09e3c52c/Aptfile: No such file or directory
remote: ls: cannot access /app/tmp/cache/apt/cache/archives/*.deb: No such file or directory
remote: -----> Writing profile script
remote: It looks like you're deploying on a stack (currently set to *lucid64*) that's not supported by this buildpack.
remote: That could be because you're using a recent buildpack release on a deprecated stack.
remote: If you're using the buildpack installed by your CF admin, please let your admin know you saw this error message.
remote: If you at one point specified a buildpack that's at git URL, please make sure you're pointed at a version that supports this stack.
remote: 
remote:  !     Push rejected, failed to compile Swift app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to kituraheroku.
remote: 
To https://git.heroku.com/kituraheroku.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/kituraheroku.git'
```

**Comment by ElderFain** [comment]
I ran into the same issue.  I worked around it by tweaking the build pack to manually install the packages instead of using the Aptfile (apt-get --assume-yes install systemtap-sdt-dev libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev libbsd-dev libhttp-parser-dev libcurl4-openssl-dev libhiredis-dev).

I also had to bump my .Package, as 0.6 didn't like Swift 3.

.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 8)

Give that a try and see how it works?

**Comment by dfirsht** [comment]
@rfdickerson Can we get a followup on this?

**Comment by rfdickerson** [comment]
@ElderFain and I were talking about it quite a bit on Gitter the other day. I have not heard an update in a while. Interested to see if the buildpack works for them there.

**Comment by FWDavide** [comment]
Hi, is there any update related to this item ?
I've tried a deployment on Heroku but the libraries marked as pre-requirements are not part of the Heroku standard image.

An hard workaround could be to compile them from source and then reconcile them in the App's path, but before taking that route I'd be interested to know if someone had successfully deployed to Heroku in another way.

**Comment by ElderFain** [comment]
Been busy with some other things, I'm picking this back up to see where we are.

**Comment by dfirsht** [comment]
I'm closing this as this is a stale issue and the environment has changed substantially since this was opened. If you are still working on this and having problems @ElderFain, feel free to open another issue.

**Comment by greggmojica** [comment]
Still having this issue....

**Comment by rfdickerson** [comment]
Woah, for some reason on Heroku it is still using Lucid? 10.04?? 

I don't think it's possible to compile Swift code on that distribution. (Because of the clang version).

I think there's a way to use 16.04, or 14.04 for your deployments.

**Comment by greggmojica** [comment]
Hey @rfdickerson could you detail how to deploy 16.04 further? thanks

**Comment by byt3smith** [comment]
The default distribution for Heroku is Ubuntu 14.04. 10.04 is deprecated.

https://devcenter.heroku.com/articles/stack

**Comment by rfdickerson** [comment]
Has anyone deployed Kitura to Heroku successfully yet?

**Comment by byt3smith** [comment]
@rfdickerson I am working on it. Will report back when successful

**Comment by byt3smith** [comment]
Working example with Deploy button: https://github.com/byt3smith/kitura-on-heroku

It is just the Kitura getting started app, but the concept should scale to production apps

**Comment by rfdickerson** [comment]
@byt3smith Wow! This is pretty neat. Looks pretty easy- all you have to do differently from Bluemix is just use the ENV var `PORT`.

**Comment by vadimeisenbergibm** [comment]
@rfdickerson `PORT` will work for Cloud Foundry/Bluemix as well.

BTW, @byt3smith you can use `Foundation.ProcessInfo` to get `PORT`.

```swift
import Foundation
...
let port = Int(ProcessInfo.processInfo.environment["PORT"] ?? "8090") ?? 8090
```

**Comment by byt3smith** [comment]
@vadimeisenbergibm Reflected that in the example, thanks for the suggestion 😃

**Comment by vadimeisenbergibm** [comment]
@byt3smith You are welcome - now you app can run both locally (without $PORT being set) and on heroku.
