### ISSUE TITLE
Generated XCode project cannot find /usr/local libraries

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#354]
I have generated the latest Swift Package Manager (04-11), and many of the issues of (03-24) snapshot regarding C module maps not being in the search paths have been resolved. However, we still have a problem. Right now the `swift build --generate-xcodeproj` does not add `/usr/local/include` to the header search paths, and `/usr/local/lib` to the linker search paths. Therefore, we still have an issue with a manual step in setting up XCode properly.

**Possible fix:**

Take the suggested route that SPM describes for system libraries- use absolute paths in the modulemaps. Note, they acknowledge the fact that cross-platform environments this is problematic. Therefore, many people have turned to do platform checking in the Package.swift file and load in a different version of the modulemap depending on the platform. Specifically, use `/usr/local/include` for Mac OS and `/usr/include` for Linux. 

**Pros**

- `--generate-xcodeproj` 'just works'. You don't have to do anything manual
- Mac OS builds on command line can just use `swift build` not `swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib`

**Negatives:**

- Buildpacks. If we turn to absolute paths, then we need to point our builds on Bluemix to point to /home/user/.apt/usr/include which is in the client library.

**Assumptions:**

- Mac OS X users will be using Homebrew for installation of system level packages, therefore it will be installed to /usr/local. not /opt/ 
- Linux - Users have root and can install to /usr/include and /usr/lib

**Changes to SPM**

There is a [proposal currently under review](https://github.com/apple/swift-evolution/blob/master/proposals/0063-swiftpm-system-module-search-paths.md) by Apple regarding module map search paths. I hope we can zero in on a solution. I believe a summary of the changes are to use pkg-config to find module maps. Also, to make recommendations to the users of how to install the package if they don't already have it. It will tell you to run `apt-get install libcurl` for instance. What I worry about, however is that pkg-config probably won't find the libraries if installed at a user-level directory prefix like `/home/rfdickerson/libcurl/include`.

**Comment by rfdickerson** [comment]
I recommend we wait for the outcome of [SE-0063](https://github.com/apple/swift-evolution/blob/master/proposals/0063-swiftpm-system-module-search-paths.md) and see how we should proceed.

**Comment by rfdickerson** [comment]
This is huge, [SwiftPM System Module Search Paths](https://github.com/apple/swift-evolution/blob/master/proposals/0063-swiftpm-system-module-search-paths.md) has been accepted!

**Comment by rfdickerson** [comment]
Just an update the pkg-config patches have been merged in.

https://github.com/apple/swift-package-manager/commit/7bb14b22df8ef0c5b8d8814e5d2ed1e6733ac9b9

**Comment by rfdickerson** [comment]
Update using 04-25 libraries on Kitura-TodoList:

`swift build -X`, and then compiling the XCode project still fails. However with this very simple change, it will compile, and no additional changes are needed to the XCode project:

**CHttpParser/shim.h:**

```
#if __APPLE__
#include </usr/local/include/http_parser.h>
#elif __linux
#include </usr/include/http_parser.h>
#endif
```

The thing that I'm worried about are buildpacks.

**Comment by rfdickerson** [comment]
Opened a PR regarding the pkg-config and Xcode project generation not working well together yet:

https://bugs.swift.org/browse/SR-1368

**Comment by rfdickerson** [comment]
@goloveychuk submitted pull request:

https://github.com/apple/swift-package-manager/pull/300

**Comment by dfirsht** [comment]
This seems to have been fixed in the 05/03 snapshot. Can we close @rfdickerson?

**Comment by rfdickerson** [comment]
Yep! That's been resolved.
