### ISSUE TITLE
Providing Samples for Kitura

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#356]
This is an epic for issues related to Kitura sample apps, like https://github.com/IBM-Swift/Kitura-Sample

**Comment by rfdickerson** [comment]
What kind of samples are you imagining?

**Comment by vadimeisenbergibm** [comment]
@rfdickerson I have updated the epic description.

**Comment by christiancompton** [comment]
Closing as complete.
