### ISSUE TITLE
Create extensions on String, NSCache, NSDate, etc for Mac/Linux Foundation API differences.

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#359]
Currently, we have platform-specific checking scattered around a lot of our code. Beyond hurting code quality and readability, it makes it very hard to keep track of these special case usage if it's everywhere in our codebase. We should instead, try to keep these in contained files:

String.swift
NSCache.swift
NSDate.swift

Inside, we can have extensions that are applied if the user is running on Linux in order to migrate them to the newer set of APIs. Developers will therefore use the latest (03-24 API) and the extensions will map the call to the older API if the user is running in Linux.

Once the Foundation library reaches parity with the newer APIs, we can simply remove these extensions from our codebase.

**Comment by rfdickerson** [comment]
Ok, new plan:

- Reach out to mailing list and see if there is a timeframe for migrating to the new API
- If no plans, and no current PRs, then work on making the API migration directly to corelibs-foundation.

**Comment by rfdickerson** [comment]
Update:

> Hi Robert,
> 
> This is something we really do need some help with. Our goal is to have the Linux version match the Darwin version exactly.
> 
> There is also a PR up to change some of the results of the automatic renaming by the importer, here:
> 
> https://github.com/apple/swift/pull/2093
> 
> So we should take those into account as well.
> 
> - Tony

**Comment by dfirsht** [comment]
It seems as if the API differences are already being taken care of. In order to avoid creating throw away code, we are just going to wait and delete the Linux specific code when we can.
