### ISSUE TITLE
Remove adding of -I parameters for modulemap files on Linux

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#360]
There used to be an issue around swift test finding all of the modulemap files from the swift build step.

This is no longer the case.

**Comment by shmuelk** [comment]
Tested by rerunning a Kitura Travis CI build, which passed.

**Comment by shmuelk** [comment]
@dfirsht Please validate

**Comment by dfirsht** [comment]
Can we delete the make_ccflags_for_module_maps script?

**Comment by shmuelk** [comment]
To be honest I don't see why not?

Opinions anyone?

**Comment by dfirsht** [comment]
I think we should, keep things lean.

**Comment by rfdickerson** [comment]
Yeah, let's no keep things around we aren't using any longer.

**Comment by dfirsht** [comment]
Validated.
