### ISSUE TITLE
Migrate to 4/12 swift binaries

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#361]
- [x] LoggerAPI
- [x] SwiftyJSON
- [x] KituraSys
- [x] KituraNet
- [x] Kitura
- [ ] KituraSample
- [x] CouchDB
- [x] Redis
- [ ] KituraCredentials....
- [ ] KituraSession
- [ ] GRMustache
- [ ] KituraTemplateEngine

**Comment by dfirsht** [comment]
At this point we are unable to switch to the 4/12 binaries because of issues with running certain tests on Linux (see https://bugs.swift.org/browse/SR-1243). We will merge the 4/12_migration branches and switch over once this gets resolved.

**Comment by rfdickerson** [comment]
We need to identify exactly what the problem is with XCTests in Linux. I don't think it's as simple as "it's broken" in this snapshot.

**Comment by dfirsht** [comment]
@rfdickerson yes, that discussion to figure this out is happening on the Swift bug I posted. We'll be taking an active role in figuring this out and getting this issue unblocked ASAP.

**Comment by rfdickerson** [comment]
FYI, my latest compile of 4/24 migration still has a LoggerAPI dependency graph error.

**Comment by dfirsht** [comment]
We are skipping 4/12 to migrate to 4/25, 4/12 will not be supported.
