### ISSUE TITLE
Add support for Swift DEV-SNAPSHOT 2016-04-12

### ISSUE THREAD

**Issue by norbertfuhs** [IBM-Swift/Kitura#363]
Hi, i use the latest dev-snapshot binary on ubuntu
Swift version 3.0-dev (LLVM 752e1430fc, Clang 3987718dae, Swift 36739f7b57)
When i try the to follow the tutorial i get the following at step 8:

noby@Jupiter:~/Swift-Code/Kitura$ swift build -Xcc -fblocks
Cloning https://github.com/IBM-Swift/Kitura.git
Resolved version: 0.9.1
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolved version: 0.9.0
Cloning https://github.com/IBM-Swift/Kitura-sys.git
Resolved version: 0.7.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolved version: 0.4.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolved version: 0.3.5
Cloning https://github.com/IBM-Swift/CCurl.git
Resolved version: 0.0.1
Cloning https://github.com/IBM-Swift/CHttpParser.git
Resolved version: 0.0.2
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolved version: 5.0.0
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolved version: 0.9.0
<unknown>:0: error: missing input '/home/noby/Swift-Code/Kitura/.build/debug/Kitura.build/main.swift.o' and no rule to build it
Compiling Swift Module 'LoggerAPI' (1 sources)
Compiling Swift Module 'Socket' (3 sources)
Compiling Swift Module 'SwiftyJSON' (2 sources)
Compiling Swift Module 'KituraTemplateEngine' (1 sources)
/home/noby/Swift-Code/Kitura/Packages/LoggerAPI-0.4.0/Sources/LoggerAPI/Logger.swift:39:24: error: missing argument label 'type:' in call
            logger?.log( .Verbose, msg: msg,
                       ^
                         type: 
/home/noby/Swift-Code/Kitura/Packages/LoggerAPI-0.4.0/Sources/LoggerAPI/Logger.swift:45:24: error: missing argument label 'type:' in call
            logger?.log( .Info, msg: msg,
                       ^
                         type: 
/home/noby/Swift-Code/Kitura/Packages/LoggerAPI-0.4.0/Sources/LoggerAPI/Logger.swift:51:24: error: missing argument label 'type:' in call
            logger?.log( .Warning, msg: msg,
                       ^
                         type: 
/home/noby/Swift-Code/Kitura/Packages/LoggerAPI-0.4.0/Sources/LoggerAPI/Logger.swift:57:24: error: missing argument label 'type:' in call
            logger?.log( .Error, msg: msg,
                       ^
                         type: 
/home/noby/Swift-Code/Kitura/Packages/LoggerAPI-0.4.0/Sources/LoggerAPI/Logger.swift:63:24: error: missing argument label 'type:' in call
            logger?.log( .Warning, msg: msg,
                       ^
                         type: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:97:42: error: missing argument label 'obj:' in call
        return isValidJSONObjectInternal(obj)
                                         ^
                                         obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:104:22: error: missing argument label 'obj:' in call
        try writeJson(obj, options: options) { (str: NSString?) in
                     ^
                      obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:118:27: error: missing argument label 'obj:' in call
        try writeJsonValue(obj, padding: padding, writer: writer)
                          ^
                           obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:135:42: error: missing argument label 'number:' in call
            writer(JSON.stringFromNumber(obj as! NSNumber).bridge())
                                         ^
                                         number: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:143:35: error: missing argument label 'obj:' in call
                try writeJsonArray(mirror.children.map { $0.value as Any }, padding: padding, writer: writer)
                                  ^
                                   obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:146:36: error: missing argument label 'pairs:' in call
                try writeJsonObject(mirror.children.map { $0.value }, padding: padding, writer: writer)
                                   ^
                                    pairs: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:150:40: error: missing argument label 'reason:' in call
                throw createWriteError("Unsupported data type to be written out as JSON")
                                       ^
                                       reason: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:157:68: error: missing argument label 'padding:' in call
        let (nestedPadding, startOfLine, endOfLine) = setupPadding(padding)
                                                                   ^
                                                                   padding: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:190:68: error: missing argument label 'padding:' in call
        let (nestedPadding, startOfLine, endOfLine) = setupPadding(padding)
                                                                   ^
                                                                   padding: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:56:53: error: missing argument label 'obj:' in call
                    guard isValidJSONObjectInternal(element.value) else {
                                                    ^
                                                    obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/LclJSONSerialization.swift:69:61: error: missing argument label 'obj:' in call
                            guard isValidJSONObjectInternal(generator.next()!.value) else {
                                                            ^
                                                            obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:185:54: error: missing argument label 'newValue:' in call
            let (type, value) = self.setObjectHelper(newValue)
                                                     ^
                                                     newValue: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:253:46: error: missing argument label 'pairs:' in call
              let elems = convertToKeyValues(children)
                                             ^
                                             pairs: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:847:54: error: missing argument label 'obj:' in call
        guard LclJSONSerialization.isValidJSONObject(self.object) else {
                                                     ^
                                                     obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:850:59: error: missing argument label 'obj:' in call
        return try LclJSONSerialization.dataWithJSONObject(self.object, options: opt)
                                                          ^
                                                           obj: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:873:42: error: missing argument label 'number:' in call
            return JSON.stringFromNumber(self.rawNumber)
                                         ^
                                         number: 
/home/noby/Swift-Code/Kitura/Packages/SwiftyJSON-5.0.0/Source/SwiftyJSON.swift:1154:46: error: missing argument label 'number:' in call
                return JSON.stringFromNumber(self.object as! NSNumber)
                                             ^
                                             number: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:645:35: warning: extraneous duplicate parameter name; 'family' already has an argument label
        public class func makeConfigured(family family: ProtocolFamily, type: SocketType, proto: SocketProtocol) throws -> Socket {
                                         ^~~~~~~
                                         
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:680:29: warning: extraneous duplicate parameter name; 'nativeHandle' already has an argument label
        public class func makeFrom(nativeHandle nativeHandle: Int32, address: Address?) throws -> Socket {
                                   ^~~~~~~~~~~~~
                                   
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:346:48: error: missing argument label 'value:' in call
                        guard let family = ProtocolFamily.getFamily(protocolFamily),
                                                                    ^
                                                                    value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:347:35: error: missing argument label 'value:' in call
                                let type = SocketType.getType(socketType),
                                                              ^
                                                              value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:348:42: error: missing argument label 'value:' in call
                                let pro = SocketProtocol.getProtocol(proto) else {
                                                                     ^
                                                                     value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:407:48: error: missing argument label 'value:' in call
                        guard let family = ProtocolFamily.getFamily(protocolFamily),
                                                                    ^
                                                                    value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:408:35: error: missing argument label 'value:' in call
                                let type = SocketType.getType(socketType),
                                                              ^
                                                              value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:409:42: error: missing argument label 'value:' in call
                                let pro = SocketProtocol.getProtocol(proto),
                                                                     ^
                                                                     value: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:535:19: error: value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>') can never be nil, comparison isn't allowed
                                if readBuffer != nil {
                                   ~~~~~~~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1103:63: error: cannot pass immutable value as inout argument: implicit conversion from 'UnsafeMutablePointer<addrinfo>' to 'UnsafeMutablePointer<addrinfo>?' requires a temporary
                var status: Int32 = getaddrinfo(host, String(port), &hints, &targetInfo)
                                                                            ^~~~~~~~~~~
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1126:15: error: value of type 'UnsafeMutablePointer<addrinfo>' can never be nil, comparison isn't allowed
                while (info != nil) {
                       ~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1280:10: error: missing argument label 'set:' in call
                fdZero(&readfds)
                       ^
                       set: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1281:8: error: missing argument label 'fd:' in call
                fdSet(self.socketfd, set: &readfds)
                     ^
                      fd: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1284:10: error: missing argument label 'set:' in call
                fdZero(&writefds)
                       ^
                       set: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1285:8: error: missing argument label 'fd:' in call
                fdSet(self.socketfd, set: &writefds)
                     ^
                      fd: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1300:18: error: missing argument label 'fd:' in call
                return (fdIsSet(self.socketfd, set: &readfds), fdIsSet(self.socketfd, set: &writefds))
                               ^
                                fd: 
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1372:62: error: cannot pass immutable value as inout argument: implicit conversion from 'UnsafeMutablePointer<addrinfo>' to 'UnsafeMutablePointer<addrinfo>?' requires a temporary
                let status: Int32 = getaddrinfo(nil, String(port), &hints, &targetInfo)
                                                                           ^~~~~~~~~~~
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1394:15: error: value of type 'UnsafeMutablePointer<addrinfo>' can never be nil, comparison isn't allowed
                while (info != nil) {
                       ~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1479:13: error: value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>') can never be nil, comparison isn't allowed
                if buffer == nil || bufSize == 0 {
                   ~~~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1634:13: error: value of type 'UnsafePointer<Void>' (aka 'UnsafePointer<()>') can never be nil, comparison isn't allowed
                if buffer == nil || bufSize == 0 {
                   ~~~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1728:28: error: value of optional type 'UnsafePointer<CodeUnit>?' not unwrapped; did you mean to use '!' or '?'?
                        try self.write(from: $0.baseAddress, bufSize: $0.count-1)
                                                ^
                                                           !
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1773:22: error: value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>') can never be nil, comparison isn't allowed
                if self.readBuffer != nil {
                   ~~~~~~~~~~~~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1118:18: error: value of type 'UnsafeMutablePointer<addrinfo>' can never be nil, comparison isn't allowed
                        if targetInfo != nil {
                           ~~~~~~~~~~ ^
/home/noby/Swift-Code/Kitura/Packages/Socket-0.3.5/Sources/Socket.swift:1387:18: error: value of type 'UnsafeMutablePointer<addrinfo>' can never be nil, comparison isn't allowed
                        if targetInfo != nil {
                           ~~~~~~~~~~ ^
<unknown>:0: error: build had 3 command failures
error: exit(1): /home/noby/Swift/usr/bin/swift-build-tool -f /home/noby/Swift-Code/Kitura/.build/debug.yaml default


Do i got this issue bescause I m using the latest trunk version?

**Comment by dfirsht** [comment]
Yes we only support 3/24 snapshot right now. We are working on migrating to 4/12, see #361.

**Comment by norbertfuhs** [comment]
Okay thanks for the help! I will try it again with the 3/24 snapshot
