### ISSUE TITLE
Create a Mac OS X continuous integration pipeline in Travis

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#366]
Travis CI supports the build matrix for cross-platform builds. 

We can add an additional pipeline to test if Kitura builds on Mac OS (XCode 7.3). I have figured out a way to easily use the Mac OS OS, pull down the 04-12-DEVELOPMENT snapshot and use it to `swift build` and `swift test` the current project.

https://github.com/IBM-Swift/HeliumLogger/issues/3

**Comment by dfirsht** [comment]
@rfdickerson I am not sure I understand what this issue is about, are you saying you want to do CI in OS X in differently? How does it give an advantage over our current pipeline?

**Comment by rfdickerson** [comment]
Good question, and totally understand given that we do a build in Mac OS as well, but aren't we using our own slave for Mac OS builds not the Travis' XCode 7.3 environment? This also relates to #137 . I see the build process going:

1. Use the native Travis CI XCode 7.3 image 
2. Install Mac OS 4-12 toolchain
3. Install Homebrew
4. Install Homebrew dependencies
5. Run 'swift build'
6. Run 'swift build -X' (to generate XCode Project)
7. Run 'xcodebuild -project XX -scheme XX -enableCodeCoverage YES clean build test
8. Submit results to codecov

**Comment by dfirsht** [comment]
We are currently using the native Travis CI image. Codecov is in our backlog and can be tracked in the issue mentioned.
