### ISSUE TITLE
Building Kitura Example App

### ISSUE THREAD

**Issue by elbandito** [IBM-Swift/Kitura#367]
Sorry to bother with what I suspect might be a trivial issue, but I'm getting desperate. I'm trying to build the example app.  Here's what I'm seeing:

```$ swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib
error: system(["/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/bin/swiftc", "--driver-mode=swift", "-I", "/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/lib/swift/pm", "-L", "/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/lib/swift/pm", "-lPackageDescription", "-target", "x86_64-apple-macosx10.10", "/Users/test/workspace/hello-swift/Package.swift", "-fileno", "3"], posix_spawn error: No such file or directory (2), `["/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/bin/swiftc", "--driver-mode=swift", "-I", "/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/lib/swift/pm", "-L", "/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/lib/swift/pm", "-lPackageDescription", "-target", "x86_64-apple-macosx10.10", "/Users/test/workspace/hello-swift/Package.swift", "-fileno", "3"]`)```

I copied the contents for the "Package.swift" and "Sources/main.swift", so as far as I can tell, the code is solid.  Does anyone have any tips?

Thanks,
Travis

**Comment by rfdickerson** [comment]
I'm curious, can you build even the simplest of apps using the 04-12 snapshot? I have seen numerous other people having problems with their installations seeing similar issues.

**Comment by vadimeisenbergibm** [comment]
`No such file or directory` seems like something is missing in your swift installation. Did you install both "Xcode" and "Debugging Symbols" links from swift.org Downloads section?

To diagnose the problem run the following commands and let us know their output:
which swift
which swiftc
swift --version
swiftc --version
swift # run REPL - see if it starts

**Comment by elbandito** [comment]
Thanks for the help guys, here's the output of the commands you asked about.

$ which swift
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/bin/swift

$ which swiftc
/usr/bin/swiftc

$ swift --version
Apple Swift version 3.0-dev (LLVM 752e1430fc, Clang 3987718dae, Swift 36739f7b57)
Target: x86_64-apple-macosx10.9

$ swiftc --version
Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
Target: x86_64-apple-macosx10.9

**Comment by vadimeisenbergibm** [comment]
The problem probably happens due to the fact that you installed "Debugging Symbols" package and not installed the swift package itself.
The snapshot appears as two links on swift.org Download page: "Xcode" and "Debugging Symbols", which point to
swift-DEVELOPMENT-SNAPSHOT-<snapshot date>-a-osx.pkg and swift-DEVELOPMENT-SNAPSHOT-<snapshot date>-a-osx-symbols.pkg, respectively.
 
If you install swift-DEVELOPMENT-SNAPSHOT-<snapshot date>-a-osx-symbols.pkg only, you get the Toolchain with swift executable and without swiftc, and this swift executable will fail to run as REPL. You have to install swift-DEVELOPMENT-SNAPSHOT-<snapshot date>-a-osx.pkg.

**Comment by shmuelk** [comment]
You have two issues:

    1. You installed the 04/12 version of Swift into your toolchains. We don't support that version of Swift quite yet. We are actively working on that.

    2. You didn't update your path to point to what ever version of swift you downloaded into your toolchain.

**Comment by elbandito** [comment]
@vadimeisenbergibm thanks for pointing out there are 2 links in the downloads!

@shmuelk what's the recommended version of swift that I should download?

**Comment by vadimeisenbergibm** [comment]
Kitura is compiled with March, 24 version. You can download it from here - https://swift.org/download/#older-snapshots

**Comment by elbandito** [comment]
Works great!  Thanks again, everyone!
