### ISSUE TITLE
Consider refactoring shortened names into long names

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#370]
Working on renaming functions for 4/12 snapshot, I would like to use this opportunity to consider getting rid of shortened names in our code.

Personally, I prefer always using full names, in both public APIs and in the implementation. 

I never saw a shortened name in Apple Swift public API, e.g. [NSTask](https://github.com/apple/swift-corelibs-foundation/blob/e3a860e1b8035c37c1027c78a44ed81cb3291525/Foundation/NSTask.swift)
```swift 
    public var arguments: [String]?
    public var environment: [String : String]? // if not set, use current
```
However, in the same class, implementation does use shortened names like `argv`, `args`, `envp`, `env`, `nenv`.
```
            for arg in argv ..< argv + args.count {
                free(UnsafeMutablePointer<Void>(arg.pointee))
            }
       
            argv.deallocateCapacity(args.count + 1)
        }
        
        let envp: UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>
        
        if let env = environment {
             let nenv = env.count
```

I, personally, do not like this shortened names style, however, implementation is less important than API. I like the following sentence of Apple from [Apple API guidelines](https://swift.org/documentation/api-design-guidelines/#fundamentals):
> Clarity is more important than brevity. Although Swift code can be compact, it is a non-goal to enable the smallest possible code with the fewest characters. Brevity in Swift code, where it occurs, is a side-effect of the strong type system and features that naturally reduce boilerplate.

In general, I think it is important that in addition to providing rich functionality, being secure and bug-less, our code should look beautiful and modern.

I propose that we decide on the conventions, follow them and refactor the code accordingly:
1. We allow/do not allow shortened names in APIs.
2. We allow/do not allow shortened names in implementation.

**Comment by dfirsht** [comment]
This was done as part of issue #473. If there are specific names that still should be refactored, we should open individual issues on those.
