### ISSUE TITLE
Integrate NSHTTPUrlResponse status codes into Http.swift

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#372]
I was looking through the commit history and saw @ianpartridge commit to Foundation. Maybe at some point we can get the status codes in to Http.swift from Foundation?

https://github.com/apple/swift-corelibs-foundation/commit/4fb767c6580b36735d9edb5f0ab9841eb7bc6419

https://github.com/IBM-Swift/Kitura-net/blob/master/Sources/KituraNet/Http.swift

**Comment by ianpartridge** [comment]
I can do this.

**Comment by rfdickerson** [comment]
Great, probably will need to coordinate with @dfirsht on this. Plus, we will have to wait until this merge makes its way into the snapshot.

**Comment by youming-lin** [comment]
I can pick this up.

@ianpartridge @rfdickerson What exactly needs to be done for this issue?

**Comment by ianpartridge** [comment]
Delete this:

https://github.com/IBM-Swift/Kitura-net/blob/master/Sources/KituraNet/HTTP/HTTP.swift#L25

and use `HTTPURLResponse.localizedStringForStatusCode()` instead.

**Comment by youming-lin** [comment]
@ianpartridge Would [these instances](https://github.com/search?q=org%3AIBM-Swift+statusCodes&ref=searchresults&type=Code&utf8=%E2%9C%93) be all the places that need to be changed if I remove that line?

**Comment by ianpartridge** [comment]
Hmm, thinking about this more, it's more complicated. Now that Kitura-net is 1.0 we can't just remove the public API without tagging 2.0 and updating dependencies to use that instead. Which we probably don't want to do.

**Comment by christiancompton** [comment]
Closing - Reopen as needed.
