### ISSUE TITLE
Kitura does not serve its static content when running on a CF environment (e.g. Bluemix).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#375]
Once the compilation phase completes (of a buildpack), everything that is included in the build folder is packaged up by CF and included into the droplet. As reference, see:
- http://mikusa.blogspot.com/2013/11/cloudfoundry-build-packs-introduction.html
- http://blog.altoros.com/creating-a-custom-cloud-foundry-buildpack-from-scratch-whats-under-the-hood.html

This has the following implication: the let fileName = NSString(string: #file) line in the Router.getResourceFilePath() method produces a path that will not be valid at runtime (if running on CF). When running on CF, the fileName variable contains a path that is valid at compilation time but not at runtime since all the files are now in a different folder inside the droplet.

As a work-around to this problem, the following the logic in the Router.getResourceFilePath() method could be implemented:

- Before returning the filePath from this method, it should verify if it indeed exists:

let fileManager = NSFileManager.defaultManager()
if fileManager.fileExistsAtPath(fileName) {
   return filePath
} else {
   // do another attempt at finding the resources folder
}

If filePath does not exist, then Router.getResourceFilePath() could do one more attempt at finding the resources folder:

let workingDir = fileManager.currentDirectoryPath
let kituraPackageName = … // need logic to determine at runtime the Kitura package name (e..g "Kitura-6.0.0”)
filePath = "\(workingDir)/Packages/\(kituraPackageName)/Sources/Kitura/resources”
if fileManager.fileExistsAtPath("\(workingDir)/Packages/\(kituraPackageName)/Sources/Kitura/resources”) {
     return filePath
} 

The above logic would work on CF environments (I have verified that fileManager.currentDirectoryPath returns the expected workingDir which contains the Packages folder).

Thoughts?

**Comment by shmuelk** [comment]
It also contains everything else in the original repository as well?

**Comment by rolivieri** [comment]
@shmuelk Correct, the folder returned from executing fileManager.currentDirectoryPath (when running on CF) contains the Swift Package repo (e.g. Kitura sample app) that was pushed along with the Packages folder generated by the swift build command.

**Comment by dfirsht** [comment]
@rolivieri Please validate.

**Comment by rolivieri** [comment]
It works now!
