### ISSUE TITLE
Combine all appends in RouterElement to one of for each scope

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#378]
https://github.com/IBM-Swift/Kitura/tree/develop/Sources/Kitura/RouterElement.swift#L300

**Comment by NikitaSullivan** [comment]
Issue update from @dfirsht "the code got moved around so look instead at RouteRegex.swift#L167. These append statements can be reduced to 1 line per case. For example the first one can be: regexStr.append("/\(prefix)(\(matchExp)(?:/\(matchExp))*)")"

**Comment by dfirsht** [comment]
I think the commit above was removed? I don't see these changes on develop.

**Comment by dfirsht** [comment]
Validated.
