### ISSUE TITLE
Group RouterMethod cases based on similarities and break case statement into shorter lines

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#385]
https://github.com/IBM-Swift/Kitura/tree/develop/Sources/Kitura/RouterElement.swift#L407

**Comment by NikitaSullivan** [comment]
Issue update from @dfirsht "I think it will be fine to just break it up into readable lines."

**Comment by NikitaSullivan** [comment]
change added in commit: 5f2dca6c74df628361e2e07151b2dddedaa8e8e0

**Comment by dfirsht** [comment]
Validated.
