### ISSUE TITLE
Remove getter/setter methods of statusCode in RouterResponse and instead use a computed property

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#388]
https://github.com/IBM-Swift/Kitura/tree/develop/Sources/Kitura/RouterResponse.swift#L240-279

**Comment by dfirsht** [comment]
Question for this: currently we have code like `router.status(.OK).send("foo")` all over the place. With this change we'd need to break this up into `router.status = .OK; router.send("foo")`. Are we ok in making this more verbose?

**Comment by rfdickerson** [comment]
Oh, good point. I guess not.

**Comment by dfirsht** [comment]
Ok well maybe we can do the other changes but keep the status method (although it should probably be renamed to setStatus)

**Comment by dfirsht** [comment]
@shmuelk Can you validate this?

**Comment by shmuelk** [comment]
Reviewed code. Looks OK.
