### ISSUE TITLE
Change ContentType to a singleton pattern

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#392]
https://github.com/IBM-Swift/Kitura/tree/develop/Sources/Kitura/contentType/ContentType.swift#L

**Comment by dfirsht** [comment]
@rfdickerson Please validate.

**Comment by shmuelk** [comment]
Reviewed the code. I think you should delete the print statement in TestContentType.swift at about line 32.

**Comment by dfirsht** [comment]
Sure, I didn't add it but I can certainly delete it.

**Comment by shmuelk** [comment]
Reviewed last change
