### ISSUE TITLE
Why readme explicit tells users to install curl for OSX?

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/Kitura#396]
In the Readme.md

The section for OSX
Install the necessary dependencies:
conatins the following:
```
brew install http-parser curl hiredis
```
Why is curl need to be re-install, I had impression that curl comes with OSX, is the one that comes with OSX not good and Kitura requires a newer version?

**Comment by ianpartridge** [comment]
I believe the version in OS X is quite backlevel.  That might be why the `brew` requirement is there. @rfdickerson ?

**Comment by dfirsht** [comment]
OSX does come with curl. It's mostly there as a "just in case" and to make sure the user has the latest version. You probably could get away with just using the preinstalled curl.
