### ISSUE TITLE
Improve API for setting content type for the response

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#397]
In Java (using JAX-RS), it’s very simple to specify the content type for the response. For instance, to specify application/json as the content type, it just requires this:

@Produces(MediaType.APPLICATION_JSON)

To achieve the same in Kitura, you need a line like this:

response.setHeader("Content-Type", value: "application/json; charset=utf-8")

The above line is prone to errors. The developer may type the wrong type of value.

Swift does not have annotations so the same approach we have in Java cannot be used… but how about providing an API (maybe in the response class) that allows the developer specify the type for the response this way?

response.setType(Type.APPLICATION_JSON)

where Type.APPLICATION_JSON is a predefined type.

**Comment by ianpartridge** [comment]
Express has `response.set('Content-Type', 'application/json');`

I guess the concern with adding `setType()` is we could end up with a whole bunch of helper methods on `response` - one for each HTTP header.  And that would make the API surface unwieldy.

**Comment by rolivieri** [comment]
That's a good point... and our API [after all] is closer to Express than to anything else.

**Comment by dfirsht** [comment]
We could have a set type function with a Type enum. @rolivieri is there a list of types that JAX-RS supports?

**Comment by rolivieri** [comment]
Check out this javadoc: http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/MediaType.html

**Comment by dfirsht** [comment]
Looks like there are 14 types from that doc. If that really does do a good job with covering use cases, I would be in favor of doing this.

**Comment by shmuelk** [comment]
But the programmer can simply use the ContentType functions to convert "json" to "application/json; charset=utf-8", same thing for "html", "jpg", etc.

**Comment by dfirsht** [comment]
This function already exists, called `type` completed in issue #336
