### ISSUE TITLE
Add capability to Kitura-net for making outbound HTTPs calls.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#401]

**Comment by rfdickerson** [comment]
Maybe the awaiting to be merged NSURLSession will help?

**Comment by rolivieri** [comment]
I heard earlier today about that possibility but it does not seem like it will happen any time soon... because of the lack of libdispatch. :-/

Not having the capability for initiating outbound HTTPs connections would require some architectural changes to some of our demo apps. I can't remember if we have a rough estimate for the effort it would take for implementing this capability as a stopgap solution... probably not trivial.

**Comment by shmuelk** [comment]
Our current outbound HTTP client code supports HTTPS.

Look at https://github.com/IBM-Swift/Kitura-CredentialsFacebookToken/blob/master/Sources/CredentialsFacebookToken/CredentialsFacebookToken.swift for an example

**Comment by shmuelk** [comment]
There once was an issue in that if you didn't explicitly specify the port you got port 80.

That HAS been FIXED.

**Comment by shmuelk** [comment]
The advantages of using well constructed C code (libCurl) are immeasurable

**Comment by rolivieri** [comment]
Thanks @shmuelk for the good news. I must admit that this well constructed system level library saved the day!  :)
