### ISSUE TITLE
Consider extending swagger-codegen or Strongloop to create Kitura backend

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#402]
Swagger codegen project - https://github.com/swagger-api/swagger-codegen
To install it - run `brew install swagger-codegen`

To generate a client side swift library:
`swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l swift -o PetsSwift`

To generate nodejs project:
`swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l nodejs -o PetsNodejs`

**Comment by seabaylea** [comment]
Am I right in saying that swagger codegen requires you to have the Swagger definition already, and from that it can create client and/or server stubs?

Whilst this is valuable, its a REST API first approach. The approach that API Connect's builder takes is datamodel first - ie, it generates the server code and the Swagger definition for you based on what you want your server data model to be.

"REST first" and "data model first" are both useful use cases - we'll need to decide which to prioritize and whether there can be reuse between the two.

**Comment by vadimeisenbergibm** [comment]
@seabaylea Correct, swagger-codegen takes a Swagger definition as an input - in the examples above it is http://petstore.swagger.io/v2/swagger.json. The use case here: a developer is familiar with Swagger only and uses Swagger for defining their REST APIs. Currently, swagger-codegen generates swift client code for this developer. We can consider adding generation of Kitura server side code.

> "REST first" and "data model first" are both useful use cases - we'll need to decide which to prioritize and whether there can be reuse between the two.

I agree. The question is how many developers use each of the approaches.

**Comment by seabaylea** [comment]
If we're going after existing iOS devs, I would argue "data model first". For the wider (longer term) audience, then I would have thought "REST first" ;-)

**Comment by vadimeisenbergibm** [comment]
Actually, there is an option to generate Strongloop models from Swagger definitions, if I understand it correctly, https://docs.strongloop.com/display/public/LB/Swagger+generator. So instead of extending swagger-codegen, we can just extend Strongloop and cover both cases.

**Comment by vadimeisenbergibm** [comment]
Strongloop generator - https://github.com/strongloop/generator-loopback

**Comment by GilGS** [comment]
you can also generate a client side or a server side by using the web interface through the swagger editor itself:

https://cloud.githubusercontent.com/assets/19588849/16612225/865ad992-436e-11e6-8d4e-31a217280dac.png

**Comment by GilGS** [comment]
_**How to generate code from Swagger using Strongloop:**_

1. **install Strongloop:**
 $ npm install -g strongloop

2. **Create a new Loopback application:**
slc loopback

3. **Generate code from Swagger url or file:**
type - "slc loopback:swagger" and follow the instructions in the tool - enter the swagger spec url to be generated, choose the models you want to generate, select the data-source to attach models to, and that's it - the code will be generated under the same directory.

**Comment by seabaylea** [comment]
Work is already underway to implement Swift code-gem based on the Loopback implementation, and then using Swagger-codegen extensions to create the client side code.

@tunniclm is leading the work, and can provide more details.

**Comment by rfdickerson** [comment]
Hey @tunniclm - came late to the discussion. Why are using Yeoman versus using Swagger Codegen for the Swagger to Kitura stub generation?

http://swagger.io/swagger-codegen/

**Comment by vadimeisenbergibm** [comment]
@rfdickerson - couple of remarks. First please note that Swagger Codegen handles both client-side and server-side code generation. @tunniclm uses Yeoman for server-side code generation. Second, yeoman is a rather standard way to scaffold projects. Third, for yeoman you need npm + node.js, for Swagger Codegen you need mvn + Java.  I do not know if the last point is important, though.
