### ISSUE TITLE
Refactor header architecture

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#404]
In our current architecture we have two arrays, singleHeaders: [String: String] and multiHeaders:[String: [String]]. This is to accommodate the HTTP specification that there may be multiple header fields of the same name.

However this architecture means that we have to access header values through methods: setHeader, setHeaders, getHeader, getHeaders. This can be somewhat unintuitive.

I propose instead, we get rid of singleHeaders have a combined dictionary for headers of type [String: [String]] this gives a more unified approach and would allow us to get rid of getter/settter methods.
Ex. set:
```
header["foo"] = ["bar"]
header["foo"] = ["bar1,"bar2"]
```
Ex. get:
```
let values = header["foo"]
for value in values {
  // do something
}
```
I considered having the array be [String: HeaderValue] where HeaderValue was an enum which could hold either a String or an array of Strings but ultimately this resulted in having to call a switch every time a header was accessed which was clunky.

**Comment by rfdickerson** [comment]
Agreed. Take a look at SwiftX Headers- it's a simple Headers structure which is really just a wrapper around a dictionary.

**Comment by dfirsht** [comment]
In order to allow the structure to be case insensitive, I pushed a completely different architecture. In this architecture, the dictionary is hidden and accessed using getters and setters inside a `Headers` struct. When values are added, the Headers struct keeps a map of lowercase field names to actual fields. This can be used later to give case insensitive behaviors in getting and deleting values.

**Comment by dfirsht** [comment]
I would like to use this struct in the ServerRequest as well. The major difference is how we would handle adding duplicate headers. The current implementation has a specific set that it looks for and will refuse to merge. https://github.com/IBM-Swift/Kitura-net/blob/develop/Sources/KituraNet/IncomingMessage.swift#L477 I think that we should ignore this and simply add everything we can as an array. It would be up to the server developer to decide how to handle these duplicates. Thoughts?

**Comment by kweinmeister** [comment]
Additional edge cases need to be developed and tested before we merge these PRs

**Comment by dfirsht** [comment]
So I added the code back the Shmuel had about the test cases but I am now wondering if we are taking good advantage of always returning an array. Since "set-cookie" is the only header that cannot be merged, it seems weird that we are always returning an array for this edge case and a single value in every other case.

I think we should then do one of the following:
A) Separate Cookies into their own class. This is already done in Kitura, so doing it again in Kitura-net could make sense. This would make headers be a dictionary of strings to strings again.

B) Explode comma separated values into separate values in the array on behalf of the server writer. However we would keep them as one string for smaller writes to the client. `set-cookie` is an edge case here since commas can be present in the values.

Thoughts anyone? @rfdickerson @shmuelk
