### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#406]
Analyze the performance of Kitura on Linux versus Mac, and also its position relative to alternative implementations (in Swift or similar popular languages).  Identify performance issues and interop issues with popular community benchmarking tools / frameworks.

**Comment by ianpartridge** [comment]
@djones6 Does having this issue add value? We can't keep it open indefinitely, and performance is always going to be important. Can we just track specific issues?

**Comment by djones6** [comment]
@ianpartridge I do want a way to keep track of performance issues (past and present) but you're probably right that an indefinite epic isn't the right way to do it.  I'll investigate dashboards.
