### ISSUE TITLE
Wrk load driver classifies Kitura responses as read errors

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#407]
In the community web framework benchmarking project [bbmark](https://github.com/antonmes/bbmark/), the author [posted some results](https://github.com/antonmes/bbmark/blob/master/raw_linux.md) which implied very low performance for 3 out of the 4 Swift frameworks (Kitura included).  The load driver he used is [wrk](https://github.com/wg/wrk).

I've been digging into the cause of these poor scores.  When driving Kitura, wrk (prior to version 4.0.2) appears to send one request for each connection, and then goes into a high CPU loop where it issues no further requests.  This is presumably what Anton experienced and can be easily replicated.

With wrk version 4.0.2, load is generated, however the driver reports socket read errors totalling the number of requests.  I narrowed the change in behaviour down to [this commit](https://github.com/wg/wrk/commit/8bf0b2e3d34a4c0fca3fbd013b675d29794ce0a5), whereby when wrk attempts to read from the socket and receives zero bytes - yet the HTTP parser is not in the 'final' state (s_message_done as defined in [http_parser.c](https://github.com/wg/wrk/blob/master/src/http_parser.c)).  Since this code is in a do-while loop which would not attempt to continue reading when there are zero bytes remaining, I can only assume that the read method is being invoked a second time, on the same socket, expecting to start reading another response.

I [added some debug printf's to the wrk code](https://github.com/djones6/wrk_debug), to see how many bytes it reads from the socket, and how it parses the HTTP response.  There are two main differences:
With Zewo, wrk sends a 49-byte request, reads the response as a single 78-byte read, parses it successfully, and then sends the next 49-byte request (on the same connection).
With Kitura, wrk sends the same 49-byte request, then reads the response in multiple smaller reads (the first is usually 9 bytes but sometimes more, representing 'HTTP 1.1').  The number and size of these reads varies.  Once the full response has been read and parsed, wrk then attempts a further read from the socket.  This is the point where there are zero bytes remaining.

What is causing wrk to decide to do this?  In the Zewo case, its next action is to send a new request on the same connection.  With Kitura, it tries an additional read.  Is it somehow related to keep-alive (and possibly lack of?).

I've tried another workload driver - jmeter - which does not complain when driving Kitura. It seems 'wrk' may be being strict (too strict?) or maybe Kitura exposes a bug in the logic.

I think it is important to resolve this (whether that be in Kitura or wrk).

[zewo-wrk_debug.txt](https://github.com/IBM-Swift/Kitura/files/231837/zewo-wrk_debug.txt)
[kitura-wrk_debug.txt](https://github.com/IBM-Swift/Kitura/files/231838/kitura-wrk_debug.txt)

**Comment by djones6** [comment]
I'm not planning to revisit this until #435 is implemented, since I expect keep-alive may resolve it.

**Comment by shmuelk** [comment]
@djones6 Is this fixed by issue #509?

**Comment by djones6** [comment]
Yes, that does fix this - closing.
