### ISSUE TITLE
Kitura response times include very high outliers

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#410]
When driven with constant load (on Linux), some of the outlier response times from Kitura are excessive, and there is generally a much higher variance in response times compared to other frameworks.
We should investigate what is causing this.
TODO:  check whether the same behaviour is present on OS X.

Zewo example:
App:  `numactl --physcpubind=0,1,2,3 --membind=0 bbmark/swift/zewo/runmany.sh 4`
(starts 4 copies of Zewo, sharing cores 0-3)
Driver: `numactl --cpunodebind=1 --membind=1 wrk --timeout 30 --latency -t16 -c128 -d60s http://127.0.0.1:8080/plaintext`
`Running 1m test @ http://127.0.0.1:8080/plaintext`
`16 threads and 128 connections`
`Thread Stats   Avg      Stdev     Max   +/- Stdev`
`Latency     2.27ms    2.68ms  81.65ms   95.45%`
`Req/Sec     4.28k   549.71     8.45k    76.17%`
`Latency Distribution`
`50%    1.81ms`
`75%    2.29ms`
`90%    2.94ms`
`99%   16.17ms`
`4093018 requests in 1.00m, 304.47MB read`
`Requests/sec:  68149.47`
`Transfer/sec:      5.07MB`

Kitura example:
App:  `numactl --physcpubind=0,1,2,3 --membind=0 /home/djones6/git-projects/bbmark/swift/kitura/.build/release/kitura`
Driver:  `numactl --cpunodebind=1 --membind=1 /home/djones6/kiturabench/wrk --timeout 30 --latency -t16 -c128 -d60s http://127.0.0.1:8080/plaintext`
`Running 1m test @ http://127.0.0.1:8080/plaintext`
`16 threads and 128 connections`
`Thread Stats   Avg      Stdev     Max   +/- Stdev`
`Latency    10.24ms   86.18ms   3.21s    97.52%`
`Req/Sec     1.70k     1.58k   11.76k    74.37%`
`Latency Distribution`
`50%  275.00us`
`75%  342.00us`
`90%  688.00us`
`99%  200.24ms`
`1287744 requests in 1.00m, 141.23MB read`
`Socket errors: connect 0, read 1287742, write 0, timeout 0`
`Requests/sec:  21443.97`
`Transfer/sec:      2.35MB`

Wrk uses sampling to derive the latency statistics, so they do not encompass all requests (and so the measure of outliers is not accurate).  In this example, the highest outlier recorded was 3.21 seconds,  although on other runs I've seen >25 seconds.

**Comment by proyb6** [comment]
When I ran the tutorial on github page with Siege, I guess I have found bug in sock.c that could be related to increase in latency?

5 connections appear to be fine:
```
MacBook-Pro:kitura194 yanli$ siege -b -c 5 -t 30S http://localhost:8090
```
More than 5 connections and you get Broken pipe:
```
MacBook-Pro:kitura194 yanli$ siege -b -c 10 -t 30S http://localhost:8090
[alert] Zip encoding disabled; siege requires zlib support to enable it
[error] socket: 3211264 unknown network error.: Connection reset by peer
[error] unable to write to socket sock.c:634: Broken pipe
[error] unable to write to socket sock.c:634: Broken pipe
```

**Comment by ianpartridge** [comment]
Hi, thanks for reporting this. It looks like a different problem to me - please can you raise a separate issue?

**Comment by simplepanda** [comment]
If it helps narrow it down, I'm seeing similar results in my FastCGI implementation using either Nginx or Apache 2.4 (Event) w/ proxy_fcgi as the HTTP front-end.

```# wrk --timeout 30 --latency -t16 -c128 -d60s http://127.0.0.1
Running 1m test @ http://127.0.0.1
  16 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.76s   677.86ms  15.47s    92.04%
    Req/Sec     9.43      8.39    50.00     65.29%
  Latency Distribution
     50%    1.77s 
     75%    1.85s 
     90%    1.94s 
     99%    4.35s 
  4393 requests in 1.00m, 2.53MB read
Requests/sec:     73.10
Transfer/sec:     43.19KB```

Latency looks OK to me given the hardware it's running on (two cores of a Xeon E5-2650L v3 @ 1.8ghz) and the fact that this is HTTP->FastCGI->Kitura without benefit of keep-alive on the FastCGI side. 

The latency distribution doesn't bother me either... but that max request time is troubling.

Try as I might I can't narrow it down to my FastCGI implementation so I was assuming it was further up the the chain.

I've seen this on both OS X and Linux with 2016-06-06. I didn't test Apache/proxy_fcgi on OS X but given I was seeing it uniformly I didn't think it was Nginx causing the issue.

**Comment by djones6** [comment]
I'm closing this issue as I believe it was related to delay in accepting new connections under stress conditions.  Implementing keepalive has eliminated these outliers (Kitura response time maximum is now consistently in the 200ms range for Hello World).

If I find any more specific cases of high response times with other workloads / environments, I'll raise more targeted issues.
