### ISSUE TITLE
Kitura process is marked as defunct in Linux

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#417]
When I start a Kitura application (such as Kitura-Sample) on Ubuntu 14.04, the process is immediately marked as "defunct".  The process does operate normally (it serves pages, I can drive load),  but various operating system tools do not show stats such as resident set size in 'top' or 'ps'.

Ian Partridge suggested I use strace to see if the process is calling 'exit' - and indeed, the main thread does.

What this means in terms of the appearance of a Kitura process under Linux:
`ps -p 13567 -o pid,tid,time,rss,vsz,cmd`
`  PID   TID     TIME   RSS    VSZ CMD`
`13567 13567 00:00:09     0      0 [Kitura-TechEmpo] <defunct>`
 \- the label '\<defunct\>' appears after the command, and the resident set size / virtual size (numbers reported for example in 'top') are zero
Looking at threads:
`ps -T -p 13567 -o pid,tid,time,rss,vsz,cmd`
`  PID   TID     TIME   RSS    VSZ CMD`
`13567 13567 00:00:00     0      0 [Kitura-TechEmpo] <defunct>`
`13567 13568 00:00:00 635960 990596 [Kitura-TechEmpo] <defunct>`
`13567 13569 00:00:00 635960 990596 [Kitura-TechEmpo] <defunct>`
`13567 13570 00:00:00 635960 990596 [Kitura-TechEmpo] <defunct>`
`13567 13571 00:00:04 635960 990596 [Kitura-TechEmpo] <defunct>`
`13567 13572 00:00:04 635960 990596 [Kitura-TechEmpo] <defunct>`
\- this view gives access to the memory utilisation numbers - but it's a little obscure.
Another side effect of the process being 'defunct', is that the various interesting files in the /proc/<pid> filesystem are empty:
`cat /proc/13567/smaps`
`<no output>`

Many system tools make use of these pseudo-files to report their information.  This behaviour would make it more difficult, for example, to spot a memory leak in a Kitura application.

**Comment by kweinmeister** [comment]
Do we see an exit call and/or <defunct> on OS X?

**Comment by djones6** [comment]
\<defunct\> does not appear on OS X.
Using 'dtruss', which appears to give the same kind of information as 'strace' on Linux, there is no 'exit' listed.  However, I'll admit to being way out of my depth at this point.

**Comment by ianpartridge** [comment]
@djones6 I've merged the fixes for this. Can you verify that it's fixed in `0.21.0` of Kitura, and close if you're happy?

**Comment by djones6** [comment]
I'm happy with the changes, this does not appear to impact performance and the process is no longer marked as a zombie.

I did want to record a little research that I did into this issue.  It seems this issue has been encountered and solved in Dispatch in the past:
https://lists.macosforge.org/pipermail/libdispatch-dev/2011-May/000522.html

The patch was applied 5 years ago - https://libdispatch.macosforge.org/trac/changeset/199/trunk/src/queue.c
\- but it was lost in the next merge (6 months later) - https://libdispatch.macosforge.org/trac/changeset/211/trunk/src/queue.c

My suspicion is that it was lost during the merge, rather than deliberately removed,  though I didn't come across any further discussions on the subject.  I'll ask the folks working on Dispatch to take a look.

@ianpartridge / @shmuelk do you think it's worth tracking this so that we could consider reverting back to dispatch_main() in the future?  Since it doesn't appear to impact performance, it would only be to make the code clearer.

**Comment by ianpartridge** [comment]
Personally I think the new code is better, and avoiding using the main queue is a good idea.
