### ISSUE TITLE
Migrate to Swift binaries from 4-25 (and implement work around for executing tests).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#418]
- [x] LoggerAPI
- [x] SwiftyJSON
- [x] KituraSys
- [x] KituraNet
- [x] Kitura
- [x] HeliumLogger
- [x] KituraSample
- [x] CouchDB
- [x] Redis
- [x] KituraCredentials....
- [x] KituraSession
- [x] GRMustache
- [x] Kitura-TemplateEngine
- [x] Kitura-MustacheTemplateEngine
- [x] Kitura-TodoList

**Comment by rfdickerson** [comment]
So testing still has not been completely fixed in the 4-25 toolchain? There is still a work around required? What is it?

**Comment by dfirsht** [comment]
From the issue: 

> A short term (less than ideal) hack would be running `swift build` then editing .build/debug.yaml and replacing the instances of `CFEnviornment.xctest` with `CFEnviornmentTest.xctest` then run `swift test` but it'll be overwritten again once you run `swift build` again...

We will have to add this into the makefile as a temporary stopgap.

**Comment by rfdickerson** [comment]
Apparently the pkg-config based system level dependency fix* on SPM might have been merged in as of 4-25. Can we check if we still need to run `swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib`?

* need to find short concise name for this fix

**Comment by dfirsht** [comment]
@rfdickerson just tested it. You can build fine with `swift build` but you still need the system includes to run tests. Otherwise you get this `ld: library not found for -lhttp_parser for architecture x86_64`

**Comment by dfirsht** [comment]
Unless we missed any I think this task is ready to be validated.

**Comment by rfdickerson** [comment]
Just added Kitura-TodoList as validated. We still need to be sure Redis, CouchDB, and credentials work.

**Comment by dfirsht** [comment]
Well they all compile and pass test cases (the ones that have them). What other validation should we do?

**Comment by rfdickerson** [comment]
Validated!
