### ISSUE TITLE
Memory leak when driving load

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#419]
When driving requests to Kitura (such as the Kitura-Sample application), the memory footprint of the Kitura process increases quite severely.  I've been able to replicate this on both Linux and OS X.  Growth looks to be directly proportional to load.

After driving ~7 million requests using JMeter at a trivial Kitura app running on Ubuntu 14.04,  the process footprint (RSS) had increased from 16MB (before any requests are driven) to 77GB.  This is equivalent to around 11kb growth per request.  (JMeter not required - I can replicate this with ab or wrk, or hitting refresh in a browser).

This is based on the Kitura 0.10.0 release running on the 0324 snapshot.

Note that the footprint under Linux is not immediately obvious - see issue #417

**Comment by ianpartridge** [comment]
Update:  my commit 8473559 has definitely fixed the *entire* leak on Mac.

![image](https://cloud.githubusercontent.com/assets/1423497/15212064/ac6cd49a-1836-11e6-885a-1983de2a7dc9.png)

Instruments shows all transient allocations during load are freed, and no leaks are found.

This was done by driving load through the `wrk` tool with this command-line: `wrk -t4 -c16 -d30s http://127.0.0.1:8090/hello`

The transient allocations are significant, so there is future performance work to do to analyse them and investigate ways to reduce them.  But there's no leak.

@djones6 is still seeing RSS rising on Linux, however more testing is needed to try and determine whether this is a real leak, or Kitura not disclaiming freed memory, or gradual expansion of the malloc arenas caused by the transient allocations.

But good progress!

**Comment by djones6** [comment]
The remaining memory leak on Linux is real:  if I set a virtual address space limit of around 1gb (ulimit -v 1000000), Kitura dies after ~180,000 requests with:
Trace/breakpoint trap (core dumped)
Looking briefly at a core dump, it appears that there is still request/response data in memory.
Ian suggested valgrind which sounds like a better way to approach this, so I'll look into valgrind first.

**Comment by djones6** [comment]
For reference, PR #464 resolved most of this leak (the parts relating to self-referencing closures).
The majority of the remaining leaks are due to what we believe is a bug in foundation on Linux: NSMutableData does not free its storage when deinitialized (see #468).

**Comment by michalkalinowski-** [comment]
Great, any idea what tag it should be in?

**Comment by djones6** [comment]
[Kitura 0.13.6](https://github.com/IBM-Swift/Kitura/releases/tag/0.13.6) (develop branch) contains this fix.
Note that develop will be merged to 'master' at the end of our current sprint, later this week.

**Comment by michalkalinowski-** [comment]
Hello,
I've just upgraded my app to Kitura 0.14 and these are the results I'm seeing on my mac:

![alt text](http://s32.postimg.org/iazuc3p9x/memory.png "Memory leaks?")

I have run 3 times
`wrk -t2 -c24 -d10s http://localhost:8090/testBlue`

where testBlue is the simplest .GET route:

```swift
router.get("/testBlue") {
  request, response, next in
  response.statusCode = .OK
  response.send("Blue OK")
  next()
}
```

Can you help me understand those results? Am I doing something wrong?

**Comment by shmuelk** [comment]
@michalkalinowski- There is still a small memory leak in Kitura 0.14.0 that has been identified as a bug in NSData and NSMutableData.

See issue #468

**Comment by djones6** [comment]
The NSData / NSMutableData leak is specific to the Linux Foundation implementation (Bhakta has submitted a PR - [\[SR-1552\] Fix memory leak in NSMutableData and NSData](https://github.com/apple/swift-corelibs-foundation/pull/380)). There were no leaks on Kitura 0.13 on Mac.  I'll check out the latest version.

**Comment by djones6** [comment]
@michalkalinowski- I found no new leaks in Kitura 0.14.0 compared to the previous version I had analyzed (0.13.6).  My testcase is a simple plaintext response (similar to the example you quoted).
Can you tell me how you produced the report / view above? I'm not that familiar with XCode.

**Comment by djones6** [comment]
Optimizing memory usage is now represented by #928.
