### ISSUE TITLE
Determine if NSOperationQueue could be used for executing async functions in a predefined order

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#42]
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Wednesday Jan 13, 2016 at 20:55 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/42_

----

This is an exploratory task (dependent on the libdispatch library) The following is just pseudocode for reference:

backgroundQueue.addOperationWithBlock(clousure1);
backgroundQueue.addOperationWithBlock(clousure2);

Where closure1 is the handler in the router code for processing the http request and http response (code provided at the app level) and closure2 is the next() closure that is used internally by the middleware router layer (not the app).

See the following links for further details:
https://tetontech.wordpress.com/2014/06/30/swift-nsoperationqueues-and-threading/
https://thatthinginswift.com/background-threads/
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSOperationQueue_class/#//apple_ref/occ/instm/NSOperationQueue/addOperationWithBlock

**Comment by dfirsht** [comment]
The implantation of NSOperationQueue is being tracked in this runtime issue: https://github.ibm.com/ibmswift/SwiftRuntime/issues/11

**Comment by ianpartridge** [comment]
Closing this for now, because `NSOperation` is not going to make it into swift-corelibs-foundation in Swift 3.0. We can reopen in the future if/when appropriate.
