### ISSUE TITLE
StaticFileServer can't handle '?' in URLs

### ISSUE THREAD

**Issue by janekp** [IBM-Swift/Kitura#423]
Adding a ? is a common cache-busting trick and it's also used by front-end development tools like livereload.js. StaticFileServer returns 404 if it's used. I can't override request.originalUrl either, because it's readonly.

For example: `/app/style.css` and `/app/style.css?livereload=1461961263116` should both serve the same file.

**Comment by shmuelk** [comment]
Reviewed source code.
