### ISSUE TITLE
Migrate to Swift 3 - May, 3rd binaries.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#432]
- [x] LoggerAPI (no changes needed)
- [x] SwiftyJSON
- [x] KituraSys
- [x] KituraNet
- [x] Kitura
- [x] HeliumLogger
- [x] KituraSample
- [x] CouchDB
- [x] Redis
- [x] KituraCredentials....
- [x] KituraSession
- [x] GRMustache
- [x] Kitura-TemplateEngine (no changes needed)
- [x] Kitura-MustacheTemplateEngine
- [x] Kitura-BluePic
- [x] Kitura-TodoList

**Comment by ianpartridge** [comment]
Suggest we do a quick scope of the effort involved, then decide whether to do this or wait for a future drop.

**Comment by rolivieri** [comment]
Agree with @ianpartridge. Just fyi, we have this Wiki page that describes the process for validation: https://github.com/IBM-Swift/Kitura/wiki/Moving-To-A-New-Version-Of-The-Swift-Binaries

**Comment by dfirsht** [comment]
All migrations complete.
