### ISSUE TITLE
Certain requests are failing on Kitura-net v0.11.4+

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#439]
Running Couch-DB tests on Travis-CI now fail when the version of Kitura-net is >= 0.11.4. In addition, while uploading photos to CouchDB in Blue-Pic, the response received in the callback is occasionally nil  causing the execution of the endpoint `/photos/:title/:photoname` to fail.

These errors are not present when using Kitura-net v0.11.3 or older.

Failing Travis-CI Build: https://travis-ci.org/IBM-Swift/Kitura-CouchDB/builds/127913233

**Comment by dfirsht** [comment]
It seems that this same error is present locally after switching to the 5/3 binaries. I pushed the 5/3 changes to a separate branch so they can be looked at.

**Comment by shmuelk** [comment]
I am going to manually merge the changes made above in side branches to the develop branch.

**Comment by dfirsht** [comment]
Seems to be solved by supporting HTTP Continue.
