### ISSUE TITLE
Simplify end user experience with single "import Kitura"

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura#448]
A user's first experience using Kitura should be VERY simple, and require only a modest level of knowledge to stand up a server.

Currently, a user needs to include 3 or more `import`s to utilize Kitura. This feels overly complex, and "exposing how the sausage is made".  The main `import Kitura` should be an aggregate class that includes all the core classes, that would cover the basic use cases. 

Concerns:
- Whats the build time penalty?
- Whats the output binary size increase?
- Would there be any class conflicts, and how to mitigate?
- Would still need to enable discreet imports of targeted sub-classes for fine grained control
- Rename current Kitura class to KituraCore or similar.

**Comment by dfirsht** [comment]
This reminds me of this issue: https://github.com/IBM-Swift/Kitura/issues/30. I agree with this idea. If there is a way to do this, we should make it a priority.

**Comment by naithar** [comment]
@dfirsht there is actually a way to use only ```import Kitura``` by adding ```@_exported``` attribute to any ```import``` statement in any source file so it would look like this:
```swift
@_exported import KituraNet
@_exported import KituraSys
```

**Comment by vadimeisenbergibm** [comment]
I think once refactoring for #467 is done, we might not need to import KituraNet and KituraSys.

**Comment by shmuelk** [comment]
We think that much of KituraSys will go away and what's left is probably not needed by the average developer.

That makes this two imports instead of three.

We are at this unsue of using the undocument @_exported annotation as supposedly it causes issues with XCoe (according to Apple)
