### ISSUE TITLE
I think the `RouterHandler` should be `throws`, which can handle errors directly

### ISSUE THREAD

**Issue by frogcjn** [IBM-Swift/Kitura#450]
Recently, `RouterHandler` is a colure does not accept throw errors, so in each routerHandler closure, developer should write the 'do,try,catch' each time as routerHandler occurs.

I used Flask and I think it is better to let `RouterHandler` to be a `throws` colure, which can handle errors throws by the code the developer provides.

For example,
```swift
router.get("/hello") { _, response, next in
     response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
     do {
         let fName = name ?? "World"
         try response.status(HttpStatusCode.OK).send("Hello \(fName), from Kitura!").end()
     } catch {
         Log.error("Failed to send response \(error)")
     }
}

router.post("/hello") {request, response, next in
    response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
    do {
        name = try request.readString()
        try response.status(HttpStatusCode.OK).send("Got a POST request").end()
    } catch {
        Log.error("Failed to send response \(error)")
    }
}
// ...as many routerHandler as possible
```
will be
```swift
router.get("/hello") { _, response, next in
     response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
     let fName = name ?? "World"
     try response.status(HttpStatusCode.OK).send("Hello \(fName), from Kitura!").end()
}

router.post("/hello") {request, response, next in
    response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
    name = try request.readString()
    try response.status(HttpStatusCode.OK).send("Got a POST request").end()
}

router.handleThrowedError { request, response, error, next in
    Log.error("Failed to send response \(error)")
    response.error = error
}
```

**Comment by shmuelk** [comment]
@frogcjn RouterHandler and RouterMiddleware explicitly do support throws in order to asynchronous handlers and middleware. That is a handler that does some asynchronous processing, perhaps invoking a RESTful API, and can "tell Kitura" when it's done, by calling next().

An alternate way of having asynchronous handlers has been from time to time considered, in which a RouteHandler or RouterMiddleware return a Promise. The Promise is fulfilled when the asynchronous work completes successfully or is failed if there was an error.

The Kitura team has a split opinion on this. Some think that this is a good modern replacement for callbacks. Others feel that since most Swift programmers have an iOS background, they are much more comfortable with callbacks.

Opinions anyone?

**Comment by michalkalinowski-** [comment]
My 2¢: callbacks are currently the standard way of writing swift code. Although there are some libraries implementing promises (https://github.com/Thomvis/BrightFutures) I'd wait to see what turn the official language implementation takes. From what I've understood it wasn't even considered for Swift 3.

**Comment by shmuelk** [comment]
That's what many in the Kitura team said as well.

However you then get callback h*ll as in https://github.com/IBM-Swift/Kitura-redis/blob/develop/Tests/SwiftRedis/TestBasicCommands.swift

**Comment by janekp** [comment]
I'm a bit confused. Isn't every request handled in a separate thread (parallel queue / thread pool)? Promises seem like a bandaid. Perhaps it makes more sense to avoid overly event-based designs at all - in the NodeJS world it also makes debugging ridiculously complicated (along with another h*ll called NPM). Synchronous-first approach, opposite of NodeJS (fs.exists = async, fs.existsSync = sync).

In the linked Redis sample, couldn't .get(), .set() etc just return tuples? And perhaps add .getAsync()?

**Comment by shmuelk** [comment]
@janekp You are correct every request that comes into a Kitura based server is handled in a parallel queue. This gives the server some level of parallelism. I have been told by people in IBM whose opinion I trust, especially when it comes to building servers, that eventually that won't be enough parallelism.

Kitura based servers will often be hosting micro services and what is called in IBM a System of Engagement. That is the server that exposes the RESTful end points to the client, but is in fact hosting a set of services that themselves are clients of other services running elsewhere. The question is what do you do while those "external" services are invoked? If you simply wait and tie up a thread, you wind up limiting your throughput as you have only so many threads (i.e. queue handlers). Avoiding "long waits" in a thread is a good thing.

After that long speech, I will admit two things:
1. When we started with Kitura the RouteHandler APIs was synchronous like you are proposing.
2. The Kitura APIs, today are actually synchronous, even though they have an asynchronous look and feel. The goal was to get something up and running quickly and then later make the implementations of the APIs asynchronous without breaking an API contracts.

**Comment by frogcjn** [comment]
I just want point out that, the HandlerFunction can be throws function, and can make the code easily to write, because of there are some throws function with response.
I think it is easy to handle this kind of things:
```swift
router.post("/hello") {request, response, next in
    response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
    name = try request.readString()
    try response.status(HttpStatusCode.OK).send("Got a POST request").end()
}
```
can be equal to original code:
```swift
router.post("/hello") {request, response, next in
let inner_closure = { request, response, next in
    response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
    name = try request.readString()
    try response.status(HttpStatusCode.OK).send("Got a POST request").end()
}
do {
    try inner_cosure(request, response, next)
} catch {
    response.error = error
}
}
```

**Comment by frogcjn** [comment]
https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/
> Express has built-in synchronous handling
> By default, Express will catch any exception thrown within the initial synchronous execution of a route and pass it along to the next error-handling middleware:
> 
> app.get('/', function (req, res) {
>   throw new Error('oh no!')
> })
> app.use(function (err, req, res, next) {
>   console.log(err.message) // oh no!
> })

**Comment by shmuelk** [comment]
@frogcjn I now understand better what you are saying. Thank you very much for the more detailed explanation. We will think about this some more.

BTW Once a handler has set response.error to some value, calling next() will automatically invoke the next error handler. Invoking next() in such a case, will NOT case a regular handler to be invoked.

**Comment by janekp** [comment]
I agree that asynchronous execution is more efficient than to block threads, but does it really matter? Most services won't ever see more than max 20 simultaneous users. Most MVP prototypes fail. Most iOS/Android apps fail. And the ease of debugging starts to matter if the application is more complicated than a simple TODO list app with many external dependencies. APIs change. Platforms change. And with Node you often end up debugging obscure stack-traces, because "something changed" (weak typing + interpreted code + async).

I like [this proposal](https://gist.github.com/oleganza/7342ed829bddd86f740a), but it's at least 1-2 years away. I don't have any idea what is the best solution for today.

**Comment by dfirsht** [comment]
@shmuelk Please validate.

**Comment by shmuelk** [comment]
Looks great
