### ISSUE TITLE
Performance benchmark / regression test for Kitura

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#456]
I'd like to propose that we create a performance benchmark, similar to the Kitura-Sample application,  which can be used to periodically regression test Kitura.

The primary aim of such a regression test would be to evaluate the effectiveness / impact of code changes and enhancements, for example:
- to indicate the benefit of a performance enhancement
- the cost of a new feature or bug fix
- the impact of migrating to a new Swift snapshot

Things that we would need:
- A benchmark (eg. 'Kitura-Bench')
- Travis CI support, to ensure benchmark is always runnable against the latest Kitura / snapshot
- A method of executing the benchmark in a consistent environment (Docker container?) which contains any dependencies (DB, for example) in a pristine state, and which ensures that each execution of the benchmark is done in a consistent manner

To automate the execution of such a benchmark, we would need:
- Performance hardware (dedicated so that a perf measurement is not tainted by other users / uses)
- A method of requesting a perf measurement against a branch / PR
- A scheduling mechanism, to serialize requests (so multiple requests do not run simultaneously, invalidating results)
- Consumable results (simple measures of ops/sec, CPU utilization, response times)
- A method of recording and comparing measurements, so that we can compare to a baseline result generated on the current release and determine whether a result is 'better' or 'worse'.

Travis-CI does not itself support performance measurement (https://github.com/travis-ci/travis-ci/issues/3313), so we would need a separate mechanism.  We might be able to use a slack bot.

**Comment by codeOfRobin** [comment]
@djones6 A guy from our local slack group created a set of [benchmarks](https://github.com/hiemanshu/server_benchmarks). Kitura seems to perform egregiously bad though. Would you have any idea why this is happening? My understanding is it's not because of libdispatch (Zewo does reasonably well), so what is the bottleneck?

**Comment by rfdickerson** [comment]
Just double checking, @codeOfRobin , did you mean to write ms instead of us (microseconds) for Kitura? If not, then Kitura actually is running at 0.3 ms which is amazing :)

**Comment by codeOfRobin** [comment]
@rfdickerson It's actually µs (There's a huge standard deviation, so the max is around 277 ms). Can someone ElIiOSDev why this is happening?

**Comment by djones6** [comment]
This has been delivered in the https://github.com/IBM-Swift/Kitura-Benchmarks project.
