### ISSUE TITLE
No such module 'KituraTemplateEngine'

### ISSUE THREAD

**Issue by AnthonyMDev** [IBM-Swift/Kitura#459]
Getting this error in `Router.swift` on version 0.13.1. This error only appears in Xcode. When using `swift build` from the command line, the build is successful.

**Comment by zzyyzz1992** [comment]
got the same problem,
and got this error when I remove the KituraTemplateEngine:
```
ld: library not found for -lCHttpParser for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kweinmeister** [comment]
This appears to have popped up in the 5/3 snapshot. It didn't seem to occur in 4/25. Will continue investigating.

**Comment by kweinmeister** [comment]
I discovered a workaround for now that compiles for me. In Xcode, rename the Kitura-TemplateEngine target to KituraTemplateEngine.

**Comment by AnthonyMDev** [comment]
@kweinmeister Hmm. That's interesting. So currently, I will need to do that each time I run `swift build --update` right? Hopefully we can get this fixed permanently, but I guess that helps for now.

**Comment by aquarchitect** [comment]
I believe you also have to point `KituraNet` and `Kitura` targets' `Library Search Paths` to `$(SRCROOT)/.build/debug` for a successful Xcode compiling.

**Comment by shmuelk** [comment]
I believe I have fixed the issue with building in Xcode.

Using the latest Kitura (0.13.4) and Swift 3.0 05/03, you can now build a Kitura based application in Xcode without manually fixing anything.

**Note:** The issues around running the application from Xcode still remain.

**Comment by kweinmeister** [comment]
I tested this and the issue has been resolved.

**Comment by dsperling** [comment]
This issue was reported to the Package Manager team and they have resolved it on their side today.

https://bugs.swift.org/browse/SR-1444

**Comment by kweinmeister** [comment]
Thank you for reporting this and following up @dsperling!
