### ISSUE TITLE
Simplify server startup API

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#467]
Currently, starting up a basic Kitura server looks like this:

```swift
let router = Router()
router.get("/") {
request, response, next in
    response.status(.OK).send("Hello, World!")
    next()
}

let server = HTTPServer.listen(port: 8090, delegate: router)
Server.run()
```

This is [confusing](https://twitter.com/jchannon/status/729991645823913985) to new users.

* The uppercase `Server` looks like a typo
* It immediately raises the question "what is the difference between `Server` and `HTTPServer` and why should I as a Kitura user care?"
* Other servers, e.g. NodeJS, do not require a separate `run()` method.  `listen()` does everything

Here are two options for improvement.

1. Add a `public func run()` to `HTTPServer` which calls through to `Server.run()`. Then the user would call `server.run()` instead of `Server.run()`
2. Add code in `HTTPServer.listen()` that calls `Server.run()`, so the user doesn't have to worry about it at all

**Comment by shmuelk** [comment]
@ianpartridge:

    1.  Actually you want a non-static function in option one. Adding a static function to HTTPServer, does nor let you code server.run. You need to code HTTPServer.run().
   2. Option two prevents one from creating a server that runs multiple listeners. Also it breaks our test code. All of this is because of the fact that when calls Server.run() to start the main queue running, there is never a return.

**Comment by vadimeisenbergibm** [comment]
To prevent confusion between `HTTPServer` and `Server`, we can rename `Server` to `Kitura` or `KituraFramework`:
```swift
let server = HTTPServer.listen(port: 8090, delegate: router)
Kitura.start()
```

To encourage the users to call Kitura.start, we can hide HTTPServer from them:

 ```swift
Kitura.addHTTPServer(port: 8090, delegate: router)
Kitura.start()
```

This way it is clear that you can have multiple http servers on different ports:
 ```swift
Kitura.addHTTPServer(port: 8090, delegate: router)
Kitura.addHTTPServer(port: 8091, delegate: anotherRouter)
Kitura.start()
```

The following is achieved:
- The user can understand that you can have multiple HTTP servers
- The user can understand that without running `Kitura.start()`, `addHTTPServer` by itself will not start listening. We can consider renaming `Kitura.start()` to `Kitura.startListening()`. 
- The user can understand that  calling `addHTTPServer` after  `Kitura.start()` will have no effect since the framework is already started

`Kitura` class can hold a static collection of http servers and call listen() method of each of them in its `start` method.

**Comment by ianpartridge** [comment]
Thanks Vadim!  Great ideas.

How about:

```swift
Kitura.createServer(port: 8090, router: router)
Kitura.createServer(port: 8091, router: anotherRouter)
Kitura.run()
```

**Comment by vadimeisenbergibm** [comment]
@ianpartridge 
I like to have HTTP server in the name since theoretically we can have other (non-http) servers in Kitura.
`createServer` seems OK, though the name does not hint that you can have multiple servers.
 `Kitura.run` or `Kitura.start` or `Kitura.startListening` are OK with me.

**Comment by ianpartridge** [comment]
Yes, good point about HTTP. I think the best might be:

```swift
let server = HTTPServer.create(port: 8090, delegate: router)
Kitura.run()
```

Thoughts?

**Comment by aquarchitect** [comment]
@ianpartridge I personally vote for @vadimeisenbergibm ideas to add servers.

```swift
Kitura.addHTTPServer(port: 8090, delegate: router)
Kitura.addHTTPServer(port: 8091, delegate: anotherRouter)
```

It is more centralized that way.

**Comment by vadimeisenbergibm** [comment]
@ianpartridge 
Here is the issue with `let server =`: the user may ask "why do I need this server variable if I do not use it?" The answer - the variable is needed in order to hold a reference to the server instance, otherwise the instance will be freed immediately.

In the case of `Kitura.addHTTPServer` you do not to create unused variables.

`let server = HTTPServer.create(port: 8090, delegate: router)` 60 characters
`Kitura.addHTTPServer(port: 8090, delegate: router)` 50 characters

**Comment by kweinmeister** [comment]
Should we still have the ability to stop listening? If so, should we still return a reference to an HTTPServer in `Kitura.addHTTPServer()`?

**Comment by vadimeisenbergibm** [comment]
@kweinmeister Correct, we can make Kitura.addHTTPServer return a reference, so the users who want to have a reference will be able to have it.

**Comment by vadimeisenbergibm** [comment]
Initial implementation is here - https://github.com/vadimeisenbergibm/Kitura-HelloWorld/blob/master/Sources/main.swift
```swift
import Kitura

let router = Router()
router.get("/") { _, response, next in
    response.status(.OK).send("Hello, World!")
    next()
}

Kitura.addHTTPServer(onPort: 8090, with: router)
Kitura.run()
```

`Kitura` class implementation is here - https://github.com/vadimeisenbergibm/Kitura

Any comments are welcome

**Comment by vadimeisenbergibm** [comment]
Another take, based on the idea of @shmuelk to use a closure.

```swift
import Kitura

let router = Router()
router.get("/") { _, response, next in
    response.status(.OK).send("Hello, World!")
    next()
}

KITURA { $0.httpListen(onPort: 8090, with: router) }
```
 If $0 looks cryptic, the last line could be written also as:
```swift
KITURA { kitura in kitura.httpListen(onPort: 8090, with: router) }
```

Alternatively:
```swift
import Kitura

let router = Router()
router.get("/") { _, response, next in
    response.status(.OK).send("Hello, World!")
    next()
}

KITURA { kitura in 
let router = Router()
router.get("/") { _, response, next in
    response.status(.OK).send("Hello, World!")
    next()
}
     kitura.httpListen(onPort: 8090, with: router) 
}
```

Several points:
- KITURA is written in capital letters to stress the point that it is a special function (it does not return, for example)
- httpListen does not return HTTPServer. instead I added a function `Kitura.stopListen()`

**Comment by aquarchitect** [comment]
@vadimeisenbergibm the `KITURA` function for me doesn't feel "swifty" at all, and it can be confusing for new users. I'd prefer your old implementation with `addHTTPServer` and `run` type methods. Just 2-cent opinion.

**Comment by aquarchitect** [comment]
@vadimeisenbergibm I understand the `KITURA` is a special function, but for me it doesn't feel "swifty" and a little out of [Apple API Design Guidelines](https://swift.org/documentation/api-design-guidelines/). I'd prefer your old implementation with simple `addHTTPServer` and `run` type methods. Just 2-cent opinion.

**Comment by vadimeisenbergibm** [comment]
@aquarchitect Thank you for your feedback. The idea here is to present some kind of DSL (domain specific language) which does not follow [Apple API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) and does not have to feel "swifty". I do not claim this solution is better than the previous one, I just present it as an additional option to get feedback/provoke more ideas for simplification. Let's see what would be the opinion of others, and if most of the feedbacks will be in favor of the first option and no other options will be proposed, I will implement the first option.

**Comment by dfirsht** [comment]
Validated.
