### ISSUE TITLE
Migration to 05-09 snapshot

### ISSUE THREAD

**Issue by NikitaSullivan** [IBM-Swift/Kitura#469]
- [x]  LoggerAPI (no changes)
- [x] SwiftyJSON
- [x] KituraSys (no changes)
- [x] KituraNet 
- [x] Kitura
- [x] HeliumLogger
- [x] KituraSample (Removed GRMustache)
- [x] CouchDB
- [x] Redis
- [x] KituraCredentials
- [x] Kitura-Credentials-Sample
- [x] KituraSession 
- GRMustache (Removed for now due to bug)
- [x] Kitura-TemplateEngine (no changes)
- Kitura-MustacheTemplateEngine (GRMustache removed for now)
- [x] Kitura-BluePic server
- [x] Kitura-TodoList

**Comment by edjiang** [comment]
Time to migrate to 5/31 instead! ;]

**Comment by dfirsht** [comment]
@vadimeisenbergibm There is an issue with compiling GRMustache on 05/09. While compilation succeeds on 05/03, in 05/09 the following error occurs: 
```
Compile Swift Module 'Mustache' (33 sources)
Assertion failed: ((isNullableTypeInC(M, func->getResultType()) || func->getResultType()->hasArchetype()) && "func's result type is not nullable?!"), function mayLieAboutNonOptionalReturn, file /Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/lib/SILGen/SILGenExpr.cpp, line 2343.
0  swift                    0x00000001040fa54b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
...
1.	While emitting SIL for getter for mustacheBox at /Users/danielfirsht/Documents/Kitura_project/GRMustache.swift/Sources/Localizer.swift:87:45
<unknown>:0: error: unable to execute command: Illegal instruction: 4
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
```
I pushed the updated code to the develop branch so you can see the error.

**Comment by shmuelk** [comment]
Validated by automated builds.
