### ISSUE TITLE
SwiftyJSON - Not handling float values right when invoking rawString() on Linux

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#470]
This issue is only reproducible on **Linux**.

If a JSON object contains float values, then invoking the rawString() method on the JSON object returns nil. For instance, see this code:

```
#if os(OSX)
    typealias JSONDictionary = [String: AnyObject]
#else
    typealias JSONDictionary = [String: Any]
#endif
```
And then we do this:

```
...
let latitude = Float(lat)
let longitude = Float(long)
...
let whereabouts: JSONDictionary = ["latitude": latitude, "longitude": longitude, "name": locationName]
let json = JSON(whereabouts)
let str = json.rawString()
print("str: \(str)")
```
The above code results in: ```str: nil```.

Now, if instead of floats, say, strings are used:
```
...
let latitude = String(lat)
let longitude = String(long)
...
let whereabouts: JSONDictionary = ["latitude": latitude, "longitude": longitude, "name": locationName]
let json = JSON(whereabouts)
let str = json.rawString()
print("str: \(str)")
```
The above code results in: ```str: Optional("{\n  \"name\": \"Austin, Texas\",\n  \"longitude\": \"80.5\",\n  \"latitude\": \"34.2\"\n}")```.

**Comment by dfirsht** [comment]
@rolivieri Please validate.

**Comment by rolivieri** [comment]
It works now, thanks!
