### ISSUE TITLE
Change public APIs to conform with Swift 3 API guidlines

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#473]
Several of our public methods can be modified to better conform with the guidelines. We should strive to follow them as close as possible.

This issue considers Kitura-sys, Kitura-net and Kitura to be in scope. Kitura's internal methods should be changed as well to improve readability.

Reference: https://swift.org/documentation/api-design-guidelines/

**Comment by dfirsht** [comment]
The PRs have been merged and all repos have been updated. @shmuelk please verify if we can close.

**Comment by shmuelk** [comment]
I have reviewed all of the changes here except my own.

**Comment by dfirsht** [comment]
I have reviewed Shmuel's changes.
