### ISSUE TITLE
Content-Type with parameters not handled

### ISSUE THREAD

**Issue by dsperling** [IBM-Swift/Kitura#474]
Content-Type with parameters are not parsed correctly.  For example, this POST should be processed as contentType="application/x-www-form-urlencoded"

    POST /message HTTP/1.1
    Cache-Control: max-age=259200
    Content-Length: 730
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    ...

Kitura's BodyParser.swift does not handle this case.

I have a fix and am working on a pull request.  Just need to get the CLA done.

**Comment by NikitaSullivan** [comment]
Hi,

Thanks for finding and correcting this, look forward to seeing the pull request.

**Comment by dfirsht** [comment]
Closing based on merger of PR #501.
