### ISSUE TITLE
'RouterResponse' has no member 'setHeader'

### ISSUE THREAD

**Issue by jamielesouef** [IBM-Swift/Kitura#475]
Hi, 

Trying to install Kitura in docker, and following the readme i'm getting the following error when running `/root/clone_build_test_kitura.sh`

`Compile Swift Module 'KituraStarterBluemix' (1 sources)
/root/Kitura-Starter-Bluemix/Sources/main.swift:37:3: error: value of type 'RouterResponse' has no member 'setHeader'
  response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
  ^~~~~~~~ ~~~~~~~~~
/root/Kitura-Starter-Bluemix/Sources/main.swift:47:3: error: value of type 'RouterResponse' has no member 'setHeader'
  response.setHeader("Content-Type", value: "text/plain; charset=utf-8")
  ^~~~~~~~ ~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /root/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-ubuntu15.10/usr/bin/swift-build-tool -f /root/Kitura-Starter-Bluemix/.build/debug.yaml
Kitura-Build/build/Makefile:37: recipe for target 'build' failed
make: *** [build] Error 1`

running Docker version 1.11.1, build 5604cbe

**Comment by naithar** [comment]
@jamielesouef that's probably because headers was refactored and there is no ```setHeader``` method now. With current implementation you could use something like ```response.headers["Content-Type"] = "text/plain; charset=utf-8"```

**Comment by ianpartridge** [comment]
I've just pushed https://github.com/IBM-Swift/Kitura-Starter-Bluemix/commit/37412bbc5f72321d9c7308fc7392c7527581dddb to fix this.

Sorry for the inconvenience - if you clone from `develop` on `Kitura-Starter-Bluemix` everything should work.

**Comment by dfirsht** [comment]
Closing based on Ian's fix.
