### ISSUE TITLE
#Question Can we have Kitura-MySQL Connector in the future?

### ISSUE THREAD

**Issue by zzyyzz1992** [IBM-Swift/Kitura#477]
Do we have a plan to develop a MySQL connector?
Thank you:)

**Comment by shmuelk** [comment]
We ourselves are not looking at implementing one at this time.

There are various third party database APIs that are written in Swift and are compatible with the Swift Package Manager. I don't know if all of them are still compatible with Swift 3.0. I know of a MongoDB driver and of a PostgreSQL driver. Some are pure Swift and some use a combination of Swift and C code.

**Comment by kweinmeister** [comment]
@nicholasjackson has written a MySQL connector that I believe works with Kitura: https://github.com/notonthehighstreet/swift-mysql

Also, we have built a pattern for connecting Kitura to multiple databases that is compliant with the [Todo Backend](http://www.todobackend.com) project. I'd recommend checking out [todolist-redis](https://github.com/IBM-Swift/todolist-redis) as an example for Redis. We'd be interested in contributions that work with other databases like MySQL also.

**Comment by dfirsht** [comment]
Closing based on Karl's answer.

**Comment by nicholasjackson** [comment]
Hi @zzyyzz1992 I will be updating this to the latest swift binary in the next day or so, been snowed sorry for the delay.

**Comment by sahandnayebaziz** [comment]
@zzyyzz1992 I found an all-Swift MySQL package being developed here and opened a PR for Swift 3.0. There are a couple pointer-related issues that I couldn't immediately figure out... but here it is :)
https://github.com/mcorega/MySqlSwiftNative/pull/17
