### ISSUE TITLE
Simplify the adding of a HeliumLogger logger to an application

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#479]
Add one line of code to the init function of HeliumLogger:

    Log.logger = self

Question: Does HeliumLogger get used anywhere not using the Logger.logger stuff?

**Comment by shmuelk** [comment]
The above idea isn't quite so good. One gets a warning when one tries to simply code HeliumLogger().

An alternate is to add to HeliumLogger a static function as in the following:

```swift
public static func use() {
    Log.logger = HeliumLogger()
}
```

**Comment by dfirsht** [comment]
Validated.
