### ISSUE TITLE
Convert HTTP protocol implementation from libcurl to NSURLSession and other native networking classes

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#48]
<a href="https://github.ibm.com/rfdickerson"><img src="https://avatars.github.ibm.com/u/1506?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rfdickerson](https://github.ibm.com/rfdickerson)**
_Thursday Jan 14, 2016 at 19:35 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/48_

---

Just a reminder to convert this code over when NSURLSession and others are implemented.

**Comment by dfirsht** [comment]
The implantation of NSURLSession is being tracked in this runtime issue: https://github.ibm.com/ibmswift/SwiftRuntime/issues/10

**Comment by christiancompton** [comment]
Closing - no longer relevant.
