### ISSUE TITLE
Network connection lost reported by iOS clients.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#487]
Description of the problem will be added below.

**Comment by rolivieri** [comment]
Long story short, 1) if the body of an HTTP request from an iOS client to a Kitura-based server app has a semi-large amount of data (e.g. ~600kb), 2) and the body of that HTTP request is not consumed (i.e. read) at all on the Kitura-based server, 3) and a response is sent to the iOS client, 4) then a network connect lost or a network timed out error is reported by the iOS application. Now if the body of the http request is consumed and, only after that, a response is sent to the iOS app, then no errors are reported on the iOS side. 

I can now reproduce this easily and have code to demonstrate this issue if needed. The question now seems to be: What changes are needed in Kitura so that a response can be sent to a client without having to consume the body of the http request? Not being able to send a response without having to consume the body of the request is having a negative impact on the **MCA** Server SDK and also on any Kitura-based application that needs to send a response without having to consume the HTTP request body (~ >600kb).

**Comment by irar2** [comment]
I can't reproduce the problem. I sent an almost 2MB picture with wrong token, and got an error from the server, but no connection lost/network timeout. Could you please provide more information how to reproduce this?

**Comment by rolivieri** [comment]
@irar2 - The easiest way to reproduce this problem is to clone the following branch: ```git clone -b ro-test2 https://github.com/IBM-Swift/BluePic.git```. Once you've cloned the repo, compile both, the iOS app (```BluePic-iOS```) and the server side code (```BluePic-Server```). Dome that, add breakpoints to the iOS app in the following file: ```BluePic/DataManagers/BluemixDataManager.swift```. You may want add breakpoints to the ```rotest()``` method, specifically lines 518, 534, 535. Also, make sure you reset your iOS simulator so that it is at known state. Now, launch the BluePic server (```.build/debug/Server```) and then launch/run the iOS app. Sign in using your Facebook account. Done that, then try to upload a picture from the camera roll in the simulator. This action will take you to the ```rotest()``` method and your breakpoints should be hit. Using the debugger in Xcode, step through lines 535 - 541. You should see that on the server side things seem to be fine but on the client (iOS side) you should see that the ```error``` variable is NOT nil and ```response``` object is nil.

Once you have reproduced the problem, you can also take the following steps. Go to the following file on the server side: ```BluePic-Server/ Sources/Server/Routes.swift```. Uncomment lines 43 and 44 and rebuild the server:
```
let rawUserData = try? BodyParser.readBodyData(with: request)
print("rawUserData: \(rawUserData)")
```
Now, try to upload an image again using the iOS app. Now that you are consuming the request body the error should not occur. In other words, the ```error``` object should now be nil and the ```response``` object should NOT be nil. You can play with uncommenting and commenting out lines 43 and 44 in the ```Routes.swift``` file to reproduce the problem. Let me know if you have any other questions.

**Comment by irar2** [comment]
@rolivieri Please validate

**Comment by rolivieri** [comment]
@irar2 Tested the fix and it is working! Thanks for your help.
