### ISSUE TITLE
Create higher level client request & response library

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#489]
Given that the "bare bones" nature of the ClientRequest and ClientResponse methods, there should be a higher level libraries on top of these, similar to how RouterRequest and RouterResponse are on top of ServerRequest and ServerResponse.

**Comment by michalkalinowski-** [comment]
Hello, I've played with a couple of ideas and this is what I like the most so far (it follows closely Alamofire interface)

``` swift
  class Request {
  ...
  init(method: RequestMethod,
       _ URL: String,
       parameters: [String: AnyObject]? = nil,
       encoding: ParameterEncoding = .URL,
       headers: [String: String]? = nil)
   ...
   }
```

ParameterEncoding is an enum that has an encode method. It takes parameters and returns elements to be added to request. It is called by Request object when creating ClientRequest in initialiser. 

```swift
enum ParameterEncoding {
  case URL
  case JSON
  case ...

  func encode(parameters: [String: AnyObject]?) throws -> (query: String?, body: NSData?) {
    ...
  }
}
```
It's quite nice as you could pass [String:AnyObject] with .JSON encoding type and have the request with application/json content type and encoded json in body as a result. Works also for encoding parameters in URL query. 

Now I had a stab at implementing this and code could be much nicer if ClientRequest could be initialised with NSURLRequest. That's what I'm looking at right now.

Please let me know if you like this idea. If so I'll keep on working on it, if there are better ones I'll just wait for official implementation.

**Comment by shmuelk** [comment]
This sounds very nice.

Make sure you check what ever you are doing with NSURLRequest on Linux. Foundation on Linux in the NSURL* space is somewhat weak.....

**Comment by michalkalinowski-** [comment]
I stated looking at ClientRequest class and I think it might be a good idea to rewrite it to use BlueSockets directly rather than going through curl. What was the reason to implement it as a curl wrapper in the first place? I don't have much experience in programming on such a low level of stack so highly probable I'm missing something.

On the other hand looking at ServerResponse, all it takes is those two methods:

```swift 
private func flushStart() throws
private func writeToSocketThroughBuffer(text: String) throws
```

**Comment by shmuelk** [comment]
We used libCurl as it gave us an easier to implement many things like:
    - HTTPS support
    - Automatic redirect following

For what it's worth the PR that adds NSURLSession support on Linux also uses libCurl under the covers.

**Comment by shmuelk** [comment]
Another point, while adding this high level HTTP request class to Kitura was probably my first choice, some have explicitly requested that we don't do that. They want to use this class without a dependency on Kitura.

**Comment by michalkalinowski-** [comment]
ok, since people want to use this wrapper outside Kitura framework I've started a module:

**Comment by michalkalinowski-** [comment]
Hello again, I've pushed a version `0.0.0` of the library to: https://github.com/michalkalinowski-/KituraRequest
Can you please have a look, review, and tell me if it's more or less in line with what you envisioned?

**Comment by ianpartridge** [comment]
Hi @michalkalinowski- thank you for working on this!

Does your repo work on Linux?

We want to have this functionality as part of the IBM-Swift GitHub org, as several teams are asking for this. The IBM Watson folks have also started something called RestKit which aims to solve the same problem - see https://github.com/IBM-Swift/swift-watson-sdk/tree/master/Sources/RestKit

We'll need to decide on the best approach and further development will be needed.  Perhaps we could merge the two??  CC: @vherrin who wrote RestKit...

Final thing... you have licensed your code under MIT. Would you be happy with Apache 2? All our repos are Apache 2.

**Comment by michalkalinowski-** [comment]
Hello Ian,

Yes, the library works on both osx and linux as Ubuntu 15.10 is a primary target in all my projects.
As I'm not a part of IBM or Kitura core team, I'll let you decide which way you want to go. 

Since you want to have this code as a part of your github organisation I can either merge, or maybe even simpler you could fork my repo and we'll continue all the development on your fork. I'm fine with any of those.

As per licence I don't have any specific preferences, MIT and Apache 2 works equally well for me.

Regards,
Michał

**Comment by ianpartridge** [comment]
Thanks @michalkalinowski-.  As a first step, please would you relicence your repo under Apache 2?

**Comment by ianpartridge** [comment]
Closing this as we now have Kitura-Request!
