### ISSUE TITLE
Implement a Kitura-Credentials plugin for HTTP Basic and Digest authentication 

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#496]

**Comment by irar2** [comment]
https://github.com/IBM-Swift/Kitura-Credentials/commit/6c0179b9139d87f7e832c08cfea2fb8dedc1b1fc
https://github.com/IBM-Swift/Kitura-Credentials/commit/7c84bc7c995a1559879aed9d02c264dfe0dc5732
https://github.com/IBM-Swift/Kitura-CredentialsHttp/commit/9050aa79b0307095c5a979ddef3ee5dad40f042d
https://github.com/IBM-Swift/Kitura-CredentialsHttp/commit/3c4af7d8ea234155429d9dd640a3a78012d30db7
https://github.com/IBM-Swift/Kitura-CredentialsHttp/commit/48ca07e92b341d2354fde646ae2ac748cf9966c3

**Comment by shmuelk** [comment]
Reviewed last changes. It all looks fine now.
