### ISSUE TITLE
Improve Codebeat warnings and add the badge

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#505]
Code Beat - https://codebeat.co

Badge PRs:
https://github.com/IBM-Swift/Kitura/pull/235
https://github.com/IBM-Swift/Kitura/pull/174

**Comment by vadimeisenbergibm** [comment]
List of refactoring commits to my forked Kitura repository is below: 

[extracted FileResourceServer class from Router to make Router smaller](https://github.com/vadimeisenbergibm/Kitura/commit/7ffa5921e6b6af57a660c68776471ee36cad9e55)
[moved header helper methods into Headers from RouterResponse to make RouterResponse smaller](https://github.com/vadimeisenbergibm/Kitura/commit/5631ff9bf041877d1e21b4314e70d7d01397f233)
[removed redirect with status parameter from RouterResponse - using default status parameter](https://github.com/vadimeisenbergibm/Kitura/commit/28a6d28ffff2a4adc561cd448bf3e929b9d12cdf)
[removed end(String) and end(NSData) functions from RouterResponse these functions are just a syntactic sugar for send(string).end() and send(data).end(), they increase the number of functions without providing real benefits](https://github.com/vadimeisenbergibm/Kitura/commit/a8334be189879d37fb63530c0b2cdb273e963abe)
[removed setOnEndInvoked(), onEndInvoked made public from RouterResponse - just use a property, reduce the number of functions in the class](https://github.com/vadimeisenbergibm/Kitura/commit/9a0ba8a9549f940fa128a7e8806620f9d7325347)
[replaced Options enum with Options struct - simplifying StaticFileServer](https://github.com/vadimeisenbergibm/Kitura/commit/322ff27b5ae28927c6a0b29a9d86acbbd54d380f)
[split Options into Options and CacheOptions - to simplify Options](https://github.com/vadimeisenbergibm/Kitura/commit/f9d7ce37b698c277bf58870929f3044c5fc806dd)
[extracred Cookie.initCookie from Cookie.init() - to simplify Cookie.init()](https://github.com/vadimeisenbergibm/Kitura/commit/2a1528c4d398fbee4f0bf6b844f129a4068412bb)

Comments are welcome.

**Comment by ianpartridge** [comment]
Hi @vadimeisenbergibm - I commented on each commit above.  I hope this helps 😃

**Comment by dfirsht** [comment]
Completed in PR: #607
