### ISSUE TITLE
Allow storing value types in RouterRequest.userInfo

### ISSUE THREAD

**Issue by jtomanik** [IBM-Swift/Kitura#507]
I'd like to propose changing `userInfo` to:
``` ///
    /// User info
    ///
    public var userInfo: [String: Any] = [:]
```

That will allow storing things other than classes in `userInfo`. I have one-line PR ready just waiting to get through CLA tomorrow. However I would like to hear your thoughts beforehand.

On the side note could anyone from dev team explain the rationale behind using classes pretty much everywhere? Couldn't spot any inheritance nor NSObject dependance and most of the objects look like a perfect fit for value types.

**Comment by dfirsht** [comment]
I think this is a good change to make and I'd support the PR when you submit it. As for your question, reference vs value types has been a divisive issue for the dev team in the past (see #355). While I agree on moving more towards structs, we'll need to carefully consider performance and object "correctness".

**Comment by dfirsht** [comment]
Hey @jtomanik because this is such a simple fix, I went ahead and implemented it. Thanks for the suggestion!
