### ISSUE TITLE
Cannot do a POST request with an empty body.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#508]
This works: `pushReq.end("--request body (ignore this value)--")`
But this doesn’t: `pushReq.end()` or `pushReq.end("")`

**Comment by triceam** [comment]
Oddly enough, when I create an isolated test case this error does not happen.  However, when I have a nested request, it does seem to happen.  Here is the OpenWhisk action where I am seeing this behavior:

https://github.com/IBM-Swift/BluePic/blob/develop/BluePic-OpenWhisk/actions/KituraCallback.swift#L88

If I remove the string value being passed into pushReq.end() then the request just seems to hang - this happens with both the empty string and nil value.

**Comment by shmuelk** [comment]
@rolivieri  and @triceam  I don't know if I fixed this issue or not. I improved things some what, but to be honest I wasn't seeing the problem before the fix.

Can you either verify that this fix actually helps or provide a standalone test case that shows the problem?

**Comment by rolivieri** [comment]
@shmuelk I defer to @triceam. Andy ran into this issue while developing the OpenWhisk code for BluePic.
