### ISSUE TITLE
Default static web content page served by Kitura should reference the new BluePic app.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#513]
As requested by management folks, the default static web content page served by Kitura should be updated. The link that references `https://github.com/IBM-Swift/Kitura-BluePic` should reference the newer BluePic app `https://github.com/IBM-Swift/BluePic`.

**Comment by rolivieri** [comment]
![image](https://cloud.githubusercontent.com/assets/6609246/15810066/2df03e58-2b60-11e6-8a33-aa76c08151ee.png)

**Comment by dfirsht** [comment]
@shmuelk please validate.

**Comment by shmuelk** [comment]
After I added a tag, it works well.
