### ISSUE TITLE
No error when starting a HTTP server when the port is in use

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Kitura#515]
While trying out the simple Hello World example in the README.md I discovered that if you start multiple concurrent instances of the application (same port number), there is no error complaining the port is in use.

Is this error being swallowed? Or is there some extra code required to listen for this error? If the latter, should that code be added to the example?

**Comment by shmuelk** [comment]
@tunniclm The error is being swallowed if you haven't added logging. We will go about updating the README.md with a comment on this.

**Comment by dfirsht** [comment]
Looks good.
