### ISSUE TITLE
Call to next() required even after sending a response

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Kitura#516]
While I was playing with the Hello World example, I noticed that the code calls:

```swift
response.send("Hello World!")
next()
```

I wondered if the `next()` call is required, and discovered that removing it would cause the example to reset the connection without sending the response.

This is different to how Express works where you usually would call `send()` instead of `next()` -- this allows for shortcutting the middleware chain to send a response (usually this is due to some runtime decision).

Is this intended? If so, how would sending an optional early response that doesn't trigger other middleware be achieved?

**Comment by tunniclm** [comment]
Would it be valid to instead of calling `next()`, call `response.end()` ?

**Comment by shmuelk** [comment]
@tunniclm The short answer is yes, with a do/try/catch block.

The long answer is that calling next() among other things causes under the covers a call to end().

end() throws an error as the writing to the socket might actually fail. Admittedly there is probably little that you can do other than log an error.

In addition there may be all sorts of middleware in the pipeline that can execute. They will only execute if next() is invoked.

**Comment by tunniclm** [comment]
OK, my misunderstanding stemmed from the difference between Express and Kitura -- in Express `response.send()` calls `response.end()` after writing to the response.

**Comment by ianpartridge** [comment]
Is this a difference we should remove?
