### ISSUE TITLE
1 test fails on 05-31 snapshot on Linux OS only

### ISSUE THREAD

**Issue by NikitaSullivan** [IBM-Swift/Kitura#517]
1 test failing on Linux OS

**Comment by NikitaSullivan** [comment]
Looked further into these test failures:

First:
TestResponse.swift line: 319
error: TestResponse.testAcceptTypes : XCTAssertEqual failed: ("Optional("text/html")") is not equal to ("Optional("html")") - Accepts did not return expected value

Could be that the acceptable type for Linux is different rather than anything's broken.

**Comment by dfirsht** [comment]
I'm not sure what this issue is but I can confirm that using the current 06/06 snapshot, all tests are passing on Linux.
