### ISSUE TITLE
Improve the LoggerAPI based on discussions.

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#523]
We should improve the LoggerAPI based on discussions in the issue IBM-Swift/LoggerAPI#7

**Comment by kweinmeister** [comment]
Now that you've given LoggerMessageType a description field, I'd recommend also conforming to the CustomStringConvertible protocol, so that users can print out the value more easily: https://medium.com/@YogX/use-auto-describing-objects-with-customstringconvertible-49528b55f446

**Comment by shmuelk** [comment]
@kweinmeister Good idea

**Comment by irar2** [comment]
Reviewed and merged.
