### ISSUE TITLE
Create middleware for response-time

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#524]

**Comment by dfirsht** [comment]
@shmuelk ready for validation.

**Comment by shmuelk** [comment]
Two comments on the following two lines of code:

```swift
 var previousOnResponseEnd = {}
 previousOnResponseEnd = response.setOnEndInvoked()
```

  1. I think the variable should be named ```previousOnEndInvoked```
  2. You should use a let and simply merge the two lines of code or at least mak it one statement with a line break after the equals sign.

**Comment by dfirsht** [comment]
@shmuelk
1. The variable was renamed in an untagged merge
2. I cannot merge those lines since in the closure argument of setOnEndInvoked, I use the `previousOnEndInvoked` var and vars cannot be used in their own initialization.

**Comment by shmuelk** [comment]
ok.
