### ISSUE TITLE
Tutorial for XCode error

### ISSUE THREAD

**Issue by chenawu2** [IBM-Swift/Kitura#539]
Hi, I am able to follow your tutorial fine to load up Kitura server via Terminal.

However when I run the command
`swift build -X`
to create a xCode project and try to build it, I get this:

![image](https://cloud.githubusercontent.com/assets/3434801/16169858/74f34066-34f2-11e6-8f19-e5f0ff1ebd78.png)

Why is that?

My package is literally:
```
import PackageDescription

let package = Package(
    name: "myFirstKitura",
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 17)
    ]
)
```

The swift version I am using is:
`Welcome to Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 9f0d189820, Swift 1c720b8f84).`

**Comment by ianpartridge** [comment]
Is that Swift 3 tech preview 1 running on Xcode 8 beta?  If so, I'm afraid that is not yet supported.

Please use Xcode 7.3.1 with DEVELOPMENT-SNAPSHOT-2016-05-09-a of Swift - see DEVELOPMENT-SNAPSHOT-2016-05-09-a
