### ISSUE TITLE
Download link in the document is self-referencing

### ISSUE THREAD

**Issue by amitmangalvedkar** [IBM-Swift/Kitura#540]
I have installed Swift 3 
```
Apple Swift version 3.0-dev (LLVM cb08d1dbbd, Clang 383859a9c4, Swift 9e8266aaeb)
Target: x86_64-apple-macosx10.9
```
and am trying the first example on kitura given in the [link](https://github.com/ibm-swift/kitura/tree/develop) by executing the following command
`swift build --init`

However, it throws an error 
```
error: unknown command: --init
enter `/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a.xctoolchain/usr/bin/swift-build --help' for usage information
```   

I also tried setting back the version of Swift to the default Swift 2.2 
```
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
Target: x86_64-apple-macosx10.9
```
but that doesnt help either and it gives another error
`error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build (No such file or directory)`
Are there any further pre-requisites to be done before we try the example?   
  
Thanks And Regards
Amit M Mangalvedkar

**Comment by shmuelk** [comment]
@amitmangalvedkar We are currently working on migrating the develop branch of Kitura to the 06/06 driver of Swift 3. Currently the develop branch of Kitura supports the 05/09 driver of Swift 3 and the master branch of Kitura supports the 05/03 driver of Swift 3.

**Comment by amitmangalvedkar** [comment]
@shmuelk Thanks a lot for the lightning fast response. So in case I have to use the 05/09 driver, could you please provide the exact command to be executed, so that I have the right driver of Swift? I tried following the l[ink](https://github.com/ibm-swift/kitura/tree/develop#swift-version) provided in the document, for the right driver, however, it points to the above incorrect version.  

Thanks and Regards
Amit M Mangalvedkar

**Comment by shmuelk** [comment]
@amitmangalvedkar You probably don't want the toolchain that is shipped with XCode. After downloading and installing the toolchain from https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a-osx.pkg you should install it. Then set your path to include the /usr/bin directory in the toolchain. Then things should work a lot better.

**Comment by amitmangalvedkar** [comment]
@shmuelk Thanks a lot, I was able to run the Hello World application. I feel the documentation needs to be modified by making it very explicit regarding the exact build to be used (in case its already specified, please ignore my suggestion). I am closing this issue.  
Thanks and Regards
Amit M Mangalvedkar
