### ISSUE TITLE
SwiftyJSON version from IBM Cloud Tools BluePic example does not work with swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a on El Capitain (macOS née OS X)

### ISSUE THREAD

**Issue by jonmarimba** [IBM-Swift/Kitura#545]
I created a BluePic project through the IBM Cloud Tools for Swift and followed the instructions for making an Xcode project for the server. The build fails in SwiftyJSON.swift as shown below:

<img width="1011" alt="screen shot 2016-06-21 at 3 48 51 pm" src="https://cloud.githubusercontent.com/assets/59490/16243952/bc509f30-37c7-11e6-82c1-1dca0bb1d5cf.png">

It looks like the version of SwiftyJSON for the version of Kitura referenced in the sample project does not work (on OS X, it does work on Linux) with the referenced swift-DEVEL snapshot.

I noticed that this was fixed in SwiftyJSON (your mirror) v. 8.1.1:
* IBM-Swift/Kitura#469 Fixed SwiftyJSON to work on OS X with snapshot 05-09, tests also fixed and passing

But the dependency tree takes SwiftyJSON v. 7.0.4

This means that we can't do the fancy debugger integration you showed in your WWDC talk using the recommended toolchain.

**Comment by jonmarimba** [comment]
Note: There are a few SwiftyJSON dependencies in the tree, so this was not a matter of tweaking the dependencies at the top level.

**Comment by shmuelk** [comment]
@jonmarimba I actually believe that the Kitura app from the ICT is setup to work with Swift 3 05/03. To get it to work with 05/09, I think you need to change the versions of the various dependencies.

@rolivieri Please chime in.

**Comment by jonmarimba** [comment]
I'm a tad confused. [Here](https://github.com/IBM-Swift/Kitura#swift-version) it says the supported swift compiler for working with Kitura is 2016-05-09. So, to clarify, the version that ICT is setup to use is just a tad older? Is there a way to check when using ICT which Swift it likes?

**Comment by jonmarimba** [comment]
I think this is related to #543

**Comment by jonmarimba** [comment]
It may also be nice to know (or easily glean) which Swift snapshot is running on your cloud service as well as which is in the docker image, especially now when the development of your tool seems likely to move forward and those may get out of sync.

**Comment by rolivieri** [comment]
@jonmarimba Hello, you may want to check the README and repo for the BluePic app: https://github.com/IBM-Swift/BluePic. On the README page, you will find a section titled `Swift version` that has the details you are looking for. To sum up, the BluePic iOS app code was tested and developed using Xcode 7.3 (default toolchain). For the back-end components, a different toolchain was used: `DEVELOPMENT-SNAPSHOT-2016-05-03-a` version. Attempting to compile the back-end code with a different version of the Swift binaries won't work and isntt supported as of now. We plan to migrate to a more recent version of the swift binaries soon.

**Comment by jonmarimba** [comment]
@rolivieri Thanks! Very nice way to say "read the fine manual"
