### ISSUE TITLE
Add a template engine for Markdown (i.e. CommonMark)

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#549]

**Comment by dillan** [comment]
@shmuelk you might take a look at https://github.com/chriseidhof/commonmark-swift

**Comment by shmuelk** [comment]
@dillan Thank you very much for taking interest in this effort.

The repository you mentioned, https://github.com/chriseidhof/commonmark-swift, is an OSX only repository, actually a cocoapod. It also uses cocoapods itself to pull in the cmark dependency.

I may look at their code later, to see if the very simplistic things I plan to start with aren't enough.

**Comment by shmuelk** [comment]
We now have the open source approvals to proceed.
