### ISSUE TITLE
xcode project build error

### ISSUE THREAD

**Issue by jjjjjeffrey** [IBM-Swift/Kitura#553]
i created my server app by following steps:

```
$ mkdir server
$ cd server/
$ swift package init --executable
```

package.swift include following code:
```
import PackageDescription

let package = Package(
    name: "server",
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 19)
    ]
)
```

main.swift include:
```
import Kitura

let router = Router()

router.get("/") {
    request, response, next in
    response.send("Hello, World!")
    next()
}

Kitura.addHTTPServer(onPort: 8090, with: router)
Kitura.run()
```

then i build it:
```
$ swift build
$ .build/debug/server
```

everything is ok, build and running success.

i use the following command to generate xcode project:
```
$ swift package generate-xcodeproj
```

i want to generate an xcode project, open the project file and build, but it gives me a build error:

ld: library not found for -lCHttpParser for architecture x86_64

how can i solve this, can anyone help me? thanks!

(xcode7.3.1 use swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-osx.pkg)

**Comment by aquarchitect** [comment]
Follow this instruction: https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-on-XCode

**Comment by jjjjjeffrey** [comment]
@aquarchitect not works 😔

![11](https://cloud.githubusercontent.com/assets/4246681/16326604/b8268a0c-39fa-11e6-9df2-66f0a94ea40b.png)

![22](https://cloud.githubusercontent.com/assets/4246681/16326609/c085f8d6-39fa-11e6-8e71-c7c89fdd0bac.png)

**Comment by jjjjjeffrey** [comment]
my god, success! thanks @aquarchitect 

![333](https://cloud.githubusercontent.com/assets/4246681/16326779/14168f82-39fc-11e6-8cef-e05c667074b8.png)
