### ISSUE TITLE
recipe for target 'build' failed

### ISSUE THREAD

**Issue by kishanravindra** [IBM-Swift/Kitura#557]
I'm facing following Issue over and over again.

/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1619:27: error: argument labels '(value:)' do not match any available overloads
            self.object = NSNumber(value: newValue)
                          ^       ~~~~~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1619:27: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (char: Int8), (unsignedChar: UInt8), (short: Int16), (unsignedShort: UInt16), (int: Int32), (unsignedInt: UInt32), (long: Int), (unsignedLong: UInt), (longLong: Int64), (unsignedLongLong: UInt64), (float: Float), (double: Double), (bool: Bool), (integer: Int), (unsignedInteger: UInt), (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool)
            self.object = NSNumber(value: newValue)
                          ^
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1774:36: error: type 'NSComparisonResult' has no member 'orderedSame'
        return lhs.compare(rhs) == NSComparisonResult.orderedSame
                                   ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1790:36: error: type 'NSComparisonResult' has no member 'orderedAscending'
        return lhs.compare(rhs) == NSComparisonResult.orderedAscending
                                   ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1802:36: error: type 'NSComparisonResult' has no member 'orderedDescending'
        return lhs.compare(rhs) == NSComparisonResult.orderedDescending
                                   ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1814:36: error: type 'NSComparisonResult' has no member 'orderedDescending'
        return lhs.compare(rhs) != NSComparisonResult.orderedDescending
                                   ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1826:36: error: type 'NSComparisonResult' has no member 'orderedAscending'
        return lhs.compare(rhs) != NSComparisonResult.orderedAscending
                                   ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /root/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-ubuntu15.10/usr/bin/swift-build-tool -f /root/Kitura-Starter-Bluemix/.build/debug.yaml
Kitura-Build/build/Makefile:37: recipe for target 'build' failed

**Comment by ianpartridge** [comment]
You are using `DEVELOPMENT-SNAPSHOT-2016-05-03`.

Currently the `develop` branch builds against `DEVELOPMENT-SNAPSHOT-2016-06-06-a` and `master` builds against `DEVELOPMENT-SNAPSHOT-2016-05-09-a`, as documented in `README.md`.
