### ISSUE TITLE
docker build is failing

### ISSUE THREAD

**Issue by stvalentin** [IBM-Swift/Kitura#561]
Hey guys

I just tried to install kitura via docker using your tutorial but i'm getting this error when i'm running this command:
/root/clone_build_test_kitura.sh

Compile Swift Module 'HeliumLogger' (1 sources)
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/LclJSONSerialization.swift:121:42: error: type 'NSJSONWritingOptions' has no member 'prettyPrinted'
        let prettyPrint = opt.rawValue & NSJSONWritingOptions.prettyPrinted.rawValue  != 0
                                         ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1735:26: error: argument labels '(value:)' do not match any available overloads
private let trueNumber = NSNumber(value: true)
                         ^       ~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1735:26: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (char: Int8), (unsignedChar: UInt8), (short: Int16), (unsignedShort: UInt16), (int: Int32), (unsignedInt: UInt32), (long: Int), (unsignedLong: UInt), (longLong: Int64), (unsignedLongLong: UInt64), (float: Float), (double: Double), (bool: Bool), (integer: Int), (unsignedInteger: UInt), (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool)
private let trueNumber = NSNumber(value: true)
                         ^
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1736:27: error: argument labels '(value:)' do not match any available overloads
private let falseNumber = NSNumber(value: false)
                          ^       ~~~~~~~~~~~~~~
/root/Kitura-Starter-Bluemix/Packages/SwiftyJSON-9.0.0/Source/SwiftyJSON.swift:1736:27: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (char: Int8), (unsignedChar: UInt8), (short: Int16), (unsignedShort: UInt16), (int: Int32), (unsignedInt: UInt32), (long: Int), (unsignedLong: UInt), (longLong: Int64), (unsignedLongLong: UInt64), (float: Float), (double: Double), (bool: Bool), (integer: Int), (unsignedInteger: UInt), (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool)
private let falseNumber = NSNumber(value: false)
       
.... more issues here ....

error: exit(1): /root/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-ubuntu15.10/usr/bin/swift-build-tool -f /root/Kitura-Starter-Bluemix/.build/debug.yaml
Kitura-Build/build/Makefile:37: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by simplepanda** [comment]
This is happening because the Docker image uses an older snapshot of Swift and the Kitura code now dependent on at least DEVELOPMENT-SNAPSHOT-2016-06-06-a.

I just pushed a Docker image that bundles Ubuntu Xenial with DEVELOPMENT-SNAPSHOT-2016-06-20-a. This will build Kitura apps just fine.

For example:

$ docker pull simplepanda/swift
$ docker run -ti simplepanda/swift /bin/bash

You can then setup your app and build it (per the "Developing Kitura applications" guide on https://github.com/IBM-Swift/Kitura), then commit it and run it as you like.

Demo on the web of Kitura running on this image:
http://swift.codeandstrings.com

**Comment by Kam21** [comment]
Hi
I am using  latest "i**bmcom/kitura-ubuntu:latest**" and trying to run my own code but  running into some issue as reported below:

https://github.com/IBM-Swift/CHTTPParser/issues/5

using :DEVELOPMENT-SNAPSHOT-2016-06-20-a

**Comment by simplepanda** [comment]
@shmuelk's answer IBM-Swift/CHTTPParser#5 is on point. There are library differences between Linux and Apple Platforms right now that are going to be brought into parity as Swift 3.0 evolves towards beta and release.

In the meantime:

```swift
#if os(Linux)
// code that only compiles on Linux
#else
// code that only compiles on Apple
#endif
```

... where you run into platform specific issues will help you out. 

I find it's easier to build helper classes that bury the Linux/Apple differences and then call those from your code as needed, so you only have to patch one helper class as thing change.

Good luck!

**Comment by youming-lin** [comment]
I followed the instructions at https://github.com/IBM-Swift/Kitura#docker just now using docker on Ubuntu 15.10, and I had no issues compiling the code and starting the server. Please reopen issue if you are still having problems.
