### ISSUE TITLE
swift build --init error: unknown command: --init

### ISSUE THREAD

**Issue by colourful987** [IBM-Swift/Kitura#562]
Mac OSX 10.11.5 Xode7.3
I watched the WWDC2016 Session 405 and Write code according to the example，However `swift build --init`command run  failed ,why?

**Comment by simplepanda** [comment]
First, Xcode 7.3 won't work for Kitura. Even the 8.0-beta release won't work right now. You need a development snapshot of Swift to build Kitura and use it as of the time I'm posting this.

Second, the syntax has changed (they mention that it will in the video):

$ swift package init

**Comment by dfirsht** [comment]
That's exactly right @simplepanda, thanks for the help!
