### ISSUE TITLE
Improve Linux unit testing using Docker

### ISSUE THREAD

**Issue by dsperling** [IBM-Swift/Kitura#564]
Now that Docker has released the Public Beta of Docker for Mac 1.12, users no longer require VirtualBox or Vagrant to develop Kitura/Docker based services.  It would be nice to have a pure Docker solution for Linux Unit testing on the Mac.

Here is a proposed solution which I can turn into a PR if folks agree.

A solution would be to have a **.dockerignore**, **Dockerfile** and **docker-compose.yml** file added to the root of the Kitura project.

**.dockerignore**
```
.DS_Store
.build
Packages
*.xcodeproj
```

**Dockerfile**
```
# Kitura Linux Unit test
FROM ibmcom/swift-ubuntu:latest
ADD . ./
RUN swift build -Xcc -fblocks
CMD swift test
```

**docker-compose.yml**
```
version: '2'
services:
  test:
    build: .
```

A "docker-compose up" does a build and a test run in one command.  Very handy.

Another improvement would be to have the ibmcom/swift-ubuntu Docker image have tags for each Swift release, so unit tests could be easily changed to test against different Swift development releases.

* ibmcom/swift-ubuntu:2016-05-31-a
* ibmcom/swift-ubuntu:2016-06-06-a
* ibmcom/swift-ubuntu:2016-06-20-a
* etc...

**Comment by rolivieri** [comment]
@dsperling - The release of Docker for Mac is very much welcome indeed!

Regarding the `docker-compose.yml` file, we just recently added one to the *develop* branch of the Kitura-Starter-Bluemix repo: https://github.com/IBM-Swift/Kitura-Starter-Bluemix/blob/develop/docker-compose.yml

Adding a `docker-compose.yml` to this repo for testing sounds great and useful. If we have a `volumes` and a `command` entries to the `docker-compose.yml` file, we could then build and test the package, without adding a `.dockerignore` and a `Dockerfile` to this repo. What do you think?

**Comment by dsperling** [comment]
@rolivieri - Yes, of course!  Here is a solution following the lead of Kitura-Starter-Bluemix:

```
test:
  image: ibmcom/swift-ubuntu
  volumes:
    - ./:/root/test/
  command: bash -c "cd /root/test && rm -rf .build && swift build -Xcc -fblocks && swift test"
```

The `rm -rf .build` step is required if a `swift build` command has previously been issued on the Mac.

**Comment by rolivieri** [comment]
@dsperling That looks good, thanks! Regarding the build command to use in the `docker-compose.yml` file; the team [as of now] relies on a makefile to abstract the actual swift build command and flags for building on Linux. I believe that once `libdispatch` is included with the Swift 3 binaries, then `swift build` should be all needed to compile on Linux (and at that time we should be able to remove the dependency on the makefile). In the meantime, we’d like to have all build commands go through the makefile. This would change the command entry to: `bash -c "make clean -C /test && make -C /test && make test -C /test"`

**Comment by dsperling** [comment]
@rolandoasmat Works great.  PR #575

**Comment by rolivieri** [comment]
@dsperling Thanks for your contribution. The PR has been merged.
