### ISSUE TITLE
FastCGI

### ISSUE THREAD

**Issue by simplepanda** [IBM-Swift/Kitura#565]
Greetings all. Are there any plans by any current committers to work on adding a FastCGI connector to Kitura?

**Comment by ianpartridge** [comment]
Not that I am aware of.  We would welcome contributions though!

**Comment by simplepanda** [comment]
Great. I'm going to start looking at updating Kitura-Net and Kitura to handle binding a Router to a FastCGI server. I'm a little worried about some semantics in the code (objects explicitly named HTTPxxxx) but I think FastCGI is a good approach for a project like Kitura. 

Nginx (with HTTP/2 SSL) serving static files and back-ending to Kitura over FastCGI seems like a dream solution for a lot of projects I'm working on right now.

**Comment by ianpartridge** [comment]
@shmuelk and @dfirsht might have ideas on this.

**Comment by simplepanda** [comment]
I've done a bit of work on this on a fork.

So far I have a working addFastCGIServer(onPort, with) call working and I'm receiving FastCGI requests from an Nginx server. 

I'm just working on parsing FastCGI down in such a way that I can pass it off to the Router.handle() transparently. I may be able to push something working to my forks and put up a demo of Nginx->Kitura this week, time permitting. :)

**Comment by simplepanda** [comment]
So I kinda lost track of time and as a result I have the entire request chain for FastCGI done in prototype. FastCGI requests come in from Nginx, headers are all decoded, and the Router then routes the request to a custom handler just like an HTTP request would. Responses are sent back from the user handlers but I haven't implemented FastCGI response encoding yet.

I'll do that tomorrow evening if I get a chance.

I still have to clean the code up before I push it and I have to implement a few FastCGI-isms (such as rejecting unknown / non-responder roles and rejecting multiplexed connection attempts (Kitura isn't really architected to allow for this) - but all in all it's coming together really quickly.

**Comment by ianpartridge** [comment]
Sounds exciting - keep us updated. I don't know how extensive your changes to Kitura are, but if possible we'd appreciate bite-sized patches :)

**Comment by simplepanda** [comment]
Sounds good. 

Almost all of my changes are against Kitura-Net#develop, which seems pretty quiet commit wise.

I think I can streamline it into a few separate pull requests from a fresh fork if you have some commentary on the concept:

1) Renaming IncomingMessage to HTTPIncomingMessage. This seems to back HTTP exchange for both the ClientRequest and ServerRequest object (as a super class) so it's clearer if this is labeled as HTTP related. Related patches to support this rename.
2) Renaming ServerRequest to HTTPServerRequest and then creating a ServerRequest class protocol that HTTPServerRequest implements. This allows the bulk of the code to carry on agnostically referring to a ServerRequest object.
3) Renaming ServerResponse to HTTPServerResponse and then creating a ServerResponse class protocol class that HTTPServerResponse implements.  Again, this allows the bulk of the code to carry on being agnostic about transport.
4) Implemented a FastCGIServer, FastCGIServerRequest, and FastCGIServerResponse class. Then Request/Response classes implement ServerRequest and ServerResponse, the same as their HTTP cousins. Like the HTTP implementation already does, all of Kitura->Socket communication is happening here.
5) There is a small patch to the main Kitura project to add support for FastCGI by adding an addFastCGIServer() method and the related data structures and listen loop.

Are any alarm bells going off, concept wise, for you?

**Comment by ianpartridge** [comment]
This sounds like a sensible approach to adding FastCGI, to me.  @shmuelk our architect can give his views, and @dfirsht too.

**Comment by simplepanda** [comment]
Ok, I have a prototype running:
http://swift.codeandstrings.com

nginx/1.10.0 on Ubuntu Xenial talking to Kitura over FastCGI. My "main.swift" for my Kitura app looks like this:

```
import Kitura
import Foundation

func shell() -> String {
    let task = NSTask()
    task.launchPath = "/bin/uname"
    task.arguments = ["-a"]
    
    let pipe = NSPipe()
    task.standardOutput = pipe
    
    task.launch()
    task.waitUntilExit()
    
    let fileHandle = pipe.fileHandleForReading
    let data = fileHandle.readDataToEndOfFile()
    let osString = String(data: data, encoding: NSUTF8StringEncoding)
    
    return osString!
}

let router = Router()

router.get("/") {
    request, response, next in

    response.send("<html>")
    response.send("<head><title>Kitura FastCGI Prototype</title></head>")
    response.send("<body>")
    response.send("<h1>Kitura FastCGI</h1>")
    response.send("<p>Running on: \(shell())</p>");
    
    response.send("<h2>Header Environment</h2>")
    response.send("<hr>")
    
    for (key, value) in request.headers {
        response.send("<b>\(key):</b> \(value!)<br>");
    }
    
    response.send("</body></html>");

    next()
}

Kitura.addFastCGIServer(onPort: 9000, with: router)
Kitura.run()
```

**Comment by shmuelk** [comment]
@simplepanda Fundamentally this sounds great!

Don't forget to sign and submit a CLA, if you haven't done so already.

**Comment by simplepanda** [comment]
I'll submit the IBM CLA shortly. :)

Quick question in terms of how to structure something in that hopefully @shmuelk @ianpartridge et al could weigh in on:

FastCGI passes many parameters to the application (Kitura) that contain both metadata describing the original/actual Web->Client relationship (for example "REQUEST_METHOD", "SERVER_PROTOCOL", "REMOTE_ADDR") as well as metadata describing the web server environment itself (things like "DOCUMENT_ROOT", "SERVER_SOFTWARE", etc).

Actual HTTP header variables sent by the client/browser (received on the web server side) are delivered via FastCGI as "HTTP_<HEADER NAME>". I've already added some code to the version I have baking that case/dash converts these down and adds them as proper headers for Kitura (HTTP_ACCEPT_LANGUAGE is added to the HeaderContainer as "Accept-Language").

My code transposes the key FastCGI specific headers into the ServerRequest object (for example, "REQUEST_METHOD" from FastCGI gets set in the "method" variable, "SERVER_PROTOCOL" gets set in the httpVersionMajor and httpVersionMinor variables, etc)...

But my question for the group is: what to do with the rest of the FastCGI specific headers? Should I simply discard them without adding them to HeaderContainer, or would it be beneficial to keep them? Since I'm trying to keep the FastCGI implementation as agnostic as possible for people building apps on Kitura, it seems like adding additional calls to ServerRequest is a no-go.

Perhaps adding them to HeaderContainer as "FASTCGI_<FASTCGI VARIABLE NAME>" so they can be accessed, but keeping them from colliding with anything via the "FASTCGI_" prefix? 

Thoughts?

**Comment by simplepanda** [comment]
Also @dfirsht , I noticed you mentioning in some other issue discussions that you're getting people to issue PR's against the master branch. Is this applying/going to apply to Kitura-net as well?

**Comment by ianpartridge** [comment]
Hi @simplepanda yes, we're going to move to working with PRs against `master` - in common with most GitHub projects.

**Comment by simplepanda** [comment]
Note in addition to the automatically added PR above, there is a second pull on Kitura-net related to this issue:
https://github.com/IBM-Swift/Kitura-net/pull/42

**Comment by simplepanda** [comment]
I'm just getting the last test units ready for my FastCGI commit. Will PR that (and reference here) in a day or two when I'm happy with the tests.

**Comment by simplepanda** [comment]
Just a heads up that I closed a PR and submitted a cleaner one from a branch of my fork just to make the PR changes a little easier to read.

**Comment by simplepanda** [comment]
Just FYI I PR'd #618 to enable FastCGI in Kitura but I know you guys have the various migration tasks going on right now so will chill on it passing CI, etc. Let me know if there is anything else you need me to do to get it merged.

**Comment by simplepanda** [comment]
Sorry, I found a tiny bug in my Kitura-net code related to port numbers. Will submit another PR on that before I PR against Kitura to fully enable support.

**Comment by simplepanda** [comment]
I think this is largely wound up in terms of actual issue deployment and will probably move into maintenance / enhancement issues (keepalive/multiplexing/performance/etc). Once Kitura proper is tagged and FastCGI starts appearing in Package Manager pulls, I think it's probably safe to close this. Yes? @ianpartridge @shmuelk
