### ISSUE TITLE
Update docker instructions for using Docker for Mac.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura#572]

**Comment by dfirsht** [comment]
@rolivieri Can you provide more details on what this issue entails?

**Comment by rolivieri** [comment]
I just haven't had time to get to it. Basically, if using Docker for Mac, then there is no need to follow all the steps I documented [in the Wiki] months ago in order to access the Kitura port inside the docker container.

**Comment by youming-lin** [comment]
I have updated the wiki page with instructions on how to expose the Docker container port if the user is developing on the new Docker for Mac app: https://github.com/IBM-Swift/Kitura/wiki/Expose-Kitura's-Port-in-Docker-Container-to-Host-Machine
