### ISSUE TITLE
Cannot build with XCode

### ISSUE THREAD

**Issue by tomasgibas** [IBM-Swift/Kitura#574]
I followed this tutorial [here](https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-on-XCode) to setup xcode project. Also added Library Search Paths $SRCROOT/.build/debug, for both Kitura and Kitura Net targets, But I am still receiving ld: library not found for -lCHttpParser for architecture x86_64 error. Using Swift development snapshot 2016-06-06 (a). .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 20)

**Comment by krugazor** [comment]
It is currently a bit wonky, but the xcode generated project contains only frameworks, and in the case of CHttpParser, the output should be a modulemap and a dylib (as seen if you build from the commandline).

The workaround is to add a new target to the project that will build the dylib file:
- new target, type library, dynamic
- in the build settings of that target, change the name (you won't be allowed to use CHttpParser, as it's used by the framework build, and you probably shouldn't remove that one, so let's assume you named it something like "CHttpParserLib") to CHttpParser
- you should see under "products" in your navigator something called libCHttpParser.dylib
- in the build phases of that target, add the 2 CHttpParser files (http_parser.c and utils.c)
- add that target as a dependency of the framework CHttpParser
- build & profit

It *looks* convoluted, but it's really hyper detailed to make sure there is no ambiguity, and is done in a handful of seconds. Hope that helps

**Comment by dfirsht** [comment]
@tomasgibas, did @krugazor's comment help? If you are still having trouble, you can post your project.

**Comment by yocaminobien** [comment]
@krugazor, @dfirsht 
I did all step by step and now I has error "library not found for -lCHttpParser" inside CHttpParserFramework itself. Looks a bit recursive (. 
Any ideas what could be wrong?

**Comment by tomasgibas** [comment]
@krugazor, @dfirsht Yes it helped me. Thanks a lot.

**Comment by krugazor** [comment]
@yocaminobien you need to add the new target (the dylib) to the link phases of the framework, and that should be enough.

I have forgotten to specify that step here:
> add that target as a dependency of the framework CHttpParser

it's both a dependency in the sense of build and in the sense of link.

**Comment by yocaminobien** [comment]
@krugazor Thanks a lot. Yes, it is working now

**Comment by yocaminobien** [comment]
Possible somebody could update wiki to mention this step

**Comment by krugazor** [comment]
It is a bug in the new swift release that didn't happen before, as far as I can tell, it will hopefully be fixed before the final version

**Comment by ianpartridge** [comment]
Thanks. Is everyone OK with this issue being closed now?

**Comment by krugazor** [comment]
@ianpartridge is there a way to "close" it but still keep it visible, until the swift package manager is updated? I'm assuming it surprises a lot more people than the ones participating in this thread...

**Comment by ianpartridge** [comment]
Hi, I think our wiki explains things. Plus people can always include closed issues in their searches.
