### ISSUE TITLE
Error in using .keys parameter with one multiple attribute key in CouchDB database.queryByView

### ISSUE THREAD

**Issue by GilGS** [IBM-Swift/Kitura#576]
the database.queryByView function cannot get one precise key but only startKey and endKey - The use of .keys parameter with one key consists of 2 attributes dosn't work.

following the next steps will show up exactly the bug:

1. **write the next few lines to create a sample Database named 'bugDB', a design named 'mydesign', a document with one row, and a view named temp that will include only that row:**
"curl -X PUT http://127.0.0.1:5984/bugDB"
"curl -vX PUT http://127.0.0.1:5984/bugdb/_design/mydesign -d '{"_id" : "_design/mydesign"}"
"curl -vX POST http://127.0.0.1:5984/bugdb -d '{"name":"John","id": "7"}"
"curl -vX PUT http://127.0.0.1:5984/bugdb/_design/mydesign -d '{"_id": "_design/mydesign", "views" : {"temp" : { "map" : "function(doc){ emit([doc.name, doc.id], doc) } }" } }}'"

2. **write a Package.swift file to include CouchDB. it will look like:**
import PackageDescription

    let package = Package(
        name: "CouchDBBug",
        dependencies: [
           .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 0, minor: 15),
        ])

3. **write a main.swift source file that will build the CouchDB cliend and call the database.queryByView function with the required .keys: running that code will conclude in printing "no matching results", which indicated on a problen in quering.**

    import CouchDB

    let connProperties = ConnectionProperties(
        host: "127.0.0.1",         // httpd address
        port: 5984,         // httpd port
        secured: false,   // https or http
        username: nil, // username
        password: nil  // password
)

    // Create couchDBClient instance using conn properties
    let couchDBClient = CouchDBClient(connectionProperties: connProperties)

    // Create database instance to perform any document operations
    let database = couchDBClient.database("bugdb")

    let key = ["John","7"]
    database.queryByView("temp", ofDesign: "mydesign", usingParameters: [.keys(key)]) {
        json, error in
        guard let json = json else {
            print("error in json returned")
            return
       }
    let rows = json["rows"].arrayValue 
    guard let answer = rows.first else {
        print("no matching results")
        return
    }
    print("the result json is:\n \(answer["value"])")
}

4. **replacing "database.queryByView("temp", ofDesign: "mydesign", usingParameters: [.keys(key)]) " with 
"database.queryByView("temp", ofDesign: "mydesign", usingParameters: [.startKey(key), .endKey(key)])" 
will work perfectly, and print the result json as required, which points on the bug when using the .keys parameter.**

**Comment by dfirsht** [comment]
@shmuelk any thoughts on this?

**Comment by shmuelk** [comment]
@GilGS There are two issues here as we discussed ofline:

  1. A bug in Kitura-CouchDB. I'll push a fix shortly
  2. the .keys enum takes an array of keys. If each key is made up multiple attributes, then each key must itself be an array. In other words in your test case, the line: ```swift
database.queryByView("temp", ofDesign: "mydesign", usingParameters: [.keys(key)]) {
``` should have been: ```swift
database.queryByView("temp", ofDesign: "mydesign", usingParameters: [.keys([key])]) {
``` Note the brackets around the key in the .kes enum.
