### ISSUE TITLE
Attaching BodyParser twice to a query causes returning empty body

### ISSUE THREAD

**Issue by GilGS** [IBM-Swift/Kitura#577]
when attaching BodyParser to a query twice (even if by mistake) it causes a return of an empty body to the query.

for example:
when writing -
          "router.all(basePath + super.path + "/diagnosis", middleware: BodyParser())
           router.all(basePath + super.path + "/diagnosis", middleware: BodyParser())
           router.post(basePath + super.path + "/diagnosis") { request, response, next in..."

request.body will afterwards be nil, even though a body was inserted correctly and in the right format.

**Comment by dfirsht** [comment]
Validated and merged.
