### ISSUE TITLE
Implement CORS middleware

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#585]

**Comment by shmuelk** [comment]
In Sources/KituraCORS/CORS.swift:

  1. Line 79: Shouldn't that include `alowed = true`
  2. Line 89: Shouldn't that be != 0

**Comment by irar2** [comment]
1. This function shouldn't be called with .all, so this case is unreachable. 
2. I think we need exactly one match here, we are trying to match a URL with a regex.
