### ISSUE TITLE
[CLOSED] Build and execute test cases as part of CI build in Travis.

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#59]
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Friday Jan 22, 2016 at 18:57 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/59_

---

**Comment by aniruddhaadak80** [comment]
Even though it is closed, hooking the test execution directly into the CI pipeline block guarantees PRs don't regress. Moving off older Travis pools often speeds this up significantly anyway.
