### ISSUE TITLE
Migrate to 06/20 Swift binaries

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#590]
- [x] LoggerAPI (no changes)
- [x] SwiftyJSON
- [x] KituraSys 
- [x] KituraNet
- [x] Kitura
- [x] HeliumLogger
- [x] KituraSample (CI changes only)
- [x] CouchDB
- [x] Redis 
- [x] Kitura-TemplateEngine (no changes)
- [x] Kitura-Session
- [x] KituraCredentials
- [x] KituraCredentialsHTTP
- [x] KituraCredentialsGoogle
- [x] KituraCredentialsFacebook
- [x] Kitura-Credentials-Sample (no changes)
- [x] Kitura-Session-Redis
- [ ] GRMustache - will be done in the next sprint
- [ ] Kitura-MustacheTemplateEngine - will be done in the next sprint
- [ ] Kitura-Cache - problems with DispatchSourceTimer (on OSX)
- [x] Kitura-Compression

**Comment by dfirsht** [comment]
Migration validated via CI.
