### ISSUE TITLE
The dependency graph could not be satisfied

### ISSUE THREAD

**Issue by Baam25** [IBM-Swift/Kitura#592]
The dependency graph could not be satisfied (https://github.com/IBM-Swift/SwiftyJSON.git)

getting the above error if I use swift 06-06 snapshot and Kitura version 21.

**Comment by ianpartridge** [comment]
Do you have a git project I can clone to recreate this problem?

**Comment by Baam25** [comment]
https://github.com/Baam25/MyExamples.git

**Comment by rfdickerson** [comment]
@chiahuang and I are having the exact same issue with our [TodoList Redis](https://github.com/IBM-Swift/todolist-redis) build. Changing the dependency from Kitura-Sys to Kitura-Net fixes the problem, strangely.

**Comment by ianpartridge** [comment]
This is because https://github.com/IBM-Swift/Swift-cfenv depends on version 7 of SwiftyJSON, but Kitura depends on version 9.

@rolivieri can you update Swift-cfenv to run on the 06-06 snapshot with version 9 of SwiftyJSON?

**Comment by rolivieri** [comment]
@ianpartridge The develop branch of Swift-cfenv has already been migrated to Swift 06-06. We haven't  merged that branch yet with master because we are still in the process of upgrading/installing the buildpack in Bluemix. Folks can still reference the latest tag for Swift-cfenv (v1.3.0) which supports Swift 06-06.

**Comment by rfdickerson** [comment]
Yeah, I think there isn't an issue with Swift-cfenv and Kitura. We have shown that to work fine. The problem emerges when we add Kitura-Redis to the dependency list. There is now a collision on Kitura when it builds.

**Comment by ianpartridge** [comment]
Thanks @rolivieri I didn't realise there was a tag which supported 06-06.

@rfdickerson - the example project from @Baam25 doesn't use Kitura-Redis, so perhaps you have a different issue?

**Comment by ianpartridge** [comment]
@Baam25 - I made this change to your project, and the problem reported is fixed.

```
-                      .Package(url: "https://github.com/IBM-Swift/Swift-cfenv", majorVersion: 1, minor: 2)
+                      .Package(url: "https://github.com/IBM-Swift/Swift-cfenv", majorVersion: 1, minor: 3)
```

There are other compilation issues with your project but they are unrelated.

**Comment by Baam25** [comment]
@ianpartridge @rolivieri  thanks :)

**Comment by rfdickerson** [comment]
We have identified our problem.

todo-redis was using Kitura-0.19 and Kitura-Redis 0.18
Kitura-0.19 was using Kitura-Net 0.19
Kitura-Redis-0.18 was using Kitura-Sys 0.18

So the conflict was on Kitura-Sys 0.18 and 0.17. We have decided to make Kitura-Redis use 0.17 to see if it fixes our problem. 

(I had to draw a tree on a sheet of paper to solve this issue)

**Comment by ianpartridge** [comment]
Ugh, SwiftPM really should help diagnose these things.....
