### ISSUE TITLE
Body for the RouterRequest is always nil when i make a post request

### ISSUE THREAD

**Issue by pahmed** [IBM-Swift/Kitura#593]
Hi,

When i make a post request, i always find the `body` property of the `request` with nil value, i was able to fix this by setting the `body` in the `RouterRequest` initializer (`init(request: ServerRequest)`) using `BodyParser.parse`, but i'm not sure if this the right way to fix the issue.

**Comment by ianpartridge** [comment]
I'm sorry, I don't quite follow you.  Could you give some more information and code showing the problem?

**Comment by pahmed** [comment]
I've a router implementing a post method like this

```
router.post("/add") { request, response, next in

}
```

The problem is whenever the client sends a request with body, i found that the the `body` property is not set, but when i call `request.readString()` it returns the body as string

**Comment by ianpartridge** [comment]
Hi @pahmed - thanks, I understand your issue now.

You can use `request.readString()` to get the body as a string, or you can add the `BodyParser` middleware to handle this automatically from the Content-Type.

See https://github.com/IBM-Swift/Kitura/blob/bc30b9cf5e2f28d3e47a6e4ce29e39848f9a2ccb/Tests/Kitura/TestResponse.swift#L648 for an example of this.

Does this work for you?

**Comment by pahmed** [comment]
Yeah thank you :)

**Comment by twobitunicorn** [comment]
Hi.  Following this line of discussion: what should the call `request.body` return?  I have yet to see this to be anything but nil when dealing with POST requests.

**Comment by ianpartridge** [comment]
Are you using Codable routing or the "request, response, next" style routes? Are you using the bodyparser middleware and if so, which routes is it attached to?

**Comment by twobitunicorn** [comment]
Hi @ianpartridge.  Here is a chunk of code:
```        
router.post("/") {request, response, next in
            print(request.body)
}
```

What should this print for request.body?  The documentation states that this will be nil until some parsing has been in place.  But then, the body is not nil if there is one provided, just not parsed.  I think this maybe where the confusion comes from.  What do you think?  And thanks for getting back!

**Comment by ianpartridge** [comment]
Hi @twobitunicorn you need to attach a `BodyParser` middleware to your route. Have a look at https://www.kitura.io/en/guides/parsingrequests.html - in the section "Parsing JSON Posts". The same principle applies for non-JSON body data too.

**Comment by twobitunicorn** [comment]
Hi @ianpartridge , thanks for putting this up.  The link is no longer valid.   I can't seem to find it on the Kitura website anywhere.  Any chance you know where it moved to?  Thanks!

**Comment by twobitunicorn** [comment]
A small proposal for this thread: What would you think about having  `body` be a `Data` type so that people can unserialize as they want, for example
```
let json = try? JSONSerialization.jsonObject(with: request.body, options: []) 
```
And refactor the current `body` to `parsedBody` with the same option of being `nil` if the body has not been parsed by the middleware?

**Comment by ianpartridge** [comment]
We're still in the process of moving over all the guides to the new site. For now, here's a link to that guide from the old site: https://github.com/IBM-Swift/kitura.io/blob/2a2883f7354b29994ba237c74744311b1e6e0134/en/guides/parsingrequests.md

**Comment by ianpartridge** [comment]
Your idea of `request.body` being a Data is interesting, but would be a breaking API change so couldn't be done during Kitura 2.x.

You can do something very similar already though:

```swift
let json = try? JSONSerialization.jsonObject(with: request.body?.asRaw, options: [])
```

**Comment by twobitunicorn** [comment]
awesome, thanks!   Any thoughts on my question above?

**Comment by ianpartridge** [comment]
I'm sorry, which question? 😁 

Can you include a full code example?

**Comment by twobitunicorn** [comment]
Hahha, sorry, we must have been typing at the same time!  😊 Yes, I see what you are saying now.  But even with
```
let json = try? JSONSerialization.jsonObject(with: request.body?.asRaw, options: [])
```
this will still be ```nil``` without a middleware parser as ```body``` will be ```nil```.  Another option maybe to have a default middleware parser that that sets the body to the ```Data``` type unless assigned another middleware parser.

Got this working for what I need.  Thanks again for your recommendation!
