### ISSUE TITLE
Could not find service BluePic-Insights-for-Weather to bind to .....

### ISSUE THREAD

**Issue by chuckbrant** [IBM-Swift/Kitura#595]
Using the "easy button" within the readme, the deployment fails with "Could not find service BluePic-Insights-for-Weather to bind to ....."

**Comment by kweinmeister** [comment]
Moving this issue to the [BluePic repo](https://github.com/IBM-Swift/BluePic)

**Comment by kweinmeister** [comment]
Issue moved to [IBM-Swift/BluePic #292](https://github.com/IBM-Swift/BluePic/issues/292) via [**ZenHub**](https://www.zenhub.com/)
