### ISSUE TITLE
Security Policy for the Server

### ISSUE THREAD

**Issue by nmvijay** [IBM-Swift/Kitura#596]
As the servers are hosted in highly secure environments, we should have a policy file which should define what swift code can access/do in the host server and what it cannot. Something similar to Java Security Policy file

Ref: http://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html

**Comment by ianpartridge** [comment]
How could this work, bearing in mind that Kitura apps are natively compiled and can call arbitrary C code?

**Comment by nmvijay** [comment]
@ianpartridge I got your point, this feature may not be required at this point of time, as Swift language is still evolving, but when Swift starts to offer features (if at all) like JINI or RMI etc...where the code is downloaded from remote location which is untrusted, the programs are expected to work in sandbox. Moreover Security policy should be part of the Language not Kitura, may be my feature request was at the wrong forum.

**Comment by simplepanda** [comment]
@nmvijay Swift has no need for JNI in that Swift is a native language. You can talk to Glibc or Darwin directly within Swift without writing any bridging code and compiled Swift is as native as compiled C is once LLVM is done with it.

As for RMI, that's kind of a dead model in my experience. I can't remember the last time I used RMI and I write a lot of remote execution code in Java. REST is everything now: Parameters out, response data in. This is as secure as you want to make it in terms of your code. 

As for sandboxing your code - this is where Docker (or the container mechanism of your liking) really shines.

**Comment by ianpartridge** [comment]
Yes, I think this is a much larger issue than can be covered under one Kitura issue.  If you have specific bugs or feature requests please raise them separately.
