### ISSUE TITLE
Connect SwiftyJSON to Travis

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#599]
Depends on https://github.com/IBM-Swift/Kitura/issues/598 .

**Comment by dfirsht** [comment]
I am unable to do this until I have admin rights on SwiftyJSON.

**Comment by dfirsht** [comment]
CI is set up and passing: https://travis-ci.org/IBM-Swift/SwiftyJSON/builds/147856264

**Comment by irar2** [comment]
It fails now with:
xcodebuild: error: 'SwiftyJSON.xcworkspace' does not exist.

**Comment by dfirsht** [comment]
@irar2 @shmuelk I do not see this 10.0.2 branch. Make sure your branch is up to date with master.
