### ISSUE TITLE
Add SSL/HTTPS tunnel for Kitura

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#60]
<a href="https://github.ibm.com/rfdickerson"><img src="https://avatars.github.ibm.com/u/1506?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rfdickerson](https://github.ibm.com/rfdickerson)**
_Saturday Jan 23, 2016 at 00:52 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/60_

----

Phoenix should eventually support SSL encryption (for instance on port 443). 

As a way to better understand how module maps to C libraries work, I created a webserver in Swift that uses OpenSSL to promote a connection to TLS 1.2. The following works, and can probably be easily integrated into Phoenix.

```swift
// Wrapper around libssl for Swift

#if os(OSX)
    import Darwin
#elseif os(Linux)
    import Glibc
#endif

import CCrypto
import Foundation

enum SocketType: Int32 {
case Stream = 1
case Datagram = 2
}
 
private func sockaddr_cast(p: UnsafePointer<sockaddr_in>) -> UnsafePointer<sockaddr> {
  return UnsafePointer<sockaddr>(p)
}

private func mutable_sockaddr_cast(p: UnsafePointer<sockaddr_in>) -> UnsafeMutablePointer<sockaddr> {
  return UnsafeMutablePointer<sockaddr>(p)
}

/**
* SSL abstracts the SSL connection
**/
public class SSLServer {

  var sslctx: UnsafeMutablePointer<ssl_ctx_st> = nil

  var cSSL: UnsafeMutablePointer<ssl_st> = nil
  
  init() {
    // load the error strings API
    SSL_load_error_strings()

    // load encryption and hash algorithms for SSL
    SSL_library_init()
    
    OPENSSL_add_all_algorithms_noconf()
    print("SSL initialized")

    
    
  }

  func listenConnections() {

    // var sockfd: Int32 = 0
    var newsockfd: Int32 = 0
    let sockfd = socket(AF_INET, SocketType.Stream.rawValue, 0)

    var remoteAddr: sockaddr_in = sockaddr_in()
    var remoteAddrSize: socklen_t = 0
    
    var addr: sockaddr_in = sockaddr_in()
    memset(&addr, 0, sizeof(sockaddr_in))

    addr.sin_family = UInt16(AF_INET)

    addr.sin_port = UInt16(8090).bigEndian

    let servAddrSize : UInt32 = UInt32(sizeofValue(addr))
    
    if bind(sockfd, sockaddr_cast(&addr), servAddrSize) != -1 {
      let listenRc = Glibc.listen(sockfd, 5)
    }

    listen(sockfd, 5)

    print("Listening for connections...")

    while true {
    newsockfd = accept(sockfd, mutable_sockaddr_cast(&remoteAddr), &remoteAddrSize)

    sslctx = SSL_CTX_new( SSLv23_server_method())
    // SSL_CTX_set_options(sslctx, SSL_OP_SINGLE_DH_USE)
    SSL_CTX_ctrl( sslctx, SSL_CTRL_OPTIONS, SSL_OP_SINGLE_DH_USE, nil)
    let use_cert = SSL_CTX_use_certificate_file(sslctx, "./serverCertificate.pem", SSL_FILETYPE_PEM)
    if use_cert <= 0 {
      print("Could not load certificate file")
    }
    
    let use_prv = SSL_CTX_use_PrivateKey_file(sslctx, "./key.pem", SSL_FILETYPE_PEM)
    if use_prv <= 0 {
      print("Could not use private key")
    }
    
    cSSL = SSL_new(sslctx)

    SSL_set_fd(cSSL, newsockfd )

    print("New socket fd is \(newsockfd)")
    let ssl_err = SSL_accept(cSSL)

    if ssl_err <= 0 {
      print("Error code \(ssl_err): Problem setting up SSL socket")
    }
    
    SSL_write(cSSL, "Hello world\n", 12)
    print("Writing Hello world through socket")
      close(newsockfd)
    }
    
  }
  

  deinit {
    ERR_free_strings()
    EVP_cleanup()
    print("SSL deinitialized")
  }

}

let server = SSLServer()

server.listenConnections()
```

You can generate private keys and server certificate using

```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out serverCertificate.pem
```

You can test the client connection to the server using:

```
openssl s_client -connect localhost:8090
```

**Comment by matteocrippa** [comment]
A little doubt, is https really needed? I mean I think that if Kitura will be used in any production env it will stay under a proxy server like nginx that will be able to manage that without any issue.
In my past each time I worked with eg. Express.js I always used nginx to manage and proxy https call.

**Comment by rfdickerson** [comment]
You bring up an interesting point that nginx or other proxy server is typically used for applying the SSL tunnel around web containers. I think there needs to be on going conversations regarding the scope of Kitura.

**Comment by rolivieri** [comment]
Wouldn't we need SSL support for outbound connections? For instance, connecting to Cloudant databases on Bluemix.

**Comment by rfdickerson** [comment]
Oh, interesting point. @shmuelk, do we have something on the roadmap for something like Node's [Request](https://github.com/request/request) library that simplifies making requests as a client? My focus has been mostly on providing support of SSL as a server which requires a certificate file and private key.

**Comment by rolivieri** [comment]
I think we should have this in the roadmap. For instance, our requests right now to Cloudant are done over HTTP... no security at all. And Cloudant is just one of the many possible services/middleware developers would want to integrate with in a secure way.

**Comment by shmuelk** [comment]
Please look at the Http class in KituraNet.

There already is a HttpClient. Kitura-CouchDB even uses it. It is basd on libCurl, so we should have SSL support. We need to expose a way to set up credentials.

**Comment by rfdickerson** [comment]
I'm adding this link for reference on how to do [SSL with libcurl](https://curl.haxx.se/libcurl/c/simplessl.html)

**Comment by ianpartridge** [comment]
Fixed.
