### ISSUE TITLE
Migrate to 07/05 Swift version

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#600]
- [x] LoggerAPI (no changes) 
- [ ] SwiftyJSON
- [x] KituraSys  (no changes) 
- [x] KituraNet
- [x] Kitura
- [x] HeliumLogger (no changes) 
- [x] KituraSample (no changes) 
- [x] CouchDB  (no changes) 
- [x] Redis (no changes) 
- [x] Kitura-TemplateEngine (no changes) 
- [x] Kitura-Session  (no changes) 
- [x] KituraCredentials  (no changes) 
- [x] KituraCredentialsHTTP  (no changes) 
- [x] KituraCredentialsGoogle (no changes) 
- [x] KituraCredentialsFacebook (no changes) 
- [x] Kitura-Credentials-Sample (no changes) 
- [x] Kitura-Session-Redis
- [ ] GRMustache
- [ ] Kitura-MustacheTemplateEngine
- [ ] Kitura-Cache
- [x] Kitura-Compression (no changes)

**Comment by dfirsht** [comment]
We have decided to not migrate to this version and instead move to the 07/25 drop.
