### ISSUE TITLE
Update wikis in Kitura

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#604]

**Comment by simplepanda** [comment]
I'll write a some documentation for the Wiki dealing with: 

a) Adding a FastCGI listener to a Kitura app
b) Configuring Nginx to use Kitura FastCGI
c) Configuring Apache / mod_proxy_fcgi to use Kitura FastCGI

Once the last patches to Kitura and Kitura-net to enable FastCGI support are merged in.

**Comment by shmuelk** [comment]
I have updated the following pages:

  1. Setting up in XCode page (very minor)
  2. Testing with XCTest
  3. Building a TodoList server.

I will point out that page for Building a TodoList server while now accurate is very very incomplete.

Do we want a complete step by step tutorial, or just a get someone in the right general direction tutorial?

**Comment by kweinmeister** [comment]
@rfdickerson FYI, you might have some thoughts on point 3 and questions above from @shmuelk

**Comment by simplepanda** [comment]
I added my FastCGI documentation as a markdown file in /Documentation. Not sure if someone wants to migrate that to a wiki or leave it in place.

**Comment by ianpartridge** [comment]
I'm working on a documentation revamp and will be consolidating all this into something (hopefully) a lot more user-friendly.

**Comment by dfirsht** [comment]
Looks good.
