### ISSUE TITLE
getContentType fails for certain file names

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/Kitura#605]
In my application I try to call `getContentType` like so:

    ContentType.sharedInstance.getContentType(forFileName: "Screen Shot 2016-07-05 at 1.18.18 PM.png")

I believe it is failing because there are multiple periods in the file name. Looking further, I found the `getContentType(forExtension:` method ends up with this string: `"18.18 PM.png"`. After all that, the method returns nil

**Comment by ianpartridge** [comment]
@tfrank64 I think https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/contentType/ContentType.swift#L114 should specify `options: NSStringCompareOptions.backwardsSearch` - can you see if that fixes it?

**Comment by tfrank64** [comment]
@ianpartridge I changed that line to use this

    fileName.range(of: ".", options: NSStringCompareOptions.backwardsSearch, range: lastPathElemRange, locale: nil)
That seemed to work, is that what you were talking about?

**Comment by ianpartridge** [comment]
Yes, I think that's the fix.

**Comment by ianpartridge** [comment]
Did you have to specify the locale?  I think there's a default so it shouldn't be necessary.

**Comment by tfrank64** [comment]
I did not, just set it to nil in that method.

**Comment by ianpartridge** [comment]
Sorry, I don't quite follow. Does this work?

```swift
if let lastDot = fileName.range(of: ".", options: NSStringCompareOptions.backwardsSearch, range: lastPathElemRange) {
    extRange = fileName.index(after: lastDot.lowerBound)..<fileName.characters.endIndex
} else {
    // No "extension", use the entire last path element as the "extension"
    extRange = lastPathElemRange
}
```

**Comment by tfrank64** [comment]
Yes that works, I didn't know I could remove the locale parameter.
I guess we can go with this fix?

**Comment by ianpartridge** [comment]
Yes I think so.  I'll fix it - thanks!
