### ISSUE TITLE
Use SwiftLint to enforce code conventions in Kitura

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Swift/Kitura#614]
* [ ] Determine which rules we should use, and create a `swiftlint.yml` with the rules
* [ ] Remediate issues found in each Kitura repo
* [ ] Include `swiftlint.yml` in each Kitura repo
* [ ] Update Travis CI as needed for each Kitura repo
* [ ] Update [CONTRIBUTING.md](https://github.com/IBM-Swift/Kitura/blob/master/.github/CONTRIBUTING.md) with Swiftlint requirement in each repo

**Comment by ianpartridge** [comment]
@vadimeisenbergibm this should link up with your CodingStyle work.

**Comment by vadimeisenbergibm** [comment]
Depends on https://github.com/IBM-Swift/Kitura/issues/254

**Comment by rob-deans** [comment]
When running `swiftlint` there are ~4700 violations in 266 files, but running the autocorrect gets that number down to ~2259 violations, some of the main violations are: line length (over 100 characters), missing docs, force casting and there are other violations that aren't quite as prevalent. This is done with the base set `swiftlint` rules so there are rules and files that we can exclude and add any custom rules

**Comment by vadimeisenbergibm** [comment]
I do not like forced casting, or any use of ! operator, forced unwrapping of optionals as well, except for trivial cases when it is clear from the code a couple of lines above that forced casting/unwrapping will succeed. In most cases, ! operator should not be used. It can cause crashes in cases when just logging the error/returning internal error would be sufficient.

**Comment by ianpartridge** [comment]
Main repos have been done.
