### ISSUE TITLE
Digital ocean supporting

### ISSUE THREAD

**Issue by cooler333** [IBM-Swift/Kitura#615]
I can't run Kitura on ubuntu at all.

A get a ton of issue, e.g:

    In file included from allocator.c:21:
    ./internal.h:245:10: fatal error: 'sys/event.h' file not found
    #include <sys/event.h>
             ^
    1 error generated.
    Makefile:658: recipe for target 'allocator.lo' failed
    make[2]: *** [allocator.lo] Error 1

**Comment by ianpartridge** [comment]
Have you installed the prerequisite packages? I think `sys/event.h` is provided by the `libbsd-dev` package.

**Comment by simplepanda** [comment]
https://swift.codeandstrings.com is my Kitura/FastCGI test/demo server and it's running at Digital Ocean here in Toronto. There's definitely nothing Digital Ocean specific that would cause any issues. Just make sure your prerequisites are satisfied and you're good.

**Comment by ianpartridge** [comment]
Closing - please reopen if you need any further help.
