### ISSUE TITLE
Follow up with Travis upgrading git to a later version

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#620]
Wrote a mail to support@travis-ci.com:

There is an issue with git 2.9.0 which was fixed in 2.9.1. The issue is described here http://marc.info/?l=git&m=146632066932159&w=2. The fix is described here - https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.1.txt:
- _Fix an unintended regression in v2.9 that breaks "clone --depth"
  that recurses down to submodules by forcing the submodules to also
  be cloned shallowly, which many server instances that host upstream
  of the submodules are not prepared for._

An example failure - https://travis-ci.org/IBM-Swift/Kitura-CouchDB/jobs/145141878.

Could you please upgrade the git version you use to v2.9.1 or later?

**Comment by vadimeisenbergibm** [comment]
An issue was opened in travis-ci github https://github.com/travis-ci/travis-ci/issues/6328

**Comment by christiancompton** [comment]
Closing, reopen as needed.
