### ISSUE TITLE
Update ResponseTime middleware for 6/20

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#624]

**Comment by shmuelk** [comment]
Two minor comments:

   1. In the README.md it says:

      ##Installation

          Add this package to your Package.swift.

      What is "this"? I think some text is missing.

    2. Please tag the latest changes....

**Comment by dfirsht** [comment]
I added the tag, do you think that I should add a line saying: `.Package(url: "https://github.com/IBM-Swift/Kitura-ResponseTime.git", majorVersion: 0, minor: 2)`?

**Comment by shmuelk** [comment]
I guess not.
