### ISSUE TITLE
SwiftyJSON: Different output from .rawString() on mac and linux

### ISSUE THREAD

**Issue by savelii** [IBM-Swift/Kitura#626]
Facing this issue from first release of IBM Cloud Tools: when using .rawString() on mac and linux get different output. 
I was hoping that this will be fixed in future release but today tried with new project in IBM Cloud Tools and seems despite new version of Kitura and swiftyJSON issue still persist.

So I just created new Kitura Project from template in IBM Cloud Tools
Then added simple test route:

```
router.get("/testRoute") { request, response, next in
    let exampleDataFromServer = ["info" : "\nConnection:keep-alive\nHost:localhost:8090\nAccept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\nUser-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17\nAccept-Language:en-us\nCache-Control:max-age=0\nAccept-Encoding:gzip, deflate"]

    response.status(HTTPStatusCode.OK).send(JSON(exampleDataFromServer).rawString() ?? "")

    next()
}
```

After redeploy I get following output on local mac:
![screen shot 2016-07-21 at 3 59 06 am](https://cloud.githubusercontent.com/assets/1983837/17008174/a8e8b1fc-4ef7-11e6-8a66-9b032da1d242.png)

And this one from bluemix hosted app:
![screen shot 2016-07-21 at 3 59 21 am](https://cloud.githubusercontent.com/assets/1983837/17008185/b3a38554-4ef7-11e6-9136-37fdf79d4e74.png)

Seems for me as something wrong with escape characters transformation. Of course there should be same output in both case.

Sorry if this was already discussed or I use it in wrong way.

**Comment by shmuelk** [comment]
@savelii We need to look into this. It may not be a SwiftyJSON issue but rather a Swift on OSX vs Swift on Linux issue.

**Comment by savelii** [comment]
Just small note to be absolutely clear - expected behavior is like OSX now, right?

**Comment by shmuelk** [comment]
I believe so. As on OSX we are using Apple's JSONSerialization writer, while on Linux we aren't.

**Comment by youming-lin** [comment]
Looks like a difference between `JSONSerialization` and `LclJSONSerialization` and how they serialize dictionaries. In addition to this difference, there may be other serialization differences between the two. I propose we backlog this until/in favor of #362.

**Comment by ianpartridge** [comment]
Could you take a look at #362 ?

**Comment by youming-lin** [comment]
Sure

**Comment by christiancompton** [comment]
Closing - reopen if needed.
