### ISSUE TITLE
Provide HTML entity encoding to mitigate XSS

### ISSUE THREAD

**Issue by nmvijay** [IBM-Swift/Kitura#627]
Is there any plan to create an Utility for encoding the HTML content to prevent Cross Site Scripting attacks?

Ref: https://www.ibm.com/developerworks/library/se-prevent/

**Comment by ianpartridge** [comment]
Contributions are very welcome.

We should also consider adding middleware to support the `X-XSS-Protection` header - see https://github.com/helmetjs/x-xss-protection

**Comment by youming-lin** [comment]
Developers can encode strings using percent encoding via [String.addingPercentEncoding(withAllowedCharacters: CharacterSet)](https://developer.apple.com/reference/foundation/nsstring/1411946-stringbyaddingpercentencodingwit).

@nmvijay @ianpartridge Would this be sufficient to fill in for the utility requested?

**Comment by youming-lin** [comment]
I have developed and uploaded an implementation here: https://github.com/IBM-Swift/swift-html-entities

It currently supports HTML4 named character entities and always escapes every other non-ASCII character and five unsafe ASCII characters via hex/dec escapes.

Will be tagged for release after I integrate Travis CI and clean up comments/README.

**Comment by youming-lin** [comment]
`HTMLEntities` 1.0.0 has been released: https://github.com/IBM-Swift/swift-html-entities/releases/tag/1.0.0
