### ISSUE TITLE
Linux Instructions step 3 fails

### ISSUE THREAD

**Issue by donutloop** [IBM-Swift/Kitura#631]
Swift version 3.0-dev (LLVM c191431197, Clang c6195325c5, Swift add621a959)
Ubuntu 16.10 

Hello,

i want compile the libdispatch libray 

3."Clone, build and install the libdispatch library. The complete instructions for building and installing this library are here, though, all you need to do is just this $ git clone --recursive -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && sh ./autogen.sh && ./configure --with-swift-toolchain=<path-to-swift>/usr --prefix=<path-to-swift>/usr && make && make install" 

the compiling process isn't running correctly 

Log:
http://pastebin.com/nyqigx1K

**Comment by shmuelk** [comment]
@donutloop  I will point out two things:

   1. Your log above says you're on Ubuntu 16.10. I'm not sure if libdispatch supports ubuntu 16.10 quite yet.
   2. You specified --with-swift-toolchain=/usr --prefix=/usr, did you really install your swift drop in root (/)?

I will ask the libdispatch guys to comment on this as well.

**Comment by donutloop** [comment]
1. yes , i use ubuntu 16.10

2. yes

**Comment by HTTP4** [comment]
i have exactly the same issue

**Comment by ianpartridge** [comment]
@dgrove-oss any advice on compiling libdispatch on Ubuntu 16.10?

**Comment by dgrove-oss** [comment]
Looks to me like you are compiling with gcc, not clang.   Did you install the clang package?  libdispatch assumes all the swift prerequisite packages are installed.

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src/common -I./include -Wall -Wextra -Wno-missing-field-initializers -Werror -g -O2 -std=c99 -D_XOPEN_SOURCE=600 -fvisibility=hidden -g -O2 -MT src/linux/libkqueue_la-platform.lo -MD -MP -MF src/linux/.deps/libkqueue_la-platform.Tpo -c src/linux/platform.c  -fPIC -DPIC -o src/linux/.libs/libkqueue_la-platform.o`

**Comment by ianpartridge** [comment]
Closing as it looks like the prerequisites haven't been installed, and Ubuntu 16.10 is not officially supported.
