### ISSUE TITLE
Problems in Foundation causing test failures in SwiftyJSON on Linux

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#633]
Some SwiftyJSON tests fail on Linux because of problems in Foundation. They are disabled on Linux until these problems are fixed. 
- autoreleasepool doesn't exist on Linux 
  PerfomanceTests: autoreleasepool was defined as an empty function for Linux
- Lack of bridging
  The following tests or parts of them were disabled on Linux:
  - RawRepresentableTests: testNumber, testBool, testArray, testDictionary
  - SequenceTypeTests: testArrayAllDictionary, testDictionaryAllArray
- [Different number of fraction digits on Linux](https://github.com/IBM-Swift/SwiftRuntime/issues/183)
    Disabled parts of the following:
  - NumberTests: testNumber, testDouble
  - PrintableTests: testNumber
- [NSNumber description differs on Linux](https://bugs.swift.org/browse/SR-1464?jql=text%20~%20%22NSNumber%22) (this may be related to the above [number of fraction digits issue](https://github.com/IBM-Swift/SwiftRuntime/issues/183))
    Disabled parts of:
  - BaseTests: testNumberPrint
  - NumberTests: testNumber
- [CFNumberGetType returns wrong type for UInt8](https://github.com/IBM-Swift/SwiftRuntime/issues/185)
    Test:
  - NumberTests: testUInt8

**Comment by ianpartridge** [comment]
Bugs have been raised to track these.

**Comment by christiancompton** [comment]
Closing - reopen if needed.
