### ISSUE TITLE
XCode 8 linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by pajapro** [IBM-Swift/Kitura#634]
I installed kitura according to the [installation guide](https://github.com/IBM-Swift/Kitura#macos). Then, I created XCode project by `swift package generate-xcodeproj`. When I try to build through XCode I get:

```
ld: library not found for -lCHttpParser for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

[Troubleshooting on this inssue](https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-on-XCode) provided in Wiki, did not fix the problem (XCode 8 does not have `Library Search Paths` option so I used `Framework Search Paths`).

I am running XCode 8.0 beta 3 (8S174q) with Swift `DEVELOPMENT-SNAPSHOT-2016-06-20-a`.

**Comment by kweinmeister** [comment]
Please confirm that you do not see `Library Search Paths`. I just double-checked this in Xcode 8 Beta 3, and I do see it.

- Click on the Kitura project in the top left corner of Xcode
- Then, click on Build Settings in the main panel.
- Confirm that you have the Kitura project selected, rather than a Target
- Search for "search path"
- You should see Library Search Path along with others like Framework, Header, etc.

**Comment by pajapro** [comment]
@kweinmeister I do not have Kitura project, but Kitura target only. 
![screen shot 2016-07-24 at 21 44 18](https://cloud.githubusercontent.com/assets/3673765/17086026/cda08f5e-51e7-11e6-99ac-703b92ffadde.png)

No modifications to the project has been made, this screenshot is taken right after `swift package generate-xcodeproj`

**Comment by kweinmeister** [comment]
Good point, the name of the project will be different. Notice the "search path" filter I have in my screenshot. Can you check that? Looks like that filter has not yet been applied in your screenshot.

![image](https://cloud.githubusercontent.com/assets/11586922/17086063/374d8216-51ae-11e6-9285-75cef934c1ef.png)

**Comment by simplepanda** [comment]
I think you may also need to click "All" in the Basic/Customized/All selector to expose the search paths. @kweinmeister can see them because he has values there, so they appear for "Basic".

**Comment by krugazor** [comment]
it's a known bug from the packagemanager that does provide the lib (without framework) in CLI mode, but not in the generated project.

cf
https://github.com/IBM-Swift/Kitura/issues/574

**Comment by pajapro** [comment]
Thanks @krugazor for pointing me to a workaround!

**Comment by kweinmeister** [comment]
I have filed an issue with the Swift Package Manager: https://bugs.swift.org/browse/SR-2215

**Comment by ianpartridge** [comment]
Based on input from the SPM team, I've updated our CHTTPParser repo to fix this issue, and updated Kitura-net to use the new version of CHTTPParser.

Once we release a new version of Kitura this issue should be fixed. Thanks everyone!
