### ISSUE TITLE
Readme: Supported Swift Compiler Link

### ISSUE THREAD

**Issue by nathan-hekman** [IBM-Swift/Kitura#635]
In the readme, clicking "supported Swift compiler" in step 4 of the macOS installation instructions just links to the "Swift version" portion of the same readme. It isn't very clear what this is linking to, and that the user needs to actually go to swift.org to find the correct toolchain/Swift version/Swift compiler. Clarifying this and using consistent terminology would help clear this up.

**Comment by ianpartridge** [comment]
Hi Nathan, thanks for your issue. The "Swift version" section says "This branch of Kitura requires the DEVELOPMENT-SNAPSHOT-2016-06-20-a version of Swift 3 trunk (master). You can download this version at swift.org (link)."  I can't immediately think of a way to make this clearer.  Can you suggest an improvement?

**Comment by nathan-hekman** [comment]
I think it would help users that are new to Kitura and Swift on the server to clarify that "supported Swift compiler" is the same as what you are calling "Swift version." This wasn't immediately clear to me.

**Comment by ianpartridge** [comment]
Good idea - I've made this change.  Thanks!
