### ISSUE TITLE
Failure in linking with libdispatch following Linux directions

### ISSUE THREAD

**Issue by msmollin** [IBM-Swift/Kitura#638]
Running Ubuntu 14.04 LTS fully up2date and using the `swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04` I get the following error during linking with libdispatch:

```
/usr/bin/ld: /home/administrator/lib-dispatch/swift-corelibs-libdispatch/src/Dispatch.o: relocation R_X86_64_PC32 against protected symbol `_TMaC8Dispatch17dispatch_object_t' can not be used when making a shared object
```

Full log: https://gist.github.com/msmollin/8165a2ba3c99b2b1777aab3e524a0022

Relevant build command used:
`git clone --recursive -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && sh ./autogen.sh && ./configure --with-swift-toolchain=/home/administrator/swift/usr --prefix=/home/administrator/swift/usr && make && make install`

**Comment by shmuelk** [comment]
I will refer this to the libdispatch folks, as this is really a libdispatch issue and not a Kitura issue.

**Comment by msmollin** [comment]
Cool. Should I post a bug over there for them?

**Comment by shmuelk** [comment]
Let's wait and see. I have contacted them offline. Pointing them at this issue.

**Comment by ianpartridge** [comment]
@dgrove-oss ?

**Comment by dgrove-oss** [comment]
You get that error when using the GNU linker (bug in GNU linker).  You need to use the gold linker instead.

**Comment by ianpartridge** [comment]
How is the gold linker specified?  Do we need to update our libdispatch build instructions?

**Comment by msmollin** [comment]
It looks like you can `apt-get install binutils-gold` and it'll replace the standard linker with `gold` for the `ld` command. However that's a system-wide change. I haven't been able to find a way yet to do that more localized to just the libdispatch project. Thoughts?

**Comment by dgrove-oss** [comment]
I don't know of a more localized way.   When I installed binutils-gold on 16.04 it was a little less invasive....I have both ld.gold and ld.bfd and /usr/bin/ld is a symlink to ld.bfd by default.

```
dgrove@dgrove-vb-swift:~/swift$ which ld
/usr/bin/ld
dgrove@dgrove-vb-swift:~/swift$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
dgrove@dgrove-vb-swift:~/swift$ ld.gold --version
GNU gold (GNU Binutils for Ubuntu 2.26.1) 1.11
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
dgrove@dgrove-vb-swift:~/swift$ ld.
ld.bfd   ld.gold  
dgrove@dgrove-vb-swift:~/swift$ ld.bfd --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
dgrove@dgrove-vb-swift:~/swift$ ll /usr/bin/ld
lrwxrwxrwx 1 root root 19 Jul 14 15:30 /usr/bin/ld -> x86_64-linux-gnu-ld*
```

**Comment by ianpartridge** [comment]
Thanks @dgrove-oss . As we know the solution to this issue, and Ubuntu 16.04 is not yet officially supported by swift.org or Kitura, I'm closing this issue.

**Comment by msmollin** [comment]
Well, so, I did some more digging, and the `binutils` package for the latest 14.04 LTS also includes `ld.gold` now. However, you have to do some work because for some reason `ld.bfd` and `ld.gold` aren't integrated into Ubuntu's `update-alternatives` list. However, it's fairly easy to do so.

```
$ sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.bfd 10
$ sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 9
$ sudo update-alternatives --config ld
```

Then you can easily switch between the two as the `ld` executable of choice.

To that end, I can confirm @dgrove-oss's original statement, as `ld.gold` does correctly compile and link, and thus allow for subsequent installation, of the libdispatch system.

**Comment by msmollin** [comment]
@ianpartridge might make sense to put a note in the README docs about this, as it affects but it solvable on 14.04

**Comment by ianpartridge** [comment]
Good point, I'll reopen this. Also need to research a bit more as I'm sure we never used to have to worry about this.

**Comment by ianpartridge** [comment]
I've updated the Readme in 1f6e660c7b5a8c488911382ca2b3e215afd7f553 to specify the gold linker.  This is how our [Package-Builder](https://github.com/IBM-Swift/Package-Builder/blob/b20987c9e482b67e41993b0d162a4cf418979f26/linux/install_swift_binaries.sh#L56) repo is doing it and it seems like a simple solution.  Thanks!
