### ISSUE TITLE
Create Response Handlers and Parsing Request Guides

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#639]

**Comment by dfirsht** [comment]
I've created a couple of guides to explain Kitura featues in more depth: https://github.com/IBM-Swift/Kitura/wiki/Special-Types-of-Response-Handlers https://github.com/IBM-Swift/Kitura/wiki/Parsing-Requests

**Comment by ianpartridge** [comment]
Reviewed.
