### ISSUE TITLE
Migrate to 07/25 binaries

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#644]
- [ ] LoggerAPI (not needed)
- [x] SwiftyJSON
- [x] KituraSys
- [x] KituraNet
- [x] Kitura
- [x] HeliumLogger
- [ ] KituraSample (not needed)
- [x] CouchDB
- [x] Redis
- [ ] Kitura-TemplateEngine (not needed)
- [x] Kitura-Session
- [x] KituraCredentials
- [x] KituraCredentialsHTTP 
- [x] KituraCredentialsGoogle
- [x] KituraCredentialsFacebook 
- [x] Kitura-Credentials-Sample 
- [x] Kitura-Session-Redis
- [ ] GRMustache
- [ ] Kitura-MustacheTemplateEngine
- [x] Kitura-Cache
- [x] Kitura-Compression
- [x] Kitura-CORS
- [x] Kitura-CSRF

**Comment by krugazor** [comment]
Actually, there is a 07-28 snapshot already...

**Comment by krugazor** [comment]
Sorry if I sound obtuse, but what is the rationale behind not skipping ahead the the 28 instead of the 25 binaries? I don't recall any major changes to my own porting efforts, but I do not deal with hugely complex issues.

**Comment by ianpartridge** [comment]
There isn't a working libdispatch for Linux available for the 07-28 toolchain, unfortunately.

**Comment by shmuelk** [comment]
All "Kitura" repositories have now been migrated to Swift 07/25.

The README.md files that mention version of Swift 3, all still say 06/20.
