### ISSUE TITLE
Kitura.start() Kitura.stop() function needed

### ISSUE THREAD

**Issue by GilGS** [IBM-Swift/Kitura#654]
**There is a need in adding functions `Kitura.start()` and `Kitura.stop()` that will start and stop the server connection, similar to what `Kitura.run()` function does, but with return.** 

I need these functions to use in a function similar to 'performServerTest' as written below.
The reason is that I want to use `Kitura.start()` to open the connection, instead of doing it manually as written in 'performServerTest'.  But when using `Kitura.run()` function, I don't have the server instance, so I don't have a way to stop the connection. I prefer not to use server.listen directly because that is exactly what `Kitura.run()` does, and what I expect from `Kitura.start()` to do.
```swift
func performServerTest(_ router: ServerDelegate, asyncTasks: (expectation: XCTestExpectation) - > Void...) { 
    let server = setupServer(port: 8090, delegate: router)
    let requestQueue = Queue(type: .serial)

     for (index, asyncTask) in asyncTasks.enumerated() {
            let expectation = self.expectation(index)
            requestQueue.enqueueAsynchronously {
                asyncTask(expectation: expectation)
            }
        }

        waitExpectation(timeout: 10) { error in
                // blocks test until request completes
                server.stop()
                XCTAssertNil(error);
        }
    }

private func setupServer(port: Int, delegate: ServerDelegate) -> HTTPServer {
        return HTTPServer.listen(port: port, delegate: delegate,
                           notOnMainQueue:true)
    }
```

**Comment by vadimeisenbergibm** [comment]
`performServerTest` should be refactored to use `Kitura.start()` and `Kitura.stop()`
