### ISSUE TITLE
"Build a To do List Backend" Tutorial Solution Mismatch

### ISSUE THREAD

**Issue by dillan** [IBM-Swift/Kitura#661]
The "Build a To do List Backend" tutorial points to a finished project at: https://github.com/IBM-Swift/Kitura-TodoList

However, the code in that repository does not match the steps outlined in the tutorial at: https://github.com/IBM-Swift/Kitura/wiki/Build-a-To-do-List-Backend

**Comment by ianpartridge** [comment]
@shmuelk I thought this had been updated?

**Comment by ianpartridge** [comment]
I think this is now updated.
