### ISSUE TITLE
Intermittent failures in Response tests

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#662]
We're seeing intermittent failures in the Response tests on Travis.

For example, https://travis-ci.org/IBM-Swift/Kitura/builds/148425739

```
Test Case 'TestResponse.testParameter' started at 20:53:20.568
/root/Kitura/Tests/Kitura/TestResponse.swift:308: error: TestResponse.testParameter : XCTAssertNotNil failed - ERROR!!! ClientRequest response object was nil
fatal error: unexpectedly found nil while unwrapping an Optional value
```

and

```
Test Case '-[KituraTestSuite.TestResponse testMultipartFormParsing]' started.
fatal error: unexpectedly found nil while unwrapping an Optional value
```

I think we have to wonder whether this is related to the recent merge of Keepalive.

**Comment by shmuelk** [comment]
I added a one second delay in the tests in Kitura after the server is started as part of the 08/23 migration.

**Comment by christiancompton** [comment]
Closing, reopen as needed.
