### ISSUE TITLE
Getting Started Error

### ISSUE THREAD

**Issue by chrisyoyo** [IBM-Swift/Kitura#663]
Hello when i follow the getting started on the readme, when I try "swift build" it goes like this, help me please.
<img width="838" alt="screen shot 2016-07-31 at 10 39 45 pm" src="https://cloud.githubusercontent.com/assets/7302317/17279242/d041338e-576f-11e6-9446-a26f12140b6c.png">

**Comment by simplepanda** [comment]
Guessing you have git v2.9.1 installed?

There's a bug in 2.9.1 that causes this issue. You can either update to git 2.9.2 or just run ```swift build``` over and over again and it should work.

**Comment by chrisyoyo** [comment]
Oh great it's the problem but I think I have another problem because I use XCode 8 with Swift 3 :
<img width="850" alt="screen shot 2016-07-31 at 10 59 40 pm" src="https://cloud.githubusercontent.com/assets/7302317/17279376/82948dc2-5772-11e6-82f3-ab01047900c6.png">

**Comment by chrisyoyo** [comment]
I generated an xcode project, i resolved all of this but there is again one left that I don't get it...
<img width="851" alt="screen shot 2016-08-01 at 12 32 49 am" src="https://cloud.githubusercontent.com/assets/7302317/17279830/98e47062-577f-11e6-8cde-2c4debb1e154.png">

**Comment by ianpartridge** [comment]
Which toolchain are you using?

**Comment by chrisyoyo** [comment]
How can we see that?

**Comment by ianpartridge** [comment]
In Xcode, like this:

<img width="607" alt="screen shot 2016-08-01 at 10 40 10" src="https://cloud.githubusercontent.com/assets/1423497/17290034/5fd2c558-57d4-11e6-9667-9f663d12ebfb.png">

Which toolchain is selected?

**Comment by chrisyoyo** [comment]
Lol, look : 
<img width="851" alt="screen shot 2016-08-01 at 12 32 49 am" src="https://cloud.githubusercontent.com/assets/7302317/17290094/090fd02c-57dd-11e6-940d-85e77a74b346.png">

**Comment by ianpartridge** [comment]
Have you installed the 06-20a toolchain and put it in your path?  Instructions are in `README.md`

**Comment by chrisyoyo** [comment]
<img width="572" alt="screen shot 2016-08-01 at 12 25 09 pm" src="https://cloud.githubusercontent.com/assets/7302317/17291251/1cf7bdb0-57e3-11e6-8bf1-8f939573549f.png">

But isn't working...

**Comment by ianpartridge** [comment]
OK, so you have the toolchain installed - good. Now are you using it on the command-line? In your previous screenshot it said `XcodeDefault.xctoolchain` which means you are using the Xcode 8.0 toolchain, not 06-20.

**Comment by chrisyoyo** [comment]
Oh okay, so how can I do?

**Comment by akrabat** [comment]
By far the easiest way is to use https://github.com/kylef/swiftenv

**Comment by ianpartridge** [comment]
Yes `swiftenv` is useful. The alternative is to add the toolchain directory to your $PATH.

**Comment by chrisyoyo** [comment]
I use swiftenv ->

<img width="629" alt="screen shot 2016-08-01 at 1 01 41 pm" src="https://cloud.githubusercontent.com/assets/7302317/17292130/2a47746a-57e8-11e6-92cb-f0c5b5c6da3f.png">

then it gives my like the other screen ... ->

<img width="847" alt="screen shot 2016-08-01 at 1 02 25 pm" src="https://cloud.githubusercontent.com/assets/7302317/17292149/481a530e-57e8-11e6-8912-42f30a7d1f1a.png">

**Comment by ianpartridge** [comment]
Can you `rm -rf Packages` and try again?

**Comment by chrisyoyo** [comment]
Yeah it's work now! Big thanks, now i had to understand all features of kitura x)

**Comment by ianpartridge** [comment]
Awesome - have fun!
