### ISSUE TITLE
Add cookie support to Kitura-CSRF

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#664]
Enable storage of secret in cookies once secure cookies are available

**Comment by ianpartridge** [comment]
Depends on HTTPS support.

**Comment by kweinmeister** [comment]
@ianpartridge is this still blocked?

**Comment by ianpartridge** [comment]
@irar2 ?

**Comment by irar2** [comment]
This is not blocked anymore. We can now store secrets in cookies.

**Comment by ianpartridge** [comment]
Does that mean this issue can be closed?

**Comment by irar2** [comment]
No, it just means that it is not blocked, but it is not implemented yet.

**Comment by christiancompton** [comment]
Closing - Reopen if needed.
