### ISSUE TITLE
The same HTTPServerRequest object is being used for multiple consecutive requests

### ISSUE THREAD

**Issue by gormster** [IBM-Swift/Kitura#667]
Have you tried adding this line to any Router.get method

```swift
Log.info(request.headers["Connection"]!)
```

and then repeatedly refreshing the page? I'll tell you what you get:

```
keep-alive
keep-alive, keep-alive 
keep-alive, keep-alive, keep-alive 
keep-alive, keep-alive, keep-alive, keep-alive 
keep-alive, keep-alive, keep-alive, keep-alive, keep-alive 
```

Those are *strings*, by the way. If you wanted to test for Connection: keep-alive, it would only work on the very first try.

This also applies to every header not in the list on line 317 of HTTPIncomingMessage.swift. In other words, it also works for Accept, Cache-Control and most worryingly, Cookie. This means that request.cookies *does not work at all* for multiple requests on the same connection, if there is only a single cookie. If there are multiple cookies, it will work, presumably because the cookies parser just overwrites the previous values

```swift
router.get("/") {
    request, response, next in

    Log.info(request.headers["Cookie"] ?? "nil")
    Log.info(request.cookies.debugDescription)

    if let c = request.cookies["test"] {
        response.send("cookie value \(c.value)")
        let newValue = (Int(c.value) ?? 0) + 1
        response.cookies["test"] = HTTPCookie(properties: [.path: "/", .name: "test", .domain: request.hostname, .value: String(newValue), .expires: Date(timeIntervalSinceNow:60 * 60 * 24)])
    } else {
        response.send("no cookie")
        response.cookies["test"] = HTTPCookie(properties: [.path: "/", .name: "test", .domain: request.hostname, .value: "0", .expires: Date(timeIntervalSinceNow:60 * 60 * 24)])
        // uncomment this next line to unbreak cookies
        // response.cookies["garbage"] = HTTPCookie(properties: [.path: "/", .name: "nothing", .domain: request.hostname, .value: "0", .expires: Date(timeIntervalSinceNow:60 * 60 * 24)])
    }

    next()
}
```

The result of this in the browser is "no cookie", "cookie value 0", "no cookie", "no cookie", "no cookie".

In the logs, it looks like:

```
nil 
[:] 
test=0 
["test": <NSHTTPCookie version:0 name:"test" value:"0" expiresDate:(null) created:2016-08-03 05:51:16 +0000 sessionOnly:TRUE domain:"" path:"/" isSecure:FALSE>] 
test=0, test=1 
[:] 
test=0, test=1, test=0 
[:] 
test=0, test=1, test=0, test=0 
[:] 
test=0, test=1, test=0, test=0, test=0 
[:] 
```

This is a problem for any code that parses header values. The header values are being concatenated not with headers in the same request, but with headers from *previous requests*. Look at the end of that log: you have multiple values of the same header in the same line.

At the moment I'm fixing this by adding `headers.removeAll()` to line 126 of `HTTPIncomingMessage.parse(_)` but to be honest I don't actually know if that's going to cause problems somewhere else. And I don't know what else is being kept around in HTTPServerRequest that shouldn't be.

My gut feeling is that Keep-Alive shouldn't reuse the same HTTPServerRequest unless it's part of the same request flow; that is, if the response was a 100-Continue or similar. There should be a mechanism to reuse connections without reusing HTTPServerRequest objects.

**Comment by shmuelk** [comment]
Thank you very much for finding and describing this issue as well as you did.

I am actively working on the fix and should have one shortly.
