### ISSUE TITLE
request.parameters incorrect in middleware?

### ISSUE THREAD

**Issue by akrabat** [IBM-Swift/Kitura#668]
There may be an issue with request.parameters in middleware.
 
(Note that I'm using Kitura 0.19.4 with DEVELOPMENT-SNAPSHOT-2016-06-06-a - can't update as Internet's not good enough where I am this week)

Given this main.swift:

```swift
import Kitura
import Foundation
import SwiftyJSON

setbuf(stdout, nil)

class AUserHandler: RouterMiddleware {
    func handle(request: RouterRequest, response: RouterResponse, next: () -> Void) {
        let id = request.parameters["id"] ?? ""
        response.status(.OK).send(json: JSON(["id" : id]))
        next()
    }
}


let router = Router()
router.get("/users/:id", middleware: AUserHandler())
router.get("/users/:id") { request, response, next in
    let id = request.parameters["id"] ?? ""
    response.status(.OK).send(json: JSON(["id" : id]))
    next()
}

Kitura.addHTTPServer(onPort: 8090, with: router)
Kitura.run()
```
I get this output:

```bash
$ curl -i http://localhost:8090/users/64f9cc52d162927b3f95ed1d94036c2b
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 63
Date: Wed, 03 Aug 2016 14:23:48 GMT
Connection: Close

{
  "id" : "6"
}{
  "id" : "64f9cc52d162927b3f95ed1d94036c2b"
}
```

**Comment by ianpartridge** [comment]
Reproduced this on macOS. Looks like we are only adding the first character to the parameters dictionary.

**Comment by naithar** [comment]
@ianpartridge it seems that i found the reason behind this issue.
It's the default value for ```allowPartialMatch``` parameter in ```RouterElement``` initializer for middleware that is passed to ```RouteRegex```.

Correct regex that is generated is with ```allowPartialMatch = false``` is ```^/users/(?:([^/]+?))(?:/(?=$))?$```

The wrong regex generated for @akrabat's ```AUserHandler``` (and for any directly passed middleware) with ```allowPartialMatch = true``` is ```^/users/(?:([^/]+?))(?:/(?=$))?```. It loses ```$``` token so only first character of parameter is used.

**Comment by ianpartridge** [comment]
Thanks @naithar - I got as far as "there must be something wrong with the regex"!

**Comment by naithar** [comment]
@ianpartridge i've made a tests for this issue in my fork, so it can be tested. [Kitura/TestRequests.swift](https://github.com/naithar/Kitura/blob/master/Tests/Kitura/TestRequests.swift).
The current problem is that switching value of ```allowPartialMatch``` from  ```true``` to ```false``` will break subrouter tests, so it's not a valid option.
I'll continue looking for a solution, if no one is taking this issue.
