### ISSUE TITLE
Build issue with other Package

### ISSUE THREAD

**Issue by remirobert** [IBM-Swift/Kitura#673]
I am trying to use a database library with **Kitura**. 🤖💡
I tried : 
 - https://github.com/OpenKitten/MongoKitten
 - https://github.com/Zewo/PostgreSQL

For both of them I got this issue 🤕👉 : 
```
error: The dependency graph could not be satisfied because an update to ...
```

This is the **Package.swift** I am using for running **PostgreSQL**:

```swift
import PackageDescription

let package = Package(
    name: "SignalAnalyserServer",
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 24),
	.Package(url: "https://github.com/IBM-Swift/HeliumLogger", majorVersion: 0, minor: 13),
	.Package(url: "https://github.com/Zewo/PostgreSQL", majorVersion: 0, minor: 8)
    ]
)
```

The ** PostgreSQL** has the same swift toolchain than my current Kitura version.
So the problem is coming from this library ?

**Comment by ianpartridge** [comment]
@rfdickerson this looks like your sort of area!

**Comment by rfdickerson** [comment]
Hi @remirobert , first of all, you should try either removing `Packages` directory and/or running `swift package update` to force fetching the packages again from scratch.

Secondly, I worry about some versioning issues with any toolchain other than 6/20 and Kitura version 0.22. We have only tested and developed on that stack.

**Comment by remirobert** [comment]
@rfdickerson ok thanks. Kitura sounds like an awesome framework, but I feel like there is a lot of versioning issue, maybe due to swift 3, which is coming soon.

But unlikely, I even can't build the mongo db example.😸

**Comment by rfdickerson** [comment]
Yeah, I feel like things are sort of coming together as of the 8/04 snapshot. Soon we'll have something that will developing on ground that is not constantly shifting. Feel free to try our todolist-mongodb framework, and make sure you set your PATH to point to the correct swift compiler (6-20-DEVELOPMENT).

**Comment by rfdickerson** [comment]
Oh, yeah! I just remembered. There is a bug in the Mongokitten driver that it won't work on 6/20- but we were able to get it to work on 6/06.

**Comment by remirobert** [comment]
@rfdickerson thanks for you help ! 👍
