### ISSUE TITLE
Static file serving failing on 0.25

### ISSUE THREAD

**Issue by joyychang** [IBM-Swift/Kitura#678]
`router.all("/", middleware: StaticFileServer(path: "./app/views"))`

This worked in 0.22, but get this runtime error in 0.25:

`ERROR: write(from:) IncomingSocketHandler.swift line 125 - Write to socket (file descriptor 6 failed. Error number=35. Message=Resource temporarily unavailable.`

**Comment by shmuelk** [comment]
I'm looking into this problem.

**Comment by shmuelk** [comment]
@joyychang I forgot to ask, on what platform did this occur? Was the client remote from the server or was it on the same box (i.e. http://localhost:pppp in your browser) ?

**Comment by joyychang** [comment]
The server is running on a mac.
We tried both remote access via IP:pppp, and local access via localhost:pppp.
Both experienced the problem.
