### ISSUE TITLE
API design for SQL abstraction layer

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#679]

**Comment by caughtinflux** [comment]
Is the end goal to have a transparent Object -> DB model system like Django? Would be really interesting to see how one could do that in Swift.

**Comment by cwoloszynski77** [comment]
Is there any place you would encourage future users to go to support this activity?  I am holding off on developing any server-side app until we have an SQL adaptation layer that is supported by Kitura.  I am anxious to help.
