### ISSUE TITLE
build kitura with make error 

### ISSUE THREAD

**Issue by RoyGeagea** [IBM-Swift/Kitura#687]
error: the module at Tests/Kitura has an invalid name ('Kitura'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/Kitura’ to have a ‘Tests’ suffix
Package-Builder/build/Makefile:37: recipe for target 'build' failed

**Comment by vadimeisenbergibm** [comment]
@RoyGeagea are using DEVELOPMENT-SNAPSHOT-2016-07-25-a snapshot of swift? Could you please provide the full output of make?

**Comment by RoyGeagea** [comment]
@vadimeisenbergibm i'm using the latest snapshot: swift-DEVELOPMENT-SNAPSHOT-2016-08-07-a/swift-DEVELOPMENT-SNAPSHOT-2016-08-07-a-ubuntu15.10, but i already try DEVELOPMENT-SNAPSHOT-2016-07-25 and gives me another error, this is the full output of make for swift-DEVELOPMENT-SNAPSHOT-2016-08-07-a/swift-DEVELOPMENT-SNAPSHOT-2016-08-07-a-ubuntu15.10:
--- Fetching Package-Builder submodule
git submodule update --init --remote --merge --recursive
Submodule 'Package-Builder' (https://github.com/IBM-Swift/Package-Builder.git) registered for path 'Package-Builder'
Cloning into 'Package-Builder'...
remote: Counting objects: 1220, done.
remote: Compressing objects: 100% (449/449), done.
remote: Total 1220 (delta 780), reused 1196 (delta 756), pack-reused 0
Receiving objects: 100% (1220/1220), 176.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (780/780), done.
Checking connectivity... done.
Submodule path 'Package-Builder': checked out '9afb94f99c2b1f3ab31163ae9c37352c16b51687'
--- Running build on Linux
--- Build scripts directory: Package-Builder/build
--- Checking swift version
swift --version
Swift version 3.0-dev (LLVM 17c4c6cf7a, Clang 4ca9e01a7c, Swift 13a9908f8d)
Target: x86_64-unknown-linux-gnu
--- Checking swiftc version
swiftc --version
Swift version 3.0-dev (LLVM 17c4c6cf7a, Clang 4ca9e01a7c, Swift 13a9908f8d)
Target: x86_64-unknown-linux-gnu
--- Checking git version
git --version
git version 2.7.4
--- Checking git revision and branch
git rev-parse HEAD
7bc93cd9b476531f523e1778c09bf9804f3ab608
git rev-parse --abbrev-ref HEAD
master
--- Checking Linux release
lsb_release -d
Description:	Ubuntu 16.04.1 LTS
--- Invoking swift build
swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug
Cloning https://github.com/IBM-Swift/Kitura-net.git
warning: unable to rmdir Package-Builder: Directory not empty
HEAD is now at e312591 updated dependency versions in Package.swift
Resolved version: 0.26.0
Cloning https://github.com/IBM-Swift/Kitura-sys.git
HEAD is now at 67737a2 Migration 0725 (#10)
Resolved version: 0.26.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
HEAD is now at 98a5abd IBM-Swift/Kitura#646 - Added entry/exit logging (#11)
Resolved version: 0.10.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
HEAD is now at b923a1e Updated to use latest (7/25) toolchain.
Resolved version: 0.7.0
Cloning https://github.com/IBM-Swift/CCurl.git
HEAD is now at abbef47 added curlHelperSetOptHeaders, curlHelperSetOptString now accepts Swift strings (#3)
Resolved version: 0.2.0
Cloning https://github.com/IBM-Swift/CHTTPParser.git
HEAD is now at 429eff6 Merge pull request #7 from ianpartridge/master
Resolved version: 0.3.0
Cloning https://github.com/IBM-Swift/CEpoll.git
HEAD is now at 111cbcb IBM-Swift/Kitura#435 Added a README.md file
Resolved version: 0.1.0
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
warning: unable to rmdir Package-Builder: Directory not empty
HEAD is now at 57621b4 Migration 0725 (#12)
Resolved version: 11.0.0
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
HEAD is now at 6445fb7 DEVELOPMENT-SNAPSHOT-2016-07-25-a
Resolved version: 0.26.0
error: the module at Tests/Kitura has an invalid name ('Kitura'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/Kitura’ to have a ‘Tests’ suffix
Package-Builder/build/Makefile:37: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by RoyGeagea** [comment]
full output for make swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu15.10:
--- Fetching Package-Builder submodule
git submodule update --init --remote --merge --recursive
Submodule 'Package-Builder' (https://github.com/IBM-Swift/Package-Builder.git) registered for path 'Package-Builder'
Cloning into 'Package-Builder'...
remote: Counting objects: 1220, done.
remote: Compressing objects: 100% (449/449), done.
remote: Total 1220 (delta 780), reused 1196 (delta 756), pack-reused 0
Receiving objects: 100% (1220/1220), 176.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (780/780), done.
Checking connectivity... done.
Submodule path 'Package-Builder': checked out '9afb94f99c2b1f3ab31163ae9c37352c16b51687'
--- Running build on Linux
--- Build scripts directory: Package-Builder/build
--- Checking swift version
swift --version
Swift version 3.0-dev (LLVM 440a472499, Clang e10506ae1c, Swift 395e967875)
Target: x86_64-unknown-linux-gnu
--- Checking swiftc version
swiftc --version
Swift version 3.0-dev (LLVM 440a472499, Clang e10506ae1c, Swift 395e967875)
Target: x86_64-unknown-linux-gnu
--- Checking git version
git --version
git version 2.7.4
--- Checking git revision and branch
git rev-parse HEAD
7bc93cd9b476531f523e1778c09bf9804f3ab608
git rev-parse --abbrev-ref HEAD
master
--- Checking Linux release
lsb_release -d
Description:	Ubuntu 16.04.1 LTS
--- Invoking swift build
swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug
/home/roy/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04/usr/bin/swift-build: error while loading shared libraries: libicuuc.so.52: cannot open shared object file: No such file or directory
Package-Builder/build/Makefile:37: recipe for target 'build' failed
make: *** [build] Error 127

**Comment by vadimeisenbergibm** [comment]
@RoyGeagea As stated in [Kitura Readme](https://github.com/IBM-Swift/Kitura/blob/master/README.md#swift-version), 

> Version `0.26` of Kitura requires the **`DEVELOPMENT-SNAPSHOT-2016-07-25-a`** version of Swift 3 trunk (master). You can download this version at [swift.org](https://swift.org/download/). *Kitura is unlikely to compile with any other version of Swift.*

Let me check the problem with DEVELOPMENT-SNAPSHOT-2016-07-25-a.

**Comment by vadimeisenbergibm** [comment]
@RoyGeagea You are running the build on Ubuntu 16.10, while Swift for Linux officially runs only on Ubuntu 15.10 and 14.04. You can try to install the missing library: `sudo apt-get install libicu-dev`, but it may still not work.

**Comment by RoyGeagea** [comment]
In the documentation they say it was tested on Ubunto 14.04 and 15.10 but
not only supported by these two versions, thank you for your help, any news
about when Kitura will be available for Ubunto 16.10 ?

**Comment by akrabat** [comment]
@RoyGeagea The main issue is that the Swift project doesn't support 16.10: https://swift.org/download/

**Comment by vadimeisenbergibm** [comment]
@RoyGeagea see https://github.com/IBM-Swift/Kitura/issues/687#issuecomment-239676815
