### ISSUE TITLE
Router returns 404 - Not Found even if a route handler matches the endpoint

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Kitura#689]
Example code:
```swift
import Kitura

let router = Router()
var count = 0

router.get("/test", handler: {request, response, next in
    count += 1

    if (count > 2) {
        next()
    }
    else {
        try response.send("count is \(count)").end()
    }
})

Kitura.addHTTPServer(onPort: 3000, with: router)
Kitura.run()
```

Start the server, then hit the `/test` endpoint multiple times. On the first two hits, `count is \(count)` is returned. After those two hits, calls to `/test` will return 404 Not Found with the message `Cannot GET /test.`

Since a route handler for `/test` exists, router should not return 404 Not Found by default.

**Comment by akrabat** [comment]
I think that this happens because there's no data in the response when it arrives at the final handler.

What response do you think should be sent back in this case?

**Comment by kweinmeister** [comment]
204 No Content?

**Comment by youming-lin** [comment]
Interestingly, 404 Not Found is also node express's default behavior; the same example in nodejs will produce 404 after two hits. However, as 404 is also used to denote cases where no handler for a given URI exists (in addition to being used explicitly in application middleware), I think we should differentiate the above scenario from the scenario where no handler exists for an URI. For starters, we can log a warning statement on the server to denote this.

**Comment by ianpartridge** [comment]
Not a bug.
