### ISSUE TITLE
Incorrect .queryParameters parsing?

### ISSUE THREAD

**Issue by naithar** [IBM-Swift/Kitura#691]
I'm having some issues with `.queryParameters`, but i'm not sure where the problem is.

I'm using this route handler:

``` swift

router.get("/query") { request, response, next
    defer {
        next()
    }

    let json = JSON([
        "query" : JSON(request.queryParameters)
    ])

    response.status(.OK).send(json: json)
}
```

And the result of request to `localhost/query?param[]=a&param[]=b` is following:

``` json
{
  "query": {
    "param%5B%5D": "b"
  }
}
```

While request to `https://httpbin.org/get?param[]=a&param[]=b` results with:

``` json
{
  "args": {
    "param[]": [
      "a", 
      "b"
    ]
  }, 
  ...
}
```

Is there a problem in `URLParser` on Kitura-net or is this behavior intentional?

**Comment by naithar** [comment]
I've started implementing query parser in my Kitura-net fork. 
Obtaining of query parameter looks like SwiftyJSON's value obtaining: [example](https://github.com/naithar/Kitura-net/blob/query-parameters/Tests/KituraNet/ParserTests.swift#L55-L148)
It's not migrated to the latest swift snapshot (uses 07-25 atm) and not tested on linux, so it's not ready for PR.

**Comment by shmuelk** [comment]
@naithar Do you have Kitura updates for this as well?

**Comment by naithar** [comment]
@shmuelk at this moment I don't. But I'll migrate parser to 8-23 and make an update for Kitura too.

**Comment by naithar** [comment]
@shmuelk I've merged and updated Kitura to use new ```QueryParameters``` struct for http body.
Latest Kitura build on travis: [link](https://travis-ci.org/naithar/Kitura/builds/155961194)
Kitura-net build on travis: [link](https://travis-ci.org/naithar/Kitura-net/builds/155963995)
Kitura-net parsing tests and parameters example: [link](https://github.com/naithar/Kitura-net/blob/master/Tests/KituraNetTests/ParserTests.swift#L55-L164)
I'll also try to refactor and clean up the code before I create PR.

**Comment by christiancompton** [comment]
Closing Per #889.
