### ISSUE TITLE
Script for installing on linux 14.04

### ISSUE THREAD

**Issue by wassimseif** [IBM-Swift/Kitura#693]
Guys i wrote this script to directly install <h3>swift with libdispatch on linux ubuntu</h3>  It's tested using  `swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a` and `ubuntu 14.04`
#### Github Link
https://github.com/wassimseif/Swift-on-linux
I will try my best  keeping it updated with the latest snapshots

**Comment by ianpartridge** [comment]
Thanks! Closing this as not a Kitura bug.

**Comment by stevemasta34** [comment]
So this does NOT work on my ElementaryOS box (which is a pretty Ubuntu 14.04). I really just ran that `install.sh` (after fixing some of the pathing to not touch `/root`) and here was my exit ERROR code:

```*** Warning: Linking the shared library libdispatch.la against the non-libtool
*** objects  /home/stephen/install_space/swift-corelibs-libdispatch/src/Dispatch.o is not portable!
libtool: link: clang++  -fPIC -DPIC -shared -nostdlib /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  .libs/allocator.o .libs/apply.o .libs/benchmark.o .libs/data.o .libs/introspection.o .libs/init.o .libs/io.o .libs/object.o .libs/once.o .libs/queue.o .libs/semaphore.o .libs/source.o .libs/time.o .libs/transform.o .libs/voucher.o shims/.libs/linux_stubs.o .libs/libdispatch_la-block.o swift/.libs/swift_wrappers.o  /home/stephen/install_space/swift-corelibs-libdispatch/src/Dispatch.o  -Wl,--whole-archive ../libkqueue/.libs/libkqueue.a ../libpwq/.libs/libpthread_workqueue.a -Wl,--no-whole-archive  -lrt -lbsd -L/home/stephen/install_space/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04/usr/lib/swift/linux -lswiftCore -lpthread -lBlocksRuntime -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../.. -L/lib -L/usr/lib -lstdc++ -lm -lc -lgcc_s /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o  -momit-leaf-frame-pointer -O2 -fuse-ld=gold   -Wl,-soname -Wl,libdispatch.so -o .libs/libdispatch.so
/usr/bin/ld: /home/stephen/install_space/swift-corelibs-libdispatch/src/Dispatch.o: relocation R_X86_64_PC32 against protected symbol `_TMaC8Dispatch17dispatch_object_t' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

The script I ran:
[install_swift.sh.txt](https://github.com/IBM-Swift/Kitura/files/440975/install_swift.sh.txt)

**Comment by shmuelk** [comment]
@stevemasta34 Do you have the so called golden linker installed? You need to use it to link libdispatch.

**Comment by stevemasta34** [comment]
@shmuelk How would I be able to check for this? I've followed the Kitura instructions as best I could and ran this script whole

**Comment by akrabat** [comment]
For 14.04 and an August snapshot, you need clang-3.8 and the gold linker. For a July snapshot, you may only need the gold linker.

From the [Vagrantfile](https://gist.github.com/akrabat/fe3dd14206d0137e83f7753114397668) that 
I use:

This will install clang-3.8:

```
  wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
  cat "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" >> /etc/apt/sources.list
  apt-get update
  apt-get -qq --assume-yes install clang-3.8 lldb-3.8
  update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
  update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
```

This will set up use of the gold linker:

```
update-alternatives --install /usr/bin/ld ld /usr/bin/ld.bfd 10
update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 9
update-alternatives --set ld /usr/bin/ld.gold
```

**Comment by stevemasta34** [comment]
@akrabat I've followed your recommended steps, but the installation still fails due to libdispatch stuff. Following that through to libdispatch, I wound up [here](https://github.com/apple/swift-corelibs-libdispatch/blob/master/INSTALL.md)

Relevant segment:
```
1. sh autogen.sh
2. ./configure
3. make
4. make install
```

Step 2 __always__ fails, emitting this
```
checking for BSD_OVERLAY... configure: error: Package requirements (libbsd-overlay) were not met:

No package 'libbsd-overlay' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

Am I seriously the only person whose dealt with this level of resistance in using Kitura (on Ubuntu)?

**Comment by shmuelk** [comment]
@stevemasta34 Two comments:

    1. Did you install libbsd-dev (I think I got it right) ?

    2. More importantly, why not move to Kitura 0.28 on Swift 3 08/23 where you **no longer** have to install libdispatch.

**Comment by stevemasta34** [comment]
@shmuelk  I have updated my attempts to the latest Swift version Kitura states. The failures persist.
I do have the libbsd-dev package installed at the latest version and I can even see the .pc file on my system (with provide picture if requested)
