### ISSUE TITLE
In README.md GettingStarted, HeliumLogger dependency should be updated to 0.14 (or 0.15?)

### ISSUE THREAD

**Issue by Utsira** [IBM-Swift/Kitura#695]
If you try to build with DEVELOPMENT-SNAPSHOT-2016-07-25-a and HeliumLogger 0.13, you get a dependency error with the LoggerAPI. This goes away if you change the HeliumLogger dependency to 0.14

**Comment by vadimeisenbergibm** [comment]
Fixed in https://github.com/IBM-Swift/Kitura/pull/694.
