### ISSUE TITLE
Add logging to Kitura Tests 

### ISSUE THREAD

**Issue by rob-deans** [IBM-Swift/Kitura#705]
Copied `PrintLogger.swift` from Kitura/Tests/KituraTests/, into Kitura-net/Tests/KituraNetTests. Added 
```
override func setUp() {
        doSetUp()
    }
```
Before the function `tearDown()` and added:
```
    func doSetUp() {
        PrintLogger.use()
    }
```
Before func `doTearDown()` in KituraNetTest extension

**Comment by shmuelk** [comment]
Reviewed the code. Looks good.
