### ISSUE TITLE
Latest Docker image is broken: not compatible with the Swift toolchain it uses

### ISSUE THREAD

**Issue by foreignfilm** [IBM-Swift/Kitura#715]
Following the instructions to install Kitura with Docker, I'm unable to run either the Starter app or my own project, because the dependencies fail to compile. It's a whole lot of syntax errors, clearly due to the image not using the latest supported Swift toolchain:

![screen shot 2016-09-04 at 8 31 09 pm](https://cloud.githubusercontent.com/assets/1100824/18229934/5b98822c-72df-11e6-841d-09e9305b84f4.png)

The README states the the latest supported Swift snapshot is `DEVELOPMENT-SNAPSHOT-2016-08-23-a`, whereas the [Docker image](https://hub.docker.com/r/ibmcom/kitura-ubuntu/) uses `DEVELOPMENT-SNAPSHOT-2016-07-25-a`.

**Comment by shmuelk** [comment]
@foreignfilm The Kitura docker image is based on the ibmcom/swift-ubuntu:latest. There is work underway to upgrade that docker image to the Swift 3 08/31 level, which is compatible with the 0.28 version of Kitura.

Hopefully this will be fixed shortly.

**Comment by rolivieri** [comment]
@foreignfilm Can you pull the latest kitura-ubuntu image? `docker pull ibmcom/kitura-ubuntu:latest`? It should now be compatible with 08-31.

**Comment by foreignfilm** [comment]
@rolivieri thanks! I've pulled down the latest image and the starter app runs now. I'm still having trouble building my project though:

```
$ swift-build: error: the module at Tests/KituraSys has an invalid name ('KituraSys'): the name of a test module has no ‘Tests’ suffix
$ fix: rename the module at ‘Tests/KituraSys’ to have a ‘Tests’ suffix
```

I'm not entirely sure why this isn't an issue for the starter app.

**Comment by foreignfilm** [comment]
Actually, never mind, this was my mistake: I haven't updated the dependency package version. This issue is resolved. Thanks!
