### ISSUE TITLE
Provide example with tests

### ISSUE THREAD

**Issue by therickys93** [IBM-Swift/Kitura#716]
Can you please provide a simple application with some tests that works on both platforms? 
I follow your 'Getting Started' guide and all works fine, but when I add some tests, the tests are not running because of this: 

/swift/.build/debug/SwiftUnit.build/main.swift.o: In function `main':
/swift/Sources/main.swift:(.text+0x0): multiple definition of `main'
/tmp/LinuxMain-483598.o:/swift/Tests/LinuxMain.swift:(.text+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /swift-3/usr/bin/swift-build-tool -f /swift/.build/debug.yaml test

Thanks

Update: I am on a Linux machine

**Comment by vadimeisenbergibm** [comment]
@ianpartridge @shmuelk we should add tests to https://github.com/IBM-Swift/Kitura-Sample

**Comment by therickys93** [comment]
@vadimeisenbergibm there is any update?
I see this repository: https://github.com/IBM-Swift/Blitter and tests are working. So i think that you have to update your wiki. What do you think?
Best Regards and Thanks for your help.

**Comment by vadimeisenbergibm** [comment]
@ianpartridge could you please handle this?

**Comment by rob-deans** [comment]
@therickys93 Added some sample tests, the problem was the naming convention, it is now merged in Kitura-Sample

**Comment by therickys93** [comment]
@rob-deans thank so much for your help
