### ISSUE TITLE
Add capabilities for credential "validation" similar to NodeJS's PassportJs

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#72]
<a href="https://github.ibm.com/KALLNER"><img src="https://avatars.github.ibm.com/u/3096?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KALLNER](https://github.ibm.com/KALLNER)**
_Tuesday Jan 26, 2016 at 16:34 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/72_

----

Create a framework for credential validation and authentication.

The framework will:

   1. Support plugins for doing specific types of authentication and/or credential validation.

    2. Supply a set of classes that implement a cache that can be used by the various plugins. The cache will support removal of items by LRU and TTL.

**Comment by shmuelk** [comment]
This issue is complete except for a README.md file which will be done in the next sprint under issue #253

**Comment by dfirsht** [comment]
Is there a reason that the .h and info.plist files are still present?

**Comment by dfirsht** [comment]
Thanks @irar2!
