### ISSUE TITLE
Document the APIs of Swift-redis

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#727]
Document the APIs of Swift-redis. Lets do this in sections:

  - The non transactional APIs
     [ ] Infrastructure APIs
     [ ] Base commands
     [ ] Hash commands
     [ ] List commands
     [ ] Set commands
     [ ] Sorted sets

  - The transactional APIs
     [ ] Infrastructure APIs
     [ ] Base transactional commands
     [ ] Hash transactional commands

**Comment by ianpartridge** [comment]
I think this is done now.
