### ISSUE TITLE
Create a plugin for the Kitura Credentials framework that supports FaceBook tokens from mobile apps.

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#73]
<a href="https://github.ibm.com/KALLNER"><img src="https://avatars.github.ibm.com/u/3096?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KALLNER](https://github.ibm.com/KALLNER)**
_Tuesday Jan 26, 2016 at 16:39 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/73_

----

Create a plugin that can be used by servers to validate FaceBook OAuth tokens sent from mobile apps.

*Note* This is not the same as logging in a web app using one's FaceBook ID. Here we assume that the mobile app has used a FaceBook SDK to perform a login using FaceBook and is now sending requests to the server using an OAuth token the app received from FaceBook.

**Comment by shmuelk** [comment]
This issue is complete except for a README.md file which will be done in the next sprint under issue #253

**Comment by dfirsht** [comment]
Validated.
