### ISSUE TITLE
Poor Blog benchmark performance

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#734]
I'm in the process of learning more about our poor performance on the Blog benchmark.
At the moment it looks like we might have some more keepalive related bugs.

Steady state (which we maintain only briefly) actually performs very well, we're ~7.5k req/sec on my Macbook Pro, which compares favourably to other frameworks.

The problem is that we don't maintain this state very long - our threads seem to gradually stop running, almost like a deadlock situation.

Recreate instructions:
```
git clone https://github.com/djones6/Server-Side-Swift-Benchmarking.git
cd Server-Side-Swift-Benchmarking
./build.sh
cd KituraPress_029
./blog.sh
```
(in another terminal)
```
wrk -c20 -t4 -d120s http://localhost:8080/blog
```
Profiling the `Blog` process using Instruments while load is being driven reveals 4 distinct phases:
1) Initially good performance (lasts 10 seconds or so) with high CPU utilization
2) Drop-off in performance and also CPU utilization (often appears stepped, as though threads gradually stop processing)
3) A recovery in CPU utilization after a variable period of time, where we briefly return to high CPU (similar to the first ~10 seconds).  Does not always happen (or possibly, I just didn't run for long enough).
4) CPU continues to be burned after load has finished, apparently trying to read from a socket, which should now be closed (@tardieu IIRC you'd also observed this) - how long this goes on for varies, but can be significant (50+ seconds).

Sometimes I have instead seen CPU utilization (and throughput) drop to zero rather than the stepped drop-off.  I need to recreate this and drive load for longer to see if we ever recover from this condition.

In all cases, if I stop and then immediately re-apply load (which has the effect of terminating and reestablishing the client connections),  we go back to the initial 'good' state for a while.  For this reason, I suspect there's something related to keepalive that is at fault.

**Comment by tardieu** [comment]
Yes I have observed the same on Mac.

For point 4, I have confirmed that the data sources keep firing after the 
client has closed the socket but I have not investigated further.

For 1 and 2, I have observed a performance drop when a benchmark exhausts 
available sockets.
But for Swift-Empower/plaintext this is no longer an issue for me since 
the lifetime of keepalive sockets has been increased from 20 to 100.
Maybe the Blog benchmark explicitly and frequently closes sockets?

Olivier

**Comment by djones6** [comment]
While we're burning CPU (stage 4), `netstat -an | grep 8080` shows that, several seconds after `wrk` has terminated, all 20 client connections are still present, in FIN_WAIT_2 on one side and CLOSE_WAIT on the other:

**Comment by djones6** [comment]
Regarding 2),  I don't think this problem is related to running out of ephemeral ports.

If the keepalive implementation is working correctly, we should see the port numbers rotate (relatively) slowly over time.  Each should last for 100 requests,  so assuming a steady throughput of 7.5k/sec across 20 connections,  each connection would last for an average of 0.25 seconds.  Or in other words, 4 connections/sec * 20 connections = 80 ports per second.
By default, there are 16384 ephemeral ports available,  so it would take over 3 minutes to use them all,  by which time they should long since have been cleaned up.

On my system at least, periodically checking netstat indicates that this is what is going on.

One interesting thing relating to 2) is that as the throughput drops, some of the client connections appear to be 'stalled', ie. those connections stay in established state for a long time while others are still cycling.  I wonder if it is possible that connections sometimes do not get re-queued for processing?

It's possible this problem is not specific to the Blog benchmark.

I have been using much higher numbers of simultaneous client connections (typically 128) while driving 'hello world',  so if a number of those were to stall,  it may not manifest as a thoughput drop.  However, if this is the case, them I'm puzzled as to why `wrk` is not reporting errors / very high latency.

I tried increasing the number of concurrent clients to 128 for Blog, and now I can sustain a good throughput level.  I'll see whether the reverse (20 clients + hello world) replicates the problem.

**Comment by djones6** [comment]
I have an idea of what (I think) is going wrong:  it relates to the `state` of the IncomingHTTPSocketProcessor for subsequent requests on a keepalive connection.

Having added debug, I see the following sequence of events:

- accept a connection
- create a Dispatch ReaderSource
- read the request
- process() the request,  state = `.initial`
- parse() the request
- parsingComplete(),  state = `.parsedHeaders`
- Router.handle(), invoke the matching route
- write the response
- call processor.keepAlive,  state = `.reset`
- read the next request
- process() the request, state = `.reset`
- reset the request/response, fallthrough, state = `.initial`
- parse() the request

... etc

In the failing case, I see process() called for a subsequent request and the state is `.parsedHeaders`.  Once we hit this state, we stop processing that socket altogether.

The only point at which we enter this state is in parsingComplete(), and we should have subsequently reset the state by calling keepAlive().

The debug for a failing case suggests that we are somehow starting to read the next request from the socket, and get as far as process(), before we've finished writing the previous response - or at least, before we have finished the actions that we take, such as calling keepAlive().

**Comment by shmuelk** [comment]
We currently parse the request in a parallel thread.

Is it possible that the next read came in before we succeeded in parsing the previous one?

**Comment by djones6** [comment]
Closing, as both functional issues originally reported (drop-off and idle CPU consumption) are fixed.
There are two further issues related to this workload for which I'll raise new items.
