### ISSUE TITLE
Fix Static File Serving in Kitura

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#741]
Serving static files should not assume that `Packages` directory exist, `Packages` directory is a build time artifact. The executable can be deployed without `Packages` directory.

Proposed design:

1. Use `Bundle.main().pathForResource`. (Should be future-proof, SPM may provide Resource management in the future)
2. Use `Makefile` to copy the resources to the `.build` directory
3. Use `Copy Files` build phase in Xcode
4. Use `customFixXcode` target in Makefile to add the build phase in 3.
5. For deployment - copy `Resources` directory to the location of the executable.

**Comment by vadimeisenbergibm** [comment]
The produced executable depends on dynamic libraries produced by SPM. These dynamic libraries, for example `libHTTPParser.dylib` are produced in the `.build` directory.

The location of the build directory can be changed by providing `--build-path` flag. This means that one cannot assume that the result executable runs in the original sources directory (of the repository, the directory that contains `Package.swift`), or in `.build` directory inside the original sources directory.

[To check which libraries an executable depends on:] (http://stackoverflow.com/a/1058872/6028420)

- On macOS: `otool -L <executable>`

Example output:
```
vadime-mac:KituraExecDir vadime$ otool -L KituraSample 
KituraSample:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1338.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1237.0.0)
	/System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork (compatibility version 1.0.0, current version 796.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1338.0.0)
	/Users/vadime/KituraBuild/release/libCHTTPParser.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	@rpath/libswiftCore.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftDarwin.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftDispatch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftFoundation.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftIOKit.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftObjectiveC.dylib (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by vadimeisenbergibm** [comment]
It was decided that the following design will be implemented:

Handling static resources will be _source-location based_.

Use `#file` directive to get the source location of the current source file, calculate the location of static resources based on their relative location in regard to the current source file.

**Pros**: Simple to the user
**Cons**: The assumption here is that the source directory (inside Packages directory of the executable) will remain at the same location after the build. Additional assumption is that the source location is accessible to the running executable, in particular it is on the same machine as the running executable and the process of the running executable has permissions to access the sources.

**Comment by vadimeisenbergibm** [comment]
It was decided on a hybrid approach:

Handling static resources will be first _working-directory based_. If the resource does not exist on a path relative to the working directory, _source-location based_ approach will be applied, see https://github.com/IBM-Swift/Kitura/issues/741#issuecomment-248541828.

**Comment by vadimeisenbergibm** [comment]
Implemented as described in https://github.com/IBM-Swift/Kitura/issues/741#issuecomment-248584516.

**Comment by shmuelk** [comment]
reviewed when merged PR.
