### ISSUE TITLE
Invalidated Socket Error in Kitura-net:handleWriteHelper in 0.32

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#762]
We were using Kitura fine at 0.30.  Starting in 0.32, we get constant socket errors.

The issue is at line 118-119 of IncomingSocketHandler.swift

As the socket is being written to over time, `writeBufferPosition` increases with every write.  Eventually, it becomes equal to `writeBuffer.length` at which point `bufSize: writeBuffer.length - writeBufferPosition` becomes `bufSize: 0`, which causes `Socket.write()` to throw `Socket.SOCKET_ERR_INVALID_BUFFER`.

This is blocking the Sandbox from moving to 0.32.

**Comment by carlbrown** [comment]
<img width="1024" alt="screen shot 2016-09-20 at 10 11 46 am" src="https://cloud.githubusercontent.com/assets/67206/18676299/c3d465d0-7f1a-11e6-939f-29d84b23e21a.png">

**Comment by carlbrown** [comment]
<img width="1018" alt="screen shot 2016-09-20 at 10 18 21 am" src="https://cloud.githubusercontent.com/assets/67206/18676555/9c537fd6-7f1b-11e6-8647-17e3fda05c1e.png">

**Comment by shmuelk** [comment]
Thanks for detailed debug of the problem. I'll get that fixed right away.

**Comment by billabt** [comment]
@carlbrown: It'd be easy to change `BlueSocket.write()` to return a zero (0) if the `bufSize` is equal to zero (0) but it seems me that that'd be most likely, the wrong thing to do...  I would think that the proper fix would be to check the length before issuing the write...
```
if writeBuffer.length != 0 {
    do {
        var writeLength = writeBuffer.length - writeBufferPosition
        if writeLength == 0 {
            writeBuffer.length = 0
            writeBufferPosition = 0
        } else {
            let written = try socket.write(from: writeBuffer.bytes + writeBufferPosition, bufSize: writeLength)
            if written != writeBuffer.length {
                writeBufferPosition += written
            } else {
                writeBuffer.length = 0
                writeBufferPosition = 0
            }
       }
    catch {
       ....
```

**Comment by billabt** [comment]
Didn't mean to close the issue. 😃

**Comment by shmuelk** [comment]
@carlbrown I have created a branch of Kitura-net with a fix. Can you please test it?

To test this branch:

  - Move up to Kitura 0.33
  - Clear your Packages directory
  - Do a `swift package fetch`
  - Do a `cd Packages/Kitura-net-0.33.x`
  - Run the following commands:
```
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git checkout issue_762
cd -
```
 - Run `swift build`
 - Run your server and test

**Comment by carlbrown** [comment]
Much better. Thank you.

Tested (and working) with Swift 3.0-RELEASE on both macOS 10.11.6 and Ubuntu 15.10 (via Vagrant)

**Comment by shmuelk** [comment]
Your welcome.
