### ISSUE TITLE
Main Readme points to 1.0 version, which cannot be installed via SPM

### ISSUE THREAD

**Issue by ogres** [IBM-Swift/Kitura#767]
Getting Started -> Step 3

`        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 0)
`

Error:

Cloning https://github.com/IBM-Swift/Kitura.git
error: The dependency graph could not be satisfied. The package (https://github.com/IBM-Swift/Kitura.git) with version tag in range (1.0.0..<1.0.9223372036854775807) is not found. Found tags ([0.0.1, 0.0.5, 0.0.6, 0.0.9, 0.0.12, 0.2.0, 0.3.0, 0.3.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.7, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.15.7, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.17.6, 0.17.7, 0.17.8, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.33.1, 0.33.2])

**Comment by ianpartridge** [comment]
Watch this space - 1.0 coming *very* soon!
