### ISSUE TITLE
Question: Platform specific code centralization

### ISSUE THREAD

**Issue by bdev36** [IBM-Swift/Kitura#774]
Platform specifics (Linux/OSX/...) may be easier to manage if centralised in a single file (e.g.: "Parity.swift", see below)

- Would anything like <https://github.com/IBM-Swift/Kitura/compare/master...bdev36:master> be of any usefulness ?
- In this project, each platform specific `#if` should have been replaced by something in "Parity.swift".
- The idea is to remove all `#if` from the source code, except in`Parity.swift`.

The forked project compiled and passed tests on OSX, nothing more for now (anything between `#if os(Linux) ... and ... #endif` may not work).

**Comment by shmuelk** [comment]
@bdev6 Thanks for the suggestion of centralizing all of the platform specific cod with Kitura. We need to think about this a bit, to decide if having all of the platform specific code in one place is worth the "un-inlining" the code, as in most places it's just one line or two.

**Comment by vadimeisenbergibm** [comment]
You can put all the platform-specific code in https://github.com/IBM-Swift/Bridging

**Comment by bdev36** [comment]
Thanks, I didn't see https://github.com/IBM-Swift/Bridging.

Just in case, I let the above-linked changesets in a [specific branch](https://github.com/bdev36/Kitura/tree/parity) and closed this issue.
