### ISSUE TITLE
Xcode Version 8 - KituraNet - No Such Module 'CCurl'   

### ISSUE THREAD

**Issue by esrshn** [IBM-Swift/Kitura#785]
How can i fix this error?

It has been working without problem in the console.

Xcode project was create with the "swift package generate-xcodeproj" command.

Xcode Version8.0(8A218A) Dependencies - KituraNet - ClientRequest.swift 
Line 18 import CCurl No Such Module 'CCurl'

swift build --version
Apple Swift Package Manager - Swift 3.0.0 (swiftpm-19)

swift --version
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9

CCurl-0.2.2
CHTTPParser-0.3.0
HeliumLogger-1.0.0
Kitura-1.0.0
Kitura-net-1.0.1
Kitura-TemplateEngine-1.0.0
LoggerAPI-1.0.0
Socket-0.11.17
SSLService-0.11.31
SwiftyJSON-14.2.0

**Comment by agnosticdev** [comment]
This sounds like Xcode does not know where to look for the CCurl module.
One thing you could try is adding CCurl in your header search path under the build settings tab for the target you are trying to compile for.

Here is a thread to a closed issue discussing potentially the same issue.
https://github.com/IBM-Swift/Kitura/issues/272#issuecomment-201291414

**Comment by esrshn** [comment]
I'm so sorry for my mistake.
My application folder contains a space character.
Currently it works flawlessly.
Thank you so much agnosticdev.

**Comment by agnosticdev** [comment]
@esrshn No problem at all.  Glad to help!
