### ISSUE TITLE
JSON benchmark performance on Linux

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#788]
Benchmarks using SwiftyJSON perform very poorly on Linux but the same benchmark performs well on OSX.

Theory is this is due to the Linux specific serializer, investigate whether we can move to Foundation on Linux yet,  and if so,  does this perform better.  Relates to #362

**Comment by wildfiremedia** [comment]
I would suggest you to read this first on Perfect on Linux.
https://medium.com/@rymcol/linux-ubuntu-benchmarks-for-server-side-swift-vs-node-js-db52b9f8270b#.m5c69j3di

**Comment by djones6** [comment]
@shmuelk The latest commit to SwiftyJSON issue_788 improves our performance by almost 4x, but introduces a memory leak.  I have a possible solution in IBM-Swift/SwiftyJSON#22 which doesn't leak and seems to perform similarly.

**Comment by djones6** [comment]
For reference, Kitura 1.0.1 (https://github.com/IBM-Swift/Kitura/commit/43d9c174e0fe3a045612c2c65e6be90bb8a9943d) and SwiftyJSON 14.2.1 (https://github.com/IBM-Swift/SwiftyJSON/commit/d8de7c8f71df7c939f3d47e7d1fb53f344b471fa) contain fixes that give us a 3.5x improvement:
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb) | Avg Lat (ms) | Max Lat (ms)
---------------|----------------|----------------|---------|--------------|--------------|--------------
  Kitura 1.0.0 |         4803.4 |        4803.48 |    99.1 |        24028 |          5.1 |        81.12
  Kitura 1.0.1 |        16707.2 |       16883.51 |    88.0 |        25719 |          1.9 |        67.27
```

**Comment by wildfiremedia** [comment]
Awesome!

**Comment by ianpartridge** [comment]
@djones6 can we close this out?

**Comment by djones6** [comment]
Yes, we can close.
Our Linux performance is still significantly worse than on OSX, but I'll create a new issue to continue that investigation at the appropriate time, probably makes sense to do this in the context of 3.0.1 and having dropped the Linux serializer.
