### ISSUE TITLE
Kitura exhausts physical memory on 2-core Mac Mini under heavy load

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#790]
While investigating performance of the Blog / JSON benchmarks on a Mac Mini (2-core i7), I discovered that we run out of memory on a long run (leads to OSX memory compression kicking in and gradually killing performance of the system).

Memory allocated seems to rapidly increase while under heavy load, however once load ceases, memory usage drops back to a low level.  The recovery seems to correspond to stopping load, rather than closing connections,  since connections are closed periodically anyway by the keepalive code (100 reqs per connection).

Theory is this may relate to the periodic (1 minute interval) cleanup for idle connections.

**Comment by djones6** [comment]
I finally spent a little time on this.  It's still happening with Kitura 1.3.0.

When we run on the Mac Mini, All four CPU threads are at 100% while the load is applied.  I applied load over a private network:  `wrk -t4 -c20 -d60s http://swiftmacminiGB:8080/blog`

I ran through the XCode debugger, and took a look at the object graph (which pauses execution).  The memory usage grew rapidly (702mb process size after around 20,451 requests) at the point I paused it.

There are no apparent leaks of Kitura or Kitura-net objects themselves (ie. no obvious retain cycles), however there seems to be a buildup of these Foundation objects:

`NSRegularExpressionCheckingResult` (20,455 of these)  - these only seem to be referenced by something labelled `@autoreleasepool content`
`NSConcreteMutableData` (21,166 of these) - the ones at the top of the list (I assume these are the youngest) are referenced by the HTTPParser / HTTPServerRequest cycle,  BufferList,  or Socket,  but the vast majority are only referenced by `@autoreleasepool content` and `VM: Dispatch continuations`.
`_NSInlineData` (40,903 of these)  - only seem to be referenced by `@autoreleasepool content`

It looks like maybe ARC simply isn't cleaning up.

As soon as I resumed process execution, the memory dropped back down to ~40mb.

**Comment by djones6** [comment]
I'm pretty sure this is simply an issue of CPU starvation.  It looks like ARC may be run on a separate thread on Mac, and when the application monopolizes the CPU, cleanup doesn't happen.

This Mini has 4 CPUs.  Running with 4 concurrent clients produces ~350% CPU load, ie. 3.5 threads, and memory usage is flat.  If I go to 8 concurrent clients,  I see spikes where memory rapidly increases and then drops back to the resting (~40mb) range.  I guess this is on the verge of preventing ARC from running.

Here's the view of CPU consumption from XCode with 3, 4 and then 8 clients:

![mini_cpu_starvation_1](https://cloud.githubusercontent.com/assets/17850918/21137988/ff5eb5ba-c123-11e6-8600-e47a07f91325.png)

And the corresponding memory consumption:

![mini_cpu_starvation_2](https://cloud.githubusercontent.com/assets/17850918/21138030/2d85ed00-c124-11e6-8d9d-7e323a0b6637.png)

I do not believe this is a Kitura problem at all.  It's more to do with the behaviour of ARC on Mac under extreme CPU load.

**Comment by ianpartridge** [comment]
You'll need to use Instruments, I think.  Sorry, I don't know any more.

**Comment by WhatYouWant** [comment]
> You'll need to use Instruments, I think. Sorry, I don't know any more.

I find this concept by using Instruments, and i found ,for the same code may be has some problem, if i use autoreleasepool, there isn't autoreleasepool content in instruments, and if i not use autoreleasepool, there has some autoreleasepool content
