### ISSUE TITLE
Explore ORM for Kitura

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#791]

**Comment by t3ndai** [comment]
If Kitura, is to be Express.js-esque. I would support continue having Swift-Kuery, as it's close to SQL hence really flexible.

**Comment by tunniclm** [comment]
@ianpartridge Just bumping this issue now we have https://github.com/IBM-Swift/Swift-Kuery-ORM

**Comment by ianpartridge** [comment]
As Mike says, we now have https://github.com/IBM-Swift/Swift-Kuery-ORM which is under active development so I'm closing this issue.
