### ISSUE TITLE
Add cfPush target to Makefile

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#798]

**Comment by ianpartridge** [comment]
@vadimeisenbergibm is this complete?

**Comment by vadimeisenbergibm** [comment]
@ianpartridge No, it is not complete, since it requires further discussion. I will create a design issue to discuss it.

**Comment by ianpartridge** [comment]
OK. Can you summarise what has been done so far and what's left?

**Comment by vadimeisenbergibm** [comment]
The issue is implemented, there is a discussion if this feature is needed at all.

**Comment by ianpartridge** [comment]
Thanks Vadim, but how can it be both implemented and incomplete?

**Comment by vadimeisenbergibm** [comment]
The implementation is done. The design decision if this feature should be added to Package-Builder and Kitura Samples is not yet taken.

**Comment by shmuelk** [comment]
We no longer have Makefiles in our projects
