### ISSUE TITLE
Use shim.h in IBM-DTeam/swift-for-db2

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#802]
It seems these flags are still needed, for example for packages that work with DB2 Driver, see - [TodoList-DB2 compilation instructions](https://github.com/IBM-Swift/TodoList-DB2#compile-and-run-tests). If these flags do not cause any problems when they are not needed, we can just add them to `make build`, for all the projects.

@rfdickerson @rolivieri @shmuelk your comments are welcome.

**Comment by shmuelk** [comment]
@vadimeisenbergibm Have you tried building the DB2 driver without those flags? Perhaps the DB2 instructions haven't been kept up to date?

**Comment by vadimeisenbergibm** [comment]
@shmuelk Yes, I tried.
```
Linking ./.build/debug/Deploy
ld: library not found for -libmdb for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
```

BTW, `make test` has the same problem and should be updated with the same flags as `make build`.

**Comment by vadimeisenbergibm** [comment]
@shmuelk I have learned why [CLibpq](https://github.com/IBM-Swift/CLibpq) works with `swift build` without additional flags. It works thanks to `pkgConfig` argument in [Package.swift](https://github.com/IBM-Swift/CLibpq/blob/master/Package.swift):

```swift
pkgConfig: "libpq"
```

Using `pkgConfig` value, SPM uses `pkg-config` command to know how to compile and link the module:

```
$  pkg-config --cflags libpq
-I/usr/local/Cellar/postgresql/9.4.0/include 
$ pkg-config --libs libpq
-L/usr/local/Cellar/postgresql/9.4.0/lib -lpq
```

`pkg-config` knows this information since during the installation of `postgresql`, the installation script probably writes file `/usr/local/lib/pkgconfig/libpq.pc` in `/usr/local/lib/pkgconfig` directory for `pkg-config` to read. No such entry is created during installation of db2 cli drivers.

So, we either have to change the installation of db2 cli driver to write a `.pc` entry in  `/usr/local/lib/pkgconfig/`, and expect the users of Makefile to use only system modules that create `pkg-config` entries, or to add `-Xcc -I/usr/local/include -Xlinker -L/usr/local/lib` to `make build/test` to relax this requirement.

**Comment by vadimeisenbergibm** [comment]
Closing as irrelevant to Kitura. swift db2 team should write a `pkg-config` `.pc` entry in /usr/local/lib/pkgconfig/ and use `pkgConfig` parameter in `Package.swift`.
