### ISSUE TITLE
Test target in xCode

### ISSUE THREAD

**Issue by maxday** [IBM-Swift/Kitura#803]
Hi,
First thanks for your awesome work 👍 

I've written some tests and I can run them using swift test but I can't figure out how can I run them directly in xCode

I've used swift package generate-xcodeproj to generate my xCode project. 
Maybe there is an option to generate a test target as well ?

I've also tried to add the test target manually, but impossible to run in xCode : first it was missing CCurl so I've played around with header search path and other options as described here https://github.com/IBM-Swift/Kitura/issues/272 but now I have some linking issues. 
Is there a simpler way to run tests from xCode ? 

Thanks

**Comment by youming-lin** [comment]
@maxday What is the exact issue you are running into? From my experience, if I `swift package init` and then `swift package generate-xcodeproj` when I start a new project, the auto-generated test files show up in Xcode and I can then run them in Xcode.

As for missing CCurl issue, do you have a space in your project folder path?

**Comment by maxday** [comment]
Thanks, I didn't use swift package init :)
All good, thanks for your quick answer
