### ISSUE TITLE
To deploy/run the app on docker, instructions must clearly indicate the use of IP address

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Swift/Kitura#804]
The  [instructions](http://www.kitura.io/en/starter/deploying.html) to deploy and run the app using Docker should clearly indicate that the browser on the host machine should use the IP address.

Perhaps, a new Step 6 can be added to the existing list of steps as shown below:

```
6. Point your browser(running on the host machine) to point at
http://<ip-address-from-DOCKER_HOST-env-variable>:8090/hello
```

**Comment by ianpartridge** [comment]
Thanks for opening the issue.  You don't need to use the IP address, you can go to `http://localhost:8090/`. I've updated the README to state this.  Thanks.
