### ISSUE TITLE
Organizing Routes examples

### ISSUE THREAD

**Issue by yoiang** [IBM-Swift/Kitura#805]
Hello!
I'm new to the Kitura project! I was wondering how one goes about organizing routes a larger project.

In a framework such Express one can build sub-routers and sub-sub-routers, all in their own files, and register them relative to their current root, eg:

``` javascript
import subroot from './subroot';
import subroot2 from './subroot2';

root.get('/', ...)
root.use('/subroot', subroot)
root.use('/subroot2', subroot2)
```

``` javascript
// subroot.js ---

import subSubroot from './subSubroot';

subroot.get('/', ...)
subroot.use('/subsubroot', subSubroot)
```

```
GET /
GET /subroot
GET /subroot/subsubroot...
GET /subroot2...
```

How does one accomplish this in Kitura? Is there a method for registering a Router within a Router I've missed?

**Comment by youming-lin** [comment]
@yoiang Yup, Kitura was designed to offer a similar routing structure as expressjs :)

Since [`Router` class extends `RouterMiddleware`](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/Router.swift#L151), you can mount a `Router` instance as you would any middleware. I made a simple example here:

```swift
import Kitura

let subrouter = Router()

subrouter.get("/world") { request, response, next in
    try response.send("Hello world").end()
}

let router = Router()

router.get("/hello", middleware: subrouter)

Kitura.addHTTPServer(onPort: 3000, with: router)
Kitura.run()
```

And then, after you build the project and run the server app, you can curl it:
```
ylin@youming-mbpr:~/Swift/swift-test$ curl localhost:3000/hello/world
Hello world
```
The server returns `Hello world` as expected.

**Comment by yoiang** [comment]
@youming-lin Perfect, thanks so much :)

Would be great to include examples like this in the Kitura examples!

**Comment by shmuelk** [comment]
While @youming-lin's example works, you can also do this as:

```swift
import Kitura

let router = Router()

let subrouter = router.route("/hello")

subrouter.get("/world") { request, response, next in
    response.send("Hello world")
    next()
}

Kitura.addHTTPServer(onPort: 3000, with: router)
Kitura.run()
```

**Comment by yoiang** [comment]
Ah cool! Both had their own benefits, thanks @shmuelk :)

**Comment by yoiang** [comment]
So I should be able to do one of the below but neither works:

``` swift
subrouter.get("/", getWithId)
// or subrouter.get("", getWithId) ?
subrouter.post("/doOnObjectWithId", doOnObjectwithId)

router.all("/:id", allowPartialMatch: true, middleware: subrouter)
```

or

``` swift
var subrouter = router.route("/:id")

subrouter.get("/", getWithId)
// or subrouter.get("", getWithId) ?
subrouter.post("/doOnObjectWithId", doOnObjectwithId)
```

Neither of the sub's routes work. However this works just fine but isn't preferable:

``` swift
router.get("/:id", getWithId)
router.post("/:id/doOnObjectWithId", doOnObjectwithId)
```

Any suggestions? (discussions aside of whether `/:id` belongs in the root or subrouter as `/:id/doOnObjectWithId` also does not work and it really should be the subrouter)

**Comment by youming-lin** [comment]
@yoiang I just had a chance to test this in Node express and express shows the same behavior. If the `:id` param is specified in the outer router, it is not available in `req.params` in the subrouter.

```js
var express = require('express');
var app = express();
var router = express.Router();

router.get('/:param2', function(req, res) {
    res.send(JSON.stringify(req.params));
});

app.use('/:param1', router);

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

`curl localhost:3000/hello/world` returns `{"param2":"world"}`. `param1` is missing in the result.

**Comment by yoiang** [comment]
@youming-lin Express has a parameter when creating a router to merge parameters across all routes it parses:

``` javascript
var router = express.Router({
	mergeParams: true
});
```

Replacing the call with the above works

**Comment by yoiang** [comment]
Also the behavior in Express is different before specifying the parameter, it is correctly reaching the second route. In the examples I gave above the later routes are not found.

I'm going to try to reorganize them one more way that just came to mind.

**Comment by yoiang** [comment]
Yea, I am unable to have parameters pass through routers. I'm going to separate out this into another issue.

**Comment by youming-lin** [comment]
I have opened https://github.com/IBM-Swift/Kitura/issues/811 to track this issue.

**Comment by yoiang** [comment]
@youming-lin perfect, thanks a lot!

**Comment by youming-lin** [comment]
@yoiang FYI, I have added `mergeParameters` support to Kitura in #838, so this feature should be available starting with the next release.

**Comment by yoiang** [comment]
@youming-lin damn, dude, thanks for going all the way :)
