### ISSUE TITLE
Improve ease of configuring and deploying Kitura

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#809]
We want to make it easy for users to configure and deploy Kitura.

This might include a solution for:
- Packaging and reading essential files, such as SSL certificates
- Detecting and reacting to the runtime environment (e.g. automatically reading VCAP variables in a Cloud Foundry environment)
- Providing the ability to run in separate `dev` and `prod` modes

This has the working title `Kitura-Configuration` but might not necessarily be a new SPM package.

**Comment by youming-lin** [comment]
Hierarchical configuration loader is generic enough that it can stand as a standalone package. I'm leaning towards developing a Swift version of nconf, a Nodejs hierarchical configuration manager, and then integrate that into a Kitura-Configuration package for Kitura-specific config object format.
