### ISSUE TITLE
Kitura.io API listings should be sorted Alpha

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura#813]
As seen here: http://ibm-swift.github.io/Kitura/Classes/RouterResponse.html
The functions are not listed in alphabetical order, which looks confusing and sloppy.

Sorting all classes will improve consumability of docs.

**Comment by ianpartridge** [comment]
Thanks. These docs are generated by Jazzy and this is already raised there: https://github.com/realm/jazzy/issues/428
