### ISSUE TITLE
Support GRMustache 2.0

### ISSUE THREAD

**Issue by groue** [IBM-Swift/Kitura#814]
Hello,

[groue/GRMustache.swift](http://github.com/groue/GRMustache.swift) has been [updated](https://github.com/groue/GRMustache.swift/blob/master/CHANGELOG.md#v200) for Swift 3. It can fuel Kitura, as demoed by [groue/GRMustacheKituraDemo](http://github.com/groue/GRMustacheKituraDemo).

Do you recommend that I submit a pull request on [IBM-Swift/Kitura-MustacheTemplateEngine](https://github.com/IBM-Swift/Kitura-MustacheTemplateEngine) from [groue/Kitura-MustacheTemplateEngine](https://github.com/groue/Kitura-MustacheTemplateEngine/tree/Swift3)?

**Comment by lroseblade** [comment]
Hi @groue - yes, please submit a PR. Thank you!

**Comment by groue** [comment]
Done!

**Comment by shmuelk** [comment]
@groue Does your new GRMustache build and run on Linux?

**Comment by groue** [comment]
@shmuelk I don't know - I'm not fluent enough with virtual machines so that I could run a linux box on my macOS machine. The Kitura-MustacheTemplateEngine package disables Mustache on linux [as for today](https://github.com/IBM-Swift/Kitura-MustacheTemplateEngine/blob/dfd5e0e6d40fdb3b910b8840da473cf1d62a25a4/Sources/KituraMustacheTemplateEngine.swift#L28).

**Comment by shmuelk** [comment]
@groue You are correct in that Kitura-MustacheTemplateEngine package disables Mustache on linux as of now. Some of the tests don't pass on Linux. We are waiting for some Swift Linux fixes.

We'll wait until @vadimeisenbergibm gets back to the office and review this. He is our GRMustache expert.

**Comment by groue** [comment]
Yes, I'm waiting from @vadimeisenbergibm as well. He has spent much time having GRMustache run on Linux, and isolating Linux Swift/Foundation bugs that prevent all tests to run.

My GRMustache is still focused on Apple toolchain: I did not make any effort to support SPM testing, for example.

Yet the new [GRMustache 2](https://github.com/groue/GRMustache.swift/tree/2.0.0) that runs on Swift 3 is not only a port from Swift 2 with a few renamed methods. It also brings a major change in the way user data feed templates: when GRMustache 1 did attempt to map Swift types to Mustache data at compile time, GRMustache 2 relies exclusively on [runtime](https://github.com/groue/GRMustache.swift/blob/2.0.0/Sources/Box.swift#L203-L231). This was not possible until Swift 3, and has the major advantage of letting third-party libraries such as Kitura expose a simple `Any?` input that can be fed with any user values, including special values that leverage advanced Mustache renderings.

This may bring a whole new set of issues on Linux - or solve some of them. I don't know.

I'm thus very interested hearing from @vadimeisenbergibm, and maybe have our works eventually converge.

**Comment by groue** [comment]
I know this is not really the correct place for that, but I would also be very interested talking about improving templating around three axes:

- **Threading model**: I could not find yet any documentation about the Kitura invariants regarding threading and LibDispatch - facts that hold true whatever the way Kitura works (as a standalone server, or behind fastCGI, or behind any future proxy). This is important for the next questions:
- **Template caching**: You don't really want templates to be parsed each time they are rendered. If the template engine supports a cache of template parsing (as GRMustache does), it would be nice to support it.
- **Template engine configuration**: How to configure the rendering engine? Globally? Per request?

**Comment by shmuelk** [comment]
In general Kitura uses Grand Central Dispatch for it's multi-programming. On Linux libDispatch is used, which is now part of standard Swift driver on Linux.

In general when KituraNet has received and parsed a request, it invokes the ServerDelegate in a block on the GCD GlobalQueue. Thus all Kitura processing, including handling of templates happens in a parallel queue.

**Comment by groue** [comment]
Thanks @shmuelk!

**Comment by vadimeisenbergibm** [comment]
Hi @groue, I am back from a vacation, glad to hear that you are interested in integrating GRMoustache with Kitura.  

I checked - GRMoustache 2.0 does not compile on Linux. It also does not support SPM layout with regard to the Tests, so you cannot run `swift test`. Due to the same issue, you also cannot run `swift build` in the GRMoustache directory (you can run `swift build` on a package which is dependent on GRMoustache).

So to integrate GRMoustache 2.0 with Kitura, it should be ported to Linux and it should support running tests to verify that the porting to Linux was successful. Ideas from my master version of GRMoustache 1.0 can help - it passes all the tests on OS X and 90% of tests on Linux.

So GRMoustache 2.0 deprecates GRMoustache 1.0, doesn't it? So most of my work on GRMoustache 1.0 is gone :(

**Comment by groue** [comment]
> Hi @groue, I am back from a vacation, glad to hear that you are interested in integrating GRMoustache with Kitura.

I'm also glad to help and join my efforts to yours, @vadimeisenbergibm!

> I checked - GRMoustache 2.0 does not compile on Linux. It also does not support SPM layout with regard to the Tests, so you cannot run swift test. Due to the same issue, you also cannot run swift build in the GRMoustache directory (you can run swift build on a package which is dependent on GRMoustache).

OK.

> So to integrate GRMoustache 2.0 with Kitura, it should be ported to Linux and it should support running tests to verify that the porting to Linux was successful. Ideas from my master version of GRMoustache 1.0 can help - it passes all the tests on OS X and 90% of tests on Linux.

All right.

> So GRMoustache 2.0 deprecates GRMoustache 1.0, doesn't it? So most of my work on GRMoustache 1.0 is gone :(

No it is not gone.

I haven't compared our versions of GRMustache yet, and I'm not sure what is the best way for us to proceed. Maybe we could start with a description of what we have done. This will highlight where we converge and where we have diverged, so we can find the best merging option.

- General direction
  
  GRMustache is and remains a Mustache template engine. It was born as a library targetting iOS/macOS applications, and has evolved into a server library thanks to you. It supports the minimal Mustache rendering language, and adds sugar for developers who want to get their job done and value productivity over logic-free purity.
  
  The 2.0.0 release has addressed the pain-point of the `Box()` function which made the previous versions clunky. This function used to turn user data (dictionaries, lambdas, custom types) into values that can feed the rendering engine. Because of the limitations of Swift 1 and 2, it was based on function overloading and compile-time information, and could not be fed with the `Any` type. Well, Swift 3 is not Swift 1 and Swift 2, and its runtime has evolved enough so that GRMustache can now get rid of the Box() function:
  
  ```
  try template.render(Box(data)) // GRMustache 1: render() accepts MustacheBox
  try template.render(data)      // GRMustache 2: render() accepts Any
  ```
  
  This is good for server APIs, because they can now expose a single entry point for their rendering stack, and let the GRMustache runtime do the boxing job (which still happens under the hood). KituraTemplateEngine eats [`[String: Any]`](https://github.com/IBM-Swift/Kitura-TemplateEngine/blob/1.0.0/Sources/KituraTemplateEngine/TemplateEngine.swift#L35). It could eat `Any` if it wanted - at least GRMustache wouldn't complain.
  
- SPM, tests, Linux, Mustache runtime

Besides the Swift 3 transition, GRMustache 2 has not changed many tests. The difference lies in the way collections are handled. GRMustache 1 could eat any Swift collection, when GRMustache 2 only eats arrays, sets, and dictionaries. A new test file takes care of checking the rendering of simple values vs. collections: [BoxTests.swift](https://github.com/groue/GRMustache.swift/blob/2.0.0/Tests/Public/BoxTests.swift). Other tests have not been changed except on tiny details (I hope I recall correctly).

I wish I can bring back your commits into the master branch of groue/GRMustache, if they don't break the Xcode tests.

Linux used to have a funny Foundation implementation. You have spent a lot of time working around Foundation oddities, and opening issues in the Swift bug tracker. I don't know if these issues are still relevant. I don't know if your efforts making Linux work had an impact of the support for the "regular" Foundation. I don't know if your efforts making Linux work have changed the GRMustache runtime in any significant way. I'm quite interested in your experience here.

- Mustache parser

The parser itself has not changed. I remember, but can't find, a commit that fixed an awful performance bug, and that you did apply into your fork. I think I've integrated it back already. Maybe you have brought other improvements. They're welcome, because the parser needs many :-)

**Comment by vadimeisenbergibm** [comment]
@groue The hardest part of the changes were the changes in `Box.swift`, as I documented it:
```swift
// It is not possible to override methods in extensions. Due to that, making                                            
// NSObject and its subclasses implement MustacheBoxable and override mustacheBox                                       
// methods does not compile. To overcome this, the following strategy is used:                                          
//                                                                                                                      
// 1. NSObject only made MustacheBoxable. Its mustacheBox implements all the logic                                      
// of boxing of subclasses of NSObject. Subclasses of NSObject are not                                                  
// MustacheBoxable and they do not implement mustacheBox method. Instead, added                                         
// Box methods per each relevant NSObject subclass                                                                      
// 2. The classes that are not subclasses of NSObject left AS IS                                                        
// 3. Handling of AnyObject changed to handling Any. On OS X, everything is AnyObject                                   
// when import Foundation is made. In general case, Any should be handled and not only                                  
// AnyObject. To this end, AnyObject was replaced by Any in the file and BoxAnyObject                                   
// changed to BoxAny                                                                                                    
// 4. Swift reflection (Mirror) is used in BoxAny to cast Any parameter to its                                          
// correct type  
```

It seems that you solved all these in GRMoustache 2.0. So it seems it would be better to start with GRMoustache 2.0 and port it to Linux, using my version of GRMoustache 1.0 as a reference. The steps to port GRMoustache 2.0 to Linux are as follows, in my opinion:

1. Change the layout of GRMoustache 2.0 to work with swift build/test, while verifying that the tests on iOS pass
2. Fix any failing tests on macOS, if any, while verifying that the tests on iOS pass
3. Perform the required changes to enable compilation on Linux, while verifying that the tests on macOS and iOS pass
4. Perform the required changes to enable tests on Linux, while verifying that the tests on macOS and iOS pass

Each step is incremental, it does not break the previous functionality. We can proceed step by step, by implementing a step on a branch/fork, and then merging it into your master. So after four such steps (branch/fork + PR/merge) we will have GRMoustache 2.0 compatible with SPM, compile on Linux and tests passing on iOS, macOS and Linux. Would you like me perform these steps and submit PRs for you to merge or would you like to perform some of the steps yourself?

**Comment by vadimeisenbergibm** [comment]
A PR submitted https://github.com/groue/GRMustache.swift/pull/39

**Comment by christiancompton** [comment]
Closing - please reopen if needed.
