### ISSUE TITLE
Fix KituraNet test issues on Linux

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#817]
As of late KituraNet builds have been failing some of the time in a very strange way. On Travis-CI it appears as if the run of swift test simply exited in the middle of the test.

I was able to recreate the issue locally and when I ran the tests under lldb, the failure is a SIGTRAP. Which to be honest seems strange, as SIGTRAP should be a breakpoint and I hadn't set any breakpoints.

**Comment by tunniclm** [comment]
Unless my memory is playing tricks on me, I think I've seen libswift generate SIGTRAP for accessing unowned references that are nil.

**Comment by shmuelk** [comment]
The fix here seems to have solved the problem.
