### ISSUE TITLE
Make it easier to access the body of a request from a RouterRequest

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#820]
Add to ParsedBody asJSON, asMultiPart, asText, and asUrlEncoded in the style of the "helper" functions that exist in Kitura-redis's RedisResponse enum.

**Comment by naithar** [comment]
Wouldn't implementing a `subscript` access to ParsedBody in future as part of Kitura also provide some convenience if exact body type is not important?

**Comment by shmuelk** [comment]
@naithar I've thought about your comment a few times, I keep getting stuck on the same issue. If we add such a subscript function, what does it return? A String? An Any?

**Comment by akrabat** [comment]
> @naithar I've thought about your comment a few times, I keep getting stuck on the same issue. If we add such a subscript function, what does it return? A String? An Any?

In my view, such a function would return a String on the basis of least surprise as that's what the underlying HTTP body is.

**Comment by naithar** [comment]
At a basic level `Any` or `String` would sufficient for most cases imo.
It could also return value like it's done in SwiftyJSON or in IBM-Swift/Kitura#707

**Comment by ianpartridge** [comment]
Closing as the main work is done. We may consider adding subscripts as well, but would do that separately.
