### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by JSafaiyeh** [IBM-Swift/Kitura#823]
Is it possible to host a GraphQL server with Kitura?

If not, is there any plans for it?

**Comment by shmuelk** [comment]
I don't know. We haven't tried it yet. At this time the Kitura team has no plans for that yet. We would love to hear from the community if anyone else has already tried it, though.

**Comment by JSafaiyeh** [comment]
Would be interesting to see. There are attempts to implement GraphQL with Swift. 
https://github.com/GraphQLSwift/GraphQL

**Comment by lgaches** [comment]
I've implemented a Middleware for Kitura and using https://github.com/GraphQLSwift/GraphQL . It's here and it's in progress https://github.com/lgaches/Kitura-GraphQL .

**Comment by shmuelk** [comment]
Cool

**Comment by kweinmeister** [comment]
Great work @lgaches! I'll close the tracking issue here in the Kitura backlog.
