### ISSUE TITLE
Write to socket error

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#828]
Transferred from:
https://github.com/IBM-Swift/BlueSSLService/issues/4

@benedictdelfierro:
> Tried to enable TLS by following sample from kitura.io in linux
> 
> but encountered this error when accesing the server
> 
> ERROR: handleWriteHelper() IncomingSocketHandler.swift line 194 - Write to socket (file descriptor 10 failed. Error number=0. Message=Success.

**Comment by na-gupta** [comment]
@benedictdelfierro: I am not able to replicate the error using the steps on http://www.kitura.io/en/resources/tutorials/ssl.html 
Could you please tell me what variant/version of Linux and swift you're using, and paste the code you're using to set up SSLConfig.

**Comment by benedictdelfierro** [comment]
Ubuntu 14.04.4 LTS 
Swift 3
Package(url: "https://github.com/IBM-Swift/Kitura.git",        majorVersion: 1, minor: 0)


Here is the code for TLS:

let myCertPath = "/tmp/Creds/certificate.pem"
let myKeyPath = "/tmp/Creds/key.pem"

let mySSLConfig =  SSLConfig(withCACertificateDirectory: nil, usingCertificateFile: myCertPath, withKeyFile: myKeyPath, usingSelfSignedCerts: true)

Logs from server:
INFO: listen(socket:port:) HTTPServer.swift line 128 - Listening on port 8090 
INFO: listen(socket:port:) HTTPServer.swift line 133 - Accepted connection from: 
INFO: listen(socket:port:) HTTPServer.swift line 133 - Accepted connection from: 
 INFO: listen(socket:port:) HTTPServer.swift line 133 - Accepted connection from: 
 INFO: listen(socket:port:) HTTPServer.swift line 133 - Accepted connection from: 
 INFO: listen(socket:port:) HTTPServer.swift line 133 - Accepted connection from: 
 WARNING: init() ContentType.swift line 44 - Loading embedded MIME types. 
 ERROR: handleWriteHelper() IncomingSocketHandler.swift line 194 - Write to socket (file descriptor 9 failed. Error number=0. Message=Success.

**Comment by benedictdelfierro** [comment]
@na-gupta I changed to kitura 1.1, seems the socket error is gone..but the javascript is not loading using FilestaticServer middleware...it was working for 1.0 without TLS

**Comment by ianpartridge** [comment]
I think the Javascript problem is likely to be #837 so I'm closing this issue as the original problem is not reproduceable in Kitura 1.1.
