### ISSUE TITLE
Package-Builder dependency breaks `swift package update`

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#829]
I'd like to be able to run `swift package update` on my Swift project to get the latest version of Kitura and all its dependent modules.

However I can't, because the `Package-Builder` git submodule causes the Swift Package Manager to believe that I have local edits:

```
$ swift package update
error: repository has changes: /Users/carlbrown/src/REDACTED/Packages/KituraRequest-0.1.0
fix: stage the changes and reapply them after updating the repository
```

Could we please come up with a mechanism to do what Package-Builder does that doesn't break this functionality?

**Comment by vadimeisenbergibm** [comment]
The mechanism is to use `ignore =all` in `.gitmodules`. It was there but was removed in this commit https://github.com/IBM-Swift/Kitura/commit/a2850eca46b62ba70c18c73b5b6e54125e0c9794#diff-8903239df476d7401cf9e76af0252622 . @BDHernand
