### ISSUE TITLE
Swift 3.0.1

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/Kitura#832]
Swift 3.0.1 is released now - can we merge this branch into master?

**Comment by youming-lin** [comment]
I made a new branch for this: https://github.com/IBM-Swift/Kitura/tree/issue_832

The old branch contained `@escaping` fixes that were needed by the previews but are no longer needed by the final release.

**Comment by collinhundley** [comment]
@youming-lin it says this branch is 2 commits behind master - are there any noteworthy differences, or is it all just metadata changes?

**Comment by youming-lin** [comment]
Closing as Kitura 1.1 has been released.
