### ISSUE TITLE
Update Kitura-CredentialsHTTP tests

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#835]
Currently, there are warnings:

```
$ swift test
Compile Swift Module 'CredentialsHTTPTests' (3 sources)
/Users/ipartrid/301/Kitura-CredentialsHTTP/Tests/CredentialsHTTPTests/TestBasic.swift:122:35: warning: 'init(userProfileLoader:realm:)' is deprecated: userProfileLoader has been deprecated from Basic Authentication because of security improvements. Please use VerifyPassword.
        let basicCredentials_v1 = CredentialsHTTPBasic(userProfileLoader: { userId, callback in
                                  ^
/Users/ipartrid/301/Kitura-CredentialsHTTP/Tests/CredentialsHTTPTests/TestDigest.swift:101:32: warning: 'init(userProfileLoader:realm:)' is deprecated: userProfileLoader has been deprecated from Basic Authentication because of security improvements. Please use VerifyPassword.
        let basicCredentials = CredentialsHTTPBasic(userProfileLoader: { userId, callback in
                               ^
Linking ./.build/debug/Kitura-CredentialsHTTPPackageTests.xctest/Contents/MacOS/Kitura-CredentialsHTTPPackageTests
```

We should fix these.

**Comment by ianpartridge** [comment]
@gtaban @irar2 tagging interested parties!

**Comment by gtaban** [comment]
Hi Ian - I added those warnings to show our plan to deprecate userProfileLoaded. It currently exists in the Test because we haven't removed the functionality.
How should this be approached?

**Comment by ianpartridge** [comment]
We should fix the tests so they're not using the deprecated functionality.

**Comment by gtaban** [comment]
I believe the deprecated functions exists still because there are IBM costumers that already are using this plugin and it was decided that we will pull the deprecated functions after a couple of releases, so we wouldn't break any code.
I think while the functionality is there, we should be testing for it, which means testing the deprecated functions.
When functionality is completely disabled from code, then test should be removed. 
Thoughts?

**Comment by ianpartridge** [comment]
OK that makes sense. Do we have tests for the new non-deprecated (replacement) functionality?

**Comment by gtaban** [comment]
Yes they have been added.

**Comment by ianpartridge** [comment]
Awesome. In that case I'll close this Issue.  Thanks @gtaban !
