### ISSUE TITLE
Add GRMustache templating engine to Kitura on OS-X Swift 3.0

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#84]
<a href="https://github.ibm.com/VADIME"><img src="https://avatars.github.ibm.com/u/5255?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [VADIME](https://github.ibm.com/VADIME)**
_Tuesday Feb 02, 2016 at 15:40 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/84_

----

Added a new repo https://github.ibm.com/ibmswift/GRMustache.swift .
Using https://github.com/groue/GRMustache.swift, MIT license

**Comment by vadimeisenbergibm** [comment]
Opened issues against Apple while porting GRMustache to Linux:
https://bugs.swift.org/browse/SR-765
https://bugs.swift.org/browse/SR-789
https://bugs.swift.org/browse/SR-790
https://bugs.swift.org/browse/SR-794

**Comment by vadimeisenbergibm** [comment]
Completed in ea0d77d1ec8f6e3b94b9973a69ccf0a3a12b8693.
All (313) tests pass.

**Comment by dfirsht** [comment]
Validated.
