### ISSUE TITLE
SwiftyJSON 14.2.1 broke bool serialization on Linux

### ISSUE THREAD

**Issue by jesspittman** [IBM-Swift/Kitura#846]
14.2.1 introduced a change to the serialization to the linux serializer causing bools in a dictionary to be converted into integers. This was a patch release which means that any of the projects that were using Kitura 1.0 now download this update when rebuilt. Our todolists project work with an API that requires a field to be true/false and it fails when it receives a 0/1 instead.

**Comment by rfdickerson** [comment]
We are currently blocked on the TodoLists supporting Kitura 1.1 until this issue of 0 and 1 vs. false and true is resolved.

**Comment by youming-lin** [comment]
There is a PR against Foundation to fix this on Linux: https://github.com/apple/swift-corelibs-foundation/pull/699

Once that is included in the toolchain and we deprecate `LclJSONSerialization` in SwiftyJSON, the bug should be fixed automatically.

**Comment by ianpartridge** [comment]
That's going to take a while though - until Swift 3.0.2? Can we unblock TodoLists before then, somehow?

**Comment by shmuelk** [comment]
I'm working on a fix. I'm merging some of the Foundation PR into our code. Testing now.

**Comment by swizzlr** [comment]
The PR has now been merged!

**Comment by rfdickerson** [comment]
Which version of Kitura should I use to use SwiftyJSON 0.15.0 which contains this fix?

**Comment by ianpartridge** [comment]
SwiftyJSON `15.0.1` has the fix. Kitura `1.1` projects should pick this up via `swift package update`.
