### ISSUE TITLE
Benchmark fails sometimes. 

### ISSUE THREAD

**Issue by sujaykakkad** [IBM-Swift/Kitura#851]
```
ab -c 2 -n 2000 127.0.0.1:8000/
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
Completed 1800 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 1999 requests completed
```

Even for as less as 2000 get requests with only 2 concurrency the benchmark is failing.

The kitura code is
```swift
import Kitura
import HeliumLogger
import LoggerAPI
import SwiftyJSON

HeliumLogger.use()

let router = Router()

router.all(middleware: BodyParser())

router.get("/"){
    request, response, _ in
    try response.send(json: JSON(["message": "Hello World"])).end()
}

Kitura.addHTTPServer(onPort: 8000, with: router)
Kitura.run()
```

Is there some problem with multithreading inside Kitura?

**Comment by djones6** [comment]
@sujaykakkad It's possible you are running out of ephemeral ports.  Are you running on a Mac?

It appears that by default, ApacheBench does not use keepalive, so will open a new socket connection to Kitura for each request.  On Mac, there are 16k available port numbers by default (49152 - 65535).  After each request completes, the socket remains in TIME_WAIT state until a period of time has elapsed.

If I repeat your command 9 times in quick succession, I get the same result.

Can you try running `ab` with the `-k` (Keep-alive) flag and see if this solves your problem?

**Comment by sujaykakkad** [comment]
Yes I am using mac. I tried with keep alive and now it is working without any timeout. Also I will have to use -k command on linux as well?

**Comment by sujaykakkad** [comment]
Also whenever anyone want to use my swift api keep-alive header is compulsory?

**Comment by shmuelk** [comment]
Keep alive is not compulsory. Kitura works perfectly well without keep alive.

Your problem was that you ran out of sockets on the client side of things on your mac. This is a mac related issue and not a Kitura related issue. Even on the mac it's only an issue if you are trying to open lots and lots of sockets, which is what you were doing without keep alive.

**Comment by ianpartridge** [comment]
Closing this as not a Kitura issue.

**Comment by sujaykakkad** [comment]
Ok thanks.
