### ISSUE TITLE
Switch to using expectations instead of sleeping in router tests

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#86]
<a href="https://github.ibm.com/dfirsht"><img src="https://avatars.github.ibm.com/u/1584?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dfirsht](https://github.ibm.com/dfirsht)**
_Tuesday Feb 02, 2016 at 22:09 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/86_

----

Currently there is a 10 sec sleep between tests to ensure the server shuts down correctly. It would be preferable to switch this to being notified instead

**Comment by dfirsht** [comment]
This is blocked since XCTest does not provide this functionality. See PR here: https://github.com/apple/swift-corelibs-xctest/pull/43.

**Comment by modocache** [comment]
https://github.com/apple/swift-corelibs-xctest/pull/43 has been merged, so this issue should now be unblocked. Please file JIRA issues for any bugs you encounter, or if you have any suggestions on how to improve the feature! :bow:

**Comment by dfirsht** [comment]
Thanks @modocache, awesome work!
