### ISSUE TITLE
Linux-only dependency graph resolution error

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#874]
I can't currently build Kitura 1.2 on Linux if I include Kitura-Session. Works fine on OS X, but on Linux, I get the `error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/OpenSSL.git)`

Kitura-Session 1.2.0 -> BlueCryptor 0.7 -> OpenSSL *_0.2_*, but Kitura 1.2.0 -> Kitura-Net 1.2.0 -> BlueSSLService 0.12.4 ->  OpenSSL *_0.3_*

We should investigate why Travis didn't catch this

**Comment by youming-lin** [comment]
I think `BlueSSLService` bumped OpenSSL minor version without bumping its own minor version. Last successful `Kitura-Session` build pulled down `BlueSSLService` version 0.12.1: https://travis-ci.org/IBM-Swift/Kitura-Session/jobs/176680610

**Comment by youming-lin** [comment]
Fixed by `Kitura-Session` 1.2.1.
