### ISSUE TITLE
Memory Issues in Kitura Middleware

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#879]
I'm seeing some issue(s) with Kitura Middleware memory.  On a simple Kitura project with StaticFileServer, BodyParser, Session and Compression, but with no user-supplied Swift code, reloading a static page over and over causes memory to grow without bound.

I've created a sample project at https://github.com/carlbrown/KituraPageLeakSpike which has the [trace from a run using Xcode Instruments](https://github.com/carlbrown/KituraPageLeakSpike/blob/master/LeakInfo/Instruments_Run.trace.zip) and [a video](https://github.com/carlbrown/KituraPageLeakSpike/blob/master/LeakInfo/Instruments_Run.mp4) that shows the problem being exercised. (It uses static content copied from Kitura.io).

Here is the memory footprint from repeatedly hitting "reload":
![instrumentsscreenshotcropped](https://cloud.githubusercontent.com/assets/67206/20575587/8f2f08de-b17f-11e6-869b-af9d025d003b.png)

I don't see this issue on the [Kitura Sample](https://github.com/IBM-Swift/Kitura-Sample/) project, so it's somewhere else. Maybe Session?

**Comment by shmuelk** [comment]
I'm curious what happens when you remove Kitura-Compression.

**Comment by djones6** [comment]
I can recreate this leak on Mac and Linux.  If I remove both Session and Compression it is fine.  However, it leaks with either (or both) middlewares.

'Leaks' indicates that there are a number of mallocs which persist per request.  Based on their sizes, this looks like buffers for the static files are being retained in memory.  My guess is, something in Session and Compression is holding a reference which results in us retaining the whole tree of objects and buffers that were used in the response.

However, Leaks is not reporting any reference cycles (or I'm not using the tool properly).

I tried to use valgrind on Linux, but running the app through Valgrind causes the responses to sometimes hang, and then it eventually crashes.  Whether this is a problem with valgrind or a symptom of something functionally wrong, I'm not sure yet.

**Comment by djones6** [comment]
So #886 appears to completely eliminate the leak on both Linux and Mac - which confirms our theory from yesterday that it is references within Lifecycle that are causing a retain cycle with Response.

**Comment by carlbrown** [comment]
![screen shot 2016-12-08 at 5 55 52 pm](https://cloud.githubusercontent.com/assets/67206/21032592/0838ab12-bd70-11e6-9fd1-0ee3a162d25e.png)

FYI, here is a graph of this leak with Kitura1.3 with PRs for #901, #902 and #911 includes (as well as a hard-coded format for HeliumLogger).

I have the Instruments trace available, but can't post it in public since it has private symbols.
