### ISSUE TITLE
BodyParser does not pass body data to request's body if not text

### ISSUE THREAD

**Issue by jacobvanorder** [IBM-Swift/Kitura#908]
As raised in [this PR](https://github.com/rfdickerson/Kitura-Protobufs/pull/2) for @rfdickerson's protobuf example, `BodyParser` is not retaining the body data made by a request if it isn't a [type outlined](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift#L31-L34) in `BodyParser`'s `parserMap` dictionary. 

In this case, the `request.body` was always `.none` instead of the expected type `.raw(Data)` [from `ParsedBody`](https://github.com/IBM-Swift/Kitura/blob/1249f60a27e7f19a55b5569cd3b630312f67b881/Sources/Kitura/bodyParser/ParsedBody.swift#L42).

As it stands, I'm not sure if anything except what is outlined in `parserMap` gets retained but `application/octet-stream` sure wasn't.

**Comment by naithar** [comment]
If i'm not mistaken `getParser` method in [BodyParser.swift](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift) determines which parser to use.  
Atm it handles types included in `parserMap`, all `text` content-types and `multipart/form-data`.  
So other types, including `application/octet-stream` is not parsed.

**Comment by jacobvanorder** [comment]
What is the point of [.raw(Data)](https://github.com/IBM-Swift/Kitura/blob/1249f60a27e7f19a55b5569cd3b630312f67b881/Sources/Kitura/bodyParser/ParsedBody.swift#L42) then? 

In @rfdickerson's example he used `BodyParser` for `JSON` payloads (rightly so). He assumed, as I would have, that because there was `.raw(Data)`, it would default to that which he could use for `application/octet-stream`. It didn't. Instead, it `nil`'d out the data which, in my opinion, seems destructive.

**Comment by shmuelk** [comment]
@jacobvanorder You are probably correct in that we should at least enable the use of .raw(Data) if the mime type isn't one of those that we know how to parse.

It's an interesting question as what is the correct thing to do. One might say, if you don't know what to do, then do nothing. Let the developer read it in themselves. Or use .raw(Data).

**Comment by jacobvanorder** [comment]
I am proposing that `BodyParser` [already has the means](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift#L122-L130) to read body data and the [`.raw(Data)`](https://github.com/IBM-Swift/Kitura/blob/1249f60a27e7f19a55b5569cd3b630312f67b881/Sources/Kitura/bodyParser/ParsedBody.swift#L42) type so why not use it? 

I'll be raising a PR soon with a proposed solution and would love to gather feedback. Thanks!

**Comment by naithar** [comment]
Currently the only way of getting `.raw(Data)` is in `.body` property in [`Part`](https://github.com/IBM-Swift/Kitura/blob/1249f60a27e7f19a55b5569cd3b630312f67b881/Sources/Kitura/bodyParser/Part.swift) type.  
But i agree that i would expect to receive at least `.raw(Data)` if Request contains a body and `nil` only if it doesn't.
