### ISSUE TITLE
Can't compile on Linux

### ISSUE THREAD

**Issue by terhechte** [IBM-Swift/Kitura#909]
Hey,

I'm trying to build a simple Kitura project (based on the starter guide) within the 'ibmcom/kitura-ubuntu:latest' Docker container. Within macOS, everything compiles fine, on Linux, however, I get the following error:

```
Compile Swift Module 'POSIX' (11 sources)
/root/testcsp/.build/debug/CHTTPParser.build/module.modulemap:2:14: error: umbrella directory '/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include' not found
    umbrella "/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include"
             ^
/root/testcsp/.build/debug/CHTTPParser.build/module.modulemap:2:14: error: umbrella directory '/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include' not found
    umbrella "/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include"
             ^
/root/testcsp/.build/debug/CHTTPParser.build/module.modulemap:2:14: error: umbrella directory '/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include' not found
    umbrella "/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include"
             ^
Compile CLibvenice dns.c
/root/testcsp/.build/debug/CHTTPParser.build/module.modulemap:2:14: error: umbrella directory '/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include' not found
    umbrella "/root/testcsp/Packages/CHTTPParser-0.14.0/Sources/include"
...
```

I'm just running
`swift build`

What am I doing wrong?

Cheers,
Benedikt

**Comment by youming-lin** [comment]
@terhechte Looks like a similar issue to the one here: https://github.com/IBM-Swift/Kitura/issues/822#issuecomment-262602964

Have you tried deleting the `.build` folder and then running `swift build` again?

**Comment by shmuelk** [comment]
@terhechte From the messages in your compile it would seem that you are not trying to build a Kitura project, but rather a Zewo project. Kitura never used libvenice nor did ever have a CHTTPParser repository tagged at 0.14.

Can you please post your Package.swift file?

**Comment by terhechte** [comment]
Sorry. I managed to find the culprit. My build script (which automatically starts up a docker with the correctly mounted folder, etc) was accidentally referencing the wrong folder. Everything is working fine now. Thanks for writing all this awesome code.
