### ISSUE TITLE
KituraSession: Additional documentation request for `secret` parameter

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/Kitura#917]
I presume this string should contain random characters. It would be useful to know length bounds on this parameter if any. E.g., would 256 characters be sufficient? Or can any length be used and additional length gives additional security?

**Comment by gtaban** [comment]
hey @crspybits, I'll be adding documentation but just FYI:

The `secret` parameter should be a large unguessable string. I usually follow the recommendations for password entropy and use minimum secret length to 14 chars. 

The `secret` parameter is used to derive a pair of encryption and signature keys via PBKDF2 and a fixed IV to make the session id cookie be authenticated encrypted. The secret isn't used directly to encrypt or compute the MAC of the cookie.

The main aim for  `secret` is to secure the sessionID and ensure that the sessionID cannot be guessed.

**Comment by gtaban** [comment]
https://github.com/IBM-Swift/Kitura-Session/pull/30

**Comment by crspybits** [comment]
Thanks!

**Comment by gtaban** [comment]
Just an update on this, it seems NIST recommends salt > 32B.
