### ISSUE TITLE
Enhance features and  performance of HeliumLogger

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Kitura#922]
Need to fix a number of issues with HeliumLogger:
- Currently HeliumLogger's detailed and basic default formats do not log date/time, which should be logged by default.
- HeliumLogger formats the log message using multiple calls of string.replacingOccurrences(of). The same thing can be done much more efficiently using string interpolation or appending pre-parsed log segments.
- The default date format is "dd.MM.YYYY, HH:mm:ss". It should be in line with standard date formatting and use "yyyy-MM-dd'T'HH:mm:ss.SSS"
- Currently the check if we actually need to log based on the log level is done at the end. It should be the first thing we check
- Getting the filename from the filepath is currently done by creating a NSURL object. It is more efficient to use string.substring()
- Give users the ability to specify the time zone for the date/time

**Comment by kweinmeister** [comment]
I'm not sure if this belongs in the same issue, but we should consider following the W3C common logging format. That will enable all kinds of log analysis tools to use the output from Kitura:
https://httpd.apache.org/docs/1.3/logs.html#common
