### ISSUE TITLE
Inconsistent use of HeliumLogger vs temlate engines

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/Kitura#923]
In the following snippet:

```
import Kitura
import KituraStencil
import HeliumLogger

let router = Router()

HeliumLogger.use()
router.add(templateEngine: StencilTemplateEngine())
```

notice the inconsistency in the use of HeliumLogger vs the use of the template engine, i.e.

```
HeliumLogger.use()
```

vs

```
router.add(templateEngine: StencilTemplateEngine())
```

how about:

```
router.use(logger: HeliumLogger())
```

instead?

**Comment by youming-lin** [comment]
Hi @gmosx
`router.use` is meant to be used to register middleware on the server. Logging statements are not middleware and is hence not "used" by the router in the sense that it's not middleware that processes a request.

Furthermore, [`HeliumLogger.use()` actually turns on logging for ALL packages/code that uses the `LoggerAPI` package to log statements](https://github.com/IBM-Swift/HeliumLogger/blob/master/Sources/HeliumLogger/HeliumLogger.swift#L83), and is not limited to enabling logging statements in Kitura alone.

**Comment by gmosx** [comment]
OK, maybe it could be renamed to 

```
HelliumLogger.enable()  // or .start(), or something similar
```

to avoid confusion?
