### ISSUE TITLE
Reorganizing Kitura's HTTP Handling for Memory Efficiency

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#928]
I recommend reorganizing Kitura's HTTP Handling.

Logically, it should work this way:

* There's a TCP connection incoming from the client
* That TCP connection delivers a stream of bytes
* Those bytes need to be parsed and divided into multiple client requests
* A response needs to be created for each of those requests
* That request needs to be turned into bytes and sent back down the TCP connection

The way Kitura does it is not nearly that straightforward.  In Kitura, the `HTTPParser` is owned by the `ClientRequest` (via its parent, `HTTPIncomingMessage`, which is also the `ClientResponse`'s parent, which means the Response has to allocate a parser it doesn't need), and the same `ClientRequest` object is re-used on each request (it has to stay because it owns the parser). `HTTPIncomingMessage` has an `isRequest` method that keeps track of whether or not it's being used as a Request or a Response so it can exhibit different behavior.

I'm assuming the current object structure made sense when each connection only handled one request, but since keep-alive has been enabled, it hasn't been updated to reflect the new reality.

While this is confusing, it also has real-world consequences.  Objects that are being re-used can't be reclaimed by the Automatic Reference Counter, and so a manual clean-up process had to be devised.  This manual process is error-prone, and is reported by Instruments (and valgrind) to be the greatest remaining contributor to Kitura's current memory problems (e.g. when Kitura is quiescent (meaning no requests have come in for for several minutes and no data from previous requests still needs to be in memory) the vast majority of the memory still resident was allocated in and around these parts of the code). See:
<img width="941" alt="screen shot 2016-12-13 at 2 29 01 pm" src="https://cloud.githubusercontent.com/assets/67206/21157912/ccad76fc-c140-11e6-9833-a16c8efe81c6.png">

It's especially critical that this gets fixed for people who are using Kitura in Cloud applications with fixed (often small) memory allotments.

I propose we:

1. Move the `HTTPParser` "up" a level so it's owned by the connection (i.e. the `IncomingHTTPSocketProcessor`) not the `ClientRequest`
2. Create a new `ClientRequest`/`ClientResponse` object for every new request that comes in from the `HTTPParser`
3. Avoid reusing the `ClientRequest` and `ClientResponse` objects so that they can both be reclaimed by ARC after the Response is sent down the TCP connection
4. Remove the `isRequest` variable from `HTTPIncomingMessage` and move all logic that is not shared by both the Request and Response from the base class into their respective instances
5. Remove the need to manually clean up or reset connections
5. Make sure the `IncomingHTTPSocketProcessor` and its associated objects are all able to be reclaimed by ARC when the TCP connection is closed (by `FIN` or `RST`).
6. Ensure that if, for some reason, the `IncomingHTTPSocketProcessor` has to stick around (e.g. because the client holds the TCP connection open), that only the minimum possible number of bytes is kept resident in memory (e.g. no previous request or response objects, data, or buffers should ever remain in memory once the response has been sent)

I've already started working on this (https://github.com/IBM-Swift/Kitura-net/pull/160 was a prerequisite step) and plan on continuing to do so, because my application deployment is blocked until the memory growth issues are resolved.  I'm creating this issue to solicit opinions and facilitate discussion of  implementation details.

**Comment by shmuelk** [comment]
A couple of comments:

   1. There is confusion in what you you have written. ClientRequest and ClientResponse are only used in outgoing messages (i.e. HTTP requests originated by the server). They are **not** used in incoming requests. HTTPServerRequest and HTTPServerResponse are used for those.
   2. You are correct that currently HTTPServerRequest and ClientResponse share a common parent HTTPIncomingMessage. The isRequest parameter is there for mainly for parsing. The HTTP Parser needs to know whether it is parsing a request or a response.
   3. The "memory" leak that occurs when there is an idle period is due in part to the attempt to reuse some of the objects. It may have been a mistake to reuse the HTTPServerRequest and HTTPServerResponse objects. But the much harder to "fix" "leak" which is really what happens at idle periods, is the link from the IncomingSocketManager -> IncomingSocketHandler -> IncomingSocketProcessor (usually a IncomingHTTPSocketProcessor). In particular on Linux, the IncomingSocketManager is in charge of driving all of the Read Socket I/O via epoll. When epoll says there i data to be read it tells the IncomingSocketHandler to read. To find the right IncomingSocketHandler, there is a Dictionary<Int32, IncomingSocketHandler> that is used. Dictionary's are **not** thread safe in Swift. Adding a semaphore here makes for a point of contention. Thus the Dictionary is only managed in the thread that accepts new incoming sockets.
  4. As far as your PR goes. I think a better thing is to remove HTTPIncomingMessage from being a delegate of HTTPParser all together. The HTTPParser should store all of the stuff that it gets from the C parser internally, which should wrapped by functions in HTTPIncomingMessage.

**Comment by carlbrown** [comment]
There are certainly better architectures than the one I'm proposing.  If I were given a green field and asked to build Kitura, this is not what I would do.  

But I have to do something to get the resident memory consumed down to something usable, and I have little choice but to do it in a series of incremental steps. Step 1 was breaking the direct coupling between the `CHTTPParser` and the `HTTPIncomingMessage`.
