### ISSUE TITLE
The dependency graph could not be satisfied because an update to `https://github.com/IBM-Swift/Kitura-net.git' is required

### ISSUE THREAD

**Issue by doronkatz** [IBM-Swift/Kitura#935]
Hi guys,

Im working with Kitura Package manager, within docker, for my Mac. Swift version is 3.0.1.

Now Im getting the following error upon building:

> The dependency graph could not be satisfied because an update to `https://github.com/IBM-Swift/Kitura-net.git' is required

Im not sure what to do. My package manager is as follows:

```
import PackageDescription

let package = Package(
    name: "x",
    dependencies: [
    	.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/Kitura-Sessions.git", majorVersion: 1)
    ]
)
```

**Comment by youming-lin** [comment]
@doronkatz Can you clear the `Packages` folder and then run `swift package update` again? Also, the URL should be `/Kitura-Session.git`, not `/Kitura-Session**s**.git`

**Comment by nstein** [comment]
Same problem here. Currently updating Xcode to 8.2 (swift 3.0.2 RELEASE toolchain). I think it may have to do sth with the toolchain.

**Comment by youming-lin** [comment]
@nstein Can you share your `Package.swift` here? This issue is caused by dependencies pulling in different versions of the same package, in this case `Kitura-net`.

Also, have you tried deleting your `Packages` folder first and then reinstalling all the dependencies? Sometimes simply doing a `swift package update` after updating dependencies in `Package.swift` may cause this issue.

**Comment by doronkatz** [comment]
Thanks @nstein, so Ive fixed up the package.swift as follows:

`
dependencies: [
    	.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 1),
        .Package(url: "https://github.com/IBM-Swift/Kitura-Session.git", majorVersion: 1)
    ]
`

I deleted the contents of the Packages folder, and ran **swift package update**. That ran fine. However, running **swift build** again, however still got the following error:

`
root@f91ac2d1260f:/projects/project4# swift build --verbose
lsb_release -r
/root/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swiftc --driver-mode=swift -I /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -L /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -lPackageDescription /projects/project4/Package.swift -fileno 4
/usr/bin/git -C /projects/project4/Packages/CCurl-0.2.3 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/CEpoll-0.1.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Cryptor-0.8.6 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/HeliumLogger-1.4.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Kitura-1.3.1 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Kitura-CouchDB-1.4.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Kitura-net-1.4.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Kitura-Session-1.3.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Kitura-TemplateEngine-1.1.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/LoggerAPI-1.4.0 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/OpenSSL-0.3.1 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/Socket-0.12.16 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/SSLService-0.12.10 config --get remote.origin.url
/usr/bin/git -C /projects/project4/Packages/SwiftyJSON-15.0.4 config --get remote.origin.url
/root/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swiftc --driver-mode=swift -I /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -L /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -lPackageDescription /projects/project4/Packages/Kitura-1.3.1/Package.swift -fileno 4
/root/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swiftc --driver-mode=swift -I /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -L /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/lib/swift/pm -lPackageDescription /projects/project4/Packages/Kitura-net-1.4.0/Package.swift -fileno 4
error: The dependency graph could not be satisfied because an update to `https://github.com/IBM-Swift/Kitura-net.git' is required

`

**Comment by youming-lin** [comment]
@doronkatz OK, I can reproduce your problem now.

For now, can you specify the minor versions for your packages as well? Be aware that currently `Kitura-Session` is only at version 1.3, which restricts your `Kitura` to version 1.3.x, and by extension your `Kitura-CouchDB` package can only be 1.3.x as well.

When you specify your minor versions, make sure the versions of sub-dependencies are not conflicting. Both `Kitura-Session` and `Kitura-CouchDB` have `Kitura` as a sub-dependency. Unfortunately, SPM is not currently smart enough to resolve sub-dependency conflicts, hence you are seeing the dependency graph error.

**Comment by doronkatz** [comment]
Thanks. So what exactly are the versions for each, Could you re-write here to make it clear?

**Comment by youming-lin** [comment]
@doronkatz For example:

```swift
import PackageDescription

let package = Package(
    name: "x",
    dependencies: [
    	.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minorVersion: 3),
        .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minorVersion: 3),
        .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 1, minorVersion: 3),
        .Package(url: "https://github.com/IBM-Swift/Kitura-Session.git", majorVersion: 1, minorVersion: 3)
    ]
)
```

Also, since `Kitura` is a sub-dependency of `Kitura-Session`, you can remove it from your `Package.swift`.

**Comment by doronkatz** [comment]
HI, so after doing as you mentioned, I got:

`
oot@f91ac2d1260f:/projects/project4# swift build
Compile Swift Module 'project4' (1 sources)
Linking ./.build/debug/project4
/projects/project4/Sources/main.swift:30: error: undefined reference to '_TMaC13KituraStencil21StencilTemplateEngine'
/projects/project4/Sources/main.swift:30: error: undefined reference to '_TWPC13KituraStencil21StencilTemplateEngine20KituraTemplateEngine14TemplateEngineS_'
/projects/project4/Sources/main.swift:30: error: undefined reference to '_TIFC13KituraStencil21StencilTemplateEnginecFT9namespaceC7Stencil9Namespace_S0_A_'
/projects/project4/Sources/main.swift:30: error: undefined reference to '_TFC13KituraStencil21StencilTemplateEngineCfT9namespaceC7Stencil9Namespace_S0_'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /root/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swift-build-tool -f /projects/project4/.build/debug.yaml
`
Ive done a clean, clear and it still has that issue. Have you been able to successfully get it working on your end?

**Comment by youming-lin** [comment]
@doronkatz Can you share more info? What is the code that is failing in your `main.swift` file?

Also, `Kitura-Session` has now been updated to version 1.4.0. You should be able to use version 1.4.0 of all the Kitura- packages now.

**Comment by doronkatz** [comment]
Hi @youming-lin  so upgrading to 1.4.0 now worked for me. No errors Strangely. I did another clean. Hopefully it helps others in that respect as well. And thanks for your help.

regards,
Doron

**Comment by youming-lin** [comment]
You're welcome!
