### ISSUE TITLE
Added boilerplate template for license & contributors

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#94]
<a href="https://github.ibm.com/andybs"><img src="https://avatars.github.ibm.com/u/1617?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andybs](https://github.ibm.com/andybs)**
_Thursday Feb 04, 2016 at 18:03 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/pull/94_

----

----

_**[andybs](https://github.ibm.com/andybs)** included the following code: https://github.ibm.com/ibmswift/Phoenix/pull/94/commits_

**Comment by dfirsht** [comment]
duplicate of #92

**Comment by rfdickerson** [comment]
Did we add a CONTRIBUTING file? I think @triceam was going to give this to us.

**Comment by dfirsht** [comment]
not yet but #93 captures this
