### ISSUE TITLE
Feature request: Kitura-CredentialsLocal

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Kitura#948]
From Slack: https://swift-at-ibm.slack.com/archives/general/p1482714084000722
Difference between local and basic authentications (as implemented by PassportJS): http://stackoverflow.com/a/20888454/6832886

Basically, I think the issue here is adding persistent login support via sessions.

**Comment by lucianboboc** [comment]
I think HTTP token auth is missing:
 
Authorization: Token token="h480djs93hd8"

https://tools.ietf.org/html/draft-hammer-http-token-auth-01

**Comment by christiancompton** [comment]
Closing - reopen if needed.
