### ISSUE TITLE
Move CHTTPParser back to its own repository

### ISSUE THREAD

**Issue by pbohrer** [IBM-Swift/Kitura#974]
I ran into the problem that I cannot use LLDB in KituraNet due to the fact that we have CHTTPParser directly included in KituraNet Sources directory.  

This bug seems to capture it: 
https://bugs.swift.org/browse/SR-3169 

They suggest that C libraries should be in a separate repository to get around this.  I know we used to do this but I think we need to switch it back so that debugging works.

**Comment by youming-lin** [comment]
IIRC we moved CHTTPParser into Kitura-Net to fix another [issue](https://github.com/IBM-Swift/Kitura/issues/822#issuecomment-261078060)

Ironically, that move fixed some debugging issues back then.

**Comment by christiancompton** [comment]
Closing - reopen if needed.
