### ISSUE TITLE
Swift@IBM Engineering slack link shows 404 Not Found

### ISSUE THREAD

**Issue by purpleblues** [IBM-Swift/Kitura#978]
[Slack Link](http://swift-at-ibm-slack.mybluemix.net/) on [Kitura Support page](http://www.kitura.io/en/support/support.html) shows '404 Not Found' response.

**Comment by ianpartridge** [comment]
@kweinmeister ?

**Comment by ianpartridge** [comment]
Thanks @purpleblues we've fixed this now :)
