### ISSUE TITLE
Implement Kitura-CredentialsPayPal

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#981]
To demonstrate working with Kitura-CredentialsOAuth2, see https://github.com/IBM-Swift/Kitura/issues/905 .

Obtaining user consent (authorization code) https://developer.paypal.com/docs/api/auth-headers/#obtain-users-consent.

Getting access token - https://developer.paypal.com/docs/api/identity/#tokenservice_createFromAuthorizationCode

Getting user information - https://developer.paypal.com/docs/api/identity/#openidconnect_userinfo

A general explanation of OAuth2 for PayPal - https://developer.paypal.com/docs/integration/direct/paypal-oauth2/

Creating a PayPal app
https://developer.paypal.com/docs/integration/admin/manage-apps/

**Comment by vadimeisenbergibm** [comment]
Learned PayPal iOS SDK login - https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_mobile.md#overview

It uses the regular authorization code flow - the SDK performs login and send authorization code to the server, as in the web login. The server uses the authorization code to get access token as usual, and then fetches profile using the access token.

**Comment by christiancompton** [comment]
Closing - reopen if needed.
