### ISSUE TITLE
Submit PR for SwiftyJson change

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#99]
Before we can submit, we need to confirm that we conform to IBM polices

**Comment by shmuelk** [comment]
We have moved this to the backlog to wait and see what happens when the automatic bridging of various Swift classes to Foundation classes is enabled on Linux.

We want to then understand the impact to the NSJSONSerialization class.

**Comment by christiancompton** [comment]
Closing - Reopen as needed.
