### ISSUE TITLE
Create Kitura-CredentialsTwitter

### ISSUE THREAD

**Issue by jacobvanorder** [IBM-Swift/Kitura#990]
I'm opening this for the ability to validate users using Twitters [Sign In with Twitter](https://dev.twitter.com/web/sign-in/implementing) feature. 

After requesting the token, a redirect occurs. Upon the user validating their credentials, an access token is provided which is then used to acquire the user's ID and Twitter handle.

This will use Twitter's [OAuth 1.0](https://dev.twitter.com/oauth) implementation.

My completed and unit tested implementation of this is [here](https://github.com/jacobvanorder/Kitura-CredentialsTwitter). Thanks to @ianpartridge for the [suggestion](https://github.com/IBM-Swift/Kitura/pull/927#issuecomment-266787982)!

**Comment by youming-lin** [comment]
I have added a link to `Kitura-CredentialsTwitter` in `Kitura-Credentials`'s [README](https://github.com/IBM-Swift/Kitura-Credentials#list-of-plugins).

@jacobvanorder Thanks for writing a Twitter plugin for `Kitura-Credentials`!
